- js/modules/k6/k6.go
- js/modules/k6/k6_test.go
The general inconsistencies between group as an idea and asynchronous code makes it not great fit and such we will try to discourage users to mix them.
Updates #2728
> Disable async function as group and check callback

- cmd/tests/tracing_module_test.go
- js/modules/k6/experimental/tracing/client.go
- js/modules/k6/experimental/tracing/module.go
- js/modules/k6/http/async_request_test.go
- js/modules/k6/http/http.go
- js/modules/k6/http/request.go
- js/modules/k6/http/response_callback_test.go
This is implementation of http.request but it return a promise and does all the networking off the event loop.
The code is pretty simple and seems fairly safe given that most possible race conditions would also happen in the case of
`http.batch`.
Even with that there is at least one test that previously couldn't have happened with http.batch.
closes #2825
> http: add asyncRequest

- cmd/test_load.go
- js/bundle.go
- js/bundle_test.go
- js/common/initenv.go
- js/console_test.go
- js/runner.go
- js/runner_test.go
- lib/test_state.go
This PR threads a way for JS modules to lookup environment variables without directly accessing the `os` package. That ended up quite simple to do, with some additional simplification as a bonus, and it would be nice to have it before https://github.com/grafana/k6/pull/2884
> Pass `LookupEnv()` to `js/` modules

- api/v1/group_routes_test.go
- api/v1/setup_teardown_routes_test.go
- api/v1/status_routes_test.go
- cmd/run.go
- js/runner_test.go
- metrics/engine/engine.go
- metrics/engine/engine_test.go
- metrics/engine/ingester_test.go
https://github.com/grafana/k6/pull/2815#discussion_r1056459921
>// TODO: refactor and move the tests that still make sense in other packages
It resolves the unit tests parts
> Metrics engine tests

- api/v1/status_routes_test.go
- cmd/run.go
- cmd/tests/cmd_run_test.go
- execution/scheduler.go
- execution/scheduler_ext_test.go
- js/runner_test.go
This reverts a big part of https://github.com/grafana/k6/pull/2885 because, with all of the logic in `Run()`, k6 didn't know if it needed to wait when `--linger` was specified.
In general, if a script error or `test.abort()` occurs during init, `--linger` should not apply and k6 should exit immediately. But if `test.abort()` is called during the test run itself, or the test was stopped in some other way besides `Ctrl+C` (e.g. REST API, thresholds with `abortOnFail`), `--linger` means that k6 should not exit immediately after stopping the test.
https://github.com/grafana/k6/issues/2804 is a somewhat related issue, where I'll also document this somewhat hidden and implicit requirements.
> Split `Scheduler.Run()` into `Init()` and `Run()` again

- js/modules/k6/ws/ws.go
- js/modules/k6/ws/ws_test.go
The panic happens when interval between 0 and 1 is given.
The code that tested whether the interval was > 0 correctly converted to
floats first and then back to time. And then checked it in order to
prevent this very panic.
Unfortunately it then did the same calculation again but this time by
converting the interval directly to int before multiplying by
milliseconds. Which ends up rounding it to 0. Making the whole result
zero and leading to time.NewTicker to panic.
This was already done correctly for setTimeout when the same panic was
found there and the wrong conversation was added for setInterval.
Previous commit https://github.com/grafana/k6/commit/df3ad1bd371ac6d0bd2d5a4c10887b08f4374eba
> Fix panic with setInterval in k6/ws

- errext/exitcodes/codes.go
I messed up the exit codes in https://github.com/grafana/k6/pull/2815, so this PR now restores the old ones. The only thing different from v0.42.0 is the meaning of the 103 exit code. It used to be `GenericEngine`, i.e. "the test died from an unknown cause", and will now be used for the well-defined `ScriptStoppedFromRESTAPI` error.
This is the `git diff v0.42.0...restore-exit-codes -- errext/exitcodes/codes.go`, for easier review: 
```diff
diff --git a/errext/exitcodes/codes.go b/errext/exitcodes/codes.go
index abcb602f..8efc0578 100644
--- a/errext/exitcodes/codes.go
+++ b/errext/exitcodes/codes.go
@@ -1,4 +1,5 @@
// Package exitcodes contains the constants representing possible k6 exit error codes.
+//
//nolint:golint
package exitcodes
@@ -13,7 +14,7 @@ const (
SetupTimeout …
```
> Restore the exit codes to the v0.42.0 values

- js/initcontext.go
- js/initcontext_test.go
This fixes a regression introduced in 2753196ab where in all imports are cached on the specifier that is provided for them. This is fine for k6 modules which happen to always have the same absolute names.
But source modules can have relative paths that resolve to different absolute ones depending on where they are imported from.
Fixes #2902
> js: Cache scripts by absolute not relative paths

- js/bundle.go
- js/bundle_test.go
This only makes certain the error does actually specify it is about the options.
Updates #2909
> Add more context when script options can't be parsed

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-browser/api/browser_context.go
- vendor/github.com/grafana/xk6-browser/api/browser_type.go
- vendor/github.com/grafana/xk6-browser/api/element_handle.go
- vendor/github.com/grafana/xk6-browser/api/frame.go
- vendor/github.com/grafana/xk6-browser/api/page.go
- vendor/github.com/grafana/xk6-browser/api/response.go
- vendor/github.com/grafana/xk6-browser/browser/mapping.go
- vendor/github.com/grafana/xk6-browser/browser/module.go
- vendor/github.com/grafana/xk6-browser/chromium/browser_type.go
- vendor/github.com/grafana/xk6-browser/common/browser.go
- vendor/github.com/grafana/xk6-browser/common/browser_context.go
- vendor/github.com/grafana/xk6-browser/common/element_handle.go
- vendor/github.com/grafana/xk6-browser/common/frame.go
- vendor/github.com/grafana/xk6-browser/common/page.go
- vendor/github.com/grafana/xk6-browser/common/response.go
- vendor/modules.txt
This is a hot-fix update for xk6-browser. We noticed some of our APIs might not work as expected and fixed the issues.
Details:
- https://github.com/grafana/xk6-browser/issues/749
- https://github.com/grafana/xk6-browser/pull/754
- https://github.com/grafana/xk6-browser/pull/758
- https://github.com/grafana/xk6-browser/pull/761
- https://github.com/grafana/xk6-browser/pull/746
Question:
- Should this fix be in a k6 hotfix release after releasing k6 v0.43.0?
> Fix xk6-browser v0.8.0

- .github/workflows/build.yml
Removed the old hack added for releasing k6 v0.41.0 with a specific Go version.
> Remove the fixed patch version for Go

- .github/workflows/arm-tests.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/tc39.yml
- .github/workflows/test.yml
- .github/workflows/xk6.yml
- Dockerfile
> Bump Go version to 1.20

- .golangci.yml
- cmd/archive_test.go
- cmd/config.go
- cmd/run.go
- cmd/run_test.go
- cmd/state/state.go
- cmd/test_load.go
- cmd/tests/tests.go
- js/module_loading_test.go
- js/modules/k6/html/gen/gen_elements.go
- js/runner_test.go
- js/tc39/tc39_test.go
- lib/archive.go
- lib/archive_test.go
- lib/fsext/cacheonread.go
- lib/fsext/changepathfs.go
- lib/fsext/changepathfs_test.go
- lib/fsext/trimpathseparator_test.go
- lib/fsext/walk.go
- lib/old_archive_test.go
- loader/loader.go
- log/file.go
Built on top of, https://github.com/grafana/k6/pull/2890, this PR adds linter rules that forbid the usage of most of the `os` and `syscall` packages. It also has the mechanical fixes to some of that previously improper usage in a bunch of places in the k6 codebase. I could safely replace a bunch of `os` usages with [the `fs` package introduced in Go 1.16](https://go.dev/doc/go1.16#fs) and the equivalent `syscall` constants, since the things in `os` are now [type aliases](https://yourbasic.org/golang/type-alias/) (see [this](https://github.com/golang/go/blob/56a14ad4bc19d5ee9d4257f370a570377e81e544/src/os/error.go#L21-L24), [this](https://github.com/golang/go/blob/56a14ad4bc19d5ee9d4257f370a570377e81e544/src/os/types.go#L20-L56) and …
> Add lint check for os and syscall usage and fix some of the issues

- .golangci.yml
It is a copy-paste of the enabled linters returned from the `make ci-like-lint` command used with `golangci-lint linters` on the master branch.
> lint: Use allowed list for linters

- cmd/ui_unix.go
Added z/OS build flags for IBM z/OS compatibility.
Enabling these build flags (along with the changes to afero mentioned here https://github.com/spf13/afero/pull/384) allows k6 to be compiled on z/OS Unix System Services. 
Closes #2888
> Update ui_unix.go with z/OS build flags

- .github/workflows/lint.yml
- .golangci.yml
- api/server_test.go
- cloudapi/api.go
- cloudapi/api_test.go
- converter/har/converter.go
- js/modules/k6/http/request_test.go
- js/modules/k6/http/response_test.go
- js/runner_test.go
- lib/netext/httpext/error_codes_test.go
- lib/netext/httpext/request_test.go
- lib/netext/httpext/tracer_test.go
- lib/netext/httpext/transport_test.go
- loader/loader.go
- loader/loader_test.go
- output/cloud/metrics_client.go
- output/influxdb/bench_test.go
- output/influxdb/output_test.go
The diff for the disabled linters:
```
-dupword: checks for duplicate words in the source code
-ginkgolinter: enforces standards of using ginkgo and gomega
-gocheckcompilerdirectives: Checks that go compiler directive comments (//go:) are valid.
-interfacebloat: A linter that checks the number of methods inside an interface.
-loggercheck (logrlint): Checks key valur pairs for common logger libraries (kitlog,klog,logr,zap). 
-musttag: enforce field tags in (un)marshaled structs
-reassign: Checks that package variables are not reassigned
-testableexamples: linter checks if examples are testable (have an expected output)
-usestdlibvars: A linter that detect the possibility to use variables/constants from the Go standard library.
```
From the previous list this PR enables the following new …
> Bump golangci version

- js/modules/k6/execution/execution.go
- js/modules/k6/execution/execution_test.go
Fix a minor panic that could happen if try to get insides about the `exec.vu.iterationInScenario` in `setup` method
In that case, we will return `0` as all other `vu.*` properties do.
Panics are bad.
Resolves: #2924
> Fix panic in `k6/execution`

- cmd/tests/cmd_run_test.go
- cmd/ui.go
- metrics/engine/ingester.go
It fixes the ui print `output: engine` restoring the expected text `output: -` when there isn't an explicit set from the user.
> Print the expected char with the default output

- cmd/run.go
This resolves https://github.com/grafana/k6/issues/2937
> Fix usage report block of k6 execution if it takes longer than 3s

- cmd/run.go
- cmd/tests/cmd_run_test.go
- cmd/ui.go
- js/modules/k6/execution/execution.go
- js/modules/k6/execution/execution_test.go
- lib/consts/consts.go
- metrics/engine/ingester.go
- release notes/v0.43.1.md
https://github.com/grafana/k6/issues/2937 / https://github.com/grafana/k6/pull/2938 is the main reason for needing to make a bugfix release :disappointed: However, since we'd be making one anyway, we can also release the more minor https://github.com/grafana/k6/pull/2926 and https://github.com/grafana/k6/pull/2934 bugfixes earlier than expected.
> k6 v0.43.1 bugfix release

- cmd/archive.go
- cmd/cloud.go
- cmd/common.go
- cmd/convert.go
- cmd/login_cloud.go
- cmd/root.go
- cmd/run.go
- cmd/state/state.go
- cmd/tests/cmd_run_test.go
- cmd/tests/test_state.go
This should close #2850 
I have added some e2e tests in the `cmd_run_test` file, although, as discussed earlier in the issue, perhaps it should be moved to another file since the `run` command is not actually being checked.
> Show actual binary name in the usage help (#2850)

- js/modules/k6/k6.go
- js/modules/k6/k6_test.go
Before this check was only returning `false` if it also could emit it, and true otherwise.
This should rarely be a problem as the same context that is being checked here is the one that interrupts the VM - so no code will be able to run after this.
Unfortunately the code checking if it should be emitted is racing with the one that interrupts the VM. So it is possible for the VM to still not be interrupted when a `check` returns a wrong value. It is even possible for more code to be run before the interrupt is actually called.
The code still checks the context as this also updates the internal check structure and we don't want to that if the context is done. The above should be changed with #2869
Fixes #2912
> k6.check: Fix returned values when iteration is ending

- js/bundle.go
- js/bundle_test.go
- js/cjsmodule.go
- js/gomodule.go
- js/initcontext.go
- js/initcontext_test.go
- js/modules.go
- js/runner.go
This refactor tries to simplify the implementation of `require` and
connected code by splitting it heavily into different parts.
These changes are similar to what will be needed for native ESM support
as shown in https://github.com/grafana/k6/pull/2563 , but without any of
the native parts and without doing anything that isn't currently needed.
This will hopefully make ESM PR much smaller and less intrusive.
This includes still keeping the wrong relativity of `require` as
explained in https://github.com/grafana/k6/issues/2674.
It also tries to simplify connected code, but due to this being very
sensitive code and the changes already being quite big, this is done
only to an extent.
The lack of new tests is mostly due to there not being really any new
code and the tests that were created …
> js: refactor how modules are loaded

- cloudapi/client.go
- cloudapi/config.go
- cloudapi/errors.go
- cmd/login_cloud.go
- cmd/run.go
- output/cloud/output.go
triggered by https://github.com/grafana/k6/pull/2916/files#r1117146117
> Reference 'k6 cloud' instead of 'Load Impact' in docs and errors

- lib/executor/constant_arrival_rate.go
- lib/executor/constant_arrival_rate_test.go
- lib/executor/ramping_arrival_rate.go
- lib/executor/ramping_arrival_rate_test.go
This is a somewhat quick and dirty fix of #1977, where instead of changing the global active VUs when the VU is activated, we change it when the VU is actually running. This synchronizes it with the running count of the internal `activeVUPool`, and reports the correct value everywhere the `ExecutionState` is used (the real-time total active VU count while the test is running, in all outputs, etc.).
> Fix active VU reporting by arrival-rate executors

- docker-compose.yml
This due to our provisioning files not working with latest grafana
see #2969
> Pin grafana version in docker compose

- cmd/tests/tracing_module_test.go
- js/modules/k6/experimental/tracing/client.go
- js/modules/k6/experimental/tracing/encoding.go
- js/modules/k6/experimental/tracing/module.go
- js/modules/k6/experimental/tracing/options.go
- js/modules/k6/experimental/tracing/options_test.go
- js/modules/k6/experimental/tracing/propagator.go
- js/modules/k6/experimental/tracing/sampling.go
- samples/experimental/tracing/tracing-sampling.js
This Pull Request adds probabilistic sampling support to the tracing module. Using it, users can specify the percentage of their instrumented requests which should have their trace context header's sampled field set to true.
From a user-interface perspective, this feature is introduced as an option meant to be set during either the instantiation of a `tracing.Client`, or during a call to `instrumentHTTP`. It consists of a single integer field of the tracing options, whose value, within the `0 <= n <= 100` bounds, is meant to represent a percentage.
```javascript
// The sampling option is available when instantiating a Client
const sampledHTTP = new tracing.Client({
propagator: "w3c",
// Up to 55% of the requests emitted using the client instance's
// methods will have their trace context …
```
> Add sampling capabilities to the tracing module

- js/runner.go
- js/runner_test.go
- js/summary_test.go
This in practice just checks that a promise was not return and get's it result.
Async functions happen to just always return promises.
Fixes #2935 and #2959
> Support async functions for setup and handleSummary

- lib/testutils/logrus_hook.go
- metrics/engine/engine.go
- metrics/engine/ingester.go
- metrics/engine/ingester_test.go
Closes #2765
At the moment the implementation doesn't support turning it off, we may consider using 0 for it in the future.
> Too many time series warning

- cmd/root.go
- cmd/root_test.go
- errext/exitcodes/codes.go
In https://github.com/grafana/k6/pull/2833 we started calling `os.Exit()` in a `defer` statement, so we inadvertently circumvented the regular handling of panics that bubble up to the top by the Go runtime. 
I could have removed the `os.Exit()` call from the `defer`, but I think this is better. Handling panics ourselves in this way is explicit, simpler to understand, and it allows us to handle them exactly how we want - including assigning them their own unique exit code, and test the whole thing with an e2e test.
> Fix panic handling and add a new exit code and a test for panics

- api/v1/metric_test.go
- js/bundle_test.go
- js/common/bridge.go
- js/console_test.go
- js/eventloop/eventloop.go
- js/summary.go
- lib/execution_segment.go
- lib/executor/constant_arrival_rate.go
- lib/executor/externally_controlled.go
- lib/executor/helpers.go
- lib/executor/per_vu_iterations.go
- lib/executor/ramping_arrival_rate.go
- lib/executor/ramping_vus.go
- lib/executor/ramping_vus_test.go
- lib/executor/shared_iterations.go
- lib/executors.go
- lib/netext/httpext/error_codes.go
- lib/netext/httpext/request.go
- lib/netext/httpext/response.go
- lib/netext/httpext/transport.go
- lib/runtime_options.go
- lib/tlsconfig.go
- lib/types/dns.go
- metrics/thresholds_test.go
- output/cloud/data.go
- output/influxdb/config_test.go
- ui/pb/progressbar.go
I got annoyed by some of the many linter errors we have unresolved. Some of them like the loopclosure ones might even hide other problems, so I decided it's time to fix them.
I'll try to do fixes for various unrelated issues commit by commit. To reduce merge conflicts, this is built on top of https://github.com/grafana/k6/pull/2960.
> Linter and formatting fixes

- js/bundle.go
- js/common/initenv.go
- js/modules/k6/html/html_test.go
- js/modules/k6/metrics/metrics_test.go
- js/modulestest/runtime.go
Instead of manually including most of its constituent parts, we can just embed the whole `*lib.TestPreInitState` in the struct. This will make any future changes much easier.
I also tried to move `FileSystems` and `CWD` in `lib.TestPreInitState`, so we can get rid of them in both `cmd.loadedTest` and `common.InitEnvironment` (at that point, we could basically replace it with `lib.TestPreInitState` directly): https://github.com/grafana/k6/blob/c09919b4961f9d93a32f482089a068d36f667ee2/cmd/test_load.go#L31-L39
Unfortunately, `FileSystems` is complicated, since when we are running .js files, its elements contain the "cache-on-read" overlay filesystems on top of the real FS (and on HTTPs), while for .tar archives we substitute them with the filesystems in the archive: …
> Directly embed `lib.TestPreInitState` in `js/common.InitEnvironment`

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-websockets/websockets/websockets.go
- vendor/modules.txt
This "fixes" a potential lock up, but that was already fixed in k6 in #3004.
So this is mostly a somewhat of refactor and simplying PR. 
As well as make `ping` throw an exception if used with a closed connection.
> Update to xk6-websockets v0.2.0

- execution/scheduler_ext_test.go
This was due to some tests stopping taking samples before stopping emitting them.
closes #3008
> Fix tests scheduler test getting stuck

- js/modules/k6/experimental/tracing/client.go
- js/modules/k6/experimental/tracing/client_test.go
- js/modules/k6/experimental/tracing/module_test.go
- js/modules/k6/experimental/tracing/trace_id.go
This Pull Request addresses #2889, and adds tests ensuring that the tracing module does add a `trace_id` metadata entry when performing a request and cleans it up afterward.
To make it possible, I had to wrap a bunch of existing behaviors throughout the module in interfaces. That way I could easily swap them with mocked/controllable behaviors: trace id generation and randomness generation.
Let me know what you think 🤝 
closes #2889
> Add tests ensuring the tracing module sets and cleans up metadata properly

- metrics/sink.go
- metrics/sink_test.go
Max is not computed correctly when negative numbers are used.
> metrics: Support Trend.Max with negative values

- docs/design/018-new-http-api.md
This is a proposal/design document for a new implementation of the JavaScript HTTP API in k6.
The team has been discussing it internally for a few weeks, but the new API has been in discussion for many years prior to this. It's finally time to start working on it, so we want to share our ideas with the k6 community, and invite opinions from existing k6 users. Please be mindful to keep discussion thoughtful and relevant, in order to minimize noise.
> Design document for the new HTTP API

- js/modules/k6/experimental/tracing/client.go
- js/modules/k6/experimental/tracing/trace_id.go
- js/modules/k6/experimental/tracing/trace_id_test.go
This PR was triggered by [this comment](https://github.com/grafana/k6/pull/2894#discussion_r1137476666) from @mstoykov. It intends to refactor the trace id structure, and its encoding method in a way that decouples them from each other.
Trace ids are serialised as 16 byte slices, which are in turn encoded into hexadecimal strings that are attached to requests HTTP headers. Some parts of the trace id have a fixed size, some others, a varying one (time, and random suffix). Because some of its parts have a varying size, we need to start serializing it to find out how much space is the random suffix gonna take.
Thus, in order to decouple the trace id creation from its encoding, we have made the trace id struct private (`traceId`) private, and exposed a trace id constructor (`NewTraceID`) …
> Decouple the trace id struct generation from its encoding

- .github/workflows/build.yml
- Dockerfile
Update the Dockerfile to support cross-compile via `GOOS` and `GOARCH`. To use docker buildx cross-compile feature, the `--platform=$BUILDPLATFORM` is included for the builder stage. `BUILDPLATFORM` matches the runner machine platform and `GOOS`+ `GOARCH` is used to tell Go to cross-compile for the specific combo passed.
Move from `go install` to `go build`, because it can't install a cross-compiled binary; instead the output is saved in `/usr/bin/k6` and copied from that path in the final stage.
Change the build workflow from docker build to docker buildx create and docker buildx build. For the build command the `--platform` flag is transformed as `TARGETOS` and `TARGETARCH` variables.
This provides a faster builder stage using the native architecture, with the slow part being left to …
> Add multi-arch docker image build support

- .github/actions/lint/action.yml
- .github/workflows/lint.yml
This allows other repositories to reuse the k6 linter checks, somewhat like this:
```yml
name: Lint
on:
push:
branches:
- main
pull_request:
jobs:
lint:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Run k6 golangci-lint CI
uses: grafana/k6/.github/actions/lint@master
```
> Make the linter CI action reusable by other repos

- .github/workflows/issue-auto-assign.yml
I made a mistake in https://github.com/grafana/k6/pull/3045 and the issue auto-assignment [fails](https://github.com/grafana/k6/actions/runs/4858384591)
> Fix issue auto-assignment script

- Dockerfile
Hadolint advises to pin a version, but in this specific case isn't very useful because:
- We always want the latest version for the ca-certificates package
- It has a date-based versioning so we couldn't use the common `=~` selector for patch updates. It mostly breaks every time the Alpine repository releases a new version because they don't keep the previous one.
See also: https://github.com/hadolint/hadolint/issues/464#issuecomment-1386948671
> docker: Do not pin the ca-certs pkg

- Dockerfile
- lib/consts/consts.go
- release notes/v0.44.1.md
We should tag `v0.44.1` on this branch, and not when it's merged to `master`, to avoid releasing everything currently on `master`.
> Release v0.44.1

- js/common/tags.go
- js/modules/k6/execution/execution.go
- js/modules/k6/execution/execution_test.go
A bare minimum API to set and get metadata set for the whole VU.
It is added on top of the vu property and on top of a new `metrics` one so. If `k6/execution` is imported as `exec` -
`exec.vu.metrics.metadata["foo"]` will get you the currently set metadata for `foo` the same way `exec.vu.tags["bar"]` will get you the value of the tag `bar`.
Setting metadata is the same.
It also adds `exec.vu.metrics.tags` which is the same as `exec.vu.tags` for consistency. While leaving the old one for backwards compatibility.
This also includes dropping the ability to list metadata keys and values from `exec.vu.tags`. This was likely left in by mistake.
This is a breaking change due to the fact that before that `iter` and `vu` could've been accessed this way but this will now need to be done through the …
> k6/execution: Add metadata JS API

- cloudapi/api_test.go
- cmd/tests/cmd_run_test.go
- output/cloud/bench_test.go
- output/cloud/data_test.go
- output/cloud/metrics_client.go
- output/cloud/output.go
- output/cloud/output_test.go
The master's version mocks the test creation for all the tests doing them dependent on the resolution logic. The current PR removes this requirement and centralizes this assertion in a single test. Instead, all the other tests use a static-injected reference ID.
It should simplify the migration to something like the following architecture that I would do in https://github.com/grafana/k6/pull/3041:
output/cloud/output.go: has the logic for the test creation and cleaning up (common logic)
- output/cloud/v1/output.go has the **old** logic for metric collect/aggregate/flush
- output/cloud/expv2/output.go has the **new** logic for metric collect/aggregate/flush
Applying the current PR would be easier to eventually divide the unit tests of the test creation from the unit tests for metrics …
> cloud: Use static reference ID in tests

- cmd/tests/cmd_run_test.go
- js/bundle.go
- lib/testutils/logrus_hook.go
This adds a warning for custom metrics that are not Prometheus compatible.
The warning is in the k6/metrics as the alternative was threading a logger in the registry specifically for this and then removing it.
The major downside of this is that extension can still register incompatible metric names without any warnings.
Updates #3065
> k6/metrics: Warn on metric names not compatible with Prometheus

- cloudapi/config.go
- cloudapi/config_test.go
- output/cloud/output.go
- output/cloud/output_test.go
It implements the ability to have multiple cloud versions and it addresses a specific request change https://github.com/grafana/k6/pull/2963#discussion_r1157118508.
> output/cloud: Versioning

- .github/workflows/pr-auto-assign.yml
I am not sure this will work, I couldn't test it since apparently draft PRs are not enabled for free private repos... :sweat_smile: But I got it from https://gist.github.com/hamelsmu/4d671aae3d51f972f56e40da9c677f69 and it seems reasonable, so :crossed_fingers:
> Disable auto-assign CI job for draft PRs

- output/cloud/expv2/collect.go
- output/cloud/expv2/collect_test.go
- output/cloud/expv2/flush.go
- output/cloud/expv2/output.go
- output/cloud/expv2/output_test.go
- output/cloud/expv2/sink.go
- output/cloud/expv2/sink_test.go
- output/cloud/output_test.go
It mainly implements the same logic as for `v1` but it extends the logic to all the generated time series instead to just limit it to HTTP metrics.
It applies basic separation of concerns, so it should be easier to improve independently the various components in the future.
The flusher is not implemented but it should be mostly a wrap around the client implemented in #2963 draining the `bucketQ` buffer. I would like to get a consensus on this PR before implementing it.
The placeholder for the Trend sink will be implemented by https://github.com/grafana/k6/pull/3027
> output/cloudv2: Aggregation

- .golangci.yml
Adjust the golangci since the old exception is no more case, but after the GRPC lib update, there are new warnings that could be resolved in https://github.com/grafana/xk6-grpc/issues/14
Keep linters trusted
> .golangci.yml maintenance

- output/cloud/expv2/output.go
- output/cloud/expv2/output_test.go
It is a small refactor for the error handling on the flush operation.
> output/cloudv2: Error handling for flush

- output/cloud/expv2/flush.go
- output/cloud/expv2/flush_test.go
- output/cloud/expv2/integration/integration_test.go
- output/cloud/expv2/integration/testdata/metricset.json
- output/cloud/expv2/mapping.go
- output/cloud/expv2/metrics_client.go
- output/cloud/expv2/metrics_client_test.go
- output/cloud/expv2/output.go
- output/cloud/expv2/output_test.go
- output/cloud/output_test.go
It implements the drain of the queue of the aggregated metrics and the conversion to Protobuf.
> output/cloudv2: Flush the aggregated metrics

- output/cloud/expv2/hdr.go
- output/cloud/expv2/hdr_test.go
- output/cloud/expv2/integration/integration_test.go
- output/cloud/expv2/integration/testdata/metricset.json
- output/cloud/expv2/mapping.go
- output/cloud/expv2/sink.go
Custom Histogram representation of the Trend metric type. It is the porting of the Histogram generation on the client side.
> output/cloudv2: Trend as Histogram

- output/cloud/expv2/collect.go
- output/cloud/expv2/collect_test.go
- output/cloud/expv2/flush_test.go
- output/cloud/expv2/hdr.go
- output/cloud/expv2/hdr_test.go
- output/cloud/expv2/mapping.go
- output/cloud/expv2/mapping_test.go
- output/cloud/expv2/output_test.go
A request change from other PRs https://github.com/grafana/k6/pull/3071#discussion_r1205215842
>  output/cloudv2: Use unix nano as bucket time

- cmd/run.go
- cmd/tests/cmd_run_test.go
- metrics/engine/engine.go
The error message "thresholds have been breached" sounded harshly to my ear. Normally I associate "breaches" with illegal acts, data exfiltrations, and military sieges.
I proposed changing the verb to "cross," which is the verb used by the docs. True, I believe I wrote those docs, so I'm biased. But I also checked the [Corpus of Contemporary American English](https://www.english-corpora.org/coca/), and "cross" is by far the most common collocation (word that co-occurs) with "threshold".
> Change thresholds-error verb from breach to cross

- output/cloud/expv2/output.go
It forces the drain not only of the collector but also of the SampleBuffer when it stops gracefully. Added also a sync once controller to have mutex protection around close otherwise potentially we could have a race around the select case closing multiple times.
> output/cloudv2: Drain the SampleBuffer on stop and abort once

- cloudapi/client.go
A tiny PR to extend cloudapi interface.
Why? To make it possible to use `cloudapi.Client` in external contexts (e.g. k6-operator).
> Retrieve the host from cloudapi Client

- cloudapi/config.go
- output/cloud/expv2/flush.go
- output/cloud/expv2/flush_test.go
- output/cloud/expv2/output.go
If the number of time series is higher than the maximum batch size than split them in chunks.
Part of https://github.com/grafana/k6/issues/3117
> output/cloudv2: Flush chunks

- cloudapi/client.go
- output/cloud/expv2/flush.go
- output/cloud/expv2/flush_test.go
- output/cloud/expv2/integration/integration_test.go
- output/cloud/expv2/metrics_client.go
- output/cloud/expv2/metrics_client_test.go
- output/cloud/expv2/output.go
- output/cloud/expv2/output_test.go
- output/cloud/output.go
- output/cloud/output_test.go
It adds two features:
- HTTP requests retry
- Pool of flushers so that if a flush operation is slow, the output can continue and not get stuck.
> output/cloudv2: Retry and flushers pool

- README.md
- ROADMAP.md
The current Roadmap is out of date after just one cycle, so we decided it was more convenient to have it as an interactive GitHub project.
> Roadmap updates

- .github/workflows/build.yml
- Dockerfile
This reverts commit 9fa50b2d1f259cdccff5cc7bc18a236d31c345ac.
[Pushing of ARM images is not working](https://github.com/grafana/k6/pull/3015#issuecomment-1525428295), and there are [issues with pushing master images](https://github.com/grafana/k6/pull/3127).
Rather than deal with risky fixes with `buildx` days before the v0.45.0 release, we've decided to roll back this change and migrate to `buildx` later, once we've understood and tested the build process better.
> Revert "Add multi-arch docker image build support"

- .github/workflows/build.yml
- Dockerfile
- entrypoint-legacy.sh
With this PR we begin the deprecation process for `loadimpact/k6` Docker image. `k6` is a part of Grafana now, and we aim to continue releasing future versions under [Grafana organization](https://hub.docker.com/r/grafana/) on DockerHub.
Once merged, all future versions of `loadimpact/k6` Docker image will be displaying a warning banner that suggests migrating to `grafana/k6` before running the tool.
This PR splits the release workflow step that builds and publishes the image to Docker Hub in two stages. The first one builds `grafana/k6` image and publishes it, the second stage creates a new image that displays deprecation warning before running `k6`. This image is than published as `loadimpact/k6`.
> Deprecate loadimpact docker image

- output/cloud/expv2/metrics_client.go
We have decided to drop the check for the body's payload. The remote service will take care of splitting the chunk more if it turns out they are too big to be handled.
> output/cloudv2: Unlimited size for body payload

- cloudapi/config.go
- output/cloud/output_test.go
k6 v0.45 is now released so we bring back the cloud v2 feature flag as planned.
> cloudv2: Renable the feature flag

- output/cloud/expv2/flush.go
- output/cloud/expv2/flush_test.go
- output/cloud/expv2/metrics_client.go
- output/cloud/expv2/metrics_client_test.go
- output/cloud/expv2/output.go
- output/cloud/expv2/output_test.go
It moves the sets of the test run id and the relative URL generation from per request to once per client.
> output/cloudv2: Use a static remote service url

- docs/design/019-file-api.md
This Pull Request contains a design document for a FIle API proposal that intends to tack #2977 as part of the #2974 epic.
There is a [POC branch](https://github.com/grafana/k6/tree/poc/experimental/fs-module/js/modules/k6/experimental/fs) available containing a very very rough, but functional implementation of it.
Looking forward to your feedback and suggestions 🙇🏻
> Add File API proposal design document

- .github/ISSUE_TEMPLATE/release.md
It adds a checklist for driving a new release.
> Release checklist

- release notes/v0.46.0.md
Document changelog record for #3136.
As we agreed inside k6-core team changelog entries, PRs should follow up during the cycle, not at the end.
#3136
> changelog: a record for the

- output/cloud/expv2/integration/integration_test.go
It's better to have the tests always enabled since the initially mentioned `3s` not affecting the total time of the k6's tests (we have worse cases).
E.g. see what it looks like on a local machine (with `time`), there is no significant difference between the runs as far as I can tell.
Without integration test:
```
go test -p 2 -race -timeout 800s -count 1 ./...  250.74s user 11.43s system 211% cpu 2:03.82 total
go test -p 2 -race -timeout 800s -count 1 ./...  230.61s user 9.15s system 197% cpu 2:01.62 total
go test -p 2 -race -timeout 800s -count 1 ./...  230.08s user 9.46s system 202% cpu 1:58.57 total
go test -p 2 -race -timeout 800s -count 1 ./...  209.84s user 8.65s system 199% cpu 1:49.31 total
go test -p 2 -race -timeout 800s -count 1 ./...  219.80s user 9.31s system 201% cpu …
```
> TestOutputFlush always enabled

- .github/pull_request_template.md
Fixing the type in the Makefile target of the pull request template.
The current version doesn't work.
https://github.com/grafana/k6/pull/3131
> chore: fix typo

- output/cloud/expv2/collect.go
- output/cloud/expv2/collect_test.go
This change is done to be on par with how the core backend handles unset tags.
> output/cloudv2: Return empty string instead of "unknown" in rmCollector

- cloudapi/config.go
- cloudapi/config_test.go
- output/cloud/expv2/flush.go
- output/cloud/expv2/flush_test.go
- output/cloud/expv2/output.go
- output/cloud/output.go
Moving cloud output v2 from MaxMetricSamplesPerPackage to MaxTimeSeriesInBatch.
The new option reflects the actual purpose and usage of the config option.
Closes #3156
> Introducing the MaxTimeSeriesInBatch config option

- output/cloud/expv2/flush.go
- output/cloud/expv2/flush_test.go
- output/cloud/expv2/mapping.go
- output/cloud/expv2/output.go
Cloud Output V2 drops labels that are reserved, for now, we're sticking with the `test_run_id` and Prometheus system metrics (everything that prefixed with `__`) 
These tags are reserved for internal use and can't be set with the client.
Closes #3155
> feat: catch, discard & warn about the labels that have reserved names

- output/cloud/expv2/output.go
Add MaxTimeSeriesInBatch to the printable config.
It's good to print it for debugging/testing purposes.
* Option was introduced in https://github.com/grafana/k6/pull/3157
* #3117
> chore: add MaxTimeSeriesInBatch to the printable config

- .golangci.yml
- cloudapi/insights/proto/gen.go
- js/bundle.go
- js/compiler/compiler.go
- js/init_and_modules_test.go
- js/modules/k6/http/response_test.go
- js/modules/k6/k6.go
- js/summary.go
- js/tc39/tc39_test.go
- lib/executor/base_config.go
- lib/executor/common_test.go
- lib/executor/constant_arrival_rate.go
- lib/executor/constant_arrival_rate_test.go
- lib/executor/ramping_arrival_rate.go
- lib/netext/httpext/response.go
- lib/netext/httpext/transport.go
- lib/runtime_options.go
- metrics/thresholds_parser_test.go
- metrics/thresholds_test.go
- output/statsd/helper_test.go
Update the golangci lint to the latest version and fix some `nolint` (linter is not used) issues.
The reason behind this is a minor inconvenience after the changes for the `deepguard` linter that caused inline reporting of the blocked package.
> golangci-lint version update & minor fixes

- js/modules/k6/grpc/client.go
- js/modules/k6/grpc/client_test.go
- lib/testutils/httpmultibin/grpc_testing/nested_types.proto
`client.load()` (grpc module) was not registering protobuf nested messages in `protoregistry.GlobalTypes`.
It was necessary to go through the message structures starting from the root, but as it was before the PR, it only registered the root message.
Closes #3160 issue.
backport from [xk6-grpc PR](https://github.com/grafana/xk6-grpc/pull/23)
> fix for registering nested message types

- js/promises/promises.go
This Pull Request introduces a `promises` package (under `js`) with a single `New` helper function facilitating the creation of a promise and obtaining its `resolve` and `reject` callback from Go code.
We noticed in the context of writing extensions and experimental modules that we would consistently rewrite the same function again and again. Thus, this specific PR aims at declaring this function in a reusable place within the k6 project. 
None of this is definitive, and really is a proposal, if you have improvement ideas, shoot 🚀 
ref #3165
> Add a `promises` package with a `New` helper function

- js/promises/promises.go
- js/promises/promises_test.go
This Pull Request addresses the misuse of named arguments introduced by #3176, and fixes the resulting `registerCallback called twice` issue that followed from it.
It also adds two minimal tests covering ensuring the `resolve` and `reject` callbacks are effective. I wasn't entirely sure how to properly test that function; this is the simplest thing I came up with. I'm all ears 👂🏻 for alternatives and suggestions to improve it 🙇🏻 
As I started using the `promises.New` function in another stream of work, I noticed that as soon as I used the `promises.New` function, I would end up having `registerCallback called twice` panic all over. I tracked down the issue, and it turned out that it was because we needed to use Go named return arguments properly.
ref #3176
ref …
> Address eventloop's double registerCallback call when using promises.New

- output/cloud/expv2/hdr.go
- output/cloud/expv2/hdr_test.go
Fix the histogram's Spans encoding.
i.e., when encoding a sequence like the following: `[1, 1, 1, 0, 2, 2]`
The second span must be:
`(offset=1, length=2)`
And not:
`(offset=2, length=2)`
`histogram.Spans.Offset` is expected to be the counter of the empty buckets and not the diff between the indexes.
Follow-up on https://github.com/grafana/k6/pull/3169
> cloudv2/hdr: Fix off-by-one error for spans

- js/promises/promises_test.go
The original tests were interacting with the runtime and the event loop from outside the eventloop.
> Fix race in js/promises package's tests

- output/cloud/expv2/output.go
Fixes a bug where `K6_CLOUD_TRACES_HOST` didn't work with default values.
> output/cloudv2: Fix insights client initialization

- js/modules/k6/experimental/tracing/client_test.go
- js/modules/k6/http/async_request_test.go
- js/modules/k6/http/response_callback_test.go
- js/modules/k6/k6_test.go
- js/modulestest/runtime.go
This Pull Request adds a `RunOnEventLoop` method to the `modulestest.Runtime`, to facilitate testing code that should be dispatched to the event loop, such as code that returns promises.
While writing tests for the #3142, I stumbled upon this code from @mstoykov, with a `TODO` attached. I thought that as I was about to copy-paste that snippet anyway, I might as well do as instructed in `TODO` and move the code to the `modulestest.Runtime` class. 
The `TODO` hinted at potential improvements without detailing that I'd be nonetheless happy to include if necessary 🤞🏻
> Add a `RunOnEventLoop` method to `modulestest.Runtime`

- output/cloud/expv2/flush.go
- output/cloud/expv2/flush_test.go
1. Split also single buckets into batches if they hit the limit of series.
2. Log the stats of the flush operation:
An example of the generated logs
```
DEBU[0000] Starting executor run...                      duration=1m0s executor=constant-vus scenario=default type=constant-vus vus=1
DEBU[0006] Successfully flushed buffered samples to the cloud  output=cloudv2 t="1.253µs"
DEBU[0012] Flush the queued buckets                      batches=1 buckets=2 output=cloudv2 series=15 t=147.787055ms
DEBU[0012] Successfully flushed buffered samples to the cloud  output=cloudv2 t=147.828593ms
DEBU[0018] Flush the queued buckets                      batches=1 buckets=2 output=cloudv2 series=15 t=57.533889ms
DEBU[0018] Successfully flushed buffered samples to the cloud  output=cloudv2 t=57.597169ms …
```
> cloudv2: Create batches for single bucket flush

- log/loki.go
After #2833 log outputs were stopped but loki didn't wait until it push was finished to signal it was done.
Which leads to the actual k6 process exiting before loki could flush its messages.
> Fix loki log output exiting before push is finished

- output/cloud/expv2/output.go
- output/cloud/expv2/output_test.go
- output/cloud/output.go
It fixes the cloud v2 initialization that was using the passed client that doesn't consider the overwritten configuration. It now uses a new allocated and dedicated client based on the passed configuration that includes the overwritten fields.
> cloudv2: Make sure to use the overwritten config

- cloudapi/config.go
The backend has the limit set to 1k so it doesn't make sense to use a bigger value forcing the system to split a single batch in multiple jobs.
We are already overwriting the default value for most of the cases.  This PR removes the requirement for setting the env var for doing the overwrite simplifing internal operations.
> cloudv2: Downscale the batch size

- api/v1/group_routes_test.go
- api/v1/setup_teardown_routes_test.go
- api/v1/status_routes_test.go
- cmd/run.go
- execution/scheduler.go
- js/runner_test.go
- js/summary_test.go
- metrics/engine/engine.go
- metrics/engine/engine_test.go
- metrics/engine/ingester.go
- metrics/engine/ingester_test.go
- metrics/metric_test.go
- metrics/sample.go
- metrics/sample_test.go
- metrics/sink.go
- metrics/sink_test.go
- metrics/thresholds.go
- metrics/thresholds_test.go
This PR contains parts of https://github.com/grafana/k6/pull/2816 that are pure refactoring of various APIs, to decouple them slightly and make them more flexible and usable for the purposes of implementing distributed execution and test suites. It does not have any breaking changes and can safely be merged now. I've tried to separate the various changes into logical self-contained and small commits, so I suggest reviewing it commit by commit.
Moving these changes to a separate PR that can be merged now reduces the scope of the big PR and makes merging other backwards-compatible parts of it possible. For the parts that aren't backwards-compatible and will remain in a separate WIP PR for a long while, it makes the upkeep of the PR (i.e. rebasing it on top of `master` changes) much, much …
> Refactor various metric APIs to make distributed execution easier

- cloudapi/insights/client.go
- cloudapi/insights/client_test.go
- output/cloud/expv2/output.go
- output/cloud/v1/output.go
This PR incorporates the request metadata output into cloud output v1.
Due to cloud output v2 being at risk for v0.46.0, we decided to incorporate the new request metadata output into cloud output v1. This change is done to mitigate the risk of failing to deliver the new insights features.
This PR is part of a PR chain. Previous PR - https://github.com/grafana/k6/pull/3201.
Previous PRs:
- https://github.com/grafana/k6/pull/3100
- https://github.com/grafana/k6/pull/3158
- https://github.com/grafana/k6/pull/3184
> k6 Insights (2/2): Integrate request metadata output to cloud output v1

- output/cloud/expv2/flush.go
- output/cloud/expv2/flush_test.go
- output/cloud/expv2/output.go
- output/cloud/expv2/output_test.go
This change moves the concurrency from flushes to batches. That fixes issue #3192 and generally improves processing.
Even if the single network request to ingester is fast enough, executing them sequentially increases the time.
Closes #3192
> Implement  concurrent pushes across batches

- .github/workflows/build.yml
- Dockerfile
This PR adds a stage to the Dockerfile that adds `chromium` to the Docker image and enables k6 Browser API. The new stage is used to build and publish images with `-with-browser` label suffix.
The resulting image is fairly large (~220MB compressed compared to ~16MB without `chromium` installed), hence a separate label for those who want to opt-in to use Browser API.
Currently there is no easy way to use Browser API when running k6 as a Docker container. This makes it difficult to run browser-based tests in CI, since users need to first launch browser process in a separate container, provide the CDP URL to the k6 container and conditionally use `browser.connect()` instead of `browser.launch()` in their test scripts.
Closes #2914
> Build and publish browser-enabled Docker image

- cloudapi/logs.go
Adds two new HTTP headers required to tail logs from k6 Cloud in the near future.
See issue https://github.com/grafana/k6/issues/3216 and backlinked issue from the Grafana private repository.
https://github.com/grafana/k6/issues/3216
> Add new auth headers required for tailing k6 Cloud logs

- log/loki.go
- log/loki_test.go
Allows users to specify custom headers for the `loki` log output option. For example:
```
--log-output=loki=http://example.org,header.X-My-Header=123,header.Authorization=mytoken
```
In this case, requests done to `example.org` will contain the HTTP headers `X-My-Header: 123` and `Authorization: mytoken`.
See issue https://github.com/grafana/k6/issues/3216 and backlinked issue from the Grafana private repository.
https://github.com/grafana/k6/issues/3216
https://github.com/grafana/k6/pull/3224 (this PR implements the other half of #3216)
> Allow specifying custom headers for Loki log output

- cmd/tests/tracing_module_test.go
- js/modules/k6/experimental/tracing/module.go
- js/modules/k6/experimental/tracing/options.go
This Pull Request ensures that if the `sampling` option of the tracing module's client is not provided by the user, the Client defaults to sample 100% of the request.
```javascript
import http from "k6/http";
import tracing from "k6/experimental/tracing";
// We do not set the sampling option, thus the default
// behavior should be to always sample.
const instrumentedHTTP = new tracing.Client({
propagator: "w3c",
})
```
As noted by @Blinkuu, the current behavior of the tracing module client is to use a 0% sampling when the option is not set. It leads to effectively no HTTP request being sampled. Whereas the desired behavior would be to have all requests sampled unless instructed otherwise.
> Fix tracing module sampling option should default to 1.0 when not set

- .github/workflows/build.yml
Fixes a syntax error in the build pipeline that publishes built Docker images to Docker Hub.
Current build pipeline is broken due to a syntax error. This prevents CI from pushing the `grafana/k6:latest-with-browser` images to Docker hub as well as legacy `loadimpact/k6`
> Quote image tag when tagging :latest-with-browser images

- js/modules/k6/experimental/tracing/propagator.go
- js/modules/k6/experimental/tracing/propagator_test.go
This Pull Request contains a fix for the sample flags values being incorrect when using the tracing module's Jaeger propagator.
As reported by @Blinkuu, the sampling option of the tracing module did not set the trace header flags correctly. That led to traces not being sampled, regardless of the options set on the `instrumentHTTP` called.
This was caused by the constant values defining the sampled/unsampled flags being inverted. This Pull Request sets their values back to their specified values. It also adds tests ensuring that we observe the correct flags from the propagators `Propagate` methods under various conditions.  
#3212
> Fix tracing module's Jaeger sampling flag

- cmd/tests/cmd_run_test.go
Instead of relying on a chrome instance being present on the dev/ci machine to verify that the correct browser options do indeed start a browser process and run the browser tests, we will instead rely on the browser module trying to start a fake command and ensure that the error message verifies that it attempted to start the fake command.
We also think that this is a useful feature to help avoid unnecessary issues for users who do not work with chrome on their dev machines or aren't working with the browser module.
We're not able to run the browser module test on the arm test runner since it does not have chrome installed.
Related to the ARM runnier error here: https://github.com/grafana/k6/actions/runs/5806262818/job/15739071012
> Refactor browser module test to run a fake cmd

- release notes/v0.46.0.md
Added the changelog's entry for the new cloud output.
> changelog: Cloud output v2

- lib/consts/consts.go
- release notes/v0.46.0.md
This Pull Request bumps k6's version and updates release notes for the upcoming version `0.46`.
https://github.com/grafana/k6/issues/3138
https://github.com/grafana/k6/milestone/36
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66271
> Release notes v0.46.0

- .github/ISSUE_TEMPLATE/release.md
The release day was not tracking the action of merging the version bump's PR.
> Added the missing step for merging the bump PR

- release notes/v0.46.0.md
Adds a link to the migration guide to make the switch easier to the new browser version.
> Add browser migration guide link to the release notes

- .golangci.yml
Keep `golangci` up to date https://github.com/golangci/golangci-lint/releases/tag/v1.54.1 and ready for go1.21.
> Bump the golangci version

- .golangci.yml
- lib/executors.go
- lib/runner.go
Added `interfacebloat` linter as it is the unique linter currently disabled that we may want to enable.
Closes https://github.com/grafana/k6/issues/2715
> Add interfacebloat linter

- .github/ISSUE_TEMPLATE/release.md
This PR fixes the grammar of the release checklist, and revamps it a bit to address the unclarities I experienced when using it for the `v0.46.0` release.
The last item of the checklist is about bringing improvements to the checklist if possible, so I've given it a shot.
I found the language of the checklist could be improved to make it easier to read, and I experienced difficulties at times really understanding what I needed to do. Although I believe some further improvements would still be possible.
PS: I've also toyed with a much more concise and direct style, just like in aviation checklists, maybe that's even better?
```mardown
// ...
// ...
```
> Improve release issue template

- loader/loader.go
Change the message to make it explicit prepending `https://` to module specifiers is deprecated. 
It was there only as that was how remote modules were only loadable before it was changed that full URLs are supported. 
As there have been 4 years and it seems like nobody is using this anymore, removing it removes some guessing and warning messages that mostly confuse users.
Part of #3287
> Deprecate prepending https:// in tries to load modules

- .github/ISSUE_TEMPLATE/release.md
It fixes the relative links for the release notes item of the release template.
An example: https://github.com/grafana/k6/issues/3274
> release-template: Fix relative links

- api/v1/setup_teardown_routes.go
This PR adds error logging for setup and teardown functions invoked from REST API.
Error logging is added to enhance visibility into errors during setup and teardown, aiding debugging.
Closes #2422
> Log errors when executing setup and teardown via REST API

- .github/workflows/issue-auto-assign.yml
This change makes the issue auto-assign workflow re-usabel. That way, we could use it in our other repositories.
Currently, it's easy to miss the open issue in the other repos.
> Make auto-assing issue workflow re-usable

- js/modules/k6/grpc/client.go
- js/modules/k6/grpc/client_test.go
Use Uint8Array type in metadata declaration to avoid any reencoding issues in goja.
Changes k6's GRPC client to accept Uint8Array types passed as metadata values.
Currently k6 does not support adding binary data in the metadata. The suggestion seems to have been to convert it to a string of some sort but there are issues therein:
* Attempting to just cast bytes into a string via String.fromCharCode or String.fromCodePoint seems to have issues on the goja side. Whenever a byte is >= 0x80 (presumably) another byte is inserted before it by the time it makes it to k6 and protobuf.
* We cannot base64 the data on the JS side because protobuf will re-encode any `-bin` metadata fields itself.
As such, it would be best for k6 to properly accept Uint8Arrays in metadata.
You cannot store Uint8Array …
> Support binary passed in GRPC metadata

- go.mod
- go.sum
- vendor/github.com/dop251/goja/compiler.go
- vendor/modules.txt
Original [issue](https://github.com/dop251/goja/issues/530)
> Update goja to fix compiler bug

- Dockerfile
Bump the `alpine` version to 3.18 so we can keep our docker build up to date.
> Bump alpine version

- output/cloud/expv2/hdr.go
- output/cloud/expv2/hdr_test.go
- output/cloud/expv2/integration/testdata/metricset.json
It expands the resolution for Histograms, setting `0.001` as the minimum resolution.
It allows us to support decimal numbers up to 3 digits, increasing the detail of the values that we can store.
> cloudv2: Higher resolution for Histograms

- errext/exitcodes/codes.go
This Pull Request adds Godoc documentation comment to k6 exit codes.
I've added my context, but if reviewers have more about specific exit codes they wish to add, that would be the perfect opportunity.
Having recently been in the situation of interpreting the status code (on-call) for debugging purposes, I found that in some instances, the reason and context for each status code could have been more straightforward. Hence, I added documentation to each of them, albeit probably not complete and not having as much context as possible.
> Add documentation to k6 exit codes definitions

- Dockerfile
Drop `K6_BROWSER_ENABLED` from the Dockerfile to be consistent with the change documented here https://github.com/grafana/k6/pull/3235.
https://github.com/grafana/k6/pull/3235#issuecomment-1667691921 already applied it, but for some reason which I'm not able to get we lost it.
> dockerfile: Drop K6_BROWSER_ENABLED env

- build-release.sh
- lib/consts/consts.go
Before we were injecting the version details via ldflags. go1.18 introduced the ability to detect the commit directly from the code.
An example of the new format:
```
k6 v0.46.0 (commit/a7aa07c26b, go1.21.0, linux/amd64)
```
We benefit from it for simplifying our build process and making it more reproducible. It now prints the commit hash instead of the timestamp, in this way should be easier to use in case of troubleshooting and reports.
The original discussion where it started https://github.com/grafana/k6/pull/3322#discussion_r1318510114
> cmd/version: Commit hash

- .github/workflows/build.yml
Support docker builds for arm64
Users are requesting it more and more times 
Closes #3301
> docker: Build multi platform images

- Dockerfile
- Makefile
Move to use the cross compilation for docker multi-arch builds.
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
#3301
> docker: Multiplatform cross-compilation

- .github/workflows/build.yml
Restoring the `target` flag for building dedicated images.
https://hub.docker.com/layers/grafana/k6/master/images/sha256-fc2e78b49a3018ed0d3f79f2b58fdd4c64fde8e03f28e7f60715ac53b4e25f3e?context=explore
Check the size here, is higher than expected.
> docker/build: Restore --target flag

- js/modules/k6/grpc/client_test.go
- lib/netext/grpcext/conn_test.go
- lib/netext/grpcext/reflect.go
This is a back-port of the https://github.com/grafana/xk6-grpc/pull/48
It brings support of reflection v1 to the `k6/net/grpc`.
Reflection v1alpha is deprecated
Resolve #3222
> gRPC reflection v1

- converter/har/converter.go
From the Go specification:
> "1. For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/mMkayUyJe69
> converter/har: remove redundant nil check

- Dockerfile
Sets the `no-sandbox` chrome argument by default through the `K6_BROWSER_ARGS` ENV variable in the Dockerfile definition for the browser enabled docker image.
In order to allow chrome to execute in the browser enabled image, either `SYS_ADMIN` Docker capability or `no-sandbox` browser argument had to be set. This sets the `no-sandbox` option in the Dockerfile definition itself so this action is no longer necessary to run the Docker container. This is arguably also the better option, as we are running the chrome browser inside a container, versus using the Docker capability.
> Add `no-sandbox` arg to browser enabled Docker image

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-grpc/grpc/client.go
- vendor/github.com/grafana/xk6-grpc/grpc/params.go
- vendor/modules.txt
This PR updates xk6-grpc dependency to the latest available version.
This change brings the new `reflectMetadata` to the connection parameters.
This is likely the version of the `k6/experimental/grpc` module that will be released in the following k6 v0.47.
https://github.com/grafana/xk6-grpc/pull/51
> Update xk6-grpc to the latest version

- cmd/tests/cmd_run_test.go
- js/bundle.go
This is inline with the current restriction.
The previous 63 character one came from Otel, but with https://github.com/open-telemetry/opentelemetry-specification/pull/3648 This has been bumped to 255.
Updates #3065
> Bump future metric name length to 128

- js/modules/k6/http/request.go
- lib/netext/httpext/batch.go
Previous http.batch code did call `runtime.NewArrayBuffer` concurrently.
Which never has been guaranteed to be safe, but with the latest goja changes to having prototypes created on demand it races.
The fix *might* have some performance implications, but they are likely to be very small as `NewArrayBuffer` mostly wraps stuff so ... hopefully not a big deal.
> Fix race in http.batch after latest goja update

- js/modules/k6/grpc/client.go
- js/modules/k6/grpc/client_test.go
- js/modules/k6/grpc/teststate_test.go
This PR contains several parts:
* First is refactoring of calling and connection params to make code more re-usable
* Second is the significant (but is mostly moving  & cleaning) refactoring of the gRPC client's test
* last but not least is an introduction to the `reflectMetadata` 
The refactoring was done to make the following changes tinier and pay some technical dept of removing copy-pasting.
The `reflectMetadata` was requested in #3241 
https://github.com/grafana/xk6-grpc/pull/51
Closes: #3241
> Refactoring of gRPC internals & tests and introducing the `reflectMetadata`

- release notes/v0.47.0.md
This adds the changes to the `v1.1.0` tagged browser module to the release notes. It doesn't add the changes for `cookies` and `page.on` since they are being added by two other PRs.
We need to update our users of what changes we have made to the browser module.
Related: https://github.com/grafana/k6/pull/3353 & https://github.com/grafana/k6/pull/3352.
> v0.47.0 release notes for browser

- release notes/template.md
UX section as h2 in release notes
https://github.com/grafana/k6/pull/3360#discussion_r1344582568 and it is how we did in the previous versions https://github.com/grafana/k6/blob/master/release%20notes/v0.46.0.md#ux-improvements-and-enhancements
> Move the improvements section as h2

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-output-prometheus-remote/pkg/remotewrite/config.go
- vendor/modules.txt
Bump Prometheus remote write output's version to v0.3.1 that includes the Bearer Token fix.
> Bump Prometheus remote write output

- lib/consts/consts.go
Bump k6 version as defined by https://github.com/grafana/k6/issues/3274:
>Open a separate PR for bumping [the k6 Go project's version](https://github.com/grafana/k6/blob/9fa50b2d1f259cdccff5cc7bc18a236d31c345ac/lib/consts/consts.go#L11).
> Bump the k6 version to v0.47.0

- .github/ISSUE_TEMPLATE/release.md
Minor fixes to the release task template:
* Avoid tagging teams at the beginning. Fix `devrel` since this is a real Github handle and it's mentioning
* Minor style & grammar fixes
Improve the release task template
> Minor fixes to the release task templates

- js/console.go
- js/runner.go
This fixes `console.debug()` messages printing with `--console-output file.txt` and `-v` given to k6 cli.
This already works when it isn't redirected to a file as it goes through the application wide logger.
> fix: Set console log level to the application one when writing to file

- js/bundle.go
- js/bundle_test.go
- js/console.go
- js/console_test.go
- js/empty_iterations_bench_test.go
- js/http_bench_test.go
- js/initcontext_test.go
- js/module_loading_test.go
- js/runner.go
- js/runner_test.go
- js/summary.go
Fix js package lint issues
Part of #linter issues https://github.com/grafana/k6/issues/769
> Fix js lint

- output/csv/config.go
- output/csv/config_test.go
Removed the options using the snake_case format, instead use the alternative camelCase versions.
Removed the options using the snake_case format (e.g.`file_name`), instead use the alternative camelCase versions (e.g. `fileName`).
Deprecation process.
> output/csv: Remove the support for snake_case options

- cloudapi/config.go
This commit updates the default value of the `tracesEnabled` option, enabling it by default. 
We hope this change can help drive ease of use of the Distributed Tracing in Grafana Cloud k6 feature.
Enables request metadata output (https://github.com/grafana/k6/pull/3201, https://github.com/grafana/k6/pull/3202) by default.
> Set `K6_CLOUD_TRACES_ENABLED` to `true` by default

- js/modules/k6/grpc/client.go
- js/modules/k6/grpc/client_test.go
In #2371 we deprecated the `headers`  param in favor of `metadata`. 
https://github.com/grafana/k6/blob/1892f9120b4a414cf7847a83126b3b02b60e65ff/js/modules/k6/grpc/client.go#L449-L452
Since it seems like a long time passed, we could finally remove the support of the `headers`.
And as the first step, we could start erroring if the `headers` param is presented. 
Once this PR is merged, I'll open the PR with the far-away milestone to clean the error advising the use of `metadata`.
We should clean up the `headers`
_Minor breaking change_: Previously, gRPC invoke's `headers` param was deprecated and fell through to the `metadata`. Since this version of k6, using the `headers` param will result in an error. Instead, users should use the `metadata` param. …
> Erroring if gRPC parameters contains headers key

- cmd/tests/cmd_run_test.go
- js/runner.go
This was mistakenly broken in 7b5aaaa0
> js: Return the new deadline error when running code

- .github/pull_request_template.md
- .golangci.yml
- CONTRIBUTING.md
- Makefile
We introduced the `ci-like-lint` target a while ago #2316. Since then, our linter's config didn't have the list of used linters, and upgrading the golangci-lint could cause triggering issues that were never seen before, which slowed the process of the actual work.
In #2715 we switched to the close-list of the linters that we run, and using different versions of the golangci-lint shouldn't cause a significant difference.
It seems safe to remove the `ci-like-lint` and keep only the `lint` target which runs on the host machine.
Also, this PR updates the version of the golangci and refactors a bit the Makefile, making it self-explanatory. 
Removing the `ci-like-lint` we do a cleanup and simplify the process. It also improves the developer UX since the `make lint` is more common and intuitive …
> Remove Makefile's `ci-like-lint` target

- cloudapi/config.go
- output/cloud/output_test.go
It sets the default version for the Cloud output as `v2`.
Closes https://github.com/grafana/k6/issues/3258
> output/cloud: Set v2 as the default

- go.mod
- go.sum
- vendor/github.com/dop251/goja/builtin_json.go
- vendor/modules.txt
https://github.com/dop251/goja/issues/543
> Update goja dependency version

- Makefile
Tiny fix for the makefile.
Current behavior:
```bash
❯ make all
cleaning
make: *** No rule to make target `test', needed by `all'.  Stop.
```
New behavior: Runs all commands
Make all should succeed
> Fixed the tests reference in the all rule of the Makefile

- go.mod
- go.sum
- vendor/github.com/dop251/goja/vm.go
- vendor/modules.txt
It fixes an issue about dumping the correct stack trace when an error is re-thrown. https://github.com/dop251/goja/commit/b396bb4c349df65109dea3df00fb60f6a044950d
> Bump goja version

- release notes/v0.48.0.md
Adds an entry for the `browser.closeContext()` method under the _UX improvements and enhancements_ section.
So it's properly documented as a new enhancement for the `v0.48.0` release.
Code: https://github.com/grafana/xk6-browser/pull/1074
Docs: https://github.com/grafana/k6-docs/pull/1376
> Add `browser.closeContext()` to v0.48 release notes

- output/influxdb/config.go
- output/influxdb/config_test.go
- output/influxdb/util.go
This PR closes #3418 by adding the K6_INFLUXDB_PROXY environment variable support.
This PR fixes the problem when your InfluxDB server is not opened for direct connections and requires a connection through proxy.
Closes #3418
> Adds the K6_INFLUXDB_PROXY environment variable support, closes #3418

- js/modules/k6/experimental/fs/file.go
- js/modules/k6/experimental/fs/file_test.go
- js/modules/k6/experimental/fs/module.go
- js/modules/k6/experimental/fs/module_test.go
This Pull Request aims to address #3354, and avoid data races involved in using the [currently proposed implementation of `fs.read` and `fs.seek`](#3309).
Namely, it modifies the behavior of the proposed `fs.read` and `fs.seek` methods to avoid data races due to:
1. accessing the `fs.read` buffer argument concurrently
2. updating the file offset concurrently when calling seek
In a nutshell, we addressed _1_ by ensuring that the provided buffer was only modified from the JS runtime's main thread, by performing it as a side-effect of the promise resolution's. We addressed _2_ by making sure the internal file structure's offset is an atomic int that cannot, as a result, be modified by two concurrent operations at the same time.
ref #3309
ref #2974 
closes #3354
> Address potential races in `fs.read` and `fs.seek` operations

- release notes/v0.48.0.md
Update the next release notes with links to the PRs that have fixed and refactored code to get `waitForEvent` to work.
To update the release notes for the next release.
> Add waitForEvent tasks to release notes

- cloudapi/config.go
This commit updates the default value of `K6_CLOUD_TRACES_HOST` to target the new endpoint in Grafana clusters.
This change is done as part of the infrastructure migration efforts. Existing customers are not impacted since `insights.k6.io` now uses the CNAME record to redirect to the new hostname.
Output from `dig`:
```bash
dig insights.k6.io
; <<>> DiG 9.10.6 <<>> insights.k6.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58234
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;insights.k6.io.			IN	A
;; ANSWER SECTION:
insights.k6.io.		300	IN	CNAME	grpc-k6-api-prod-prod-us-east-0.grafana.net.
grpc-k6-api-prod-prod-us-east-0.grafana.net. 60	IN …
```
> Set `K6_CLOUD_TRACES_HOST` to new hostname

- release notes/v0.48.0.md
This adds an internal change to the release notes. This adds https://github.com/grafana/xk6-browser/pull/1090 which moves from `ioutil` to `io` and `os` packages.
To keep the maintainers informed of release changes.
> Add internal browser change

- examples/experimental/fs/fs.js
- js/modules/k6/experimental/fs/errors.go
- js/modules/k6/experimental/fs/errors_gen.go
- js/modules/k6/experimental/fs/file.go
- js/modules/k6/experimental/fs/file_test.go
- js/modules/k6/experimental/fs/module.go
- js/modules/k6/experimental/fs/module_test.go
This Pull Request builds (and is based) upon #3142 and adds a `read` and a `seek` method, the the `File` object exposed by the `k6/experimental/fs` module. 
The `File.read` method allows to read a file into a `Uint8Array`. The amount of bytes read is equal to the size of the provided buffer.
The method resolves to either the number of bytes read during the operation or EOF (represented as `null`) if there is nothing more to read.
The `File.seek` method allows to seek to a specified `offset` within a file under the given `whence`.
The offset is expressed in bytes. Whence allows you to seek from the start of the file (the offset needs to be strictly negative), the current position within the file (offset can be either positive or negative), or from the end of the file (offset needs to be …
> [fs] Add `file.read` and `file.seek` methods to the `fs` module (2/3)

- js/modules/k6/http/request_test.go
- lib/netext/httpext/compression.go
Before this on a response which has a Content-Encoding value, but no body will error out with EOF as we still try to decode it.
As the code and the semantics of network requests mean that we might not know if we are going to be able to read something and whether we got and EOF because of network error or because there was no body - we need to figure out if we should try to read at all.
Unfortunately `Content-Encoding: chunked` exists which makes a more general solution much harder IMO.
As such the current solution is to short circuit on known status codes that do not have content. Namely all 1xx and 204 (aptly named no content) and 304 (not modified).
https://www.rfc-editor.org/rfc/rfc9110.html#section-6.4.1-8
Additionally a bare minimum tests was added reproducing what the user reported. …
> fix EOF errors on http response with content and encoding headers

- Dependencies.md
Writes down the information about the golang updates convention.
To have this written down.
> Golang versions convention

- api/server.go
- cmd/root.go
- cmd/run.go
- cmd/state/state.go
- cmd/ui.go
This change exposes profiling endpoints for the k6.
This won't have significant performance implications (if the endpoints are not used), so we could expose them by default.
But having this endpoint allows efficient development of k6 (and extension) 
Closes #1692
> Expose profiling endpoints

- release notes/v0.48.0.md
Add grafana/xk6-browser#1078 to release notes.
This adds a note about a network interception deadlock fix.
grafana/xk6-browser#1072
> Add request interception fix to release notes

- cmd/root.go
- cmd/tests/cmd_run_test.go
- cmd/version.go
Adds support for `--version` global flag that matches the `version` subcommand.
Running the usual Unix-like flags returns an error.
<https://github.com/grafana/k6/issues/2352>
> Add support for --version flag

- js/initcontext.go
- lib/fsext/filepath.go
- lib/fsext/filepath_unix_test.go
- lib/fsext/filepath_windows_test.go
This PR adds a `fsext.Abs` helper function to facilitate computing the absolute path of a file.
Similar code already exists in the current `master` branch: https://github.com/grafana/k6/blob/5e83d389fde71d3d7bf96fbe98d9a2938e903b82/js/initcontext.go#L23 and as the `fs` module also relies on the same operation, I took this opportunity to refactor it in a the `lib/fsext` package.
ref #3165 (blocks)
> Add fsext.Abs helper function

- cmd/tests/cmd_run_test.go
- js/bundle.go
- metrics/registry.go
- metrics/registry_test.go
> metrics: enforce more otel/prometheus aligned names

- cmd/root.go
- cmd/root_test.go
Removed the deprecated --logformat flag, the --log-format alternative should be used.
Deprecation process.
> Remove the --logformat flag

- .github/workflows/issue-auto-assign.yml
- .github/workflows/pr-auto-assign.yml
Adds [`joanlopez`](https://github.com/joanlopez) to _auto-assign_ GitHub workflows.
Onboarding new maintainer.
N/A
N/A
> Add joanlopez to auto-assign gh workflows

- release notes/v0.48.0.md
Adds the `page.throttleCPU` and `page.throttleNetwork` changes to the release notes which were implemented in the browser module.
To notify users of the latest new feature.
Updates: https://github.com/grafana/xk6-browser/issues/887
> Add CPU and Network throttling to release notes

- .golangci.yml
Bump golangci-lint to the latest version. It contains the fixes for the `gosec` linter, which won't cause false-positive errors.
Otherwise, we must make inline exceptions in the projects using the same linter ruleset.
For cases like:
```golang
const distributionKey = "LOREM_IPSUM"
```
it could scream that this is hardcoded credentials.
> Bump golangci-lint to v1.55.2

- release notes/v0.48.0.md
Adds https://github.com/grafana/xk6-browser/pull/1106 and https://github.com/grafana/xk6-browser/pull/1096 to the release notes.
These were deemed necessary fixes to go into the release which will benefit users.
> Add browser patch fixes to release notes 

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/tc39.yml
- .github/workflows/test.yml
- .github/workflows/xk6.yml
- Dockerfile
This is as otherwise we will/might get the old 1.21.4 and we want to release with the new one.
This is to be reverted after v0.48.0 is released.
> Pin golang version to 1.21.5 in github actions and docker

- lib/consts/consts.go
This bumps k6 to v0.48.
We're going to release the v0.48.
Part of #3382
> Bump the k6 version to v0.48.0

- api/server.go
- api/server_test.go
works on #769 
This also fixes a bug where we always logged all responses were 200 ... :facepalm:
> Fix lint issues in api package

- js/compiler/compiler.go
> Fix lint issues in js/compiler

- output/cloud/output.go
- output/cloud/output_test.go
- output/cloud/v1/data.go
- output/cloud/v1/output.go
- output/cloud/v1/output_test.go
> Fix lint issues in output/cloud/*

- output/csv/config.go
- output/csv/config_test.go
- output/csv/output.go
- output/csv/output_test.go
This pull request fixes the linter issues in the output/CSV package.
As we agreed, we aim to fix most of the linter issues.
Part of #769
> Minor refactoring of the CSV output

- api/v1/client/client.go
- api/v1/group.go
- api/v1/group_routes_test.go
- api/v1/metric.go
- api/v1/metric_routes_test.go
- api/v1/setup_teardown_routes_test.go
- api/v1/status.go
- api/v1/status_routes.go
- api/v1/status_routes_test.go
This PR addresses the linter issue reported for an `api/v1` package. 
As we agreed we'd like to fix the existing issues for the master branch and this PR is part of that movement.
Part of https://github.com/grafana/k6/issues/769
> Adressing linter issues for the `api/v1` package

- js/modules/k6/crypto/crypto.go
- js/modules/k6/crypto/crypto_test.go
- js/modules/k6/crypto/x509/x509.go
- js/modules/k6/crypto/x509/x509_test.go
- js/modules/k6/encoding/encoding.go
- js/modules/k6/encoding/encoding_test.go
This PR fixes ~105 linter issues in `js/k6/crypto` and `js/k6/encoding` packages.
It's recommended to start looking by commits.
As we agreed, we aim to fix most of the linter issues.
Part of #769
> Linter fixes for the crypto and encoding k6 modules

- .github/ISSUE_TEMPLATE/release.md
Document changes in a release process.
It's essential to keep the checklist of the release activities up to date.
> Release process recent changes

- lib/fsext/changepathfs.go
- lib/fsext/walk.go
> Fix lint issues in lib/fsext

- js/modules/k6/http/request.go
- lib/netext/dialer.go
- lib/netext/httpext/batch.go
- lib/netext/httpext/compression.go
- lib/netext/httpext/error_codes_syscall_posix.go
- lib/netext/httpext/error_codes_test.go
- lib/netext/httpext/request_test.go
- lib/netext/httpext/tracer.go
- lib/netext/httpext/tracer_test.go
- lib/netext/httpext/transport.go
- lib/netext/httpext/transport_test.go
- lib/netext/resolver_test.go
- lib/netext/tls.go
This PR addresses the linter issues in the `netext` package.
It's better to do a review by commits. I've tried to combine them for the impact.
The first commit is applying simple changes.
Everything else deserves a more focused look since it also contains some refactorings.
Note: one linter issue is still there:
```
lib/netext/httpext/request.go:122:2                nestif             `if preq.Body != nil` has complex nested blocks (complexity: 6)
```
Since the function it deserves a separate PR, it's more complicated.
https://github.com/grafana/k6/blob/856a767bda62fe5a0f1fd6ee6e354e39539ea97d/lib/netext/httpext/request.go#L109-L114
Also, `grpcext` package's linter issues have yet to be touched since I'm planning to address them in #3152 
As we agreed, we have to fix the linter issues …
> Adressing linter issues in `netext`, `netext/httpext` packages

- .github/workflows/trivy.yml
This adds the trivy security scanner scheduled check to k6 repository. It aims to check the `master` tag (the most up-to-date). 
Inspired by: https://github.com/grafana/agent/blob/main/.github/workflows/trivy.yml
It has no slack integration _yet_, first I'm curious to see the frequency of the reporting. If it's acceptable and we won't be use this actively by-ourselves we could set up the slack integration.
Currently, it shows no issues, so it's a good opportunity to start using it.
```
trivy image grafana/k6
2023-12-11T15:08:04.324+0100    INFO    Vulnerability scanning is enabled
2023-12-11T15:08:04.324+0100    INFO    Secret scanning is enabled
2023-12-11T15:08:04.324+0100    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning …
```
> Adds trivy scheduled checks

- go.mod
- go.sum
- vendor/modules.txt
Update x/crypto and x509roots/fallback
There is moderate security issue - one that we do not actually hit.
It still will be nice to not get flagged by scanners.
> Update x/crypto and x509roots/fallback - no actual changes

- release notes/v0.49.0.md
Listing PRs in v0.49.0 release notes for:
- https://github.com/grafana/xk6-browser/issues/987
- https://github.com/grafana/xk6-browser/issues/981
- https://github.com/grafana/xk6-browser/issues/469
Keep users up to date with browser module changes.
> Add various browser module changes

- cloudapi/errors_test.go
- cloudapi/util_test.go
I added some unit tests
Hi, thank you very much for this awesome tool! I am using it for quite some time now and LOVE it. I was looking through the code base and I like it a lot and wanted to contribute some tests. 
I will eventually contribute more in the future!
> Add unit tests

- js/initcontext_test.go
- js/runner.go
- lib/netext/httpext/error_codes_test.go
- lib/netext/httpext/tracer.go
- lib/testutils/httpmultibin/httpmultibin.go
It removes all the uses of `net.Dialer.DualStack`, because now it's deprecated, and the desired behavior (enabled) is now by default. It also slightly modifies few comments to make that more clear.
Not sure why `staticcheck` is not complaining, but I guess it's always good idea to stop using a deprecated field, especially in this case that I can't see any pain.
N/A
> Stop using deprecated net.Dialer.DualStack

- release notes/v0.49.0.md
Updates v0.49.0 release notes for the PRs: grafana/xk6-browser#1137 and grafana/xk6-browser#1145.
Provides better error messages when Chromium/Chrome isn't found.
grafana/xk6-browser#1136
> Browser: Update release notes for chrome not installed errors

- release notes/v0.49.0.md
Adds `clear` to the `locator` PR (https://github.com/grafana/xk6-browser/pull/1149) to the release notes.
Keep users informed of the new addition.
Updates: https://github.com/grafana/xk6-browser/issues/1114
> Add clear to the locator PR to the release notes

- .github/dependabot.yml
This PR adds Dependabot config to check for experimental module updates daily and create PRs to upgrade them. 
The process of releasing a new version of an experimental module, such as xk6-browser or xk6-redis, requires a manual step to upgrade the dependency in k6's `go.mod`, vendor the code and open a PR. This is a routine task that can be automated to avoid human error.
> Automate experimental module updates

- js/runner_test.go
It modifies the `TestVUIntegrationClientCerts` test on `runner_test.go` in order to generate certificates at runtime, instead of using pre-generated ones.
This test is currently failing when `runtime.GOOS == "darwin"`, because it expects the `"certificate signed by unknown authority"` error but it gets `"certificate is not standards compliant"` instead, because the pre-generated certificate has a validity of 1000 years since 2022, and that's not considered standards compliant by Apple.
So, instead of having a pre-generated certificate that expires every year (so we'd need to update it every year), this makes the test to generate the required certificates at runtime (so always up to date), which also seems to be fine for MacOS.
I think it fixes https://github.com/grafana/k6/issues/2578, …
> Generate certificates at runtime for runner test

- api/v1/group_routes_test.go
- api/v1/setup_teardown_routes_test.go
- api/v1/status_routes_test.go
- cmd/archive.go
- cmd/cloud.go
- cmd/inspect.go
- cmd/run.go
- cmd/test_load.go
- execution/controller.go
- execution/local/controller.go
- execution/scheduler.go
- execution/scheduler_ext_test.go
- execution/scheduler_int_test.go
- js/runner_test.go
This is another sliver of the [newly refactored](https://github.com/grafana/k6/pull/2816#issuecomment-1635466149) https://github.com/grafana/k6/pull/2816, a follow-up to https://github.com/grafana/k6/pull/3191.
It adds the concept of an `execution.Controller`, a very lightweight API by which multiple k6 instances could synchronize the concurrent execution of different [segments](https://k6.io/docs/using-k6/k6-options/reference/#execution-segment) of the same test run. However, it doesn't actually add any distributed execution by itself, just a `local` implementation of it that doesn't do anything (because a single instance doesn't need to synchronize with itself... [yet](https://github.com/grafana/k6/issues/1342) :sweat_smile:)
This is a backwards-compatible prerequisite for distributed …
> Introduce `execution.Controller` with a `local` no-op implementation

- cmd/report_test.go
Fixing the tests I just broke :sweat_smile: 
Merging https://github.com/grafana/k6/pull/3204 for old times' sake apparently broke some recently introduced tests :sweat_smile: 
https://github.com/grafana/k6/pull/3204
> Fix report tests

- cmd/tests/cmd_run_test.go
Fixes `TestBrowserPermissions` [failure](https://github.com/grafana/k6/actions/runs/7500578048/job/20419551355?pr=3537). Expects the fake command to be in the error message rather than looking for the entire message to be more resilient for future changes.
We've changed the browser not found error message in grafana/xk6-browser#1136. So, this PR (#3537) that includes the new changes currently fails without this fix.
grafana/xk6-browser#1136
> Fix browser not found err in TestBrowserPermissions

- output/cloud/expv2/integration/integration_test.go
- output/cloud/expv2/integration/testdata/metricset.json
- output/cloud/expv2/output_test.go
- output/cloud/insights/enable.go
- output/cloud/output_test.go
Use raw `Bool` instead of `ValueOrZero`.
If the value hasn't been set by the user, the default value set to `true` in https://github.com/grafana/k6/pull/3398 was not respected.
Fixes a bug introduced in https://github.com/grafana/k6/pull/3398.
> Fix k6-insights enabled check

- release notes/v0.49.0.md
Adds release notes for tracing instrumentation implemented in k6 browser module.
Required step towards `v0.49.0` release.
grafana/xk6-browser#1100
grafana/xk6-browser#1104
> Add browser tracing release notes

- release notes/v0.49.0.md
Adding https://github.com/grafana/xk6-browser/pull/1152 to the `v0.49.0` release notes.
To keep our users up-to-date with the new fix.
> Fix NPD in browser frame

- .github/workflows/test.yml
- js/runner_test.go
It enables `macos-latest` for test-related (`test.yml`) CI workflows.
Ha, why not? Jokes aside, imho now that MacOS-related issues (https://github.com/grafana/k6/issues/2578 and https://github.com/grafana/k6/issues/1230) have been closed (fixed), and that it looks like MacOS runners have at the very least a performance equivalent to Windows runners' (in fact, [test jobs seems to be taking less time in MacOS runners](https://github.com/grafana/k6/actions/runs/7493056548)), I guess it's good idea to make the check of the good functioning of k6 on MacOS part of the CI checks.
Also, in the worst case we can disable it again, but why not giving it a try?
I haven't found any.
> Run CI (tests) on MacOS

- README.md
- js/initcontext.go
- js/modules/k6/k6.go
- loader/loader.go
- metrics/engine/ingester.go
- metrics/thresholds_parser.go
This PR switches the URLs from the `k6.io/docs/` to the `grafana.com/docs/k6/latest/`
`grafana.com/docs/k6/latest/` is the primary source of the documentation right now.
> Switching to grafana URLs

- release notes/v0.49.0.md
Changelog entry for the report.
> Changelog for the report updates

- .github/workflows/issue-auto-assign.yml
Run the Triage workflow if a comment has been added to an issue without an assignee. It adds an event as described here https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
It makes sure comments are not lost and we can react in case needed.
> github: Run the triage process for comments

- go.mod
- go.sum
- vendor/modules.txt
Upgrade xk6-dashboard to v0.7.2
gomod: sync'd the dependencies with k6.
https://github.com/grafana/xk6-dashboard/pull/146
> xk6-dashboard upgraded to v0.7.2

- release notes/v0.49.0.md
In the `v0.49.0` release notes, the default URL port of the web dashboard was incorrectly `6565`, which was changed to the correct value of `5665`.
> docs: fix web dashboard default URL port

- .golangci.yml
- js/modules/k6/http/file.go
- js/modules/k6/http/http.go
- js/modules/k6/http/request.go
- js/modules/k6/http/request_test.go
- js/modules/k6/http/response.go
- js/modules/k6/http/response_callback_test.go
- js/modules/k6/http/response_test.go
Updates https://github.com/grafana/k6/issues/769
> js/k6/http: Fix lint errors

- js/modules/k6/grpc/client_test.go
It removes a few gRPC client tests.
Because by observing them running in CI, and based on what has been discussed in https://github.com/grafana/k6/pull/3545 and #3551, it looks like these have a flaky nature that's not easy to fix, and we even have doubts about its utility, so better to remove them for now.
I also tried to replace the hard-coded certificates, as suggested in https://github.com/grafana/k6/issues/3549, and in a similar way as in https://github.com/grafana/k6/pull/3527, but in this case it's not as easy as that because the server we use for the these tests (`HTTPMultiBin`) heavily relies on `httptest.NewTLSServer` from Go stdlib, which manages its own set of certificates. 
Indeed, that's the reason why we also have to use the `example.com` domain there.
So, I'd suggest to …
> Remove flaky gRPC tests

- .github/actions/lint/action.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/issue-auto-assign.yml
- .github/workflows/lint.yml
- .github/workflows/packager.yml
- .github/workflows/tc39.yml
- .github/workflows/test.yml
- .github/workflows/xk6.yml
Update actions to version using node 20
node 16 is EoL and will be dropped by github in sprint 2024 - so soon :tm: 
#3572
> Bump to github actions to use node 20

- CODEOWNERS
As the title mentions, it excludes the `release notes` folder from the CODEOWNERS and consequentially from the auto-assignment in case of pull requests.
The authors will have to manually assign the reviewers by picking a team (`k6-core` or `k6-browser`) and/or single team members. 
Hopefully, it will make the assignments more relevant to the context of the working area.
> Exclude release notes folder from CODEOWNERS

- lib/archive.go
- lib/consts/consts.go
- lib/context.go
- lib/execution_segment.go
- lib/execution_segment_test.go
- lib/executor/base_executor.go
- lib/executor/common_test.go
- lib/executor/constant_arrival_rate.go
- lib/executor/constant_vus.go
- lib/executor/constant_vus_test.go
- lib/executor/executors_test.go
- lib/executor/externally_controlled.go
- lib/executor/per_vu_iterations_test.go
- lib/executor/ramping_arrival_rate.go
- lib/executor/ramping_arrival_rate_test.go
- lib/executor/ramping_vus.go
- lib/executor/shared_iterations.go
- lib/executor/shared_iterations_test.go
- lib/executor/vu_handle_test.go
- lib/models.go
- lib/netext/httpext/request.go
- lib/options.go
- lib/options_test.go
- lib/types/hostnametrie.go
- lib/types/hosts.go
- lib/util.go
> lib: lint fixes

- cloudapi/api.go
- cloudapi/api_test.go
- cloudapi/client.go
- cloudapi/config.go
- cloudapi/errors.go
- cloudapi/errors_test.go
- cloudapi/logs.go
- cloudapi/logs_test.go
- output/cloud/expv2/output.go
- output/cloud/expv2/output_test.go
- output/cloud/v1/output.go
- output/cloud/v1/output_test.go
This has a breaking change in the API as it renames an error type.
This should not really be used by anything, but tests :crossed-fingers:
works on #769
> cloudapi: fix lint issues

- .github/workflows/test.yml
It adds the use of pre-compiled Go tip (https://github.com/grafana/gotip).
To speed up the Go tip related CI jobs runs (_it is much faster to download the artifacts and unzip them, than downloading the source code and building it on CI_).
> Use pre-compiled Go tip

- lib/testutils/untar.go
This attempts to fix the "noise" from the security tab (CodeQL reported).
Fixing such cases helps us focus on the right things.
> fix zip-slip noise in tests

- .github/workflows/codeql-analysis.yml
Switching to the most recent version of the CodeQL.
```
This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
```
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
An example: https://github.com/grafana/k6/actions/runs/7842697583
> Update codeql to v3

- go.mod
Bumps the Go module version to 1.20.
The browser team wants to use the new multi-error feature.
N/A
> Bump Go module version to 1.20

- lib/executor/ramping_arrival_rate.go
- lib/executor/ramping_arrival_rate_test.go
It slightly modifies how the execution requirements are calculated to prevent issues when the execution is segmented and the `PreAllocatedVUs` aren't evenly distributed (not divisible by the number of segments).
Previously, `PreAllocatedVUs` were not always correctly subtracted from `MaxVUs`, causing weird situations during the load zone distribution calculations.
> Fix ramping-arrival-rate execution requirements

- .github/workflows/issue-auto-assign.yml
Previously the action was checking always whether the author of the issue was one of the maintainers instead of whether the comment was created by a none-maintainer.
So we do not get assigned issues when we (the maintainers of k6) comment on them.
> Fix auto assign on issue comment

- cloudapi/config.go
- cloudapi/config_test.go
- cmd/archive_test.go
- cmd/cloud.go
- cmd/login_cloud.go
- cmd/tests/cmd_run_test.go
- lib/options.go
- output/cloud/output.go
This is an attempt to introduce the new option `cloud`, which should start the process of sunsetting the `options.ext.loadimpact`
The `options.ext.loadimpact` is the legacy option, and we should migrate from it to something more neutral like `cloud`
Closes #1155
> Introducing options.cloud

- release notes/v0.50.0.md
Add 1215 to release notes.
Keep the users up to date with a new bug fix that they may encountering.
Updates: https://github.com/grafana/xk6-browser/issues/1066
> Add 1215 to release notes

- release notes/v0.50.0.md
Add screenshot upload release notes.
Update users of a UX improvement where by the browser module can be configured to upload screenshot to a remote location.
> Add screenshot upload release notes

- release notes/v0.50.0.md
Update release notes for grafana/xk6-browser#1217.
> Add browser 1217 to release notes

- release notes/v0.50.0.md
Update release notes for https://github.com/grafana/xk6-browser/pull/850.
Should we combine this with the big refactor internals?
> Add browser 850 and other Go 1.20 PRs to release notes

- cmd/cloud.go
- cmd/login_cloud.go
- cmd/new.go
- cmd/tests/cmd_cloud_test.go
- output/cloud/output.go
These changes aim to start promoting the `options.cloud`. It's the state when it's safe to say to customers that it's safe to use. 
These changes were originally part of #3348, but there is a chance that we could merge #3348, but we won't be ready to start offering usage of the `options.cloud`.
Reduce the scope and try to make #3348 mergable.
* #3348 
* #3394
> Warnings about options.cloud

- lib/executor/helpers.go
- lib/executor/ramping_arrival_rate.go
- lib/executor/ramping_vus.go
- lib/executor/ramping_vus_test.go
It validates the VU values. If a VU is larger than the chosen constant, an error is appended.
This includes the startVU.
The conclusion was reached to handle it that way during the discussions of this pull request.
Closes #1693
> handling large vu shifts

- release notes/v0.50.0.md
Add xk6-browser#2066 to release notes.
Keeps users up to date.
https://github.com/grafana/k6-cloud/issues/2066
> Add xk6-browser#2066 to release notes

- .github/workflows/build.yml
Update sbom github action to use node20
Makes all our github actions use node 20
> Update sbom github action to use node 20

- docs/design/020-distributed-execution-and-test-suites.md
- execution/controller.go
> fix some comments

- release notes/v0.50.0.md
Add browser#1242 release notes.
Keep users up to date with fixes.
https://github.com/grafana/xk6-browser/issues/1243
> Add browser#1242 release notes

- release notes/v0.50.0.md
Updating the browser#1097 release notes to take into account the change to the API which is in browser#1244.
There's been a change in the API.
https://github.com/grafana/xk6-browser/pull/1244
> Update browser#1097 release notes

- release notes/v0.50.0.md
Updates the release notes for https://github.com/grafana/xk6-browser/pull/1246.
> Add browser 986

- lib/types/hosts.go
- lib/types/hosts_test.go
It updates the `Hosts` type constructor `NewHosts` store `source` keys (i.e. hosts) lowercased, to consider them case insensitive. The internal trie, and the [`Hosts.Match`](https://github.com/grafana/k6/blob/master/lib/types/hosts.go#L142-L157) is already considering them insensitive, as they're treated as lowercase.
Because otherwise, `options.hosts` doesn't work well with non-lowercase hosts.
Closes https://github.com/grafana/k6/issues/3651
Also related with https://github.com/grafana/k6/issues/3620
> Make options.hosts case insensitive

- go.mod
- go.sum
- vendor/github.com/go-sourcemap/sourcemap/README.md
- vendor/github.com/go-sourcemap/sourcemap/consumer.go
- vendor/modules.txt
It bumps the go-sourcemap dependency.
We fixed a bug on the upstream and we need to fix a panic issue.
Closes https://github.com/grafana/k6/issues/3556
> Updated go-sourcemap to v2.1.4

- lib/executor/executors_test.go
- lib/executor/ramping_arrival_rate.go
Validate timeUnit in ramping-arrival-rate isn't 0 apart from not being negative.
Previous to this negative time units will error but 0 timeunit will panic.
This was fixed in constant-arrival-rate long ago, but nobody checked ramping-arrival-rate.
> Validate timeUnit in ramping-arrival-rate

- release notes/v0.50.0.md
This is to notify all browser APIs users that in a future release we will be breaking most of the APIs by moving them to async (`Promise`).
To notify users of this change so that they are forewarned of it and maybe start preparing for it.
https://github.com/grafana/xk6-browser/issues/428#issuecomment-1964020837
> Add browser async breaking change

- lib/consts/consts.go
This Pull Request bumps k6's `lib/consts.go` file to reflect version `v0.50.0`.
#3577
> Bump k6 version to v0.50

- .github/ISSUE_TEMPLATE/release.md
s/v0.4x/v0.5x/g
We passed the v0.4x phase. So, it would require to change all the time the number from `4` to `5`. Let's reduce at minimum the chance of error.
> Bump the version for the release template

- lib/executor/base_config.go
It slightly modifies the errors related with scenarios' name (like empty or prohibited characters).
Because, as stated in #3601, the current error messages are misleading.
I might be wrong, but in my opinion, I understand that every object under the `scenarios` key is a scenario definition, thus the key is the name of the scenario, not the name of the executor (type). Also, that's what can be guessed from [our docs](https://grafana.com/docs/k6/latest/using-k6/scenarios/executors/):
```
scenarios: {
arbitrary_scenario_name: {
//Name of executor
executor: 'ramping-vus',
// more configuration here
},
},
};
```
So, `arbitrary_scenario_name` is the scenario name, and `ramping-vus` is the executor, it's name/type.
Closes #3601
> Make errors with scenarios' name more clear

- cmd/config_consolidation_test.go
- go.mod
- go.sum
- vendor/github.com/mstoykov/envconfig/envconfig.go
- vendor/modules.txt
It updates the [`envconfig` dependency](https://github.com/mstoykov/envconfig) to include a [recent fix](https://github.com/mstoykov/envconfig/pull/1) to adequately support nil marshalable pointers,
which is causing #3638.
After having discarded https://github.com/grafana/k6/pull/3660, we decided (see [here](https://github.com/grafana/k6/pull/3660#discussion_r1549862704) and [here](https://github.com/grafana/k6/pull/3660#discussion_r1542767339)) to just push the fix to our own fork of [`envconfig`](https://github.com/mstoykov/envconfig), for simplicity.
Closes #3638
> Update 'envconfig' to fix environment variables reads

- js/bundle.go
- js/runner.go
- js/runner_test.go
Stop unsetting `open` and `require` after init context just do redo some of the work.
This still prevents them being used outside of the init context.
This was done to prevent them to be used outside of the init context, except that this wasn't enough as you can save them to another variable.
More fixes have been added on top - but in reality there is no need to unset them.
If anything this makes it harder for users to figure out what happens as in the case of `require` it will tell you that you can't call `undefined`.
For `open` this was handled by setting it to a function that just reports it can't be used outside the init context. But this is already the case if it isn't unset and then reset to this function.
So this change makes the whole thing more consistent and doesn't do a bunch …
> Don't "unset" `open` and `require` after the init context

- cloudapi/client.go
- cloudapi/config.go
- cloudapi/config_test.go
Some leftover lint fixes and just move to crypto/rand for the idempotency token.
Part of #769
Fixes lint issues
> cloudapi: lint fixes + just use crypto/rand

- js/jsmodules.go
- js/modules/k6/grpc/grpc.go
This change completely removes the experimental GRPC module, as it was announced in https://github.com/grafana/k6/pull/3490
The same functionality is in k6-core, and we waited for several releases.
https://github.com/grafana/k6/pull/3490
> Completely remove experimental GRPC module

- js/bundle.go
- loader/loader.go
- loader/readsource.go
- loader/readsource_test.go
Usually the working dir for a given script is set based on it's path.
For test from stdin that path is file:///- so it is basically the root folder. With this change this changes to the directory k6 was ran from.
This means when you do `cat script.js | k6 run -` the working dir will be the same as if you did `k6 run script.js`.
But there is still no way to fix `cat path/to/somewhere/script.js | k6 run -` as k6 can't know where it got it's stdin from.
fixes #1462
Fixing the issue and potentially having less people report it 
This is marked as breaking change as it changes the behaviour - arguably most people expect the new behaviour, so I expect no users actually depend on the current one.
> Set working dir to the current one if test is read from stdin

- .golangci.yml
Update golangci-lint and fix configuration warning
To keep it up to date and also to fix the warning for users who do not run the *exact* version we run in the CI. 
There are some loop var linters around go 1.22 changes in behaviour, but we are not using only go1.22+ so we can't use them.
There is also a new open telemetry span linter which also doesn't seem like a thing we can use.
The configuration change is due to deprecation from 5 years, but golangci-lint just wasn't reporting until 1.57.2.
> Bump golangci-lint to 1.57.2 and fix configuration warning

- js/path_resolution_test.go
Add more tests for paths and ESM
Found corner cases that ESM make harder to handle and/or break.
Other PRs will handle fixing and warning them.
> js/path_resolution_test: more ESM related tests

- README.md
Mention that we do consider the upvotes as an essential metric for feature prioritization.
We should be transparent with the community.
> chore: importance of upvotes

- CONTRIBUTING.md
This pull request updates an incorrect URL for golangci-lint in the documentation to the correct URL.
before: https://golangci-lint.run/usage/install/#local-installation (now, 404 page not found)
↓
after: https://golangci-lint.run/welcome/install/#local-installation
URL is changed.
> Fix Incorrect golangci-lint URL in Documentation

- .github/workflows/build.yml
It removes the (_already commented out_) `publish-macos` CI job that was originally added to automate k6 releases publication to [Homebrew](https://brew.sh/).
Because it's no longer needed, as now Homebrew [has a recurrent (every 3h) CI job](https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/autobump.yml) that goes over all the Homebrew projects and checks for updates.
Look at [this PR](https://github.com/Homebrew/homebrew-core/pull/167104), as an example, from the latest k6 release (v0.50.0).
Closes #1998
> Remove no longer needed CI job (Homebrew)

- .github/workflows/test.yml
This PR temporarily disables running the tests in CI on the Mac OS platform because it's too flaky right now.
If this PR is approved after the merge, I'll open a separate issue for investigation and bring Mac OS tests back.
Unfortunately, Mac OS tests failed for many runs. Constantly failing tests are destructive for the project since people tend to trust test runs less, and we could miss something essential.
> ci: temporary disable running tests on macOS

- js/bundle.go
- js/modules/resolution.go
- js/runner_test.go
Make it an error to try to resolve not previously resolved modules, after initialization
Partly because it should be given how we make k6 work and want `k6 archive` and `k6 cloud` to "just work".
Partly because this ended up being the only not completely hackish way to know that we are past the initialization state which was needed in order to make a warning only in the init context. 
See https://github.com/grafana/k6/pull/3681
> Lock module resolution after initialization

- js/modules/require_impl.go
- js/path_resolution_test.go
Add warning on require invocations that do not follow the specification.
Depends on https://github.com/grafana/k6/pull/3680
As this isn't how it works we would like to fix it.
Also happens to be hard to keep it working once we move to ESM.
part of #3534
> Emit warning if require will not comply with specification

- go.mod
- go.sum
- vendor/google.golang.org/grpc/clientconn.go
- vendor/google.golang.org/grpc/internal/channelz/funcs.go
- vendor/google.golang.org/grpc/version.go
- vendor/modules.txt
Bumpt grpc dep
Mostly to revert a change where they deprecated an API.
The API will be depracated in a later version again, but we can skip seeing the warning and decide to move of it in #3699
> Bump google.golang.org/grpc to v1.63.2 from v1.63.0

- .golangci.yml
- js/bundle_test.go
- js/modules/k6/http/request_test.go
- js/runner_test.go
- lib/executor/constant_vus_test.go
- lib/executor/executors_test.go
- lib/executor/externally_controlled_test.go
- lib/executor/per_vu_iterations_test.go
- lib/executor/shared_iterations_test.go
- lib/executor/vu_handle_test.go
- lib/netext/httpext/error_codes_test.go
- log/file_test.go
- metrics/engine/ingester_test.go
Disable forcetypeassert on tests.
It seems most core developers agree this isn't really a good linter for tests and makes a lot of them more complicated or longer.
see https://github.com/grafana/k6/pull/3701#discussion_r1574671547
> golangci-lint: Disable forcetypeassert for tests

- js/modules/k6/grpc/client.go
- js/modules/k6/grpc/client_test.go
- lib/netext/grpcext/conn.go
- lib/netext/grpcext/conn_test.go
This PR refactors the logic of the grpc's unary `Invoke` so that it can be reused in the `AsyncInvoke` and also implements `AsyncInvoke` itself.
It's better to check the changes by the commits.
At the k6-core, we agreed that the modern way of defining API is the async one.
Closes #3550
> gRPC async invoke

- release notes/v0.51.0.md
Add recent browser PR merges to release notes.
To keep users up to date with browser related changes.
https://github.com/grafana/xk6-browser/pull/1259
https://github.com/grafana/xk6-browser/pull/1260
https://github.com/grafana/xk6-browser/pull/1261
https://github.com/grafana/xk6-browser/pull/1262
https://github.com/grafana/xk6-browser/pull/1264
> Add recent browser PR merges to release notes

- cmd/config_consolidation_test.go
- cmd/state/state.go
Add env option K6_PROFILING_ENABLED to enable it in k6
Fix issue #3670
- [ x] I have performed a self-review of my code.
- [ x] I have run linter locally (`make lint`) and all checks pass.
- [ x] I have run tests locally (`make tests`) and all tests pass.
> feat: promote env variable to ProfilingEnabled option

- js/modules/k6/execution/execution.go
- js/modules/k6/execution/execution_test.go
Fixes a panic when accessing `k6/execution`.test.options in the init context.
Not to panic but give an exception.
> k6/execution:Don't panic on accessing test.options

- js/compiler/compiler.go
- js/initcontext_test.go
Fix sourcemaps when they are inlined.
Before that if there was an inline sourcemap we won't load it and go through the already used method of updating it. 
This isn't a problem if babel actually transpiles it as it will load it, but in case the sourcecode was already transpiled with inline maps this will now update the lines correctly.
To have correct lines when people user sourcemaps . 
#3689
> fix line numbers when inline sourcemap is used

- release notes/v0.51.0.md
Add a breaking-change note for the async `Tap` method.
The `Tap` method is converted from sync to async.
Updates: grafana/xk6-browser#1251
> Release notes: Browser async `Tap`

- examples/experimental/ws.js
Update experimental/websocket example to set binaryType as to not get a warning after latest update
> Update experimental/websocket example

- .golangci.yml
Golangci-lint config fixes.
`deadline` was renamed to `timeout` ... long time ago.
And  config verificaiton showed more settings that were no longer available and were removed.
The ci keeps timing out - so lets actually configure it correctly.
Cleaning up the config along the way.
> Increase golang ci lint timeout

- release notes/v0.51.0.md
Add https://github.com/grafana/xk6-browser/pull/1291 to the release notes.
Keep users up to date of changes.
https://github.com/grafana/xk6-browser/issues/1144
> Add browser#1291 release notes

- lib/consts/consts.go
It bumps the k6 version to `v0.51.0`. It is part of the release process https://github.com/grafana/k6/issues/3662.
> Bump k6 version to v0.51.0

- js/common/util.go
Stop printing an empty stacktrace of goja when capturing panics.
This has been broken for years after some goja refactoring.
There doesn't seem to be a way for this to be fixed without a lot of boilerplate all over the code. And this functionality has not been used in the last few years in my experience.
> Don't print empty goja stacktraces on captured panics

- api/v1/group_routes.go
- api/v1/group_routes_test.go
- cmd/run.go
- cmd/test_load.go
- cmd/ui.go
- js/initcontext_test.go
- js/modules/k6/grpc/params_test.go
- js/modules/k6/grpc/teststate_test.go
- js/modules/k6/http/request_test.go
- js/modules/k6/http/response_test.go
- js/modules/k6/k6.go
- js/modules/k6/k6_test.go
- js/modules/k6/ws/ws_test.go
- js/runner.go
- js/runner_test.go
- lib/models.go
- lib/runner.go
- lib/test_state.go
- lib/testutils/minirunner/minirunner.go
- lib/vu_state.go
Group and check were tightly coupled between them and also to the end of test summary and the REST API.
This change the tight coupling is removed. Group and check no longer interact with each other while being run.
In order to keep the same end of test summary and REST API behavior the code makes the same aggregation it used to be but *only* based on the metrics emitted by `check` and `group`.
There are several breaking changes still in it as a bunch of things are no longer useful, and technically not implementable if we want to remove the tight coupling.
The only one that is relevant though is that
`lib.State` no longer has `Group`.
There are 2 extensions using that and both of them use it to use the "magic" that tight `group` and `check` together.
The previous code apart from having …
> Refactor group and check to not be tightly coupled

- lib/executor/ramping_vus_test.go
Fix race conditions in ramping-vus tests
See https://github.com/grafana/k6/actions/runs/9283064573/job/25542459831 failure
During #3470 some sub tests were added and they access the same variable from the not sub test.
This obviously is a race condition that nobody noticed.
> Fix race condition in ramping-vus tests

- .golangci.yml
It removes an old linter setting, set for gRPC's reflection.
Because the issue used to track it was completed some months ago.
So, it should no longer be required, or we should re-open it create a new issue.
> Drop old linter setting (GRPC's reflection)

- .github/ISSUE_TEMPLATE/config.yml
The old link was pointing to the deprecated community.k6.io that doesn't redirect to the k6 section on community.grafana.com
> Fix the Community URL in the Issue template

- js/modules/k6/timers/timers.go
- js/modules/k6/timers/timers_test.go
This PR fixes a panic that could be caused by a script like:
```js
export default function() {
setInterval(undefined, 100);
}
```
We shouldn't panic
> Handling undefined function in timers

- js/modules/k6/grpc/stream.go
- js/modules/k6/grpc/stream_test.go
This PR fixes a panic that happens if pass undefined (null) handler to the `stream.on`
E.g.
```js
stream.on("data", undefined)
```
We shouldn't panic
> Fixes `undefined` handler passing to the gRPC stream

- js/modules/k6/experimental/streams/module.go
- js/modules/k6/experimental/streams/module_test.go
It addresses https://github.com/grafana/k6/pull/3740#discussion_r1631126330
Forgotten after a UI-through rename suggestion.
> Missing 'streams' variable & test renames

- cmd/tests/cmd_run_test.go
- examples/experimental/browser.js
- js/jsmodules.go
Provides two JS import paths:
* `k6/experimental/browser`: The k6 browser sync API shipped in k6 0.51 (which we're planning to remove in k6 0.54).
* `k6/browser`: The k6 browser async API.
Closes: #3778
* Large breaking changes are no longer expected.
* [Async API](https://github.com/grafana/xk6-browser/issues/428) w/Playwright compatibility and API stability.
* Major runtime stability issues are fixed (although there are still some minor issues).
* Tested on the cloud, and no regressions.
- grafana/xk6-browser#428
- grafana/xk6-browser#1117
> Graduate to `k6/browser` from an experimental module

- cmd/ui.go
This PR switches to debug the log level of the case when we can't get the terminal size.
As was shown in #3796, there could be no error, but we still can't determine the size of the terminal. It seems that it's not important since it's just switching some of the rendering features. However, having this as the `warning` in CI pipelines affects UX usage.
Closes #3796
> Log as debug the case when we can't get terminal size

- cmd/archive.go
- cmd/archive_test.go
This PR allows k6 to output archives to stdout when the special value `-` is used as the argument to `--archive-out`.
The only current way I know of to tell k6 to output an archive to stdout is to specify `--archive-out=/dev/stdout`. However, this relies on `/dev` existing, which in some fringe cases may not be the case, e.g. when running inside a chroot.
https://github.com/grafana/sm-k6-archiver/pull/25
>  cmd/archive: output archive to stdout if - is passed as --archive-out 

- cmd/archive_test.go
A follow-up to https://github.com/grafana/k6/pull/3797, which I didn't want to push over as it already has approvals.
Additionally to check for non-existence of `archive.tar`, also check for non-existence of a file named `-`, which could happen if the special case of `-` = stdout is mishandled.
https://github.com/grafana/k6/pull/3797
>  cmd/archive: additionally test for non-existence of file named `-`

- js/compiler/compiler.go
- js/compiler/compiler_test.go
As part of testing for #3265 it was noticed this isn't uncommon.
As there is no way for this to be supported and it will be against how the specification works we prefer to warn users on this at least for a little while.
> Warn on mixing ESM and commonJS

- lib/consts/consts.go
It bumps the k6 version to `v0.52.0`. It is part of the release process https://github.com/grafana/k6/issues/3766.
Closes https://github.com/grafana/k6/issues/3802
> Bump k6 version to v0.52.0

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-browser/browser/browser_mapping.go
- vendor/github.com/grafana/xk6-browser/browser/sync_browser_mapping.go
- vendor/github.com/grafana/xk6-browser/common/browser.go
- vendor/github.com/grafana/xk6-browser/common/browser_context.go
- vendor/github.com/grafana/xk6-browser/common/helpers.go
- vendor/modules.txt
- [Fix potential races in createWaitForEvent*](https://github.com/grafana/xk6-browser/pull/1389)
- [Desobekify Browser](https://github.com/grafana/xk6-browser/pull/1389)
- [Updates to k6 `master`](https://github.com/grafana/xk6-browser/pull/1392)
To prevent potential race conditions.
> Updates to latest browser

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-dashboard/dashboard/customize.go
- vendor/modules.txt
Upgrade xk6-dashboard to v0.7.5
Configuration customization from JavaScript code has been removed
Until now, the dashboard configuration could be customized with a JavaScript code. Supporting this feature after switching the JavaScript interpreter (goja to sobek) causes serious difficulties. Since this feature is rarely used, it is easier to drop it than to support it.
> feat: upgrade xk6-dashboard to v0.7.5

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-websockets/websockets/blob.go
- vendor/github.com/grafana/xk6-websockets/websockets/helpers.go
- vendor/github.com/grafana/xk6-websockets/websockets/websockets.go
- vendor/modules.txt
Updates to the latest version of xk6-websockets, which includes support for [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob).
See https://github.com/grafana/xk6-websockets/pull/74 for further details.
Contributes to https://github.com/grafana/xk6-websockets/issues/35
> Update to xk6-websockets@v0.6.0

- js/jsmodules.go
Update k6/experimental/timers warning as we missed to dropp it in v0.52.0 and it seems to still be fairly used. 
Also mae it the same as for experimental/browser
To give more time to users and to be more useful.
> Update k6/experimental/timers warning and consolidate with browsers

- README.md
- We encounter k6 OSS users who don't know we have cloud. 
- Browser wasn't mentioned.
> Add Browser and cloud support information to README

- go.mod
- go.sum
- vendor/google.golang.org/grpc/metadata/metadata.go
- vendor/google.golang.org/grpc/version.go
- vendor/modules.txt
Update grpc for security fix
The fix is actually in x/net/http2 , but this gRPC lib is also marked as having it, instead of just propagating from x/net/http2.
So this is mostly to stop github recommend us to update on push
> Update google.golang.org/grpc v1.64.0 => v1.64.1 - security fix

- cmd/outputs.go
We fixed the version of the k6 where we aimed to remove the statsd output, and it also updates the recommendation for the datadog output 
Part of #2982
> Update StatsD output deprecation (define removal version)

- js/modules/k6/grpc/stream.go
- js/modules/k6/grpc/stream_test.go
Update the grpc stream being call to pass tags and params that include custom tags and method information
Addresses https://github.com/grafana/k6/issues/3745
https://github.com/grafana/k6/issues/3745
Closes #3745
> Fix metrics for GRPC streams do not correctly include tags when stream ends

- js/jsmodules.go
Recommedn just using the globally availabe timers instead of `k6/timers`
There is no reason to import them.
> Recommend using the globally available timers

- js/jsmodules.go
Deprecate k6/experimental/tracing. 
The module is now fully available as javacript implementation from https://jslib.k6.io/ and documented [here](https://grafana.com/docs/k6/latest/javascript-api/jslib/http-instrumentation-tempo/)
Closes #3212
> Deprecate k6/experimental/tracing

- cmd/runtime_options.go
- js/bundle.go
- js/compiler/compiler.go
- js/compiler/compiler_test.go
- js/initcontext_test.go
- js/tc39/README.md
- lib/runtime_options.go
Cleanup comments and messages around ESM merge
A lot of those comments no longer make sense with Babel gone and some refactoring of the internals
> Cleanup comments and some code after ESM merge

- cmd/run.go
- js/common/interrupt_error.go
- js/console_test.go
- js/modules/k6/experimental/streams/errors.go
- js/modules/k6/experimental/streams/readable_stream_reader.go
- js/modules/k6/experimental/streams/tests/testharness.js.patch
- js/modules/k6/html/gen/gen_elements.go
- js/modules/k6/ws/ws.go
Some places where Goja was uppercased have been missed in the previous times this was accessed.
It will be confusing some places mentioning Goja and some Sobek
#3817
> More Goja to Sobek substitutions

- js/modules/k6/http/request_test.go
As part of 1.22 minimum tls version by default is now 1.2, but the test didn't specify lower one, even though they are testing exactly that.
While we still haven't set the go directive in go.mod ot 1.22 - we will do it one day and it will be better if things to fail then.
> Fix tls min version in tests with go 1.22

- cmd/cloud_login.go
**Supersedes #3835** 
It drops the support for the interactive login with email and password from the [recently introduced](https://github.com/grafana/k6/pull/3813) `k6 cloud login` subcommand.
Because that authentication mechanism is considered deprecated, and so we only leave the support for it through the deprecated `k6 login cloud` subcommand, but not in the new `k6 cloud login` command.
> Drop support for log in with email & password in the new `k6 cloud login`

- release notes/v0.53.0.md
Release notes for v0.53.0
Explain what is new in v0.53.0
> Release v0.53.0

- SUPPORT.md
~~The Slack link on our support page works for all the already registered users but it doesn't work anymore for new users. I replaced the link based on the k6io domain with the workspace's link under slack.com domain.~~
Update: we decided to drop the links to Slack k6io workspace. It isn't anymore an official channel supported by the core team. 
Closes #3887
> Update the Support page

- .golangci.yml
- cloudapi/client.go
- cloudapi/logs.go
- cmd/scale.go
- cmd/tests/cmd_run_test.go
- js/modules/k6/crypto/x509/x509.go
- js/modules/k6/grpc/client.go
- js/modules/k6/http/response_callback.go
- js/modules/k6/http/tls_test.go
- js/runner.go
- js/runner_test.go
- lib/archive.go
- lib/executor/base_config.go
- lib/executor/executors_test.go
- lib/executor/helpers.go
- lib/netext/grpcext/conn_test.go
- lib/options.go
- lib/options_test.go
- output/cloud/expv2/flush.go
- output/cloud/output_test.go
- ui/form.go
- ui/pb/helpers.go
Update golangci-lint to 1.60.1
Once again a new release of go makes golangci-lint use all available memory.
This also fixes some new linter issues, mostly:
- staticheck dropping a bunch of checks
- min/max overriding. They are now build-in in 1.21+, but I didn't want to replace them and bump to 1.21 in this commit already, given the whole toolchain thing.
- printf not being error checked or not being used with format + arguments.
> Update to golangci-lint 1.60.1 to support go 1.23

- .golangci.yml
- cloudapi/client.go
- cloudapi/logs.go
- lib/executor/vu_handle.go
Add new linters from golangci-lint update 
- fatcontext prevents a problem we had in the past where you keep adding variables to a context 
- canonicalheader has some performance improvements as it doesn't require go to canonize the header on each invocation
Those are the only new linters since last we updated
> golangci-lint: enable fatcontext and canonicalheader

- cmd/cloud.go
- cmd/root_test.go
When implementing the new cloud command structure, we marked the
k6 cloud command as deprecated by setting the `cobra.Cmd`, `Deprecated`,
option.
By doing so, Cobra took over itself to hide the command all in all from
the help text's output, and users couldn't see the cloud command as
part of the "Available Commands".
This PR removes the Cobra.Cmd Deprecated option usage, and ports
the message to the Long version of the help text.
This PR also rephrases the message to be more accurate. Considering
the cloud command itself is not deprecated, but rather its existing
behavior, we have mentioned the original behavior consisting in taking
a test resource as input is deprecated, specifically.## What?
We discovered that while shipping the new cloud command structure, we had missed the cloud …
> Fix cloud command not listed in k6 command's help text

- release notes/v0.54.0.md
Adding https://github.com/grafana/xk6-browser/pull/1406 to the release notes.
Keep users up to date with fixes in the browser module.
https://github.com/grafana/xk6-browser/pull/1406
> Add browser#1406 to v0.54.0 release notes

- cmd/cloud.go
- cmd/tests/cmd_cloud_test.go
_(**Note:** It looks like there is probably a couple of scenarios more that could also be reported more concretely, but I prefer to open a separate pull request for each, so we can discuss them independently)_
It handles the exceptional case when `testProgress.RunStatus == cloudapi.RunStatusFinished` but with `testProgress.ResultStatus == cloudapi.ResultStatusFailed`, which means that the test run failed due to thresholds being crossed, in order to exit with the specific error code (`ThresholdsHaveFailed = 99`).
**Before**
```
> k6 cloud playground/script.js
...
...
...
test status: Finished
Run    [======================================] Finished
ERRO[0044] The test has failed                          
exit status 97
```
**After**
```
> k6 cloud playground/script.js
...
...
...
test …
```
> Report ThresholdsHaveFailed on Cloud runs

- execution/scheduler_ext_test.go
- js/runner.go
- js/runner_test.go
- lib/netext/dialer.go
- output/cloud/insights/collect_test.go
Drop the NetTrail container and emit iterations metric in runner instead of in Dialer.
Also fix #1605 
As part of looking over issues I found #1250 which has some additional work required. But dropping the specific NetTrail and moving the code around was really simple. 
FIxing some of the test took a bit more time :(
#1250 
#1605
> Drop NetTrail - emit iterations metrics in runner instead of dialer

- go.mod
- go.sum
This PR switches requirements go minimum 1.21 and introduces the `toolchain` into the `go.mod`
Soon, we'll start actively use go 1.23, which leads us anyway to implement this change since `toolchain` nowadays a default output of the `go mod`
> Switch to the go1.21, introduce toolchain to go.mod

- cmd/cloud.go
- cmd/cloud_login.go
- cmd/cloud_upload.go
- cmd/tests/cmd_cloud_upload_test.go
It introduces a new cloud subcommand: `k6 cloud upload` to replace the old `k6 cloud --upload-only`.
It also marks the old flag as deprecated, so it is no longer displayed in help, and a deprecation message is displayed when used, as follows: *`Flag --upload-only has been deprecated, use "k6 cloud upload" instead`*.
As part of the task of revamping the k6 cloud commands.
N/A
> Introduce k6 cloud upload to replace --upload-only

- js/modules/k6/grpc/stream.go
- js/modules/k6/grpc/stream_test.go
- lib/netext/grpcext/conn.go
- lib/netext/grpcext/stream.go
Adds a new gRPC stream option `discardResponseMessage`. See #3820.
Parsing heavy responses can result in high CPU and memory usage.
https://github.com/grafana/k6/pull/3820
> Add `discardResponseMessage` option for gRPC stream

- js/tc39/README.md
This documents my recent learnings from the conversation with @mstoykov and recent PR about maintaining of tc39 test
Knowledge sharing
> Document maintanance of tc39

- .github/actions/lint/action.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/tc39.yml
- .github/workflows/test.yml
- .github/workflows/wpt.yml
- .github/workflows/xk6.yml
Since no 1.23.1 has been released, we updated our workflows to use that version as the current one.
Keep go version up to date.
> Update go workflows to 1.23

- js/console_test.go
- js/module_loading_test.go
- js/runner_test.go
- js/share_test.go
Refactor js tests so we do not repeat the same pattern to create a runner from an archive.
This was copy-pasted around and similar to how getSimpleRunner makes it hard to refactor if you add new fields that need to be around always.
We could also make a helper to create a runner + archive and run the provided test as function argument. But that would work in a lot less of the cases and isn't as necessary for #3917 to be a bit less noisy.
> js: DRY creation of a runner from archive in the tests

- api/v1/group_routes_test.go
- cmd/outputs.go
- cmd/report.go
- cmd/report_test.go
- cmd/runtime_options_test.go
- cmd/test_load.go
- execution/scheduler_ext_exec_test.go
- execution/scheduler_ext_test.go
- js/bundle.go
- js/bundle_test.go
- js/console_test.go
- js/init_and_modules_test.go
- js/modules/k6/marshalling_test.go
- js/modules/resolution.go
- js/modulestest/runtime.go
- js/runner.go
- js/tc39/tc39_test.go
- lib/test_state.go
- lib/vu_state.go
- output/cloud/output.go
- output/cloud/output_test.go
- output/types.go
- usage/usage.go
- usage/usage_test.go
Implement support to collect Usage dynamically
Previously Usage collection happened in one place in a pull way. The usage report needed to get access to the given data and then pull the info from it and put it in.
This reverses the pattern and adds (if available) the cloud test run id to the usage report.
Future work can pull a bunch of the other parts of it out. For example:
1. used modules can now be reported from the modules
2. outputs can also report their usage
3. same for executors
Currently all the above are still done in the usage report code, but that is not necessary.
This also will allow additional usage reporting without the need to propagate this data through getters to the usage report, and instead just push it from the place it is used.
Allowing potentially reporting usages …
> Implement support to collect Usage dynamically

- js/jsmodules.go
Drop k6/experimental/timers
We have stabilized the API and it is now available for k6/timers for some time. We would like to stop supporting the old import path.
> Drop experimental timers

- cmd/report.go
It updates the endpoint used to send [usage stats](https://grafana.com/docs/k6/latest/set-up/usage-collection/), to the service used by the rest of the projects of the organization.
Because that's the one used by the rest of the projects of the organization, and the legacy (current) one will be deprecated soon. See some examples:
- Loki: https://github.com/grafana/loki/blob/main/pkg/analytics/stats.go#L27
- Grafana: https://github.com/grafana/grafana/blob/main/pkg/infra/usagestats/service/usage_stats.go#L29
Closes #3878
> Use the new usage-stats endpoint

- cmd/ui.go
- lib/consts/consts.go
to
Updating the banner logo. 
Terminal colors are user configurable so on my terminal "yellow" is ... green :P
> Update k6 logo

- js/bundle.go
- js/bundle_test.go
It early returns when `options` is `nil`, to prevent reaching the point where `json.Marshal(v.Export())` with `v == nil`.
To prevent it from panicking.
In v0.52, that code was slightly different: https://github.com/grafana/k6/blob/v0.52.0/js/bundle.go#L176, and so the value received was `goja.valueUndefined`, which is enough for not panicking when calling `json.Marshal(v.Export())`.
Since changes introduced in v0.53, `v` is `nil`, and thus it panics.
Another approach that I suggested was changing the behavior of [`SourceTextModuleInstance.GetBindingValue` in Sobek](https://github.com/grafana/k6/blob/master/vendor/github.com/grafana/sobek/modules_sourcetext.go#L63-L69), so it returns `sobek.Undefined()` when no _getter_ is found, but @mstoykov had doubts around the general correctness of …
> Prevent panic when 'options' value is nil

- js/bundle.go
- js/compiler/compiler.go
- js/modules/require_impl.go
Add reporting some additional usages to better figure how k6 is used.
We do need to make decisions on what to work on or break or keep working if it is problematic.
We usually make a lot of those based on anecdotal data or only on data we have access through direct communication with customers. This is not terrible but definitely leaves us with blind spots.
The newly added usage counters have descriptions in each of the commits and are used for different areas where we might decide to cleanup k6 or work more on a give feature.
> Add additional usages

- release notes/v0.54.0.md
Add:
- https://github.com/grafana/xk6-browser/pull/1408
- https://github.com/grafana/xk6-browser/pull/1422
To keep users up to date with latest fixes in browser.
> Add release browser 1408 1422

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-browser/browser/module.go
- vendor/github.com/grafana/xk6-browser/browser/registry.go
- vendor/github.com/grafana/xk6-browser/chromium/browser_type.go
- vendor/github.com/grafana/xk6-browser/common/browser.go
- vendor/github.com/grafana/xk6-browser/common/connection.go
- vendor/modules.txt
Update to latest browser v1.8.2
- Includes the memory leak fix that was a regression.
- Includes the NPD fix.
https://github.com/grafana/xk6-browser/issues/1429
https://github.com/grafana/xk6-browser/pull/1432
> Update to latest browser v1.8.2

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-browser/common/page.go
- vendor/modules.txt
Fixes a NPD in `elementHandle.checkHitTargerAt` in the browser module.
Avoids aborts which may not be needed.
> Update to k6 browser 1.8.3

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-browser/common/element_handle.go
- vendor/modules.txt
Contains a fix to prevent a goroutine from hanging around.
Avoids having to force abort the test if it seems to hang.
https://github.com/grafana/xk6-browser/issues/1437
> Update to 1.8.4 of the browser moduler

- event/system.go
- event/system_test.go
This removes the `default` case for when reading done events from the extension or when sending events to the extension.
If we drop events due to the channel being full and there being a `default` case, then we can end up in a situation where either the event system indefinitely waits since incoming done events were not handled by the event system or the extension waits indefinitely if the event was dropped when sending it the event.
https://github.com/grafana/xk6-browser/issues/1440
> Fix buffered chan event system

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-browser/chromium/browser_type.go
- vendor/github.com/grafana/xk6-browser/common/browser.go
- vendor/github.com/grafana/xk6-browser/common/connection.go
- vendor/modules.txt
Updates to browser v1.8.5.
Fixes a situation where the browser might hang if the browserProc exits before the connection closes.
Related: https://github.com/grafana/xk6-browser/issues/1440
> Update to browser v.1.8.5

- go.mod
- go.sum
- vendor/github.com/grafana/xk6-websockets/websockets/websockets.go
- vendor/modules.txt
Update xk6-websockets
Fix `readyState` in `k6/experimental/websockets` to actually be a number.
> Update xk6-websockets to fix readyState bug

- .github/dependabot.yml
Add more dependancies to be checked by dependabot
While k6 still doesn't update all its dependencies, we do update quite a lot of them.
Currently there is a manual step of not only updating them and making a PR but also trying to gather what has changed.
While having a PR for every small change is likely going to be a lot noisier and we will have to ignore some of them. It seems like a better idea than having someone go through 20 repositories trying to figure out what commits have changed, given that dependabot does this automatically.
> dependabot: add a bunch more dependencies to it

- js/compiler/compiler_test.go
Fix a test in gotip/go1.24
as part of https://github.com/golang/go/commit/0fe6347732bdb9918e3af4e0c4b52f7f0c162894 now messages around encoding/json better specify the fields when embedding fields.
This does break a check on the message and the message will now be different between go versions.
With this commit the check is made to work between go versions.
> test: split error message check to fix it for go 1.24

- js/runner.go
- lib/testutils/minirunner/minirunner.go
Use context.AfterFunc
This cuts down on the amount of goroutines needed to be up for each VU.
> refactor: use context.AfterFunc around VU management

- js/bundle.go
- js/bundle_test.go
- js/modules/require_impl.go
- js/modules/resolution.go
- js/tc39/breaking_test_errors-experimental_enhanced.json
- js/tc39/breaking_test_errors-extended.json
- js/tc39/tc39_test.go
top-level-await support
It is part of the specification and it is hepful if you have async APIs ... which k6 starts to get more and more off.
> Top level await

- .github/dependabot.yml
- try to group golang/x and google dependancies for nicer PRs
- don't assign specific reviewers - we already do this with another integration
- increase the amount of PRs that it can open so we do not get blocked on a few PRs.
Fiddle with the configuration to make updating dependancies more seemless
> dependabot: update configuration with fixes

- cmd/ui.go
- go.mod
- go.sum
- vendor/github.com/fatih/color/README.md
- vendor/github.com/fatih/color/color.go
- vendor/modules.txt
Update fatih/color and use the RGB functionality to match the banner logo to the official k6 color.
RGB :sparkles:
> Update fatih/color and set the logo color to be the correct RGB one

- js/modules/k6/k6.go
This change updates the recommendation for using the check polyfill that does support async functions. 
https://grafana.com/docs/k6/latest/javascript-api/jslib/utils/check/
It improves UX of k6.
> update recommendation for async check

- js/bundle.go
- js/modules/require_impl.go
- js/path_resolution_test.go
Warn on usage of open that will break in the future
TODO: do it for `grpc.Client#load`  and `fs.open()` as well.
This is kind of a draft at this point to get some of the code inline.
Align open like functions and align them with how module imports work 
see #3857
> Warn on usage of open that will break in the future

- .github/workflows/issue-auto-assign.yml
Adding @ankur22 and @inancgumus to the issue auto-assigner. 
That way, you folks will be in rotation for the GitHub issues in main k6 (or extensions that we maintain) repository.
Knowledge sharing
> Update issues auto-assigner maintainers

- examples/experimental/csv-parse.js
- examples/experimental/csv-parser.js
- examples/experimental/fs/fs.js
Update examples to use TLA instead of the workaround
Better examples
#4007
> chore: update examples to use TLA

- js/modules/k6/k6.go
This address @heitortsergent feedback from the:
* https://github.com/grafana/k6/pull/4037#discussion_r1833004273
* https://github.com/grafana/k6/pull/4037#discussion_r1833013294
Feedback proposes a better texting which is better for end-users
https://github.com/grafana/k6/pull/4037
> Adjusts recommendations for check

- metrics/registry.go
`(*Regexp).Match` have a string-based equivalent `(*Regexp).MatchString`. We should use the string version to avoid unnecessary `[]byte` conversions. 
It's a one-line change that provides a free performance gain.
Benchmark:
```go
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := compileNameRegex.Match([]byte("my_metric_name1")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := compileNameRegex.MatchString("my_metric_name1"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: go.k6.io/k6/metrics
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 1457095	       820.7 ns/op	      16 B/op	       1 allocs/op
BenchmarkMatchString-16    	 1664458	       726.6 ns/op …
```
> metrics: use `regexp.MatchString` for metric name check

- .github/ISSUE_TEMPLATE/release.md
Update and adapt the release template past v0.55.0's release, as per #3979
> Update release template following v0.55.0

- js/module_loading_test.go
- js/modules/gomodule.go
This fixes an issue where a module only expose a default object, but we also want to allow the the module to be imported as a namespaced object. 
This is how node works, and this is how we have chosen to work even after the changes to work with ESM from commonJS. It prevents breaking changes with older scripts that were not intended.
Related: https://github.com/grafana/k6/issues/4050
> Fix namespaced object export when default is the only one available

- js/modules/modules.go
Update js/modules docs to be accurate
The previous comment made it seem that for each invocation of `require` or `import` it will be called for each VU. While it only gets called on the first `require`/`import`.
While this is only gets called the first time it is required for each VU that `imports`/`require`
> js/modules: update docs around NewModuleInstance

- .github/workflows/build.yml
- .github/workflows/test.yml
- .github/workflows/xk6.yml
- lib/netext/httpext/error_codes_test.go
Get github actions to not be broken on windows gotip
Not having CI red is good. 
I tried to actually fix the issue but can't reproduce it locally on windows VM and it doesn't seem anything I tried made a difference in github actions. So for now just disabling the test.
I also bumped to use latest windows as a thing that we probably should've done long ago. My testing hasn't shown it being more flaky so :shrug:
> Windows test go tip under carpet

- .github/workflows/browser_e2e.yml
- .github/workflows/test.yml
- js/modules/k6/browser/storage/file_persister_test.go
- js/modules/k6/browser/tests/element_handle_test.go
- js/modules/k6/browser/tests/frame_manager_test.go
- js/modules/k6/browser/tests/frame_test.go
- js/modules/k6/browser/tests/keyboard_test.go
- js/modules/k6/browser/tests/lifecycle_wait_test.go
- js/modules/k6/browser/tests/locator_test.go
- js/modules/k6/browser/tests/page_test.go
- js/modules/k6/browser/tests/webvital_test.go
> Fix browser tests in CI

- cmd/root.go
- cmd/version.go
- cmd/version_test.go
- lib/consts/consts.go
This PR introduces the new `--json` flag for `k6 version` sub-command, which switches the output format to a JSON. 
Here are some examples:
Basic
```bash
./k6 version --json | jq
{
"commit": "ec1f601e4f",
"commit_dirty": true,
"go_arch": "amd64",
"go_os": "linux",
"go_version": "go1.23.2",
"version": "v0.55.0"
}
```
```bash
./k6 version
k6 v0.55.0 (commit/ec1f601e4f-dirty, go1.23.2, linux/amd64)
```
```bash
./k6 --version
k6 v0.55.0 (commit/ec1f601e4f-dirty, go1.23.2, linux/amd64)
```
With extensions:
```bash
./k6 version --json | jq
{
"extensions": [
{
"imports": [
"k6/x/sql"
],
"module": "github.com/grafana/xk6-sql",
"version": "v0.0.1"
}
],
"go_arch": "amd64",
"go_os": "linux",
"go_version": "go1.23.2",
"version": "v0.55.0"
}
```
```bash
./k6 --version
k6 v0.55.0 (go1.23.2, …
```
> Introduces --json flag for k6 version sub-command

- cmd/test_load.go
It adds a new `deprecated_options` field into the usage reports, and accounts if `ext.loadimpact` is still being used, and how often.
Because we likely will remove that option parameter before v1, so we need to make some plans.
Related with https://github.com/grafana/k6-cloud/issues/2210
> Report usages of the deprecated 'ext.loadimpact' option

- go.mod
- go.sum
- release notes/v0.55.1.md
- vendor/golang.org/x/net/html/doctype.go
- vendor/golang.org/x/net/html/foreign.go
- vendor/golang.org/x/net/html/parse.go
- vendor/modules.txt
This cherry picks two commits from `v0.55.x` branch:
1. e35c31cc311daf8d4e447df95c99878b48a0f330 -- update golang.org/x/net.
2. Add the `v0.55.1` release notes.
To keep `master` up to date with all necessary changes from long living branches.
> Update to the latest version of golang.org/x/net

- lib/consts/consts.go
- release notes/v0.55.2.md
Bumping to v0.55.2.
Due to a build/release issue, the published version of the .deb file seems to have also failed. For an unknown reason the size of the file doesn't match the expected size: `File has unexpected size (28726870 != 28726866). Mirror sync in progress?`.
> Bump version to 0.55.2

- js/modules/k6/browser/common/browser.go
- js/modules/k6/browser/common/browser_context.go
It's an attempt to address a nil pointer from #4128 
Unfortunately, we don't have a script/steps to reproduce the #4128, but after analyzing the stack trace and code it seems like one of the possible scenarios what happens is that we reached the [default (30s) context timeout](https://github.com/grafana/k6/blob/d3c7fc51bdd3135492ddb8bd615ad0965357e259/js/modules/k6/browser/common/browser.go#L457-L458) which causing context deadline, [somewhere down the `createWaitForEventHandler`](https://github.com/grafana/k6/blob/d3c7fc51bdd3135492ddb8bd615ad0965357e259/js/modules/k6/browser/common/helpers.go#L129-L176) it exits the releases the channel and as result [we didn't fill the page](https://github.com/grafana/k6/blob/d3c7fc51bdd3135492ddb8bd615ad0965357e259/js/modules/k6/browser/common/browser. …
> Explicitly check if we actually timed out

- js/modules/k6/browser/common/http.go
- js/modules/k6/browser/common/http_test.go
- js/modules/k6/browser/common/network_manager.go
- js/modules/k6/browser/common/network_manager_test.go
A new `resource_type` tag is being added to allow users to view and filter metrics based on the chrome resource types, which are currently defined as:
- "Document"
- "Stylesheet"
- "Image"
- "Media"
- "Font"
- "Script"
- "TextTrack"
- "XHR"
- "Fetch"
- "Prefetch"
- "EventSource"
- "WebSocket"
- "Manifest"
- "SignedExchange"
- "Ping"
- "CSPViolationReport"
- "Preflight"
- "Other"
Linked: https://github.com/grafana/xk6-browser/issues/1551
> Add resource_type tag

- lib/consts/consts.go
This PR bumps the k6 version to v0.56.0.
- https://github.com/grafana/k6/issues/4064
- https://github.com/grafana/k6/pull/4066
> Bump version to v0.56.0

- README.md
Drop slack URL (see https://github.com/grafana/k6/pull/3889#issue-2450627620)
The https://k6io.slack.com/ has been deleted.
> Drop slack URL

- js/modules/k6/experimental/streams/readable_streams_test.go
Use modulesTest insead of k6/timers module
This breaks in some cases and more importantly isn't really necessary
> streams: just use modulestest to get setTimeout and co.

- js/modules/k6/browser/tests/browser_context_test.go
- js/modules/k6/browser/tests/page_test.go
- js/modules/k6/browser/tests/test_browser.go
Fixes some tests to work on Windows.
These tests stopped working after the updates in #4177 (CI runs: [1](https://github.com/grafana/k6/actions/runs/12772268654/job/35602414728), [2](https://github.com/grafana/k6/actions/runs/12791222587/job/35658838255)).
- Fixes the HTTP handler slash misusage.
- Fixes gradient differences on Windows.
- #4177
- #4118
> Fix some browser Windows tests

- cmd/config.go
- cmd/config_consolidation_test.go
Warn on shorthand options(vus, duration, stages, iterations) overriding scenarios from previously defined scenarios. Mostly applicable when using cli flags to override them from within the script.
This is currently implemented only for scenarios as that is the case that is most confusing. Implementing this for duration overriding stages (for example) is possible, but it seems to not be nearly hit enough.
Unfortunately due to too many of things of #883 and the way shorthand options are handled in particular, the code can't be in any Apply function with enough information to have a nice message.
This is probably one of the things that confuses the most users as explained in the original #2529 issue.
Fixes #2529
> Warn on shorthand options overriding scenarios

- js/modules/k6/grpc/client_test.go
- js/modules/k6/grpc/teststate_test.go
Disable tests so that they do not fail after recent security update
CI being red is pretty bad, and this doesn't seem to have an easy fix. 
The real fix will likely require
https://github.com/grafana/k6/issues/3549
or something similar as the problems appears to be the update of the test certificates.
> grpc: disable tests to make CI green

- js/modules/k6/grpc/client_test.go
- js/modules/k6/grpc/teststate_test.go
Get the localhost certificate programatically instead of having a hard copy of it from within stdlib
This localhost certificate was update in https://github.com/golang/go/commit/6783377295e0878aa3ad821eefe3d7879064df6d and this broke this tests in a none obvious way. 
Big part of the problem is that the `httptest` stdlib package always use the in stdlib certificate. 
But this test had a copy of this, but it is not obvious that the problem was this Certificate instead of something else.
> Grpc get localhost certificate programically

- js/modules/k6/browser/common/event_emitter.go
- js/modules/k6/browser/common/frame.go
- js/modules/k6/browser/common/frame_manager.go
- js/modules/k6/browser/common/frame_session.go
- js/modules/k6/browser/common/network_manager.go
- js/modules/k6/browser/common/page.go
- js/modules/k6/browser/common/session.go
- js/modules/k6/browser/common/touchscreen.go
- js/modules/k6/browser/common/worker.go
Removing the BaseEventEmitter from `Touchscreen`, `Page` and `Worker`, as well as the events which are emitted.
While debugging another issue i found that these components had instances of their own event emitter, which were emitting events, but nothing was consuming them. It's confusing to see these events being emitted and can cause confusion while debugging issues with the event emitter. This is why they are being removed.
> Remove BaseEventEmitter from components

- internal/js/modules/k6/browser/common/event_emitter.go
Overwrite the empty `queue.read` with a new slice.
When we read off the `queue.read` slice, it essentially pops the first available element by doing this:
```go
case eh.ch <- eh.queue.read[0]:
eh.queue.read[0] = Event{}
eh.queue.read = eh.queue.read[1:]
```
([link to code](https://github.com/grafana/k6/blob/3f1536e258273e0df5ff347ee63e39fbf4a3c798/js/modules/k6/browser/common/event_emitter.go#L146-L148))
So the entry where the event used to exist has been overwritten with a fresh instance of `Event` which will help avoid a memory leak (which was recently [fixed](https://github.com/grafana/xk6-browser/pull/1488)). However the issue is that the underlying slice keeps growing. During a long running test the slice could grow to an unnecessarily length.
To avoid this issue, when `queue.read` …
> Fix memory leak in queue

- internal/cmd/run.go
Do not stop REST API until flushing outputs is done
Flushing outputs may take some time and it will be good if the REST API is up for this - there is no need for it not to be.
> Do not stop REST API before outputs are flushed

- internal/js/modules/k6/browser/browser/registry.go
- internal/js/modules/k6/browser/browser/registry_test.go
Fix browser test on reused VUs.
This also techinically fixes being able to use browser on reused browser VUs that are not in browser scenarios.
While a rare case, reusing VUs is still part of k6. 
The cost currently seems to be around 33% performance for *empty* iterations.
But if I do http.get to not open port it dissapears so I would expect for any real world scripts this is a none issue.
- #4240
> Simple fix for 4240

- internal/cmd/runtime_options.go
- internal/cmd/test_load.go
- internal/cmd/tests/cmd_run_test.go
- internal/js/compiler/compiler.go
- internal/js/compiler/enhanced_test.go
Enable type stripping by default
Closes #4194 
This does currently skip doing any cleaning in part because most of it will be intrusive but also because it will be somewhat breaking changes. Also might be completely different with #3864 and some other refactoring issues in mind, I feel like not trying to remove stuff now is better. 
Additionally, `experimental_enhanced` is currently just a synonym for `base`. Again touching on #3864
> Enable type stripping by default

- internal/js/modules/k6/browser/storage/storage.go
- internal/js/modules/k6/browser/tests/browser_test.go
Renames `xk6-browser-data-*` to `k6browser-data-*`.
* To be consistent with the artifact directory: `k6browser-artifacts-*`
* Removing the deprecated `xk6-browser` name.
- #4288
> Rename browser data directory

- cloudapi/logs_test.go
Increase the timeout
This fails fairly regularly in CI and it is no problem if the wait is a bit longer.
> TestStreamLogsToLogger: increase wait time to get less flakiness

- .golangci.yml
- cloudapi/logs.go
- internal/cmd/ui.go
- internal/js/modules/k6/browser/browser/browser_mapping.go
- internal/js/modules/k6/browser/common/element_handle.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/frame_session.go
- internal/js/modules/k6/browser/common/network_manager.go
- internal/js/modules/k6/browser/common/screenshotter.go
- js/modules/k6/http/response.go
- lib/executor/ramping_vus.go
- lib/netext/httpext/transport.go
Bump the golangci version and fix the related issues.
Note: there are new linters but I plan to review and open a dedicated pull request for adding them.
It keeps our code base aligned with the latest Go (almost std) linter's version.
> golangci-lint: Bump the version

- .github/actions/lint/action.yml
It bumps the golangci linter's version.
Maintainace
> Bump the golangci-lint-action version

- internal/js/modules/k6/data/data.go
- internal/js/modules/k6/experimental/csv/module.go
- internal/js/modules/k6/experimental/csv/module_test.go
- internal/js/modules/k6/experimental/csv/reader.go
- internal/js/modules/k6/experimental/csv/reader_test.go
Adds support for a `header` option to the csv module's option. When set to `true`, the `header` option leads the module's `parse` function as well as the `Parser.next` method to return records as objects with the header corresping row name as the property key, and value as the value.
```javascript
const file = await open('data.csv');
const csvRecords = await csv.parse(file, { header: true })
export default async function() {
console.log(csvRecords[scenario.iterationInTest])
}
```
**Would print:**
```
INFO[0000] {"age":"72","firstname":"fariha","lastname":"ehlenfeldt"}  source=console
INFO[0000] {"age":"50","firstname":"qudratullah","lastname":"gillfillan"}  source=console
INFO[0000] {"age":"41","firstname":"jeleah","lastname":"rodina"}  source=console
INFO[0000] …
```
> Add `header` option support to the CSV module

- internal/js/bundle_test.go
- internal/js/initcontext.go
- internal/js/modules/k6/experimental/fs/module.go
- internal/js/modules/k6/experimental/fs/module_test.go
- internal/js/modules/k6/grpc/client.go
- internal/js/modules/k6/grpc/client_test.go
- internal/js/modules/k6/grpc/teststate_test.go
Fix `open` and experimental `fs.open` and `grpc.Client#Load` to work with file scheme paths
Fixes #4512
This apparently has never been supported which is likely due to nothing really returning absolute paths.
After adding import.meta.resolve though this is changed. And there is really no reason why it shouldn't be supported.
> Support file scheme in open and experimental fs

- .github/workflows/xk6.yml
Do not fail all of the xk6 tests if one fails
There now have been a couple of cases where this fail. It will be nice to know if all of them fail or just one. So failing fast isn't a particularly good idea in this case.
> don't fail fast on xk6

- internal/js/modules/k6/browser/browser/keyboard_mapping.go
- internal/js/modules/k6/browser/browser/mouse_mapping.go
- internal/js/modules/k6/browser/browser/page_mapping.go
In a lot of places in the k6ext.Promise will create a separate goroutine and then access the arguments in it. This isn't safe and will race with anything running on the event loop.
It is very likely that this happens very rarely especially as in a bunch of the cases this is only for `opts` - which seems to be less used in most cases.
Additionally in a bunch of cases mapping back to the sobek.Values is done in that same goroutine instead of on the event loop.
I am marking all of those in one commit and not fixing them all as that will take a lot longer and likely a bunch of them will not be the same as the rest.
> browser: Mark a bunch of places where races happen

- internal/js/modules/k6/browser/browser/page_mapping.go
Reduce the number of sobek.Runtime used in page.evaluate that are off the event loop
This is racy and very likely the underlying cause of #4085 - although without a runnable example, it is impossible to check.
Unfortunately some of the usage for `evalueateHandle` will require even more changes. In order to provide some fixes I opted to not try to fix everything in one go.
Possibly fixing #4085
> browser: reduce races in evaluate*

- internal/js/modules/k6/browser/browser/frame_mapping.go
- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/tests/frame_test.go
- internal/js/modules/k6/browser/tests/launch_options_slowmo_test.go
- internal/js/modules/k6/browser/tests/lifecycle_wait_test.go
- internal/js/modules/k6/browser/tests/locator_test.go
- internal/js/modules/k6/browser/tests/page_test.go
- internal/js/modules/k6/browser/tests/setinputfiles_test.go
Same as https://github.com/grafana/k6/pull/4522 this PR fixes usages of `sobek.Value` inside go routines which could lead to the race.
It fixes this for following APIs:
* SelectOption
* SetChecked
* SetInputFiles
* TextContent
Note that `SelectOption` and `SetInputFiles` still not fully migrated, since some usages of the `sobek.Value` requires a bigger refactoring there.
https://github.com/grafana/k6/issues/4085
> browser: fix possible races

- internal/js/modules/k6/browser/browser/frame_mapping.go
- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/common/page_options.go
- internal/js/modules/k6/browser/tests/browser_test.go
- internal/js/modules/k6/browser/tests/frame_test.go
- internal/js/modules/k6/browser/tests/keyboard_test.go
- internal/js/modules/k6/browser/tests/launch_options_slowmo_test.go
- internal/js/modules/k6/browser/tests/locator_test.go
- internal/js/modules/k6/browser/tests/page_test.go
- internal/js/modules/k6/browser/tests/webvital_test.go
Fixing more page and frame (where they intersect) mappings
> browser: race fixes

- internal/js/bundle.go
It modifies the `Bundle.makeArchive` function so `Bundle`'s URLs (pointers) aren't directly reused by the `lib.Archive` it constructs, but cloned ("deep copy") and set.
Because the `Archive.Write` method normalizes and anonymizes these URLs to prevent certain details (like OS's user, HOME dir, etc) to be leaked to the GCk6, but we not always want these modifications to be propagated to the `Bundle`'s URLs - e.g. when running the test script locally: `k6 cloud ... --local-execution`.
A better explanation of why this (#4168) happens is because the process goes as follows:
1. The test is loaded and configured, which includes the initialization of the first runner, and thus the cache of the module resolutions.
2. The process of creating the test remotely also involves the creation of the …
> Clone Bundle's URLs into lib.Archive

- internal/js/modules/k6/browser/browser/frame_mapping.go
- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/tests/keyboard_test.go
- internal/js/modules/k6/browser/tests/launch_options_slowmo_test.go
- internal/js/modules/k6/browser/tests/lifecycle_wait_test.go
- internal/js/modules/k6/browser/tests/page_test.go
- internal/js/modules/k6/browser/tests/setinputfiles_test.go
Same as https://github.com/grafana/k6/pull/4522 this PR fixes usages of sobek.Value inside go routines which could lead to the race.
It fixes this for the following APIs:
* Type
* Uncheck
* WaitForLoadState
* WaitForSelector
https://github.com/grafana/k6/issues/4085
>  browser: fix possible races p4

- examples/browser/multiple-scenario.js
Make multiple scenario example a bit lighter to run. Hopefully reducing CI flakiness on MacOS
It seems like on MacOS running 3 browsers is way too much and it regularly fails.
Given that the failure is due to threshold being blown over as the CI just can't load pages fast enough, I see no point for this to keep being flaky.
The example is about multiple scenarios not about multiple browsers in scenarios as well.
> Fix E2E browser CI flakiness by reducing example number of browser

- internal/js/modules/k6/browser/browser/frame_mapping.go
- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/tests/frame_test.go
- internal/js/modules/k6/browser/tests/launch_options_slowmo_test.go
- internal/js/modules/k6/browser/tests/lifecycle_wait_test.go
- internal/js/modules/k6/browser/tests/page_test.go
Continue https://github.com/grafana/k6/pull/4524
>  browser: Fix options races p5

- internal/js/modules/k6/browser/browser/element_handle_mapping.go
- internal/js/modules/k6/browser/browser/frame_mapping.go
- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/common/element_handle.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/locator.go
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/tests/element_handle_test.go
- internal/js/modules/k6/browser/tests/launch_options_slowmo_test.go
- internal/js/modules/k6/browser/tests/page_test.go
- internal/js/modules/k6/browser/tests/setinputfiles_test.go
More fixes along #4521 
Fixing potential race conditions
> Browser fixes part6

- internal/js/modules/k6/browser/common/frame.go
As per https://github.com/grafana/k6/pull/4533#discussion_r1951060681.
> Add TODO to Frame.SetContent

- release notes/v0.57.0.md
This PR contains the Release notes for the upcoming k6 version v0.57.0. Please add commits as you see fit to update the content according to the changes you've made this cycle 🙇🏻 
#4162
> Release v0.57.0

- .github/workflows/wpt.yml
- internal/js/modules/k6/experimental/streams/readable_streams.go
Run wpt tests with -race and fix race in ReadableStream.cancel
So we catch race conditions
> Run WPT tests with `-race` and fix race in ReadableStream.cancel

- internal/cmd/root.go
- internal/cmd/ui.go
Only color the k6 logo with `RGB(0xFF, 0x67, 0x1d)` if the terminal supports TrueColor. Otherwise, it picks k6 v0.54.0's yellow color. This change should cover most cases, but we can still improve it later. It feels safer to fall back to a 256-color scheme rather than using TrueColor from the get-go.
#4542
- #4542
> Add true color detection for k6 banner

- lib/executor/constant_arrival_rate_test.go
The test is testing how constant arrival rate is starting iterations over time. But it used time.Sleep of 1 second which means that it doesn't actually check every second it checks and then it waits for 1 second and then again.
This seems to move enough, especially on windows, that it sometimes fails.
This PR uses time.Ticker to make it check every second, making it more likely that it won't drift.
Flaky test bad
> Try to make TestConstantArrivalRateRunCorrectRate less flaky

- .github/workflows/build.yml
Searches the `Windows Kit\bin` directory for the most recent `signtool` executable, instead of hardcoding the exact version.
This PR also moves the `Add signtool to PATH` build step to right above the signing step, and only runs in the same conditions used for the signing step. The condition is added because the search adds around 20 seconds, so it shouldn't be run for all builds.
[Successful manual test showing signtool was called](https://github.com/McMastS/k6/actions/runs/13255968023/job/37002839657)
The path to the `signtool` executable recently had to be [changed ](https://github.com/grafana/k6/pull/4102) because Windows moved its directory. This change means the `signtool` path won't need to be manually updated every time the Windows version is upgraded.
Closes #4105
> Avoid hardcoding signtool PATH in package-windows build step

- internal/js/modules/k6/browser/common/frame_session.go
Use the session we get a bit earlier in attachIFrameToTarget instead of regetting it there.
This should fix https://github.com/grafana/k6/issues/4125 as we already check the session isn't nil at the time.
It is still strange it suddenly disappears, and my expectation is that it is likely something to do with k6 stopping and session going away. 
Also reuse the session we get in other cases within `onAttachedToTarget` as we already have it.
> browser: get session only once - trying to fix #4125

- internal/cmd/options.go
- internal/cmd/tests/cmd_run_test.go
Support setting tags which values contain commas through cli flags
It seems very strange that this isn't supported at all on the cli, but you can do it through options. 
This is a breaking change as before you can do `--tag one=value,two=value`  which will produce 2 flags one with key `one`, the other with `two`. 
This will now produce only 1 tag. 
I would argue though that the alternative is to forbid commas in the values. And that seems like a bigger breaking change. 
Given our documentation and help we have never documented that you can put two tags with the same flag, so :shrug:
> Support comma in tag values through cli flag

- examples/browser/throttle.js
Try to make the throttle.js lighter to pass on MacOS CI
MacOS github action runners are ... not very performant, and it seems that they do not do well with running 3 browser at the same time.
This PR spreads the three browser executions in time so it hopefully will not fail on the normal (not throttled one) being too slow every once in a while 
Similar to https://github.com/grafana/k6/pull/4529
> examples/browser/throttle.js make it lighter to pass in MacOS CI

- .github/pull_request_template.md
Adds the documentation updates checklist to the PR template.
To streamline the release process and reduce mistakes.
* **Ownership:** The PR owner is responsible for making all documentation updates.
* **Mandatory documentation updates:** To prevent documentation from being overlooked, reduce mistakes, and streamline the release process (avoiding bottlenecks).
* **Direct documentation updates:** To reduce mistakes and avoid having to keep a to-do list throughout the cycle.
* **External contributor PRs:** The reviewers are responsible for updating the documentation (bonus: request updates from the contributor if possible).
> Add doc updates checklist to PR template

- internal/js/modules/k6/browser/browser/keyboard_mapping.go
- internal/js/modules/k6/browser/browser/mouse_mapping.go
- internal/js/modules/k6/browser/common/mouse.go
- internal/js/modules/k6/browser/tests/mouse_test.go
Fixes Sobek value usage for `Mouse` and `Keyboard`.
Fixing potential race conditions.
- #4521
- #4219
- #4565
> Fix sobek values for mouse and keyboard

- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/browser/request_mapping.go
- internal/js/modules/k6/browser/common/http.go
- internal/js/modules/k6/browser/common/network_manager.go
- internal/js/modules/k6/browser/common/network_manager_test.go
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/tests/page_test.go
This implements the `page.on('request')` API from Playwright. When the handler is created, all subsequent requests will be directed to the handler, where the user can interact with the read only request. The request is intercepted just before it is sent from the browser to the website under test.
An example usage is:
```js
import { browser } from 'k6/browser'
scenarios: {
ui: {
executor: 'shared-iterations',
options: {
browser: {
type: 'chromium',
},
},
},
},
}
export default async function () {
const page = await browser.newPage()
// Logs the url of the request
page.on('request', async (request) => {
console.log(request.url());
})
await page.goto('https://quickpizza.grafana.com/', { waitUntil: 'networkidle' })
await page.close();
}
```
This can be useful to:
* …
> Add `page.on('request')`

- internal/js/modules/k6/browser/browser/element_handle_mapping.go
- internal/js/modules/k6/browser/common/element_handle.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/tests/element_handle_test.go
- internal/js/modules/k6/browser/tests/keyboard_test.go
- internal/js/modules/k6/browser/tests/page_test.go
- internal/js/modules/k6/browser/tests/setinputfiles_test.go
Fixes Sobek value usage for `ElementHandle`.
Fixing potential race conditions.
- #4521
- #4219
- #4565
> Fix sobek values for `ElementHandle`

- examples/browser/pageon-request.js
Add `page.on('request')` example.
To show how to use the feature and also for E2E testing.
- #4281 
- #4290
> browser: Add page on request example

- internal/js/console_test.go
It closes the open file descriptors on the logger's output file on `TestFileConsole`. 
Because, as discussed [here](https://github.com/grafana/k6/pull/4604#issuecomment-2703809796), that's what's causing that test to fail on Windows.
> Chore: Close FDs on TestFileConsole to avoid issues on Win

- .golangci.yml
- internal/js/bundle_test.go
- internal/js/console_test.go
- internal/js/modules/k6/browser/browser/registry_test.go
- internal/js/modules/k6/browser/common/browser_test.go
- internal/js/modules/k6/browser/common/element_handle.go
- internal/js/modules/k6/browser/storage/storage_test.go
- internal/js/modules/k6/browser/tests/browser_test.go
- internal/js/modules/k6/experimental/fs/file.go
- internal/js/modules/k6/experimental/websockets/blob.go
- internal/lib/testutils/httpmultibin/grpc_wrappers_testing/service.go
- metrics/builtin.go
Bump golangci-lint to latest version
Mostly so it actually works with a version that works with go1.24, but also as to get some bugfixes ... and new stuff.
- usetesting seems okay and we already had tenv - I have done some t.TempDir() fixes around it as well
- exportloopref - is not relevant after using go 1.22
> Update golangci-lint to 1.64.6 and update code to conform

- .github/actions/lint/action.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/tc39.yml
- .github/workflows/test.yml
- .github/workflows/wpt.yml
- .github/workflows/xk6.yml
- Dockerfile
- go.mod
Update k6 to use go 1.23 and 1.24 instead of 1.22 and 1.23. 
This bumps us to the currently supported by the golang team go versions
We already have PRs #4601 that are blocked on us still using 1.22 in some places. 
Also go 1.24.1 has been released with a number of bugfixes and CVE fix that is only available for 1.23.+
> Bump go version

- internal/cmd/runtime_options.go
Small refactor to make the code to populate `lib.RuntimeOptions` from different sources (CLI flags, environment variables, etc) slightly more readable and cleaner, by separating the read from each source into a different method.
As discussed 👉🏻  https://github.com/grafana/k6/pull/4089/files#r1965192447
> Chore: Refactor lib.RuntimeOptions load

- internal/js/doc.go
- output/csv/doc.go
Use line code comments (instead of blocks) for existing package docs (`*/doc.go`).
As discussed 👉🏻 https://github.com/grafana/k6/pull/4089#discussion_r1963551641
> Chore: Homogenize pkg docs comment block format

- internal/ds/histogram/doc.go
- internal/ds/histogram/hdr.go
- internal/ds/histogram/hdr_test.go
- output/cloud/expv2/hdr.go
- output/cloud/expv2/hdr_test.go
- output/cloud/expv2/mapping.go
- output/cloud/expv2/sink.go
- output/cloud/expv2/sink_test.go
It extracts the HDR histogram implementation from the `expv2` Cloud output package, into an internal but shared package, so it can be reused for our `metrics.TrendSink` implementation and/or (at the very least) for the `Summary` output.
Because as discussed and suggested [here](https://github.com/grafana/k6/pull/4089#discussion_r1965269259) it's likely the best way to move forward. Plus, now that we're about to release a new major, it's likely a good moment to add this kind of breaking change (behavioral, not programmatic API).
Related with #763 
To facilitate the review, I'd suggest to do a clipboard diff between the contents that were on `expv2/hdr.go` vs the new `histogram/hdr.go`. But to summarize, it's mostly about making the type and constructor public, and leaving the protobuf …
> Extract HDR histogram implementation into a shared package

- cmd/state/state.go
- examples/secrets/file.secret
- examples/secrets/secrets.test.js
- ext/ext.go
- internal/cmd/root.go
- internal/cmd/test_load.go
- internal/cmd/tests/cmd_run_test.go
- internal/cmd/tests/test_state.go
- internal/js/jsmodules.go
- internal/js/modules/k6/secrets/secrets.go
- internal/js/modules/k6/secrets/secrets_test.go
- internal/secretsource/file/file.go
- internal/secretsource/file/file_test.go
- internal/secretsource/init.go
- internal/secretsource/mock/mock.go
- js/modules/k6/k6.go
- js/modules/k6/k6_test.go
- lib/test_state.go
- secretsource/doc.go
- secretsource/extension.go
- secretsource/hook.go
- secretsource/interface.go
- secretsource/manager.go
Adds an extensible secret sources. Basically #4139 but without http secret source as that turned out to have too many configuration problems. But it has a mock secret source which basically gets them form the cli arguments - probably should be renamed.
Usage:
```javascript
import secrets from "k6/secrets";
export default async () => {
const my_secret = await secrets.get("cool"); // get secret from a source with the provided identifier
console.log(my_secret);
await secrets.get("else"); // get secret from a source with the provided identifier
console.log(my_secret);
}
```
```
go run . run --secret-source=mock=cool=some,else=source script.js
```
or with a secret file:
```
cool=some
else=source
```
```
go run . run --secret-source=file=file.secret script.js
```
The extension points are under …
> Secret Source Implementation

- internal/loader/loader.go
Update anchor link to the official docs in the error message `The moduleSpecifier "%s" couldn't be found on local disk`. New anchor link is `https://grafana.com/docs/k6/latest/using-k6/modules/#local-modules-2`.
Anchor link  `https://grafana.com/docs/k6/latest/using-k6/modules/#using-local-modules-with-docker` in the error message `The moduleSpecifier "%s" couldn't be found on local disk...`  is not up-to date, so anchor link is being resolved to the beginning of the page. 
> UX: fix anchor link in the error message

- internal/js/bundle.go
- internal/js/bundle_test.go
This predominantly tries to actually list the problematic part of the options.
Hopefully help users figure out what the problem is
> UX: better error message for json errors while parsing options

- internal/cmd/new.go
- internal/cmd/new_test.go
- internal/cmd/templates/templates.go
This PR adds support for local templates and addresses a bug when an empty script file is created even if the template name is invalid.
The current script templating feature is limited to three pre-defined templates that are bundled with `k6`: minimal, protocol and browser. While this already reduces the amount of boilerplate code to write when starting a new project, being able to use custom user-defined templates would help to simplify the first steps even further, by allowing users to extract common parts, such as authentication, custom sets of options, into a template file that can be used to initialize tests.
Relevant issue https://github.com/grafana/k6/issues/4154
> Local templates support in `k6 new`

- internal/js/bundle.go
- internal/js/bundle_test.go
Make the error message not print practically the whole options on error.
The original idea of #4602 was to report at least the key with potentially the option in question. Due to the lack of support from the error - it can't parse it. The commit was trying to get everything between the previous and next new line.
But in practice was getting anything until the end, both because of error in the coed to get the index, but also because there were no newlines due to how we marshal the data before that.
This should fix both and make it less likely we just get everything until the end.
> Fix options parsing error printing the most of the options

- internal/js/modules/k6/browser/tests/webvital_test.go
Increase timeout and add a 1s delay after page load to ensure metrics are collected.
The `TestWebVitalMetricNoInteraction` test is [failing on Windows](https://github.com/grafana/k6/actions/runs/13816953723/job/38652540550#step:4:69) due to timing issues when collecting web vital metrics.
> browser: fix web vitals test flakiness on Windows

- .github/pull_request_template.md
This is for linking issues/PRs if needed.
Updating the documentation right away is no longer necessary. However, we'll link issues/PRs if relevant. Updating the release notes is still a must.
> Update PR template for docs

- internal/lib/summary/summary.go
Without this adding `--summary-export` wil fail because `root_group` isn't defined and then it can be used to seriallize it.
This is part of the k6 functionality.
> Fix --summary-export by marshalling the root group with its original name

- metrics/tags.go
- metrics/tags_test.go
Fix easyjson behaviour when buffer grows
Tried to output samples as json and it failed
> Fix: tagset json buffer content

- internal/js/tc55/timers/timers_test.go
Try to reduce flakiness in a test
Test sometimes fails for no reason, due to the timings being too small - it is better if we do not have a flaky test
> chore: fix TestSetTimeoutOrder flakiness

- .github/workflows/xk6-tests/xk6-test.js
- internal/cmd/run.go
- internal/cmd/tests/cmd_run_test.go
- internal/js/runner.go
- internal/js/summary-wrapper.js
It moves back _"programmatic"_ interfaces of the end-of-test summary (both custom `handleSummary()` and JSON output through `--summary-export`) to the legacy data structure (`lib.LegacySummary`), despite of the `--summary-mode`.
It technically makes https://github.com/grafana/k6/pull/4089 non-breaking.
Because after having caught https://github.com/grafana/k6/issues/4640, and while discussing https://github.com/grafana/k6/pull/4647, we realized that _maybe_ it's better to play safe and don't break this until v2.0, whenever that comes. Also, because the re-design of the machine-readable format (JSON) hasn't been planned until then.
> Summary: Use lib.LegacySummary to avoid breaking the API

- .github/ISSUE_TEMPLATE/release.md
It updates the release issue's template:
- versions bumped to v1.x
- Reverse the order between posts
#k6 is the main channel for the product so we should not post a link there but a real post. Then it sounds better to link in k6-changelog channel.
It keeps things up to date.
> Update the release issue's template

- internal/cmd/tests/tests.go
Block the usage endpoint in cmd tests so that we do not report those as runs
So we do not report those as runs. Also probably makes the test a bit faster.
> Block the new stats.grafana.org in tests instead of the old reports

- .github/ISSUE_TEMPLATE/release.md
It adds an item to lock the conversation on release issues.
Release issues are functional only for the maintainers. The community's members should create new issues or comment on ones already available relevant to their topic.
> Add item to lock the issue

- secretsource/hook.go
Ignore float32 and float64 values when trying to redact secrets in logs
It is one more type that is commonly found in log values that is unlikely to be secret and more importantly a very bad candidate for one. 
> secretsource: also ignore float32 and float64 values when redacting

- cmd/state/state.go
It drops a redundant logic about `NO_COLOR`.
Because we are already checking here https://github.com/grafana/k6/blob/b61ca160537a021d26695b2b36d2b63259b7016f/cmd/state/state.go#L188-L192
> Drop the redundant NO_COLOR detection

- internal/cmd/options.go
Drop the `https://k6.io` link from the user agent. In addition, rename `k6` to `Grafana k6`.
The k6.io website has been deprecated, which initially required a link update. However, we reevaluated this decision and ultimately opted to remove the website from the user agent. We found no clear historical justification for its inclusion; it may have been for marketing purposes. Currently, we don't see any tangible benefits to keeping it.
Closes #4653
> Drop the link of the k6 website from the user agent

- .github/workflows/wpt.yml
- internal/js/modules/k6/experimental/streams/readable_streams_test.go
- internal/js/modules/k6/webcrypto/tests/crypto_test.go
- internal/js/modules/k6/webcrypto/tests/subtle_crypto_test.go
- internal/js/modules/k6/webcrypto/tests/test_setup_test.go
This changes so WebCrypto and Streams to not require tags and instead get skipped if the repo isn't checkout and tells you that.
This improves DX significantly as gopls doesn't work great if tags are required for building. Golangci-lint also has problems.
Also aligning with tc39, Sobek/goja as well.
> wptTests: run without tags or skip if repos not checkout

- internal/js/modules/k6/browser/common/js/injected_script.js
- internal/js/modules/k6/browser/tests/page_test.go
Avoids a page under the test to overwrite native JavaScript objects, like `Set` and `Map`, by injecting a temporary and invisible frame in execution contexts. We can extend this to support other native objects in the future. However, for now, this solves crucial issues for users.
Note: I will update the release notes after I get the approvals, but before the merge.
See #4687 for details.
Updates: #4687
> browser: Fix JS native objects override

- internal/launcher/analyze.go
- internal/launcher/analyze_test.go
fixes the scanning of commands that require binary provisioning by excluding `cloud login`
Cloud logging does not require binary provisioning
> fix scan of cloud login command

- cmd/execute.go
- internal/cmd/root.go
It unifies the Execute methods.
It simplifies the API, reducing the surface to one single method. It has the benefit to clarify the execution path. This is a blocking work for Binary provisioning, as it is a prerequisite.
> Unify the internal/cmd.Execute methods

- internal/cmd/launcher.go
Disable search for dependencies manifest.  Manifests are not used currently. 
Any `package.json` file in the directory where the test is located or any parent will be picked.
> disable manifest search

- internal/cmd/launcher.go
- internal/cmd/launcher_test.go
skip binary provisioning for `k6 run` command
Binary provisioning is currently supported only for users who have a cloud account, because it requires authenticating to GCK6.
Enabling binary provisioning only for cloud command (e.g. `k6 cloud run`) offers a more consistent user experience. The exception to this are the `k6 archive` and `k6 inspect` commands that are require for the users to upload tests to the cloud.
> skip binary provisioning for run command

- cmd/execute.go
- internal/cmd/launcher.go
Changes to improve the UX. 
There is also a change that skips the launcher very early in the root code. As we are still early days, it might be better if we don't take a risk disrupting the stable execution path.
> [Binary provisioning] Exclude fallback path

- internal/output/summary/summary.go
- internal/output/summary/summary_test.go
It filters out samples tagged with `group: ::setup` or `group: ::teardown` so they aren't collected as "group samples".
Since #4089, we modified not only how the data in the summary is displayed but also how it is collected. So, since then, we started to collect samples with `group: ::setup` or `group: ::teardown`, while previously we did not because there are no groups named like `::setup` or `::teardown`, we only "artificially" tag samples with the `group` label (more details [here](https://grafana.com/docs/k6/latest/using-k6/workaround-iteration-duration/)).
So, for now, and until we decide the opposite (if any), we want to preserve the old behavior, where none of these two are displayed in the summary as "real" groups.
**Please do not merge this PR until the following items are filled …
> Summary: Filter out samples tagged with group: setup/teardown

- internal/js/modules/k6/browser/common/frame_session.go
- internal/js/modules/k6/browser/common/page.go
As browser workers get accessed from different events it is possible for this to race. So a new mutex was added so this doesn't happen and abort the test.
Fixes #4566
Races are bad.
> browser: fix race on workers being accessed concurrently

- internal/js/modules/k6/browser/common/screenshotter.go
Removes the deprecated `GetLayoutMetrics.VisualViewport` usage.
See https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-getLayoutMetrics.
The CDP API, `GetLayoutMetrics.VisualViewport`, is deprecated. It doesn't pose an issue for our public surface area. However, it might fail sporadically, which is why we had a check for it.
> Fix deprecated `GetLayoutMetrics.VisualViewport`

- .github/actions/lint/action.yml
Try to fix the lint github action.
Lint action needs to be reusable in different repos. And if used in grafana/k6 it needs to the config from the PR- otherwise use the one from master.
> Try to fix lint GHA

- internal/js/tc55/timers/timers_test.go
Fix for timers tests
It seems to everyonce in a while failing in CI and my only explanations is that the timers tick fast enough most times, but not always.
> timers: Fix test by waiting on the eventloop if it was ran too fast

- internal/cmd/launcher.go
Handle signals in the parent process when calling a subprocess.
Prevent the parent from ending prematurely before the subprocess ends.
Also fixes https://github.com/grafana/k6/issues/4735. By separating the `Start` of the process from waiting for the child to end, we can handle separately errors like binary not found (and report them) from the non-zero return codes from the child.   
> handle signals

- cmd/state/state.go
- internal/cmd/config_consolidation_test.go
- internal/cmd/config_test.go
- internal/cmd/launcher.go
- internal/cmd/tests/test_state.go
Adds a flag for configuring the directory used to cache provisioned binaries.
The default value may result confusing as it makes reference to the `k6provider` library. 
Fixes #4741 
> Binary provisioning/add cache dir flag

- examples/browser/colorscheme.js
- examples/browser/device_emulation.js
- examples/browser/dispatch.js
- examples/browser/evaluate.js
- examples/browser/fillform.js
- examples/browser/grant_permission.js
- examples/browser/hosts.js
- examples/browser/keyboard.js
- examples/browser/locator.js
- examples/browser/locator_pom.js
- examples/browser/mouse.js
- examples/browser/multiple-scenario.js
- examples/browser/pageon-metric.js
- examples/browser/pageon.js
- examples/browser/querying.js
- examples/browser/screenshot.js
- examples/browser/throttle.js
- examples/browser/touchscreen.js
- examples/es6sample.js
- examples/http_batch.js
- examples/thresholds_readme_example.js
Replace test.k6.io with the quickpizza variant to fix e2e tests and examples
test.k6.io was shutdown which leads to the e2e browser tests to fail
> examples: move from test.k6.io to quickpizza and related fixes

- .github/workflows/packager.yml
Use the shared workflow to login to the DockerHub registry instead of using a custom logic
> packager: Use the shared workflow for Docker login

- .github/workflows/build.yml
- .github/workflows/packager.yml
It adjusts permissions for the packager workflow. It also drops the login to DockerHub as it isn't required.
> packager: Adjust permissions

- release notes/v1.0.0.md
Release notes for k6 v1.0.0. Because we've shipped most of the stuff already, and it also builds on top of release candidates, I've extracted a couple of highlights based on my presentation and the upcoming blog article.
Pending task is to list the merged PRs for UX/bugs since v1.0.0-rc1 (rc2?)
> Release notes for k6 v1.0.0

- internal/js/modules/k6/browser/common/element_handle.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/js_handle.go
Before this in cases like #4564 you can have an error that stringifies ElementHandle object. That object has many other objects inside of it, some of which have maps or other more complex structure. None of which are thread safe to be accessed without locking.
This is very likely the reason for the race conditions in #4564 (maybe other cases as well). In this case we do have ElementHandle as the argument - we get an error due to likely it getting disposed while converting it. And then we start returning an error that has it just stringified. While fmt goes through the object we get another event (maybe exactly the same) modifying one of the many maps within the object - likely under the Frame specifically.
This also likely leads to pretty useless logs due to the amount of fields both …
> k6/browser: Fix race conditions from stringifying types

- internal/js/modules/k6/browser/browser/locator_mapping.go
- internal/js/modules/k6/browser/browser/mapping_test.go
- internal/js/modules/k6/browser/common/js/injected_script.js
- internal/js/modules/k6/browser/common/locator.go
- internal/js/modules/k6/browser/common/selectors.go
- internal/js/modules/k6/browser/tests/locator_test.go
This PR adds three APIs for the `locator` class. These are:
* `nth` which can be used to return the nth element given a selector (e.g. if we have many rows, and we want to select the 5th row in a table, then we can do `locator.nth(4)`).
* `first` which will return the first element (0th) given a selector (e.g. if we have many rows, and we want to select the first row in a table, then we can do `locator.first()` instead of `locator.nth(0)`).
* `last` which will return the last element given a selector (e.g. if we have many rows, and we want to select the last row in a table, then we can do `locator.last()` instead of `locator.nth(-1)`).
There are many benefits of working with `locator` based APIs over element based APIs such as `$` and `$$`. The main two are that we can declare it once and …
> Add `locator` APIs `nth`, `first`, and `last`

- internal/js/modules/k6/browser/common/element_handle.go
We're swapping out the use of working with `cdppage.GetLayoutMetrics` to working with a manual workaround that retrieves the current frame's width and height from the utility context.
This should avoid NPDs that we sometimes see. More context can be found here in Playwright's PR for a similar issue: https://github.com/microsoft/playwright/pull/2669.
Issue: https://github.com/grafana/k6/issues/4123
Comment: https://github.com/grafana/k6/issues/4123#issuecomment-2962348396
> Fix NPD on `click` API call

- .github/workflows/build.yml
- packaging/bin/create-deb-repo.sh
- packaging/bin/create-msi-repo.sh
- packaging/bin/create-rpm-repo.sh
- packaging/bin/entrypoint.sh
- packaging/docker-compose.yml
Retrieves secrets from Vault and adjusts the k6packager deployment process.
Passing builds:
- https://github.com/grafana/k6/actions/runs/15641571150/job/44070316796
- https://github.com/grafana/k6/actions/runs/15641760295/job/44070908513
See grafana/k6-cloud#3483 for more details.
For stronger security.
- grafana/k6-cloud#3483
> Switch k6 packager to Vault

- internal/js/modules/k6/browser/common/element_handle.go
- internal/js/modules/k6/browser/tests/locator_test.go
Add [locator.selectOption](https://grafana.com/docs/k6/next/javascript-api/k6-browser/locator/selectoption/) support for label matching if it's a string input, cases like:
```
<select name="numbers" id="numbers-options" multiple>
<option value="zero">Zero</option>
<option value="one">One</option>
<option value="two">Two</option>
<option value="three">Three</option>
<option value="four">Four</option>
<option value="five">Five</option>
</select>
await options.selectOption(['Two', 'Four']); // labels
await options.selectOption('Five'); // label
```
Playwright does support that https://playwright.dev/docs/api/class-locator#locator-select-option
Closes https://github.com/grafana/k6/issues/4111
> Browser: Support string-labels in locator.selectOption

- internal/js/modules/k6/browser/browser/mapping_test.go
- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/js/injected_script.js
- internal/js/modules/k6/browser/common/locator_options.go
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/common/selectors.go
- internal/js/modules/k6/browser/tests/get_by_test.go
- internal/js/modules/k6/browser/tests/static/get_by_role_edge_cases.html
- internal/js/modules/k6/browser/tests/static/get_by_role_explicit.html
- internal/js/modules/k6/browser/tests/static/get_by_role_implicit.html
- internal/js/modules/k6/browser/tests/test_browser.go
This PR adds a long awaited feature which is `page.getByRole`. It makes working with selectors slightly simpler. More `getBy*` APIs are in the works.
It is a lot simpler to work with `getByRole` instead of XPath or CSS selectors in most cases.
https://github.com/grafana/k6/issues/4764
https://github.com/grafana/k6/issues/4320
https://github.com/grafana/k6/issues/4248
> Add getByRole in the browser module

- README.md
This PR adds a note under the first example script before the Documentation section to mention k6 Studio is available for users that don't want to write scripts themselves.
This change is made to increase visibility of the k6 Studio application.
> add k6 Studio mention in readme

- internal/js/modules/k6/browser/common/network_manager.go
Downgrading a specific log from error to debug.
Internal error that the user cannot action on. Occurs when the request is no longer being tracked by chromium, usually due to a navigation.
> Update log to debug on "Invalid InterceptionId"

- internal/js/modules/k6/browser/browser/locator_mapping.go
- internal/js/modules/k6/browser/browser/mapping_test.go
- internal/js/modules/k6/browser/common/locator.go
- internal/js/modules/k6/browser/tests/locator_test.go
Adds support for locator.all() function to get an array of locators (see https://playwright.dev/docs/api/class-locator#locator-all).
This is a useful function of the Playwright API to work with multiple elements.
> Browser: Add locator.all

- internal/js/modules/k6/browser/browser/frame_mapping.go
- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/frame_options.go
- internal/js/modules/k6/browser/common/frame_options_test.go
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/tests/frame_manager_test.go
- internal/js/modules/k6/browser/tests/frame_test.go
- internal/js/modules/k6/browser/tests/lifecycle_wait_test.go
- internal/js/modules/k6/browser/tests/page_test.go
- internal/js/modules/k6/browser/tests/static/waitfornavigation_test.html
- internal/js/modules/k6/browser/tests/webvital_test.go
This adds/uses the `url` option in `waitForNavigation`. This extends `waitForNavigation` so that k6 waits for a specific URL before continuing on.
Many users have to work with websites which perform lots of redirects during an auth login process. They would currently have to either:
```js
await Promise.all([
page.waitForNavigation(),
page.locator('a[href="/my_messages.php"]').click(),
]);
// Wait for an arbitrary amount of time to make sure that any redirects during the navigation have completed entirely and we are now on the specific page.
page.waitForTimeout(2000);
```
Or
```js
await page.locator('a[href="/my_messages.php"]').click()
await page.locator('//div[text()="You made it passed all the redirects!"]').waitFor()
```
Now we have another option for those who want a repeatable, …
> Add `url` option for `waitForNavigation`

- output/cloud/expv2/output.go
It creates log lines that announce that metrics and traces have been flushed to the cloud at the `trace` level instead of `debug`.
Because these operations are executed many times per test execution, these lines are repeated repeatedly, generating noise rather than bringing value. We generally use `debug` as the "default" log level when monitoring our systems and/or in integration tests, but these log lines are generally filtered out.
In case of error while flushing, the error will be handled and reported as such (with `error` log level).
N/A
> Log metrics & traces flush to cloud as 'trace'

- .github/workflows/test.yml
- internal/js/modules/k6/browser/tests/page_test.go
- internal/js/tc55/timers/timers_test.go
Couple of fixes for tests that are flaky in the GHA CI
CI stability helps with development.
> Ci stability

- internal/api/server.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
- vendor/modules.txt
I have a friend who is using k6 for some massive database load-tests that run for hours. However, k6 is OOMing sometimes and they'd like to understand if they need to modify GOGC values.
The easiest way for them to do it is to leverage the Prometheus Golang runtime metrics. This was brought up before in #3535 however, it was rejected for two reasons:
1. `client_golang` dependency might go away in favor of OTel
2. The future of metrics exposition is OTel
However I'd like to reopen this for two reasons. `client_golang` is a dependency of `opentelemetry-go` as well. So that dependency is not going away.
But the more important reason is that there are already many high performance Golang systems exposing `/metrics` and the metrics and tooling around them is pretty mature and extensive.
The …
> Add Prometheus metrics endpoint

- internal/js/modules/k6/browser/common/element_handle.go
Potential fix for [https://github.com/grafana/k6/security/code-scanning/91](https://github.com/grafana/k6/security/code-scanning/91)
To address the issue, we need to ensure that the conversion from `float64` to `int` is safe and does not result in unexpected values. This can be achieved by:
1. Adding bounds checks to ensure the `float64` value is within the valid range for the `int` type.
2. Returning an error or a default value if the bounds are violated.
The fix involves modifying the `count` function in `internal/js/modules/k6/browser/common/element_handle.go` to include bounds checks using constants from the `math` package (`math.MinInt32` and `math.MaxInt32` for 32-bit systems, or equivalent for 64-bit systems).
---
_Suggested fixes powered by Copilot Autofix. Review carefully before …
> Potential fix for code scanning alert no. 91: Incorrect conversion between integer types

- internal/js/console_test.go
Fix a race using the same sobek.Runtime in parallel in recently added tests
It triggers the race detector, albeit requiring `-timeout` to be used by every experiment I ran
hat tip @ankur22 for bisecting the original commit
> tests: fix a race using the same sobek.Runtime in parallel

- internal/js/modules/k6/browser/browser/mapping_test.go
- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/tests/get_by_test.go
- internal/js/modules/k6/browser/tests/static/get_by_title.html
This adds a convenience method on `page` to be able to select on elements with the `title` attribute.
This is part of the story of adding `getBy*`, which makes working with selectors a little easier. We used to have to work with the `page.locator` API providing either a `CSS` selector or a `XPath` selector if we wanted to get the element by the `title` attribute on an element:
```html
<div title="Information box">This is some information</div>
```
```js
const l = page.locator('div[title="Information box"]'); // CSS
const l = page.locator('//div[@title="Information box"]'); // XPath
```
Now we can use:
```js
const l = page.getByTitle('Information box');
```
Working with `getBy*` in general is an industry standard in the frontend testing world.
**Please do not merge this PR until the …
> Add getByTitle in the browser module

- internal/js/modules/k6/browser/browser/module.go
- internal/js/modules/k6/browser/env/env.go
- internal/js/modules/k6/experimental/websockets/blob.go
- internal/lib/testutils/untar.go
- internal/output/opentelemetry/tls.go
- internal/output/prometheusrw/remotewrite/config.go
- internal/output/prometheusrw/remotewrite/config_test.go
Remove some `gosec` nolint warnings
Reducing potential security issues, especially where there is no need for the small issues to be fixed.
This is marked as breaking change due to Prometheus and opentelemetry outputs now requiring TLS 1.3 - which seems just like the correct thing to do. I can't imagine there are any implementations that do not support 1.3 for the last many years now. Yet it still changes the version so I am marking it as a breaking change.
> Drop some gosec comments

- internal/js/modules/k6/browser/browser/mapping_test.go
- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/js/injected_script.js
- internal/js/modules/k6/browser/common/page.go
- internal/js/modules/k6/browser/common/selectors.go
- internal/js/modules/k6/browser/tests/get_by_test.go
- internal/js/modules/k6/browser/tests/static/get_by_text.html
This adds a convenience method on `page` to be able to select on elements with the `text` in the element.
This is part of the story of adding `getBy*`, which makes working with selectors a little easier. We used to have to work with the `page.locator` API providing either a `CSS` selector or a `XPath` selector if we wanted to get the element by the `text` in the element:
```html
<div>Hello World</div>
```
```js
// Not available in CSS
const l = page.locator('//div[text()="Hello World"]'); // XPath
```
Now we can use:
```js
const l = page.getByText('Hello World');
```
Working with `getBy*` in general is an industry standard in the frontend testing world.
https://github.com/grafana/k6/issues/4792, …
> Add getByText in the browser module

- go.mod
- go.sum
- internal/cmd/launcher.go
- internal/cmd/launcher_test.go
- vendor/github.com/grafana/k6deps/README.md
- vendor/github.com/grafana/k6deps/analyze.go
- vendor/github.com/grafana/k6deps/dependencies.go
- vendor/github.com/grafana/k6deps/internal/rootfs/rootfs.go
- vendor/github.com/grafana/k6deps/options.go
- vendor/modules.txt
Creates a bridge between the internally used `afero.Fs` library and golang's standard `fs.FS` and use it in the `k6deps` library.
`afero.FS` will eventually be removed from `k6`. Therefore, we want to prevent creating more dependencies from this library
> Binary provisioning/pass fs to k6deps

- internal/cmd/launcher.go
- internal/cmd/launcher_test.go
Analyze if the built-in extensions satisfy the dependencies before provisioning a new custom binary
Binary provisioning is available in any k6 binary, including those with built-in extensions. Considering these extensions can save unnecessary custom binary provisionings.
Depens on https://github.com/grafana/k6/pull/4801
Closes https://github.com/grafana/k6/issues/4697
> analyze built-in extensions

- .github/workflows/test.yml
Tests in the CI were not run with `-race` for some cases (except on x86_64 linux machines). This was due to them being flaky, but me running test 10 times on GHA seems to have no more flakiness.
I do expect this is in big parts golang making the race detector lighter and in some parts our tests being less flaky.
Actually it does fix a timeout on a test within cloud that I can't understand or figure out, that only happens on arm64 runners. It will be nice if we know if this is a bug, but it only happens on arm runners and only if we do not have `-race`. 
The arm runners failing is quite distracting especially as it truly seems like a not real issue, just some test problem. 
It also is nice if we catch race conditions earlier, and as it seems that we do not hit flakiness with this it seems …
> ci: Run tests with `-race` always

- examples/browser/route_continue.js
- internal/js/modules/k6/browser/browser/route_mapping.go
- internal/js/modules/k6/browser/common/frame_manager.go
- internal/js/modules/k6/browser/common/http.go
- internal/js/modules/k6/browser/common/network_manager.go
- internal/js/modules/k6/browser/tests/frame_manager_test.go
This PR adds the `route.continue` function. Used in `page.route`, it allows to continue a request with modified: header, body, method or URL. 
This helps with Playwright compatibility and allow to add headers to specific request (especially useful when dealing with CORS or authentication issues).
> Browser: add route.continue

- .github/workflows/test.yml
Revert partially 45a99b7e9 on windows and cleanup MacOS 
Windows CI is failing a bit more it seems (hard to judge really) and while the failure isn't around race it seems reasonable that it might be provoked by it.
Also there are some macos stuff - but it doesn't seem likely we will run CI on MacOS. 
> ci: Again run windows tests with -race and MacOs cleanup

- cmd/state/state.go
- internal/cmd/launcher.go
- internal/cmd/launcher_test.go
Modifies the logic for using the community extensions catalog to prevent changing the URL for custom build service deployments.
The changes introduced in [support community extensions #4922](https://github.com/grafana/k6/pull/4922) added the `/cloud` path to the build service URL by default and added `/oss` when community extensions are enabled.
This is correct for the default build services, but not for custom build services that don't implement either of these paths.
Closes #4995
> fix logic for getting the build service URL

- cmd/state/state.go
- internal/cmd/launcher.go
- internal/cmd/launcher_test.go
- internal/cmd/root.go
- internal/cmd/tests/cmd_run_test.go
Update feature for binary provisioning as automatic extension resolution, and adjust comments and log messages.
Use a name that reflects the functionality instead of the technical details of the implementation.
> Binary provisioning/rename feature

- internal/js/modules/k6/browser/browser/page_mapping.go
Fixes 2 panics in new APIs found during documentation creation by @ankur22 
Panics are bad, even in new APIs. 
> Fix panics in waitForURL and waitBy*

- cmd/state/state.go
- internal/cmd/tests/cmd_run_test.go
Adds a smoke test for running k6 with the automatic extension resolution (formerly known as binary provisioning) disabled.
This feature is now enabled by default, so all tests in the k6 test suite will go through the binary provisioning path. It is important to have a test that goes through the other path (binary provisioning disabled)
> test for binary provisioning disabled

- internal/cmd/launcher.go
- internal/cmd/tests/tests_test.go
This happened due to auto extension resolution wrongly guessing that `cloud` here means it needs to analyze a script. But it doesn't, and consequently panics.
Panics are bad.
Fixes #5055
> fix: do not panic on `k6 login cloud`

- internal/cmd/launcher.go
- internal/cmd/tests/tests_test.go
This is backporting #5057 to 1.2.x 
So we can release a 1.2.2 with this fixed.
> Backport: fix: do not panic on k6 login cloud

- internal/build/version.go
- release notes/v1.2.2.md
v1.2.2 release notes and version bump
This part of creating v1.2.2 to fix a breaking change in v1.2.1 
> Release v1.2.2

- packaging/Dockerfile
- packaging/bin/create-rpm-repo.sh
It updates the k6packager base image to the latest Debian LTS release.
It also replaces `createrepo` with its variant implemented in C, named `createrepo_c`.
Because the Debian version in-use is more than one year old and no longer under LTS guarantees.
Because `createrepo` (the old one, written in Python) is no longer available in newer Debian repositories, and its variant implemented in C is the way to go, as mentioned in https://github.com/grafana/k6/issues/4947#issuecomment-3161112089.
Closes #4947
> k6packager: Update to the latest Debian LTS and adjust the createrepo variant

- internal/js/modules/k6/grpc/client.go
- internal/js/modules/k6/grpc/client_test.go
- internal/lib/netext/grpcext/conn.go
- internal/lib/netext/grpcext/stream.go
After #5017 turned out that k6 does not propagate the types it loads when making gRPC calls. This means that in many of the cases the globalTypes will be used, which will lead to errors. 
This likely is not just around `Any` but is how it was reported.
This PR goes and propagates the types in each place where they will be marshaled/unmarshalled.
The added test is not perfect, but does catch the problem without needing #4981 which I would expect would've also caught this. As currently the server will load the prototypes in the global types and k6/net/grpc will load them in their local types. And then they will technically work. 
This likely breaks loading grpc proto types for anything using `Any`, but likely more cases.
**Please do not merge this PR until the following items are filled …
> grpc: Fix usage of Any types after refactor on protobuf loading

- internal/cmd/launcher.go
- internal/cmd/launcher_test.go
The original PR is fixing auto resolution not working if the k6 binary is not called `k6` as if it is called `k6.v1.2.2`.
Auto extension resolution should not depend on what the binary is called.
> Backport fix: better detection of root command for auto extension resolution

- internal/js/modules/k6/browser/browser/locator_mapping.go
- internal/js/modules/k6/browser/browser/mapping_test.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/locator.go
- internal/js/modules/k6/browser/tests/locator_test.go
This change adds `boundingBox` to `locator`.
When working on another issue (https://github.com/grafana/k6/pull/5071) I found it useful to work with this API. It's also part of Playwright, so bringing this in will give us better parity with Playwright.
https://github.com/grafana/k6/issues/4490
> Add `locator.boundingbox`

- packaging/bin/create-rpm-repo.sh
After #5072 the createrepo command is createrepo_c - apperantly as it is now implemented in c.
Fixes the rpm repo build 
> k6packager: createrepo command is now createrepo_c

- internal/js/modules/k6/browser/common/page.go
Adding a comment to help others know why we use the element's session to get the description of itself.
NA
https://github.com/grafana/k6/pull/5071/commits/38a49a8ac468118ff77ed82f9a249e66636fe908
> Add comment on why we use element's session

- internal/js/modules/k6/browser/browser/frame_mapping.go
- internal/js/modules/k6/browser/browser/mapping_test.go
- internal/js/modules/k6/browser/tests/get_by_test.go
It adds the mapping for all the `getBy*` methods for the `frame` API.
Because we have already implemented all those methods, and we want to expose them as a way to increase our compatibility with Playwright, as described in #5037.
Closes  #5037
> Implement the `frame.getBy*` methods

- internal/js/modules/k6/browser/browser/element_handle_mapping.go
- internal/js/modules/k6/browser/common/element_handle.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/js/injected_script.js
- internal/js/modules/k6/browser/tests/element_handle_test.go
- internal/js/modules/k6/browser/tests/locator_test.go
- internal/js/modules/k6/browser/tests/mouse_test.go
- internal/js/modules/k6/browser/tests/static/hide_unhide.html
This fixes an issue that was long standing but was made evident after a recent fix for CORS and `click` (https://github.com/grafana/k6/pull/5071). It does three things:
1. Calling `BoundingBox` in `ElementHandle` now returns an error to the caller. It wasn't obvious that the bounding box could be `nil` which caused the NPD in the first place. There is a valid reason for the bounding box being `nil` when returned back to the caller if it was called in a script, which is why we keep that behaviour but move it to the mapping layer.
2. We automatically retry when chrome returns us an error indicating that the element is not visible and therefore it can't retrieve data on it (such as the bounding box). The retry will keep retrying until it hits the default timeout or a timeout set by the user …
> Fix actionability retry

- internal/js/modules/k6/browser/common/browser.go
There's nothing that the user can do with this warning, so lets change it to debug to avoid confusion. It's an internal issue that we should look into when users want to work with other types. At the moment we support page and background_page. We might need to work with service_worker in the future when the use case is clearer, and maybe other types.
When i was creating the migration doc from PW to k6, the PW example test script in k6 was logging this warning. Not a great first start to a migration doc with confusing logs that can't be actioned on.
> Update log from warn to debug

- internal/js/modules/k6/browser/browser/page_mapping.go
- internal/js/modules/k6/browser/tests/frame_test.go
- internal/js/modules/k6/browser/tests/page_test.go
This PR aims to tidy up the tests and add new ones where necessary including a refactor in the implementation for `waitForURL`:
1. Refactor to work with `parseStringOrRegex` in `waitForURL`;
2. Refactor tests so that they're easier to maintain and fix when/if they fail;
3. Refactor tests so that they're not flakey;
4. Add `waitForURL` tests to `frame`.
Refactors based on comments made in this PR: https://github.com/grafana/k6/pull/4920
- https://github.com/grafana/k6/pull/4920#discussion_r2215746887
- https://github.com/grafana/k6/pull/4920#discussion_r2238980488
https://github.com/grafana/k6/pull/4920
> Update, add and refactor `waitForURL` and `waitForNavigation` tests

- internal/js/modules/k6/browser/browser/frame_locator_mapping.go
- internal/js/modules/k6/browser/browser/locator_mapping.go
- internal/js/modules/k6/browser/browser/mapping_test.go
- internal/js/modules/k6/browser/common/element_handle.go
- internal/js/modules/k6/browser/common/frame.go
- internal/js/modules/k6/browser/common/frame_locator.go
- internal/js/modules/k6/browser/common/locator.go
- internal/js/modules/k6/browser/common/selectors.go
- internal/js/modules/k6/browser/tests/locator_test.go
- internal/js/modules/k6/browser/tests/page_test.go
This adds a few new APIs. It would have been difficult to implement `frameLocator` on its own without the other two APIs:
1. It implements `frameLocator` which allows the user to interact with elements within `iframe`s with `locator` like APIs.
2. On top of that it implements `locator.contentFrame` which returns a `frameLocator`, allowing the user to actually retrieve a `frameLocator` to start working with elements from with an `iframe`.
3. It implements `frameLocator.locator` allowing users to actually select elements in an `iframe`.
Working with `locator` like APIs is important for maintainable, less flakey tests. It's also a preferred way of working when interacting with `iframe`s in Playwright. We're currently on a drive to improve k6 browser's parity to make migrating from Playwright …
> Add `frameLocator`, `frameLocator.locator` and `locator.contentFrame`

- internal/js/modules/k6/browser/common/locator.go
- internal/js/modules/k6/browser/common/selectors.go
Changes for `Locator.Filter` reviews.
See #5033 tasks.
#5114
> Changes for `Locator.Filter` reviews

- .github/actions/lint/action.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/tc39.yml
- .github/workflows/test.yml
- .github/workflows/wpt.yml
- .github/workflows/xk6.yml
- Dockerfile
Update k6 to use go 1.24 and 1.25 instead of 1.23 and 1.24.
1.25.1 contains bug fixes and security fixes.
> Deps: upgrade go to 1.25 in workflows and Dockerfile

- internal/cmd/run.go
- internal/cmd/runtime_options.go
- internal/cmd/tests/cmd_run_test.go
- internal/lib/summary/summary.go
👋🏻  _(I have already created https://github.com/grafana/k6/issues/5119, which somehow accompanies the `TODO`s I left in the code, and will represent the effective cleanup for `--no-summary`)_
It adds a new `disabled` summary mode and marks `--no-summary` as deprecated, with the idea of being removed by v2.0, as described in #5119.
Because we want to unify both the codebase and the user-experience, by unifying the available options around the end-of-test summary and its different modes.
Closes https://github.com/grafana/k6/issues/4624
> Move `--no-summary` as a `--summary-mode` and deprecate it

- internal/cmd/version.go
- internal/cmd/version_test.go
Try to more accurately asses the version of k6 also in cases where it is build with xk6.
This should remove the need to bumpd the constatnt with the version.
When using xk6, k6 is a dependancy instead of the main version which leads to `k6 version` just returning the constant, irregardless if k6 is build from a later commit.
Before with `xk6 build e2181aa00` - previous commit from before this changes:
vs wiuth latest commit here
and vs `go build` from the latest commit here again
Some of this functionality seems to be dependant on go 1.24.x as discussed in https://github.com/grafana/k6build/pull/197 
I am not removing the constant for now, probably after 1.3.0 we can consider removing it.
> Make k6 get it version entirely from the build info

- examples/browser/locator_filter.js
- internal/js/modules/k6/browser/browser/frame_locator_mapping.go
- internal/js/modules/k6/browser/browser/locator_mapping.go
- internal/js/modules/k6/browser/common/frame_locator.go
- internal/js/modules/k6/browser/common/locator.go
- internal/js/modules/k6/browser/tests/locator_test.go
- internal/js/modules/k6/browser/tests/page_test.go
- Adds `LocatorOptions` to `Locator.Locator`.
- Adds `LocatorOptions` to `FramrLocator.Locator`.
- Tests the behavior with `LocatorOptions` and `Locator.Filter`.
It's a part of #5033.
- Updates: #5033 
- Related: #5114
- Related: #5131
> Add `Locator|FrameLocator.Locator(..., LocatorOptions)`

- internal/output/prometheusrw/remotewrite/prometheus.go
- internal/output/prometheusrw/remotewrite/prometheus_test.go
- internal/output/prometheusrw/remotewrite/remotewrite_test.go
- internal/output/prometheusrw/remotewrite/trend.go
It changes the way we look for the `__name__` label in order to transform trend stats metrics, according to our docs.
Because the current code doesn't always find the label, as expected, and thus it doesn't produce the expected outcome.
Closes https://github.com/grafana/k6/issues/5175
Thanks for your contribution @cuelebreorg! 🙏🏼
> Fix Prometheus RW trend stats metric transformation

- .github/workflows/issue-auto-assign.yml
Add @AgnesToulet to the issue auto assigne workflow
Both so Agnes gets assigned issues and prevents assigning issues to other member created by her. 
> Add Agnes to the issue auto assign workflow
