grafana/k6

README.md
Had to rewrite a little of the text also as a result
=> Changed info about non-existent --quit flag

run.go
Fix for feature/usagereports that was merged prematurely
=> Send UDP usage report packet from goroutine

stats/influxdb/util.go
Inspired by https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb/influxdb.go and https://github.com/influxdata/influxdb/blob/master/client/v2/example_test.go
=> Create specificed db if it doesn't exist

lib/engine.go
Fix for failure to write JSON output
=> Closes #98

main.go, run.go, ui/progress_bar.go
Me and @majavojnoska just spent the entire afternoon making the output look good, I think it came out pretty good: https://asciinema.org/a/1a6o0a5fkrqtq7f75d6v2hd9u
(asciinema doesn't handle lone `faint` attributes properly, but the placeholder in the progress bar is faint white/black depending on your terminal's theme)
=> Colors! (and ASCII art!)

js/api_http.go
=> Expose effective URL in HTTP response

lib/collector.go, run.go, stats/dummy/collector.go, stats/influxdb/collector.go, stats/json/collector.go
Base changes for implementing https://github.com/loadimpact/k6/issues/156. I'll amend @martinfijal WIP commit on `feature/cloud` branch with changes to cloud collector.
=> Add Collector Init() interface

js/lib/k6/html.js
Implement attr() https://github.com/loadimpact/k6/issues/21
NO tests included since the new JS implementation will lead to refactoring this implementation. The attr() implementation is needed to implement the sample scripts.
=> Added attr() implementation

samples/custom_metrics.js, samples/html_form_post.js, samples/http_basic_auth.js, samples/http_verbs.js, samples/json.js, samples/stages.js, samples/tagging.js, samples/thresholds.js, samples/tls_skip_cert_verification.js
A bunch of example scripts with the intent to showcase different k6 features.
=> Various scripting samples to showcase k6 functionality

samples/REST_API_testsuite/v3_account_login.js, samples/REST_API_testsuite/v3_account_me.js, samples/REST_API_testsuite/v3_load-zones.js, samples/REST_API_testsuite/v3_server-agents.js, samples/REST_API_testsuite/v3_tokens.js
=> Fix samples importing local files

stats/cloud/client.go, stats/cloud/collector.go, stats/cloud/collector_test.go
This PR add batching of when metrics are pushed to the cloud.
=> Cloud batching

README.md
Clarify in README where to ask specific types of questions.
=> Add info on appropriate channels to ask questions

js/bundle_test.go, js/runner.go, js/runner_test.go, lib/options.go, lib/options_test.go, lib/tlsconfig_go1_7.go, lib/tlsconfig_go1_8.go, samples/tlsconfig.js
I missed the !go1.8 tag in the 1.7 file in the last PR, this should build OK now.
=> Quick fix for PR #235

stats/cloud/api_test.go, stats/cloud/client.go, stats/cloud/errors.go
Very simple retry for HTTP requests sent to the cloud
=> Retry feature for cloud communication

main.go
=> cli version and help flags

run.go
With this fix, the usage reports may actually work
=> HTTP-based usage reports, fixed opts.NoUsageReport.Valid bug

js/modules/k6/ws/ws.go
The WebSocket RFC describes that when receiving a `ping` the recipient must send back a pong.
Overwriting the default `pongHandler` disables the `pong` auto-reply for incoming `ping` messages. This change brings back the `pong` auto-reply.
=> fix: websocket sends automatically a `pong` when `ping` is received

stats/cloud/collector.go
=> Fix: when uploading results anonymously, the cloud collector returns the correct URL

Dockerfile
=> Include ca certs in the k6 scratch-based docker image

cmd/run.go, core/local/util.go, core/local/util_test.go, lib/util.go, lib/util_test.go
=> Fix progressBar endDuration when using `stages`

cmd/root.go
=> Fix colored output from windows cmd

cmd/cloud.go, stats/cloud/api.go, stats/cloud/client.go, stats/cloud/collector.go, stats/cloud/util.go
Implements the command to execute a `k6` script onto the Load Impact cloud service.
`k6 cloud script.js`
Closes #366
=> `k6 cloud` command

.circleci/config.yml
=> Add test coverage

lib/metrics/metrics.go, lib/netext/tracer.go, lib/netext/tracer_test.go
Added TLS handshake timing metrics. 
Closes #188.
This PR is an update for closed PR #417, to fix diff issues.
=> Added TLS handshake timing metrics.

stats/cloud/api.go
Add `req.Header.Set("Content-Encoding", "gzip")`
=> Cloud: set `gzip` value to `Content-Encoding` header

js/modules/k6/http/response.go, js/modules/k6/http/response_test.go
=> Implemented `response.clickLink`.

cmd/options.go, js/modules/k6/http/http_request.go
Taking the baton and finishing up https://github.com/loadimpact/k6/pull/406 :)
=> Set default user agent

converter/har/converter.go, converter/har/converter_test.go
Fix the conversion when the `post` data is present on the `postData.params` array. 
```
"postData": {
"mimeType": "application/x-www-form-urlencoded",
"text": "custname=Hola&custtel=123123&custemail=ppcano%40gmail.com&size=medium&topping=bacon&topping=cheese&delivery=12%3A00&comments=",
"params": [
{
"name": "custname",
"value": "Hola"
},
{
"name": "custtel",
"value": "123123"
},
{
"name": "custemail",
"value": "ppcano%40gmail.com"
},
{
"name": "size",
"value": "medium"
},
{
"name": "topping",
"value": "bacon"
},
{
"name": "topping",
"value": "cheese"
},
{
"name": "delivery",
"value": "12%3A00"
},
{
"name": "comments",
"value": ""
}
]
}
```
It will convert to 
```
req = [{
"method": "post",
"url": "https://httpbin.org/post",
"body": {
"custname": "Hola",
"custtel": "123123",
"custemail": …
```
=> Converter: fix `body` parameter when `PostData.Params` values are present.

cmd/common.go, cmd/run.go, core/engine.go, core/engine_test.go, core/local/local.go, core/local/local_test.go, core/local/util_test.go, js/bundle_test.go, lib/executor.go, lib/models.go, lib/models_test.go, lib/options.go, lib/options_test.go, lib/types/types.go, lib/types/types_test.go, lib/util.go, lib/util_test.go, stats/thresholds.go, stats/thresholds_test.go
Closes #449 
Did not add mentioned grace period (check issue), should be trivial to add if we decide to do it.
=> Added support to abort test early if a threshold fails

js/common/state.go, js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go, js/runner.go
This PR gives the same TLS configuration to either HTTP or WebSocket.
Fixes #531
=> Adds TLS configuration to websockets

Gopkg.lock, Gopkg.toml, js/modules/k6/http/http_request.go, js/modules/k6/http/http_request_test.go, release notes/upcoming.md, samples/http_digest_auth.js, vendor/github.com/Soontao/goHttpDigestClient/.gitignore, vendor/github.com/Soontao/goHttpDigestClient/.travis.yml, vendor/github.com/Soontao/goHttpDigestClient/LICENSE, vendor/github.com/Soontao/goHttpDigestClient/README.md, vendor/github.com/Soontao/goHttpDigestClient/challenge.go, vendor/github.com/Soontao/goHttpDigestClient/client.go, vendor/github.com/Soontao/goHttpDigestClient/rfc2617.go, vendor/github.com/nu7hatch/gouuid/.gitignore, vendor/github.com/nu7hatch/gouuid/COPYING, vendor/github.com/nu7hatch/gouuid/README.md, vendor/github.com/nu7hatch/gouuid/uuid.go, vendor/github.com/sirupsen/logrus/README.md
This PR adds support to HTTP Digest authentication
closes #527
=> Adds support to HTTP Digest authentication

Gopkg.lock, js/modules/k6/http/http_request_test.go, js/modules/k6/http/http_test.go, js/modules/k6/http/response_test.go, js/modules/k6/ws/ws_test.go, js/runner_test.go, lib/netext/tracer_test.go, lib/testutils/httpmultibin.go, loader/loader_test.go, vendor/github.com/mccutchen/go-httpbin/httpbin/handlers.go, vendor/github.com/mccutchen/go-httpbin/httpbin/helpers.go, vendor/github.com/mccutchen/go-httpbin/httpbin/httpbin.go, vendor/github.com/mccutchen/go-httpbin/httpbin/middleware.go
Closes https://github.com/loadimpact/k6/issues/464
=> Remove all httpbin.org usage in tests and use a local HTTP server instead

Gopkg.lock, js/bundle.go, vendor/github.com/spf13/afero/.travis.yml, vendor/github.com/spf13/afero/basepath.go, vendor/github.com/spf13/afero/cacheOnReadFs.go, vendor/github.com/spf13/afero/copyOnWriteFs.go, vendor/github.com/spf13/afero/lstater.go, vendor/github.com/spf13/afero/match.go, vendor/github.com/spf13/afero/os.go, vendor/github.com/spf13/afero/path.go, vendor/github.com/spf13/afero/readonlyfs.go, vendor/github.com/spf13/afero/unionFile.go
This PR enables a cached filesystem to avoid successive real disk accesses
closes #530
=> Enabling Cache Filesystem

lib/netext/http.go
When using the `no-connection-reuse` option, the NTLM authentication worked only in the first iteration. This PR fixes it by disabling the NTLM cache when using that option, so every request it will do the whole authentication roundtrip.
closes #599
=> Fixing NTLM auth when using no-connection-reuse option

api/v1/routes.go, api/v1/setup_teardown_routes.go, api/v1/setup_teardown_routes_test.go, core/local/local_test.go, js/runner.go, lib/runner.go
This would hopefully be enough for fully implementing #539 in the backend
=> Add methods for setup and teardown control in the API

release notes/upcoming.md
Ping @jmccann - please take a look if I've missed or messed up something. And again, thank you for contributing these features!
=> Release notes fixes

cmd/convert_test.go, converter/har/converter.go
Use random sleep time between 20s and 40s.
=> k6 convert: set more realistic sleep time.

lib/netext/tracer_test.go
The test `TestTracerNegativeHttpSendingValues` was randomly failing on the CI.
Unfortunately, I wasn't able to reproduce the failure in my local machine, but, since the test is depending on a `time.Sleep` I made a change to avoid that and hope this fixes the problem.
=> Fixing flaky negative http sending test

cmd/login_cloud.go, release notes/upcoming.md
=> Adds option to reset cloud token

js/modules/k6/k6.go, js/modules/k6/k6_test.go, release notes/upcoming.md
=> Add JS API to set seed for PRNG

.circleci/config.yml, appveyor.yml
This changes should fix all the packages building the problem as mostly related to the version variable
=> Fixing package building

README.md
=> simplify brew install

js/modules/k6/http/http_request_test.go
=> Adding tests to verify the cookies on redirect cases

js/modules/k6/http/limiter.go, js/modules/k6/http/limiter_test.go, release notes/upcoming.md
This also fixes https://github.com/loadimpact/k6/issues/770
=> Fix, refactor, document and test the slot limiters

release notes/upcoming.md
Original PR was https://github.com/loadimpact/k6/pull/766, closing issue https://github.com/loadimpact/k6/issues/290
=> Add JSON selectors and an example with them to the release notes

js/common/init_error.go, js/modules/k6/http/http.go, js/modules/k6/http/http_request.go, js/modules/k6/k6.go, js/modules/k6/metrics/metrics.go, js/modules/k6/ws/ws.go, js/runner_test.go, release notes/upcoming.md
instead return an error telling you this is not supported
=> Don't panic on http requests in init context fix #699

js/initcontext_test.go
Added few symbols to test data.
Refactored test of open() method
Related to  #754
=> Refactor init context open()

appveyor.yml, cmd/convert_test.go, cmd/runtime_options_test.go, js/console_test.go, js/initcontext.go, js/initcontext_test.go, js/modules/k6/http/http_request_test.go, lib/archive.go, lib/archive_test.go, lib/netext/tracer.go, lib/netext/tracer_test.go, lib/testutils/httpmultibin.go, loader/loader_test.go
This PR fix all the tests when running them on a Windows machine.
=> Fix tests on Windows

js/common/bridge.go, js/modules/k6/http/request.go, js/modules/k6/http/response.go, js/modules/k6/http/response_test.go
Mostly just documentig exported messages and some more changes to make the package more golint compliant
=> Document/refactor http js module 

stats/cloud/api_test.go, stats/cloud/errors.go
Soon, there will be coming a new error API of the cloud service. This PR allows `k6` to support both error APIs: the current and the new API format and fix some existing marshaling issues (`Details     map[string][]string`).
We plan to remove the handling of the current error API in another PR when this API becomes deprecated, but we have to ensure that:
- all`k6` users are using a version that includes this error handling (a version higher than `v0.23.1`) 
- the current error API is totally obsolete. We plan to support both APIs during the transition period.
cc @Griatch @sniku
=> Handle new cloud error API

README.md
Any other places you think we should mention it?
=> Add community.k6.io in the README

.codecov.yaml
=> Lower codecov PR threshold to 0.3%

.circleci/config.yml, README.md, appveyor.yml, cmd/config_consolidation_test.go, cmd/root.go, core/engine_test.go, js/modules/k6/http/request_test.go, js/modules/k6/marshalling_test.go, js/modules/k6/ws/ws_test.go, js/runner_test.go, release notes/upcoming.md, release notes/v0.24.0.md
This will close https://github.com/loadimpact/k6/issues/938
=> Release k6 v0.24.0

.circleci/config.yml, appveyor.yml, js/runner_test.go
=> Update CI to go1.13

lib/netext/httpext/transport.go
=> docs(httpext): update newTransport comment

.golangci.yml
New golangci-lint release: https://github.com/golangci/golangci-lint#september-2019
=> Disable or relax settings for new golangci linters

cmd/collectors.go
Just taken out the lambda as a separate function, as was suggested in https://github.com/loadimpact/k6/pull/1007#discussion_r333911062.
=> Split newCollector() to silence the funlen linter

stats/cloud/collector_test.go, stats/cloud/config.go, stats/cloud/data.go
Improve and expand `TestCloudCollector()`, as well as further document some of the aggregation code.
Closes https://github.com/loadimpact/k6/issues/1218
=> Aggregation test and doc improvements

lib/executor/shared_iterations.go, lib/executor/variable_looping_vus.go, lib/executor/vu_handle.go, lib/types/types.go, ui/pb/helpers.go, ui/pb/progressbar.go
=> Fix minor issues for #1007 (typos, interface check)

js/modules/k6/http/request_test.go
The commit in question is https://github.com/golang/go/commit/64cfe9fe22113cd6bc05a2c5d0cbe872b1b57860 which is actually pretty good in general, but broke the test and unfortunately I misunderstood which part wasn't working ... so wasted way too much figuring out why we previosly weren't getting this error >.>
=> Fix broken test in go1.14rc1

lib/executor/executors_test.go, lib/executors.go
=> Always get the biggest plannedVUs for a givem timeoffset 

js/modules/k6/ws/ws.go
For the release notes 
```
Websocket: emit metrics for websockets as soon as possible instead of when the websocket is closed (#1367)
```
A future improvement might be to move the WSSessions and WSConnecting before closing as well, but I didn't want this to take more then 5 minutes :D
=> Push websocket metric samples as they are produced

lib/consts/consts.go
Missed this from the actual release... :man_facepalming:
=> Actually bump the version to v0.26.2

Gopkg.lock, vendor/github.com/dop251/goja/builtin_array.go, vendor/github.com/dop251/goja/builtin_json.go, vendor/github.com/dop251/goja/compiler_expr.go, vendor/github.com/dop251/goja/func.go, vendor/github.com/dop251/goja/object.go, vendor/github.com/dop251/goja/object_goreflect.go, vendor/github.com/dop251/goja/object_goslice_reflect.go, vendor/github.com/dop251/goja/runtime.go, vendor/github.com/dop251/goja/string.go, vendor/github.com/dop251/goja/string_unicode.go, vendor/github.com/dop251/goja/vm.go
This pulls in some of the recent fixes from `goja` master.
=> Update goja to latest version

loader/cdnjs_test.go
=> Skip TestCDNJS

.circleci/config.yml, .golangci.yml
=> Run golangci-lint on CircleCI

.circleci/config.yml, .golangci.yml
=> golangci-lint improvements #2

.circleci/config.yml, .golangci.yml, api/v1/status_routes.go, lib/executor/helpers.go, ui/pb/progressbar.go
Another update + linter silencing for now.
=> Merge master into new-schedulers

js/runner.go, js/runner_test.go
~The test time out, but I'm not sure if it's because I have a bug in this code, or if a test is broken somewhere~
This is ready for review, all of the stupid bugs have been fixed... :sweat_smile: It should close https://github.com/loadimpact/k6/issues/1404
=> VU deactivation synchronization fix

lib/netext/httpext/httpdebug_transport.go
=> bug/1402 Stop http-debug from exiting on dump error

README.md
- Update README link to contributing section 
- Closes #1533
=> Update README link for contributing section

cmd/ui.go, lib/executor/constant_arrival_rate.go, lib/executor/constant_vus.go, lib/executor/externally_controlled.go, lib/executor/per_vu_iterations.go, lib/executor/ramping_arrival_rate.go, lib/executor/ramping_vus.go, lib/executor/shared_iterations.go
This should fix points 2 and 3 in https://github.com/loadimpact/k6/issues/1514, and an extra typo... Point 1 of that issue is a bit trickier and will be done in a separate PR
=> Minor fixes

js/modules/k6/http/request_test.go, lib/netext/httpext/request.go
=> Don't log an error we are going to throw

go.mod, go.sum, vendor/github.com/dop251/goja/builtin_regexp.go, vendor/modules.txt
This will make k6 include the fix for https://github.com/dop251/goja/issues/184
=> Update goja to the latest version

go.mod, go.sum, vendor/github.com/dop251/goja/README.md, vendor/github.com/dop251/goja/builtin_regexp.go, vendor/github.com/dop251/goja/runtime.go, vendor/modules.txt
(edit) link to the goja issue: https://github.com/dop251/goja/issues/185#issuecomment-675411987
=> update goja for better regexp.match performance

.github/pull_request_template.md, CONTRIBUTING.md
Adds a PR template asking the user to discuss changes either on slack or in an issue before getting started with their implementation. Adds the same text to the contribution guidelines as well.
=> Contribution updates

.circleci/config.yml, cmd/run.go, go.mod, go.sum, lib/consts/consts.go, vendor/github.com/dop251/goja/README.md, vendor/github.com/dop251/goja/array.go, vendor/github.com/dop251/goja/array_sparse.go, vendor/github.com/dop251/goja/builtin_regexp.go, vendor/github.com/dop251/goja/builtin_string.go, vendor/github.com/dop251/goja/builtin_typedarrays.go, vendor/github.com/dop251/goja/date.go, vendor/github.com/dop251/goja/func.go, vendor/github.com/dop251/goja/object.go, vendor/github.com/dop251/goja/object_args.go, vendor/github.com/dop251/goja/object_gomap.go, vendor/github.com/dop251/goja/object_gomap_reflect.go, vendor/github.com/dop251/goja/object_goreflect.go, vendor/github.com/dop251/goja/object_goslice.go, vendor/github.com/dop251/goja/object_goslice_reflect.go, vendor/github.com/dop251/goja/object_lazy.go, vendor/github.com/dop251/goja/proxy.go, vendor/github.com/dop251/goja/runtime.go, vendor/github.com/dop251/goja/typedarrays.go, vendor/github.com/dop251/goja/value.go, vendor/github.com/dop251/goja/vm.go, vendor/modules.txt
=> Various updates

stats/cloud/config.go, stats/cloud/logs.go
This replaces https://github.com/loadimpact/k6/pull/1620
=> Rename K6_CLOUD_LOGS_HOST to K6_CLOUD_LOGS_TAIL_URL

lib/netext/httpext/request.go, lib/netext/httpext/request_test.go, lib/netext/httpext/transport.go
=> Set url, name and method only once and fix name being empty

.github/workflows/all.yml, Dockerfile
This closes https://github.com/loadimpact/k6/issues/1589
=> Build k6 with Go 1.15

README.md, samples/es6sample.js, samples/http_batch.js, samples/thresholds_readme_example.js
=> Use k6.io test domains instead of loadimpact

README.md
Bump windows installer version in readme
=> [fix] update windows installer to latest version.

cmd/ui.go
This closes https://github.com/loadimpact/k6/issues/1860. The data race is completely harmless, but its annoying when k6 is ran with `-race`, potentially masking other more serious ones.
=> Fix a data race when rendering progress bars

output/cloud/output.go
This is a quick fix, I'll write up a test later
=> Fix cloud output metric pushing

.github/workflows/xk6.yml
=> Run xk6 CI job on k6 fork for external PRs

stats/kafka/config.go, stats/kafka/config_test.go
=> Fix influxdb format configuration for kafka output

js/bundle.go, js/bundle_test.go, lib/options.go
=> Warn on unknown options from script

.github/workflows/packager.yml
Sorry, second time's the charm :)
This time it's confirmed working, I ran https://github.com/k6io/k6/actions/runs/740694498 from this branch.
=> Proper fix GHCR k6packager image tagging and pushing

go.mod, go.sum, vendor/github.com/dop251/goja/object.go, vendor/github.com/dop251/goja/object_goreflect.go, vendor/github.com/dop251/goja/string_unicode.go, vendor/modules.txt
fixes issue reported in the [community forum](https://community.k6.io/t/error-with-goja-goja-valuestring-is-goja-asciistring/1665)
=> Update goja to latest master

lib/executor/constant_arrival_rate_test.go, lib/executor/ramping_arrival_rate.go, lib/executor/ramping_arrival_rate_test.go, stats/sink_test.go
Taken out of https://github.com/k6io/k6/pull/2000
=> Fixes for ARM

go.mod, go.sum, vendor/github.com/andybalholm/brotli/brotli_bit_stream.go, vendor/github.com/andybalholm/brotli/compress_fragment.go, vendor/github.com/andybalholm/brotli/compress_fragment_two_pass.go, vendor/github.com/andybalholm/brotli/encode.go, vendor/github.com/andybalholm/brotli/entropy_encode_static.go, vendor/github.com/andybalholm/brotli/reader.go, vendor/github.com/andybalholm/brotli/write_bits.go, vendor/modules.txt
mostly because of https://github.com/andybalholm/brotli/issues/22
=> Update brotli to v1.0.2

.github/workflows/all.yml, .github/workflows/arm-tests.yml, .github/workflows/packager.yml, build-release.sh
Minor CI changes done while testing the full release pipeline in my fork.
=> Minor CI fix and changes

release notes/v0.32.0.md
=> Release notes for v0.32.0

release notes/v0.32.0.md
Not sure how we missed this :sweat_smile: :man_facepalming:
=> Fix a mistake in the v0.32.0 release notes

js/runner.go, js/runner_test.go, lib/options.go
This fixes https://github.com/k6io/k6/issues/2034
=> Make `minIterationDuration` cancellable

CODE_OF_CONDUCT.md
=> Update CoC k6

js/modules/k6/metrics/metrics.go, js/modules/k6/metrics/metrics_test.go, samples/custom_metrics.js
=> Added GetName method for metrics

output/statsd/config.go, output/statsd/datadog.go
Closes https://github.com/k6io/k6/issues/2048
=> Add `vu`, `iter` and `url` to the default StatsD tag blocklist

loader/cdnjs.go
=> Fix panic on missing files in cdnjs links

log/loki.go
=> Loki: push logs with POST instead of GET request

core/local/local_test.go
Hey,
I hope this fixes this problem as the test now passes on my Mac.
Fixes #2027
Thanks.
=> Fix DNSResolver Fails on OSX

lib/consts/consts.go
=> Release k6 v0.34.0

lib/consts/consts.go, release notes/v0.34.1.md
=> Release k6 v0.34.1

README.md
Fixed the punctuation errors and did other small modifications
=> Copyedited the document upto Script Execution

README.md
Rename `Community` to `Community Forum`
=> [content] readme minor change

cmd/config_consolidation_test.go, js/runner.go, lib/executor/base_config.go, lib/executor/constant_arrival_rate.go, lib/executor/constant_vus.go, lib/executor/externally_controlled.go, lib/executor/helpers.go, lib/executor/per_vu_iterations.go, lib/executor/ramping_arrival_rate.go, lib/executor/ramping_arrival_rate_test.go, lib/executor/ramping_vus.go, lib/executor/ramping_vus_test.go, lib/executor/shared_iterations.go, lib/options_test.go, output/cloud/output.go, output/csv/output.go, output/influxdb/output.go, output/statsd/output.go
This PR is an attempt to resolve GH-2203.
Any kind of feedback are welcome 🎉
=> Use TimeDuration helper for NullDuration types

.github/pr-auto-assign-config.yml
=> Add oleiade to pr-auto-assign config

js/modules/k6/crypto/crypto.go, js/modules/k6/crypto/crypto_test.go, js/modules/k6/crypto/x509/x509.go, js/modules/k6/crypto/x509/x509_test.go
Migrated `k6/crypto` to the `modules.Module` (aka modules.ModuleV2) interface.
=> js/crypto: ModuleV2 migration

.golangci.yml
Disable the `varnamelen` to not block the other PRs
=> Disable varnamelen

.golangci.yml
=> Disable ireturn linter

js/bundle.go
=> chore: fix clarity

cmd/archive.go, cmd/cloud.go, cmd/config.go, cmd/config_consolidation_test.go, cmd/config_test.go, cmd/inspect.go, cmd/run.go, core/engine_test.go, core/local/local_test.go, lib/executor/execution_config_shortcuts.go
this is the last commit (with changes) from #2353
=> Remove global logrus usage from DeriveScenariosFromShortcuts

.github/pr-auto-assign-config.yml
=> Unique pool of reviewers

CODE_OF_CONDUCT.md, README.md, SUPPORT.md
=> Updating Code of Conduct and Github urls

.github/workflows/tc39.yml, go.mod, go.sum, vendor/github.com/dop251/goja/vm.go, vendor/modules.txt
=> Maintenance update of dop251/goja to a18ffb9 from b09a6bf

packaging/deb.json, packaging/k6.portable.nuspec, packaging/k6.wxs, packaging/rpm.json
=> Updated packages ownership

js/modules/k6/grpc/client.go
This is a simple refactor of the dialling part and some other minor changes for easier splitting in next PRs the `js/k6/grpc` module.
Going through the PR commit by commit is suggested.
=> js/grpc: Connect refactor

js/modules/k6/grpc/client.go, lib/netext/grpcext/conn.go, lib/netext/grpcext/conn_test.go, lib/netext/grpcext/reflect.go
Added some nice suggestions provided in the previous PR. https://github.com/grafana/k6/pull/2484#discussion_r855101304)
=> Amended the gRPC module refactor

samples/graphql.js
Updating the graphql sample to use new GitHub org :sparkles:
=> chore: update graphql sample

metrics/metric.go
=> Don't error on adding submetrics again, reuse them

.github/pr-auto-assign-config.yml
It was lowered cased in github a few weeks back
=> Lower case MStoykov username in pr auto assign

lib/executor/ramping_vus.go, lib/executor/ramping_vus_test.go
This reverts commit b725f03be5873b9b0d933b94a83924ff7c1f15e4.
=> Revert "Try to respect zero target stages at the end (#2532)"

core/engine_test.go
Previous to that some tests were trying to not run the engine, which is
both not how the Engine is supposed to work and could lead to a
particular race condition where VUs metrics are emitted but the engine
has been stopped (after never been run).
=> core: make all test run the engine

js/common/bridge_test.go, js/common/randsource.go, js/common/util.go, js/common/util_test.go, lib/netext/httpext/transport_test.go
I tried to run the benchmarks and (once again actually) found out that some benchmarks haven't been passing at all for some time.
So this is basically fixing that.
=> Fix benchmarks

README.md
This closes https://github.com/grafana/k6/issues/2608
=> Fix install advice for older rpm-based distros

lib/netext/grpcext/conn.go
The `getTags` function was returning an empty map in the case the tags per request are not found in the context.
It's a bit fragile logic and it was difficult for new maintainers. It should help with the transition to the new TagSet.
Related to: https://github.com/grafana/k6/pull/2594
=> js/grpc:  vu.State.Tags in case of Reflection requests

js/runner.go, js/runner_test.go
Hello 🙂,
Here is my contribution regarding #2613 
Is this what you had in mind ?
=> fix(js/runner): set RPSLimit if value is above zero. Closes #2613

lib/executor/constant_arrival_rate_test.go
https://github.com/grafana/k6/issues/1715 became more of an issue apparently with this Windows slowdown :disappointed:
=> Fix more flaky tests on Windows

samples/base64.js, samples/jwt.js, samples/tlsconfig.js
=> Update script samples to work with latest k6 version

.github/workflows/arm-tests.yml, .github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/tc39.yml, .github/workflows/test.yml, .github/workflows/xk6.yml, Dockerfile
Upgrading go attempts to fix https://github.com/grafana/k6/issues/2474
=> Bump go to 1.19.1 and alpine to 3.16

js/modules/k6/grpc/client.go, js/modules/k6/grpc/client_test.go
This PR resolves #2661 - following the guidance given in the issue.
=> add nil check for req, to prevent marshalling nil to json

output/cloud/bench_test.go
This is the current situation between `master` and `atlas` branches. I updated the benchmark for not generating a new Registry for each new bench iteration.
~~Apparently the easyjson part is not so happy, I haven't found an obvious reason, I need to isolate the [EasyJSON function](https://github.com/grafana/k6/blob/3e88e18166d90ddf5ca395a6e07b47cb221255c0/metrics/sample.go#L255-L269) in a dedicated benchmark.~~
```
name                       old time/op  new time/op  delta
AggregateHTTP/tags:1-4      185ms ± 6%    37ms ±11%  -79.90%  (p=0.008 n=5+5)
AggregateHTTP/tags:5-4      218ms ± 6%    53ms ±11%  -75.45%  (p=0.008 n=5+5)
AggregateHTTP/tags:35-4     225ms ± 3%    60ms ±10%  -73.42%  (p=0.008 n=5+5)
AggregateHTTP/tags:315-4    310ms ± 3%    61ms ±12%  -80.31%  (p=0.008 n=5+5) …
```
=> cloud/output: Atlas friendly benchmarks

SECURITY.md
For easy copying.  It makes it stand out more than plain text too.
=> Put PGP into a code block

cmd/convert.go, cmd/convert_test.go
=> Deprecate k6 convert

js/common/tags.go, js/modules/k6/execution/execution.go, js/modules/k6/execution/execution_test.go, js/modules/k6/grpc/client.go, js/modules/k6/grpc/client_test.go, js/modules/k6/http/request.go, js/modules/k6/k6.go, js/modules/k6/metrics/metrics.go, js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go, lib/netext/httpext/request.go, lib/netext/httpext/request_test.go
Refactoring of the logic for applying user-defined tags in a centralized function.
It also includes the change for always raising an exception in case of a denied type is provided. https://github.com/grafana/k6/issues/2653
Closes https://github.com/grafana/k6/issues/2653
=> js: ApplyCustomUserTags

lib/netext/httpext/transport_test.go
=> httpext: Fix the emit metric benchmark

README.md
=> chore: use hkps

cmd/test_load.go, cmd/tls_integration_test.go
Hey 🙂 
This is what I understood of the #2364 issue.
I'd like some input on how to test this programmatically. I don't see much change when running k6 with or without the line.
Regards,
=> feat(local): load system cert pool. Resolves #2364

js/modules/k6/ws/ws.go
This refactors parts of the `WS.Connect()` method to extract argument parsing and establishing of the WS connection into separate functions.
It's built on top of #2767, so we should review/merge that first.
=> Refactor `WS.Connect()`

CONTRIBUTING.md, README.md
=> Shorten and modernize README

go.mod, go.sum, vendor/github.com/grafana/xk6-websockets/websockets/events/events.go, vendor/github.com/grafana/xk6-websockets/websockets/helpers.go, vendor/github.com/grafana/xk6-websockets/websockets/listeners.go, vendor/github.com/grafana/xk6-websockets/websockets/params.go, vendor/github.com/grafana/xk6-websockets/websockets/websockets.go, vendor/modules.txt
Bumping xk6-websockets to the latest version.
We implemented some things, we'd like to give them to the users.
TODO(@olegbespalov )
=> xk6-websockets v0.1.6

core/local/local_test.go
This closes https://github.com/grafana/k6/issues/1974
=> Fix a flaky error check in a test on Windows

README.md
=> Fix link to protocols documentation in README.md

go.mod, go.sum, vendor/github.com/grafana/xk6-output-prometheus-remote/pkg/remote/client.go, vendor/github.com/grafana/xk6-output-prometheus-remote/pkg/remotewrite/config.go, vendor/github.com/grafana/xk6-output-prometheus-remote/pkg/remotewrite/remotewrite.go, vendor/github.com/grafana/xk6-output-prometheus-remote/pkg/remotewrite/trend.go, vendor/github.com/grafana/xk6-output-prometheus-remote/pkg/stale/stale.go, vendor/modules.txt
It updates the output to v0.0.9 version
=> Bump the Prometehus remote write

lib/consts/consts.go, release notes/v0.42.0.md
=> Release notes v0.42.0

go.mod
go.mod: merge indirect require section.
=> go.mod: merge indirect require section

js/bundle.go, js/runner_test.go
DRYing the initialization of a bundle and adding a test for previously not tested archiving of an archive
=> js: Refactor initializing a bundle

js/runner_test.go
https://github.com/golang/go/commit/62a994837a57a7d0c58bb364b580a389488446c9
=> Fix test that fails on gotip due to wrong error message

Dockerfile
* Use COPY not ADD  for files 
* Pin versions for apk packages
https://hadolint.github.io/hadolint/
=> Implement Dockerfile lint recommendations from hadolint

lib/consts/consts.go, release notes/v0.43.0.md
I didn't include some less relevant PRs like #2835, #2852, #2862, #2868 and #2880, but let me know if I missed something that should be mentioned. And any other suggestion, of course :)
=> Release v0.43.0

js/common/bridge_test.go, js/compiler/compiler_test.go, js/modules/k6/http/async_request_test.go, js/modules/k6/http/http_test.go, js/modules/k6/http/request_test.go, js/modules/k6/http/response_test.go, lib/options_test.go
This is a non functional change for tests
=> tests: Refactor `if assert.*` into `require.*

js/modules/k6/experimental/tracing/module.go
=> Use correct functions in instrumented tracing client for POST and PUT

js/eventloop/eventloop.go, js/eventloop/eventloop_test.go
This is a behaviour change which will make it possible for users of the eventloop to use it as the only way to stop stuff, without needing to do additional stuff if the event loop has errored out, detect it and have a separate way to stop without using it.
The above is in practice very error prone and neigh impossible.
In the future when we have additional mechanism for notifying users of an iteration ending, this behaviour will stay the same as using the event loop is still likely the best way to synchronise around stuff such as the runtime.
=> Change eventloop.WaitOnRegistered to execute callbacks

go.mod, go.sum, vendor/github.com/grafana/xk6-browser/browser/mapping.go, vendor/github.com/grafana/xk6-browser/browser/module.go, vendor/github.com/grafana/xk6-browser/common/browser.go, vendor/github.com/grafana/xk6-browser/common/frame_session.go, vendor/github.com/grafana/xk6-browser/common/session.go, vendor/github.com/grafana/xk6-browser/k6ext/cloud.go, vendor/github.com/grafana/xk6-browser/k6ext/env.go, vendor/github.com/grafana/xk6-browser/k6ext/metrics.go, vendor/modules.txt
This will bring in the latest "release" version of xk6-browser module.
=> Update to v0.9.0 of xk6-browser

js/runner_test.go
turns out the test has been *slightly* broken as it checks the metric against a specific builtinMetrics instance.
Unfortunately that was the instance for the "archive" test and the "source" one was never used.
This works as Equals will compare recursively and both the registry and the builtinMetrics should be the same.
I only noticed it as a test failed with this, but it likely was supposed to fail with something differently. For example a sink having a different value :shrug:
=> Fix TestVUIntegrationMetrics not checking metric exactly

go.mod, go.sum, vendor/github.com/grafana/xk6-browser/common/frame.go, vendor/github.com/grafana/xk6-browser/common/frame_session.go, vendor/github.com/grafana/xk6-browser/common/js/injected_script.js, vendor/github.com/grafana/xk6-browser/common/locator.go, vendor/github.com/grafana/xk6-browser/common/remote_object.go, vendor/github.com/grafana/xk6-browser/k6ext/metrics.go, vendor/modules.txt
This will bring k6 up to date with the latest "release" of the browser module that we want to bring to the attention of our users.
=> Update to v0.10.0 of xk6-browser

cmd/archive_test.go, cmd/convert_test.go, cmd/run_test.go, examples/grpc_server/main.go, js/bundle_test.go, js/console_test.go, js/runner_test.go, ui/pb/progressbar_test.go, vendor/github.com/jhump/protoreflect/desc/protoparse/parser.go
=> chore: remove refs to deprecated io/ioutil

.github/workflows/issue-auto-assign.yml
=> Add triage label to each new issue not by maintainer

.github/ISSUE_TEMPLATE/release.md
It includes some improvements to the release process with steps for opening the long-lived branches for docs and DefType.
=> Updates for the release process

release notes/v0.48.0.md
Update the next release notes with links to the PRs that have refactored `clearPermissions` and `grantPermissions`, as well as the fix for `clearPermissions`.
To update the release notes for the next release.
=> Add clear and grant permsissions tasks

release notes/v0.48.0.md
This adds some internal PR links to the next release notes.
To keep the release note up to date prior to the next release.
=> Add other internal changes to release notes

release notes/v0.48.0.md
- Internal fix
- Fix for `page.$`
Keep community up to date with changes.
=> Adding additional Browser changes

SECURITY.md
=> Update the PGP key

js/path_resolution_test.go
Highly recommended to go commit by commit as it makes the changes way more managable.
A bunch of refactors for some of the js path based tests.
Mostly to make them easier to understand and extend.
=> js: path based tests refactor

.github/ISSUE_TEMPLATE/release.md
Update the release issue with some info on where to bump definitely typed version
This wasn't obvious at all and was missed
=> Update the release issue with some info on definitely typed version

metrics/builtin.go, metrics/sample_test.go, metrics/sink.go, metrics/sink_test.go, metrics/system_tag_test.go, metrics/tags_test.go
=>  metrics: Fix lint issues 

output/json/json.go, output/statsd/config.go, output/statsd/helper_test.go
Fix lint issues in the output packages
Part of #769
=> output: fix linter errors

release notes/v0.50.0.md
Update release notes for https://github.com/grafana/xk6-browser/pull/1209.
=> Add browser 1209 to release notes

release notes/v0.50.0.md
Add details of xk6-browser#1238 to release notes
Keep users up to date on latest fixes.
https://github.com/grafana/xk6-browser/issues/1225
=> Add details of browser#1238 to release notes

release notes/v0.50.0.md
Add details of xk6-browser#1097 to release notes.
Keep users up to date of the latest API feature.
https://github.com/grafana/xk6-browser/issues/384
=> Add details of browser#1097 to release notes

examples/experimental/browser.js
Update and fix the example browser test.
The example browser test was out of date and was failing.
=> Update and fix the example browser test

js/modules/k6/experimental/tracing/encoding.go, js/modules/k6/grpc/listeners.go, js/modules/k6/grpc/teststate_test.go, metrics/thresholds_parser.go
=> chore: fix function names

cmd/tests/cmd_run_test.go, js/module_loading_test.go, js/path_resolution_test.go, js/runner_test.go
Extract additional tests from #3456 
Make the PR smaller and add tests now
=> Extract tests from esm

log/file.go
This PR ensures the log lines channel is drained after context cancellation.
As described in https://github.com/grafana/k6/issues/3843, as the lines channel used by `fileHook` is buffered, it is possible for items to remain in the channel after the context is cancelled, if we're unlucky with goroutine scheduling. If that were to happen, lines may remain in that channel and not be logged.
Closes https://github.com/grafana/k6/issues/3843
=> log/file: drain lines channel after context is cancelled

js/bundle.go, js/module_loading_test.go
Previously getting main module exports only worked if they were defined in the main module.
But if they were indirectly exported a null/nil will be acquired instead.
Why this isn't common, not supporting it is definetely a bug.
=> js: Support indirect exports for main module functions

lib/consts/consts.go
Bump the k6 version
Part of the release
=> Bump Version to v0.53.0

README.md
A cosmetic change to make the roadmap more visible.
Make roadmap visible
=> Add top level roadmap link

go.mod, go.sum, vendor/github.com/grafana/xk6-browser/browser/element_handle_mapping.go, vendor/github.com/grafana/xk6-browser/browser/frame_mapping.go, vendor/github.com/grafana/xk6-browser/browser/locator_mapping.go, vendor/github.com/grafana/xk6-browser/browser/page_mapping.go, vendor/github.com/grafana/xk6-browser/common/frame.go, vendor/github.com/grafana/xk6-browser/common/frame_session.go, vendor/github.com/grafana/xk6-browser/common/locator.go, vendor/github.com/grafana/xk6-browser/common/page.go, vendor/modules.txt
Contains a good fix that would benefit users.
Updates to k6-browser v1.7.1.
Contains a fix that would be very useful for our users/customers.
https://github.com/grafana/xk6-browser/issues/1224
=> Update to browser v1.7.1

.github/workflows/issue-auto-assign.yml
Don't auto-assign to me.
I will be on PTO for some time.
=> Removed codebien from autoassign

js/timeout_error.go
fixed typo.
coresponding -> corresponding
=> docs: update timeout_error.go

Dockerfile
This PR updates a dockerfile, by updating the golang to the version 1.23 (the latest available at the time of PR creation) and also updates to alpine 3.20, which is the current stable.
Keep dockerfile up to date
=> Dockerfile: update alpine and golang

lib/consts/consts.go
Bump the k6 version
Part of the release
=> Bump Version to v0.54.0

CONTRIBUTING.md
Correct the style-guide hyperlink in the Contribution readme file
Better navigation 
Closes #4012
=> Update style-guide hyperlink in Contribution.md

lib/consts/consts.go
=> Bump version to v0.55.1

.github/workflows/packager.yml
Fix k6packager with similar problem to https://github.com/grafana/k6/pull/3894 
Not certain it actually needs to be rebuild every Sunday, but there is a chance this is a problem around #4142
=> Fix k6packager workflow

release notes/v0.55.2.md
Cherry picked the `v0.55.2` release notes from `v0.55.x` branch.
=> Add release notes for v0.55.2

.github/ISSUE_TEMPLATE/release.md
Slightly improves the release notes template.
There were some repetitions, little typos, and outdated parts.
=> Improve release notes template

.github/dependabot.yml
Add more dependancies to dependabot
Automating getting PRs for dependancy updates
=> Add more dependancies to dependabot

go.mod, go.sum, vendor/modules.txt
Update taskqueue
Reduce needed changes in #4133 mostly
=> Update github.com/mstoykov/k6-taskqueue-lib v0.1.2 to v0.1.3

.github/workflows/issue-auto-assign.yml
Temporary change while i'm afk for a while.
=> Remove ankur22 from the issue assignee pool

internal/js/modules/k6/browser/browser/page_mapping.go
More fixes for browser mappings and removing some overzealous TODOs
While trying to fix some mappings that originally I recognized as places that races are possible, I found that is not the case.
As mappings are just a map that is methods/fields to their values, as long as no usage the runtime happens outside of any mapping it is fine.
This is the case for most cases, this fixes the one that isn't.
=> browser: fix some mappings and remove overzealous TODOs

internal/js/modules/k6/browser/browser/frame_mapping.go, internal/js/modules/k6/browser/browser/page_mapping.go, internal/js/modules/k6/browser/common/frame.go, internal/js/modules/k6/browser/common/page.go, internal/js/modules/k6/browser/tests/frame_test.go, internal/js/modules/k6/browser/tests/page_test.go
Continue https://github.com/grafana/k6/pull/4524
=> browser: Fix options races p2 

lib/consts/consts.go
=> Bump k6 version

go.mod
Move used deps in the right `go.mod` block.
Keep things clean
=> Tidy the indirect block

internal/build/version.go
Bump k6 version
We want to release a new version
=> Bump k6 version to v1.0.0-rc1

release notes/v0.58.0.md
It adds v0.58 release notes
The release notes itself explains why
=> Add release notes for v0.58 mirroring

.github/workflows/issue-auto-assign.yml
Add ankur22 into the issue assignee pool
=> Add ankur22 into the issue assignee pool

internal/js/modules/k6/webcrypto/tests/subtle_crypto_test.go
Fix exception not propagating from within WebCrypto tests
Originally one of the edits that was done to the test would mean that any exception would propagate and stop the whole execution.
This was later reverted in
https://github.com/grafana/xk6-webcrypto/commit/03d70232100cc657e1564a51039e049d1775421e After this change every exception would be eaten by this code and not propagate upwards.
Upstream(the tests) this was done so different runners have easier time running the tests.
And after reading testharness.js docs for a while it is obvious that you are meant to get the result in another way which is now being done in this PR.
This probably can be done better and we can similarly to tc39 tests record breaking ones instead of editing files, but this should be done in a separate patch. …
=> WebCrypto: fix its errors not propagating from the tests

go.mod, go.sum, vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc/version.go, vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/version.go, vendor/go.opentelemetry.io/otel/sdk/metric/internal/aggregate/exponential_histogram.go, vendor/go.opentelemetry.io/otel/sdk/metric/version.go, vendor/modules.txt
Bump the OpenTelemetry exporters and related.
=> Bump OTel exporters

internal/js/modules/k6/browser/common/keyboard.go
Fix race on map access in keyboard.
Races are bad.
=> Browser keyboard race

internal/cmd/options.go, internal/cmd/root.go, internal/cmd/run.go
=> cmd/root: Wrap with max 120 cols for help text

.github/actions/lint/action.yml, .github/workflows/browser_e2e.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/packager.yml, .github/workflows/tc39.yml, .github/workflows/test.yml, .github/workflows/trivy.yml, .github/workflows/wpt.yml, .github/workflows/xk6.yml
Fix [zizmor](https://woodruffw.github.io/zizmor) warnings 
Potential GHA security issues fixes - by the looks of it, it seems very unlikely. I even put hashes for github own actions in some cases or codeql - which likely are as trusted as possible, but still.
Most of the changes are pretty straightforward:
- replace templates within code with env variables where that comes from outside
- do not keep credentials after checkout
- disable cache when making release artificats
The major problem is permissions - by default the github token is way too powerful. But most actions do not document what they need, so it is quite hard to figure out if something is working or not. I tried my best to find what needs what using issues and the API documentation.
But I do expect I have not done it …
=> Update GHA to fix zizmor warnings

.github/workflows/build.yml
Added the required permission to push on ghcr.io
=> Add the required permission to write on ghcr.io

internal/build/version.go
Bump the version for rc2
We want to release a new release candidate for v1.0.0
=> Bump version to v1.0.0-rc2

release notes/v1.0.0-rc2.md
Release notes for k6 v1.0.0-rc2
=> Release notes for v1.0.0-rc2

release notes/v0.59.0.md
Release notes for the mirroring version v0.59.0
=> Release notes for v0.59.0

internal/js/modules/k6/browser/common/connection.go, internal/js/modules/k6/browser/common/execution_context.go, internal/js/modules/k6/browser/common/http.go
A collection of small k6/browser performance improvements - maybe bigger ones will follow
=> Browser optimizations

internal/build/version.go
=> Bump k6 version to v1.1.0

release notes/v1.1.0.md
=> Release notes for v1.1.0

internal/js/modules/k6/browser/browser/mapping_test.go, internal/js/modules/k6/browser/browser/page_mapping.go, internal/js/modules/k6/browser/common/frame.go, internal/js/modules/k6/browser/common/js/injected_script.js, internal/js/modules/k6/browser/common/locator_options.go, internal/js/modules/k6/browser/common/page.go, internal/js/modules/k6/browser/common/selectors.go, internal/js/modules/k6/browser/tests/get_by_test.go, internal/js/modules/k6/browser/tests/static/get_by_label.html
This adds a convenience method on `page` to be able to select on `label` elements or elements with the `aria-label` attribute.
This is part of the story of adding `getBy*`, which makes working with selectors a little easier. We used to have to work with the `page.locator` API providing either a `CSS` selector (when the `aria-label` attribute was used) or a `XPath` selector if we wanted to get the element by the `label`:
```html
<label for="password-input">Password</label>
<input id="password-input">
```
```js
// Not possible in CSS
const l = page.locator('//label[text()="Password"]'); // XPath
```
Now we can use:
```js
const l = page.getByLabel('Password');
```
Working with `getBy*` in general is an industry standard in the frontend testing world.
**Please do not merge this PR until the …
=> Add getByLabel in the browser module

internal/js/tc55/timers/timers_test.go
Sometimes the test will race and reset the context, before it has fully finished. This test makes certain that is not the case.
Races in tests fail CI. 
=> chore: Fix race in timers test due to context reset

internal/build/version.go
Bump the version
We need tothis before the release of 1.2.0
=> Bump the version to 1.2.0

.github/ISSUE_TEMPLATE/release.md
Updates the release issue template.
Try to make it better for the next user.
=> Updates release issue template after v1.2.0

release notes/v1.2.3.md
Adds release notes for v1.2.3
Inform users on what changed in v1.2.3
=> Release notes for v1.2.3

internal/build/version.go
Bump version for v1.2.3
Releasing a new version requires it
=> Bump v1.2.3

internal/js/eventloop/eventloop.go, internal/js/modules/k6/execution/execution.go, internal/js/modules/k6/experimental/websockets/params.go, internal/js/modules/k6/experimental/websockets/websockets.go, internal/js/modules/k6/grpc/client.go, internal/js/modules/k6/ws/ws.go, internal/js/summary.go, js/modules/k6/http/cookiejar.go, js/modules/k6/http/request.go
Continue #5074 to be actually not only in browser
Consistancy and not pushing this on the previous PR by mistake :facepalm: 
=> Use common.IsNullish more

internal/js/modules/k6/browser/tests/page_test.go
The hope is that this will prevent flakiness in CI.
=> Update timeout to nanosecond
