tutorials/getting-started.md
I am assuming `test` was the old function and `check` is the new one as the example didn't work for me.
=> Replace 'test' with 'check' in group example

lib/options.go, lib/options_test.go, run.go
Send a UDP datagram to k6reports.loadimpact.com:6565 whenever `k6 run` is invoked. Possible to disable this behaviour through a `--no-usage-report` flag.
(server side not implemented yet, but tcpdump always works...)
=> Very simple, UDP-based usage reports

web/app/routes/index.js
Updated web application to find root group by using `name` instead. Could be checking if `parent` relationship is empty instead. What do you think @uppfinnarn ?
=> [fix] find root group by name

README.md
- npm is usually lowercased
- npm comes bundled with node.js, so there's really no need to explicitly list it
- ember-cli is required to build k6
- both bower and ember-cli can be installed with one command
=> Add more detailed information on npm dependencies

CODE_OF_CONDUCT.md, CONTRIBUTING.md
We need contribution guidelines and a code of conduct before we start picking up any more contributors. I'll look into automatically enforcing these guidelines later - there are several bots that can do it.
(Ping @pnn in particular)
=> CONTRIBUTING.md and CODE_OF_CONDUCT.md

.gitignore, js/api_http.go, js/api_http_test.go, js/lib/k6/http.js, samples/http_batch.js
[WORK IN PROGRESS]
this implements #72. api is as described in the original issue:
```js
let responses = http.batch([
"http://test.com",
{
"method": "GET",
"url": "http://test.com?cool=1"
// optionally, body or params
}
])
```
the only problem that currently exists with this implementation is that the array of responses is jumbled, making is pretty difficult to `check()` single requests. i wanted to gather some opinions on how to best solve this here before attempting to do so myself, as i'm not quite sure how to go about this
=> Implement http.batch()

js/api_http_test.go, js/lib/k6/http.js
Automatically add `application/x-www-form-urlencoded` Content-Type header when user passed in JS object as data parameter.
This is basically a convenience patch to shorten this:
```js
http.post("http://httpbin.org/post", {field: "value"}, { headers: {"Content-Type": "application/x-www-form-urlencoded"} });
```
to
```js
http.post("http://httpbin.org/post", {field: "value"});
```
=> Add form-urlencode header when auto encoding body

js/api_http_test.go, js/lib/k6/http.js
Dependant on https://github.com/loadimpact/k6/pull/168.
Adds handling of lists/arrays being passed as Object properties in `data` parameter,  automatically encodes the list items as multiple entries with same key.
Given:
``` js
let form = {topping: ["cheese", "lettuce", "kebab", "tomatoes"]};
let r = http.post("http://httpbin.org/post", form);
console.log(r.json()["form"]["topping"]);
``` 
this patch will change the behavior of the automatic form urlencoding so that the contents of the `topping` field will be changed from:
`topping=cheese,lettuce,kebab,tomatoes` to `topping=cheese&topping=lettuce&topping=kebab&topping=tomatoes`
and the output of the above script will change from:
`"cheese, lettuce, kebab, tomatoes"` to `["cheese", "lettuce", "kebab", "tomatoes"]`
This to match how …
=> Handle lists/checkbox form input when form urlencoding

README.md
We need to update logo, animation, probably "Development setup" and think about overall structure of the README, but this PR at least includes prominent links to k6.io and docs.k6.io, plus includes some basic "getting started" info.
=> Intermediate README fix

stats/cloud/api.go, stats/cloud/api_test.go, stats/cloud/collector.go
Sample structs in the cloud collector have been made public so that they can be imported in other projects.
=> Made sample structs public in the cloud collector

run.go
Ref #243
The change modifies the check console output to:
I tried the suggested format but I find better the one above.
Please, let me know any suggestion or change.
=> Improve Checks console output

stats/sink.go
@liclac 
This commit changes the percentile output as `p(90), p(95)`:
The issue was discussed at #160
=> Make the console format of percentiles to be consistent with thresholds syntax

README.md
Since our current Slack invitation flow has been blocked by Slack (because of hitting an invite acceptance rate limit with very unclear answers on if/how/when it would be lifted) we have to use an alternative flow, using time limited shared invite links.
We've set up a page on k6.io/slack for managing the rotation of this invite link. This PR updates the README to point to that page instead of the current invite flow.
=> Update Slack links because of new invitation flow

js/modules/k6/crypto/crypto.go, js/modules/k6/crypto/crypto_test.go
=> Add HMAC support to Crypto module

stats/cloud/api.go
Status should start at 0 when streaming to cloud service.
=> [fix] status should start at 0

lib/netext/dialer.go
Data received and sent metrics were not collected for HTTP requests.
This is because the DialContext method required a non-pointer receiver,
which meant that the BytesRead and BytesWritten references were not
carried to the connection created from the Dialer.
=> Fix data received/sent metrics for HTTP

samples/grafana_dashboard_influxdb.json
First cut at a nice-lookin' dashboard.  Notes:
* All stats are grouped by a time interval of `>1s` to minimize noise due to extreme fluctuations.  [See discussion around this](https://k6io.slack.com/archives/C3EDLHPTR/p1494353407564315)
* Played around with different ways of viewing the same data (different percentiles, and also the "heatmap" feature) - Feedback welcome!
/cc @liclac @ragnarlonn
=> Add grafana dashboard for influxdb stats

samples/http_2.js
Hi @liclac
I created a branch, pushed upstream and then created a PR. 
I am getting ```proto``` from here: 
https://github.com/loadimpact/k6/blob/80c201125846f9954312e8f65cc40111b04c5fc4/js/modules/k6/http/http_test.go#L219
I tried ```r.h2``` and it failed
Apologies for being a retard!!!
=> HTTP/2 check on BBC Homepage

lib/models.go, run.go, stats/stats.go
Added a new command line parameter `report`: the file where the aggregated metrics are written to in JSON format.
Resolves #271
=> Aggregated metrics in JSON format

js/modules/index.go, js/modules/k6/encoding/encoding.go, js/modules/k6/encoding/encoding_test.go, samples/base64.js, samples/http_basic_auth.js
PR to add base64 encoding/decoding capabilities to k6 JS API. See included sample for full usage, simple sample:
```js
import { check } from "k6";
import encoding from "k6/encoding";
export default function() {
let str = "hello world";
let enc = "aGVsbG8gd29ybGQ=";
check(null, {
"is encoding correct": () => encoding.b64encode(str) === enc,
"is decoding correct": () => encoding.b64decode(enc) === str
});
}
```
HTTP Basic Auth example:
```js
import encoding from "k6/encoding";
import http from "k6/http";
import { check } from "k6";
export default function() {
let res = http.get("http://httpbin.org/basic-auth/user/passwd", { headers: { "Authorization": "Basic " + encoding.b64encode("user:passwd") }});
// Verify response
check(res, {
"status is 200": (r) => r.status === 200,
"is …
```
=> Add base64 JS API

js/modules/k6/crypto/crypto.go, js/modules/k6/crypto/crypto_test.go
Adds two base64 variants as possible output encodings of k6/crypto `hasher.digest(...)`. Use cases includes JSON Web Token (JWT), see: https://gist.github.com/robingustafsson/7dd6463d85efdddbb0e4bcd3ecc706e1
=> Add support for base64 URL and raw-URL output encoding to hashers

stats/cloud/collector.go, stats/cloud/config.go
Continue support for K6CLOUD_TOKEN and add a deprecation message
> K6CLOUD_TOKEN will be deprecated soon. Use K6_CLOUD_TOKEN instead.
closes #349
=> Support K6CLOUD_TOKEN with deprecation message

docker-compose.yml
With the new CLI we can obtain the version with `k6 version`.
`k6 --version` doesn't work
=> Update docker-compose with the new k6 version call

stats/cloud/client.go
Fix: anonymous users running the `cloud` collector will not send the `Authorization` header.
cc @martinfijal
=> Avoid `Authorization` header for anonymous users

build-release.sh
I have included instructions to generate a k6-$VERSION-checksums.txt file.
@ppcano, about the #392 issue, the CHECKSUM var should be now:
```
CHECKSUM=${BINARY}-${VERSION}-checksums.txt
```
=> Include release checksums file, fix go.rice install instructions

cmd/run.go
- Add info for system OS and ARCH.
- Add info for stages duration.
- Duration properties become float type on `seconds` instead of strings.
Pending
=> Extend usage report information

cmd/run.go
The progress bar was not working correctly when using the `duration` option.
The bug was introduced at 330b0a678a795595de7d59b8864dcf57339be6e2
=> Fix progress bar when using the option `duration`.

js/modules/k6/http/http_request.go, js/modules/k6/http/http_request_test.go
The Go stdlib handles gzip compressed response bodies automatically. This PR adds automatic decompression of deflate compressed response bodies as well, as specified in [RFC 1950](https://tools.ietf.org/html/rfc1950) (so might not be compatible with some older servers that don't follow the [HTTP/1.1 spec](https://tools.ietf.org/html/rfc2616#section-3.5) and instead send raw deflate data).
=> Handle deflate encoded response bodies

cmd/login_cloud.go, stats/cloud/api.go
Will close #367
`k6 login cloud` has three options:
-  `k6 login cloud -s`: show the stored token.
- `k6 login cloud -t YOUR_TOKEN`: set up the token.
- `k6 login cloud`:  ask for your Load Impact user email and password to automatically set up the token.
@liclac 
From a functional perspective, it looks ready.
Some possible next steps:
- hidden the password. Found this [post](https://stackoverflow.com/questions/2137357/getpasswd-functionality-in-go). Thoughts?
- replace the `login` request for a new endpoint request to avoid the error: `You have to create an API Token with your Load Impact account.`
=> `k6 login cloud` command

stats/sink.go
=> [Fix] Corrects calculation of t.Med in stats output

cmd/cloud.go
The fix allows sending the cloud test name when running `k6 cloud script.js`
```
export let options = {
vus: 50,
duration: "60s",
ext: {
loadimpact: {
name: "my new test name",
distribution: {
one: {
loadZone: "amazon:us:ashburn",
percent: 100
}
}
}
}
};
```
cc @robingustafsson
=> Fix cloud test `name`

js/modules/k6/http/http_request.go, js/modules/k6/http/http_request_test.go, js/runner.go
If PR #419 works for zlib encoded response with a "deflate" HTTP "Content-Encoding" header, I see anything about the "gzip" encoding ([www.gzip.org/zlib/zlib_faq.html#faq38](www.gzip.org/zlib/zlib_faq.html#faq38)).
My Apache HTTP Server 2.4 only deliver gzip content and when I use k6 (without this fix) to test some URLs, I've got binary data instead of JSON content.
=> Handle gzip encoded response bodies

js/modules/k6/http/response.go, js/modules/k6/http/response_test.go
@marklagendijk Here's a quick fix for handling GET form submissions, until we have https://github.com/loadimpact/k6/issues/436.
=> Fix handling of GET form submissions in submitForm()

stats/cloud/api.go, stats/cloud/api_test.go, stats/cloud/collector.go, stats/cloud/config.go
`K6_CLOUD_COMPRESS` enables gzip compression on metric push. 
Default false.
When compression becomes the default protocol, the setting should be changed.
=> Cloud: `K6_CLOUD_COMPRESS` enables gzip compression when pushing metrics

js/modules/k6/http/http_request.go, js/modules/k6/http/http_request_test.go, js/modules/k6/http/response.go
No related issue, missed this in the previous PR #446.
=> Expose TLS handshake timing to response

js/common/state.go, js/modules/k6/http/http_request.go, js/modules/k6/k6.go, js/modules/k6/k6_test.go, js/runner.go, js/runner_test.go, lib/metrics/metrics.go
Changes: 
- introduce new iteration_duration metric
- add "vu" and "iter" tags to the following metrics:
- http_reqs
- http_req_*
- checks
- data_send
- data_received
- group_duration
- iteration_duration
=> Add vu and iter tags to metrics

cmd/options.go, cmd/run.go, lib/options.go, ui/summary.go, ui/summary_test.go
Add CLI option to specify what stats to report for trend metrics to stdout summary
Closes #450 & #408
=> CLI option to specify what stats to report for trend metrics

stats/cloud/api.go, stats/cloud/collector.go, stats/cloud/config.go
Replace `K6_CLOUD_COMPRESS` with `K6_CLOUD_NO_COMPRESS` option.
=> Cloud: Default `gzip` compression when pushing metrics.

js/modules/k6/http/http_request.go
**1. Set response cookies using the correct response URL.**
req.URL: the url of the initial request.
res.Request.URL: the url of the request that gave the response, after all redirects. In other words: the response url.
Example:
- Request `https://domain1.com` which redirects to `https://domain2.com`
- Response of `https://domain2.com` sets cookie `myCookie`.
Before this fix `myCookie` would be set using url `https://domain1.com` instead of `https://domain2.com`
**2. Clear cookies on request before setting them in CheckRedirect**
When a redirect response contains new cookies (Set-Cookie) these are put in the cookieJar.
After this is done the cookies are set on the request using the jar.
The problem is that the request already contains the original cookies (without the new ones). This …
=> [Bugfix] Several bugfixes related to redirects and cookies

cmd/common.go, cmd/convert.go, cmd/convert_test.go
Changed the default behavior of the HAR->JS converter to output to stdout rather than a default file ("har-script.js").
Closes #471.
CC @ragnarlonn
=> Output HAR->JS conversion to stdout by default

cmd/cloud.go, stats/cloud/api.go, stats/cloud/config.go
Using in the script `projectID` or  environment variable `K6_CLOUD_PROJECT_ID`.
```
export let options = {
vus: 40,
duration: "10s",
ext: {
loadimpact: {
name: 'Test name',
projectID: 6
}
}
};
```
=> cloud: support project selection 

js/modules/k6/http/http.go, js/modules/k6/http/http_request.go, js/modules/k6/http/http_request_test.go, js/modules/k6/http/response.go
Fixes #440 
Adds HTTPRequest struct, includes the request as a field in the response, and finally a test for whether or not the request information is properly populated in a response.
cc: @robingustafsson @marklagendijk
=> Expose HTTP request information in response

cmd/convert_test.go, cmd/options.go, cmd/root.go, cmd/run.go, js/modules/k6/html/elements_gen_test.go, js/modules/k6/http/http.go, js/modules/k6/http/http_request.go, js/modules/k6/http/response_test.go, lib/options.go
Implements logging of HTTP requests and responses (#331).
- Initial requests are logged with `Request:`
- Redirect responses are loggged with `RedirectResponse:`
- Redirect requests (new requests based on a redirect response) are logged with `RedirectRequest:`
- Eventual responses are logged with `Response:`
Currently `fmt.Printf` is used, instead of `state.logger.Infof` because the logger escapes the message (especially newlines), which makes it unusable.
@robingustafsson do you agree with this approach?
ToDo:
- Write tests?
=> HTTP Debug Logging

stats/cloud/api.go
Minor refactor:
Cloud: request data property `status` becomes `result_status`
=> Cloud: request data property `status` becomes `result_status`

js/runner.go, js/runner_test.go, lib/netext/dialer.go, lib/options.go, lib/options_test.go
This PR closes #474. Adds the option to override DNS lookup with a specific array of IPs. 
Although I implemented the option of passing multiple IPs per domain, I'm not entirely sure if that is the best options for some reasons:
- If we consider @markingman needs, I think the option using environment variables that @robingustafsson gave it is a much better approach, once it makes easier to compare the results and there is no need to change the code to do that.
- Using multiples IPs per domain implies in required use of *noConnectionReuse*. Otherwise, the IP will be selected only in the first iteration of each VU.
- Using only one IP, we match the user experience of /etc/hosts.
- If one need to test multiple servers at once, it will probably put all those servers behind a load balancer …
=> Overriding DNS

cmd/convert.go, converter/har/converter.go
Produces simpler code using `http.<method>` calls instead of batch (concurrent calls). This will in turn make two converted recordings easier to diff.
We have more changes coming to this so the code is not very pretty at the moment. But we would like to keep it like this until we have merged in our other stuff and then do a code cleanup.
=> Add --no-batch option to HAR convert

cmd/convert.go, cmd/convert_test.go, converter/har/converter.go
Detect redirects in recordings and follow the redirects at runtime instead of following a hard-coded redirect. Also fix a bug with GET requests (http.get() does not take a body parameter)
=> har converter: Correlate variables in recordings (just redirects for now)

stats/sink.go, stats/sink_test.go
Changes percentile calculation to use linear interpolation of two bounding values if percentile doesn't precisely fall on a value index. Also, fixes issue where calls to `TrendSink.P()` and `TrendSink.Format()` could return wrong results if `TrendSink.Calc()` hadn't been previously called.
Closes #465.
=> Fix TrendSink stats and add tests for all sink types

cmd/archive.go, cmd/cloud.go, cmd/inspect.go, cmd/run.go, cmd/runtime_options.go, cmd/runtime_options_test.go, converter/har/converter_test.go, gometalinter.json, js/bundle.go, js/bundle_test.go, js/console_test.go, js/initcontext_test.go, js/runner.go, js/runner_test.go, lib/archive.go, lib/archive_test.go, lib/runtime_options.go
This closes #467. I wrote a comment in the issue with some information from a discussion with @robingustafsson about the implementation details, since my initial attempts at writing this hit a bit of a snag.
This should be mostly finished now, it should be mostly ready for code review. The [documentation](https://docs.k6.io/docs/environment-variables) is not yet done, though I think that's outside of the git repo. There are also a few remaining things that I'm not sure how to address:
- Should the `inspect` command [also accept](https://github.com/na--/k6/blob/31d0055857ad4524a017e1d9515f3966571137d6/cmd/inspect.go#L66) CLI environment variables? I'm leaning towards "yes", since with the old code system environment variables could …
=> Add CLI flags to set environment variables

js/runner_test.go, lib/netext/tracer_test.go, stats/cloud/api.go, stats/cloud/collector.go
Decrease `pushMetrics` payload by grouping http metrics and iteration metrics like:
```
{"type":"Points", 
"data": {
"time":"2017-12-05T11:58:30.906235601+01:00", 
"value": null, 
"tags":{"group":"", "method":"GET","name":"http://test.loadimpact.com","status":"200","url":"http://test.loadimpact.com"}},  
"values":{   "http_req_duration": 4.865751,
"http_req_blocked": 4.865751,
"http_req_connecting": 4.865751,
"http_req_sending": 4.865751,
"http_req_waiting": 4.865751,
"http_req_receiving": 4.865751,
"http_reqs": 1
} 
},
,"metric":"http_req_li_all"
}
```
```
{"type":"Points", 
"data": {
"time":"2017-12-05T11:58:30.906235601+01:00", 
"value": null, 
"tags":{"group":"",   "method":"GET","name":"http://test.loadimpact.com","status":"200","url":"http://test.loadimpact.com"}  
"values":{ …
```
=> Cloud: decrease payload when pushing metrics

cmd/cloud.go, stats/cloud/api.go
Implements:
- a progress bar
- aborting cloud test (via CTRL+C)
- return a CLI error if the test result has failed
WIP - The PR is pending for the backend to be ready.
=> Cloud: support progress bar & aborting cloud test

stats/cloud/collector.go
ref #375
This PR solves this issue:
```
docker run --rm -i loadimpact/k6:latest run -o cloud -<script.js
/\      |‾‾|  /‾‾/  /‾/
/\  /  \     |  |_/  /  / /
/  \/    \    |      |  /  ‾‾\
/          \   |  |‾\  \ | (_) |
/ __________ \  |__|  \__\ \___/ .io
time="2018-02-20T20:24:01Z" level=error msg="Unknown Error: {\n  \"error\": {\n    \"code\": 0, \n    \"details\": {\n      \"name\": [\n        \"Shorter than minimum length 2.\"\n      ]\n    }, \n    \"message\": \"Validation error\"\n  }\n}\n"
```
With STDIN mode the filename is "-", not "" (empty) (see https://github.com/loadimpact/k6/blob/master/cmd/run.go#L87)
and "-" length is shorter than 2, the minimum length for the test name.
=> fix default test name from stdin

Dockerfile
Changes required to have easy configuration of k6 in CI, particularly in gitlab.
Why:
1) gitlab require to have `script` section in yml. https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image
2) then "The Runner sends the script to the container's shell STDIN and receives the output.". shell STDIN is key message here
3) in k6 docker image there is from scratch section -> means that container is empty except k6 in it. No shell no nothing. So nothing to be used in gitlab script
=> Updated Dockerfile - included alpine image

stats/cloud/collector.go
Fix `cloud` collector when returning `iteration_duration` metric
=> Fix `cloud` collector when returning `iteration_duration` metric

stats/cloud/client.go
The current error message depends on the raw unexpected server output and can contain all sorts of unprintable characters while giving no actual information on the HTTP error.
=> Fix the error message for unexpected server responses

.circleci/config.yml
From my local tests, this should be able to catch if we've forgotten to vendor something, but I'll test again it for real when it's merged into master.
=> Add a simple CI check for non vendored dependencies

api/v1/group_routes_test.go, cmd/run.go, core/engine_test.go, core/local/local.go, core/local/local_test.go, js/bundle.go, js/bundle_test.go, js/runner.go, js/runner_test.go, lib/executor.go, lib/runner.go, release notes/upcoming.md
```js
export function setup() {
return {v: 1};
}
export default function(data) {
console.log(JSON.stringify(data));
}
export function teardown(data) {
if (data.v != 1) {
throw new Error("incorrect data: " + JSON.stringify(data));
}
}
```
Both `setup()` and `teardown()` are ran in full VU contexts, and can thus do things like network requests just like you can in `default()`.
Pass `k6 run --no-setup --no-teardown ...` to skip running them; for clustered execution, etc.
Closes #194
=> Setup & Teardown

cmd/options.go, cmd/options_test.go, core/engine.go, core/engine_test.go, lib/options.go, lib/options_test.go, stats/dummy/collector.go, stats/dummy/collector_test.go
Closes #461 
I changed the option name to `--run-tags` to keep consistent with the new `--system-tags` option. `--tags` looked to general.
=> Adding run tags option, apply default tags to all samples per run

stats/dummy/collector.go, stats/dummy/collector_test.go
This should fix https://github.com/loadimpact/k6/issues/469 and simplify https://github.com/loadimpact/k6/pull/553
I investigated the `lib.Collector` interface and its various implementations and I think that the current assumption in the dummy stat collector that `Collect()` should only be called after `Run()` is wrong. The purpose of `Run()` is to periodically, in batches, send the collected samples to some upstream collector. It would be concurrently run with all of the calls to `Collect()` (which themselves should only be sequential), but I don't see a reason why it must be started before `Collect()` is ever called.
Also, the current synchronization in the dummy collector actually prevented something important from being tested. `Collect()` should never be called concurrently, and …
=> Simplify the dummy collector

js/runner.go, js/runner_test.go, release notes/upcoming.md
=> Better error message when using the open function outside init code

loader/loader.go, loader/loader_test.go
Closes #528 
I added some checks for URL parsing and valid hostnames but I guess this would work without those. Let me know if we want to remove them.
=> Better error message when script/module can't be found

release notes/upcoming.md
The release notes were forgotten for https://github.com/loadimpact/k6/pull/565 by @antekresic and https://github.com/loadimpact/k6/pull/555
=> Add missed updates to upcoming.md

cmd/options.go, core/engine.go, core/engine_test.go, core/local/local.go, js/modules/k6/http/http_request.go, js/modules/k6/http/http_request_test.go, js/modules/k6/k6.go, js/modules/k6/k6_test.go, js/modules/k6/metrics/metrics.go, js/modules/k6/metrics/metrics_test.go, js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go, js/runner.go, js/runner_test.go, lib/netext/tracer.go, lib/netext/tracer_test.go, lib/options.go, lib/options_test.go, lib/testutils/httpmultibin.go, stats/cloud/api.go, stats/cloud/collector.go, stats/influxdb/collector.go, stats/json/wrapper.go, stats/stats.go, stats/stats_test.go
This optimizes how sample tags are created, stored and compared in preparation for the cloud output aggregation functionality. There also are some fixes to the per-run tags and system tags and a much more comprehensive test for per-run tags as well.
=> Refactor sample tags and per-run tags

cmd/collectors.go, cmd/login_influxdb.go, samples/config.json, stats/influxdb/collector.go, stats/influxdb/config.go, stats/influxdb/config_test.go
This implements:
https://github.com/loadimpact/k6/issues/569
The code can be optimised so that we don't create a new map each time in `func extractFields` but I would like some input on  how to do that.
To configure this see samples/config.json or you can use the env var INFLUXDB_TAGS_AS_FIELDS. Default value is "iter,vu,url".
=> Influxdb tags as fields

stats/cloud/api.go, stats/cloud/api_test.go, stats/cloud/collector.go
This fixes https://github.com/loadimpact/k6/issues/513
@ppcano, @Griatch: please review and merge whenever you want. This is a relatively self-contained change, so I think it can wait as an open pull request until you want it and are ready for it in the backend.
=> Encode times as microsececond UNIX timestamps in cloud collector

cmd/options.go, core/local/local.go, lib/options.go, release notes/upcoming.md
This fixes https://github.com/loadimpact/k6/issues/576, though we should add some upper limits when implementing https://github.com/loadimpact/k6/issues/539
=> Add configurable setup and teardown timeouts

js/modules/k6/html/html.go, js/modules/k6/html/html_test.go, release notes/upcoming.md
Fixes #549 by passing the correct element to the function
=> Fixing Selection.each function

core/engine.go, core/engine_test.go, release notes/upcoming.md, stats/stats.go, stats/stats_test.go
Fixes #590 by validating that sub metric tags are included in the sample tags.
=> Fixing tagging on submetrics

lib/options.go, lib/options_test.go, release notes/upcoming.md
this PR validates the stages option, making sure only valid stages are being passed down to the test.
fixes #547
=> Validating stages option

lib/options.go, lib/options_test.go
Stages don’t require a target value, only duration
While documenting all the options, I realize that target is not a required value for a stage. If not set it will just keep running with the current value
=> Fixing stages validation

js/modules/k6/http/http_request.go, js/modules/k6/http/http_request_test.go, js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go, lib/netext/tracer_test.go, lib/options.go, release notes/upcoming.md
This fixes #509
I decided to create this PR branch from the `cloud-aggregation` one instead of `master because this way I wouldn't have to resolve the many merge conflicts between those two. Only the [last commit](https://github.com/loadimpact/k6/pull/616/commits/a8a01e5d1b6640660323cf7a0d4599081317ae73) here is important, the rest are from the aggregation changes and should hopefully be hidden by github's diff when we merge https://github.com/loadimpact/k6/pull/600
=> Remote IP address as a new optional system metric tag 

cmd/cloud.go
Adds a `exit-on-running` option that allows k6 to exit right after the test starts running on the cloud.
closes #583
=> Adding exit-on-running option

stats/kafka/collector.go
Fixing broken master by adding the missing method of the `lib.Collector`
=> Adding SetRunStatus to kafka collector

lib/netext/tracer.go, lib/netext/tracer_test.go, release notes/upcoming.md
When an error happened on the connection write in a TLS connection, k6 was reporting negative `http_req_sending` values in the summary, this PR fixes this problem.
fixes #588
=> Fixing negative http_req_sending values

CONTRIBUTING.md
Update guidelines to state that a CLA signature is needed for contributions.
=> Update contributing guidelines with CLA information

cmd/options.go, core/engine_test.go, js/runner.go, lib/options.go, lib/options_test.go, release notes/upcoming.md
This PR adds a new option `--no-vu-connection-reuse` that closes the idle connections between each iteration of a VU, and changes meaning of `--no-connection-reuse` to disabling keep-alive connections
=> Adding no-vu-connection-reuse option

api/server.go, api/server_test.go, cmd/cloud.go, cmd/config_test.go, cmd/convert_test.go, cmd/login_cloud.go, cmd/root.go, cmd/run.go, cmd/runtime_options_test.go, converter/har/converter.go, core/local/local_test.go, js/initcontext_test.go, js/modules/k6/http/http_request_test.go, js/runner_test.go, loader/loader_test.go, stats/cloud/api_test.go, stats/cloud/collector_test.go, ui/form.go, ui/summary.go
It seems like `errcheck` won't ignore unchecked `fmt.Fprint*()` calls anymore, this should fix all of the issues we had in k6.
=> errcheck fixes

cmd/convert.go, cmd/convert_test.go, cmd/testdata/example.js, converter/har/converter.go, lib/options.go, release notes/upcoming.md
This adds a new `--options` flag for injecting options in the HAR converter output script (and closes https://github.com/loadimpact/k6/issues/690). It also adds new `--min-sleep` and `--max-sleep` flags that determine the minimum and maximum sleep times at the end of the iteration in the output script.
=> Add HAR converter options

js/runner.go, js/runner_test.go, lib/options.go
Fixes: [613](https://github.com/loadimpact/k6/issues/613)
The options sent from cli flags will also be saved as environment variables .
So they can be easily accessed as __ENV.XXXX
eg:
**Running**
`./k6 run  --vus 1 --iterations 1  --blacklist-ip 192.168.1.2/8,192.178.12.1/16 --duration 1s --summary-trend-stats "avg,p(95)" --system-tags check,group --tag test=p,l=0 --stage 5s:10,5m:20,10s:5  /media/sf_MCMP/Code/src/github.com/loadimpact/k6/test.js
`
**test.js**
```
export default function() {
console.log("---START---")
console.log("VUS" + __ENV.vus)
console.log("duration" + __ENV.duration)
console.log("stages" + __ENV.stages)
console.log("throw" + __ENV.throw)
console.log("systemTags" + __ENV.systemTags)
console.log("blackListIPS" + __ENV.blacklistIPs)
console.log("tags" + __ENV.tags) …
```
=> Options will be passed as ENV_variables from command line

cmd/root.go, release notes/upcoming.md
As noted in https://github.com/loadimpact/k6/issues/711, for some reason Go's standard library sometimes logs errors and warnings instead of returning them... But since we exclusively use [`github.com/sirupsen/logrus`](https://github.com/sirupsen/logrus) for logging in k6, those messages looked very different and didn't obey the `--logformat` configuration...
While fixing this, I noticed the (probably copy-paste) error `stdout.Writer = colorable.NewNonColorable(os.Stderr)` and fixed that as well :sweat_smile:
=> Fix a bug with --no-color and wrap Go's std logger with logrus

release notes/upcoming.md, stats/json/collector.go
This fixes https://github.com/loadimpact/k6/issues/714... `errcheck` [for the win](https://github.com/loadimpact/k6/pull/692), this has probably been silently buggy for a long long time...
=> Prevent the JSON collector from closing stdout

cmd/convert_test.go, cmd/options.go, cmd/run.go, cmd/testdata/example.js, converter/har/converter.go, js/bundle.go, js/runner.go, js/runner_test.go, lib/options.go, release notes/upcoming.md
After merging https://github.com/loadimpact/k6/pull/681, I realized that my advice to @mohanprasaths there to use something like `rt.Set("options", runner.GetOptions())` probably wasn't the best idea... The main reason for that was very similar to the reason I recently had to do [this hack](https://github.com/loadimpact/k6/pull/694/files#diff-2a3d79a0a11711742c3804c5e3846597R373) in for the options injection in the HAR file conversion. Basically, directly exporting the null-able types in `lib.Options` to JSON produces a lot of `null` and empty array/object values. Another slight drawback is that if a user adds their own non-k6 keys in the `options` object, they would have been overwritten and lost.
This PR adds a new method to `lib.Options` that allows us to flexibly traverse the …
=> Improve options exporting in HAR conversion and to JS runtime

core/engine_test.go, core/local/local.go, core/local/local_test.go, js/modules/k6/http/http_request.go, js/modules/k6/k6.go, js/modules/k6/metrics/metrics.go, js/modules/k6/ws/ws.go, js/runner.go, lib/netext/dialer.go, release notes/upcoming.md, stats/stats.go
The fix is not to emit metric samples when a VU's context is canceled. This should fix https://github.com/loadimpact/k6/issues/708, but it still needs unit tests and more checks in general. For example, are there some metrics we actually want to emit even from VUs that are canceled?
=> Fix zero-filled and wrongly emitted metrics

js/bundle.go, js/runner_test.go
This should fix the panic from and close https://github.com/loadimpact/k6/issues/720
=> Fix the creation of an options map in the runtime when setting options

cmd/options.go
This makes it RFC-compliant and fixes https://github.com/loadimpact/k6/issues/727
=> Remove the trailing semicolon in the default user-agent value

cmd/options.go, js/runner.go, js/runner_test.go, lib/options.go, lib/options_test.go, release notes/upcoming.md
=> Adding no cookies reset option

Gopkg.lock, cmd/archive.go, cmd/cloud.go, cmd/config.go, cmd/login_cloud.go, cmd/login_influxdb.go, cmd/run.go, release notes/upcoming.md, ui/form.go, ui/form_fields.go
This should fix #640 and #695 and also fix a another newly found bug where `k6 login influxdb` failed because we forgot to use `types.NullDecoder` for the mapstructure library.
I'm now also more convinced than ever that we need to wholly redesign/refactor/rewrite how we deal with configuration. The current way is super easy to mess up due to human error and it's just plain annoying to work with.
=> Config fixes

stats/cloud/collector.go, stats/cloud/config.go, stats/cloud/data.go, stats/cloud/data_test.go
Now buckets with fewer HTTP samples can also be aggregated, with outlier detection using the original sorting method, but with interpolation for improved accuracy. This is a more resource-intensive process, so for larger sample sizes quickselect is still the preferred algorithm.
There's also a new `AggregationSkipOutlierDetection` option that disables outlier detection altogether. It is disabled by default and is intended mostly for testing purposes.
And finally, the in-code documentation about the aggregation algorithm and options is expanded, which should help with https://github.com/loadimpact/k6/issues/628 and https://github.com/loadimpact/k6/issues/743
=> Improve cloud aggregation docs and support for smaller batches

.circleci/config.yml, lib/options.go, lib/options_test.go, release notes/upcoming.md
The bug also caused the stages set by the CLI flag to be doubled, since the options from CLI flags are used both for their default values and as the most important user-supplied options, so this PR fixes https://github.com/loadimpact/k6/issues/758 as well
=> Fix a bug that causes stages to be appended instead of overwritten

converter/har/converter.go, release notes/upcoming.md
Edit: the root cause of reaching the state with 0 `entries` was simply using something invalid with the `--only` flag in `k6 convert` like the URL instead of the domain name
=> Fix a panic in HAR conversion due to missing length check

ui/summary.go
As reported in #789 , when running an empty test, the rate for `data_received`, `data_sent` and `iterations` are unexpectedly huge. It happens when the execution time `t` is `0`.
This change fixes that by setting the rate to 0 when t is 0, which is reasonable.
=> Show reasonable rate when t is 0

js/runner.go, stats/cloud/collector.go
Previously in #710 I fixed a bug in k6 so that some metrics aren't emitted when an iteration is canceled, a bug that was introduced by the [real-time metrics](https://github.com/loadimpact/k6/pull/678) refactoring (which was itself needed for the in-k6 data aggregation). In the case of the metrics emitted at the end of an iteration, I made it so that the `data_sent` and `data_received` metrics are always emitted, but the `iteration_duration` metric [would only be emitted for complete iterations](https://github.com/loadimpact/k6/pull/710/files#diff-d604a8ac10b2cdb24a6f77aa17608b8aR109).
The trouble comes from the fact that I forgot that we [bundle iteration metrics in a `iter_li_all` metric](https://github.com/loadimpact/k6/blob/c665a73e561bcef243b40207640d8099d392f488/stats/cloud/collector …
=> Do not send interrupted iteartions' duration to the cloud ingest API

cmd/options.go, cmd/run.go, release notes/upcoming.md
Combined with mentions in the readme, docs and CLI help this should be enough to prevent confusion, so we can close https://github.com/loadimpact/k6/issues/663
=> Add a hint when MaxVUs is more than the total number of iterations

js/modules/k6/html/element.go, js/modules/k6/html/html.go, js/modules/k6/http/http_request.go, js/modules/k6/http/response.go, js/modules/k6/marshalling_test.go, js/modules/k6/ws/ws.go, lib/netext/tls.go
When goja bridges go objects it makes all Public fields to be case snake
as is the js standard. But because of lack of json tags when we marshall
and then unmarshall them due to them being returned by setup, the names
were becoming the go struct ones.
This was obviosly confusing and not intentional so now all objects that
are bridged by goja have json tags added to them to fix it.
=> Equalize k6 js objects' fields names returned by setup

js/bundle.go, js/bundle_test.go, js/initcontext.go, js/runner.go, js/runner_test.go, lib/archive.go, lib/archive_test.go
Before this commit running an archive meant that all the files will be
loaded and cached before execution. This also included precompiling all
the javascript files without actually running any of them.
This in itself wasn't a problem the problem came from anonymazation of
usernames in directories. This when the paths are absolute meant that we
had to change the script as well in order for them to match - we both
didn't do it and it wouldn't have worked in all cases as they could be
made concatinating strings for example.
The solution - either remove anonymization or anonymize everything
coming trough open. The second solution was choosen for now.
This commit also makes it so that we have an afero.Fs when running from
archive that is populated with all the files from the archive with their …
=> Retouching how files are handled when running from archive fixes #819

js/initcontext.go, release notes/upcoming.md
Previously scripts would've been ran for each time they were imported
this is both slower and not how it works in most(all?) interpreters
so we are changing the behavious to be more compliant.
=> Run imported scripts only once

cmd/cloud.go
This change basically makes certain that the whole
options->ext->loadimpact gets combined from all configs and than gets
send to validation and also setted in archive that will be uploaded to
the cloud.
=> Fix not sending ProjectID from env to options validations

cmd/options.go, core/engine_test.go, js/runner.go, js/runner_test.go, lib/options.go, release notes/upcoming.md
This should fix https://github.com/loadimpact/k6/issues/818, though I didn't have time to test it very much...
=> Add a minIterationDuration option

cmd/cloud.go
After the fixes in c6c928a k6 basically unmarshalled the whole
options.ext.loadimpact in cloud.Config merged it with all other settings
and marshalled it back.
This would've worked perfectly if cloud.Config had everything the
options.ext.loadimpact could have as a field. But it doesn't and this is
by design, which leads to this fields disappearing.
The whole idea of options.ext is that it's something that will be parsed outside
k6 and will - k6 just copies it around.
But for three fields there is an exception k6 actually wants to merge
configs for projectID, token and name of the script. This obviosly has to be
refactored in the future to be outside the options.ext.loadimpact, but
currently this will be too big of change.
The new fix is that we will unmarshall in map[string]interface{} so …
=> k6 cloud: Correctly merge options.ext.loadimpact see c6c928a

cmd/run.go, lib/timeout_error.go, release notes/upcoming.md
There are now 4 new non zero exit codes that will be revisioned at later
date when we more exit codes arise.
The 4 new ones are for each of setup and teardown timeouts, if it is a
timeout in the engine but it is not in setup/teardown - no such is known
at this time and 1 for engine error which is not timeout.
=> Exit with non zero code when setup/teardown timeouts fix #868

js/modules/k6/crypto/crypto.go, js/modules/k6/crypto/crypto_test.go
Adds method `randomBytes` to `k6/crypto`. The method takes a single parameter `size` specifying byte count and returns an array of random bytes. Bytes are represented as number literals.
Toward #900.
=> Add crypto.randomBytes

.golangci.yml
currently most checks are enabled but we are only fixing error going
forward and all current problems will stay and will be fixed as we
refactor the code around them.
=> Add config for golangci

cmd/run.go
As the help summary implies:  
```
-q, --quiet              disable progress updates
```
The --quiet flag should not prevent summary stats to be displayed
=> --quiet should allow the display of summary stats

js/modules/k6/crypto/crypto.go, js/modules/k6/crypto/crypto_test.go
this commit also add crypto.hexEncode which given byte array something
that looks like it will return a string with the value of the array in
hex
=> Add binary outputEncoding to the crypto functions

.editorconfig
Configures editor to trim trailing whitespace in Golang code.
Uses the approach suggested in #924 of removing the Golang setting to fall through to the global setting.
=> Configure editor to trim whitespace

js/initcontext.go, js/module_loading_test.go
Previously scripts would've been ran for each time they were imported
this is both slower and not how it works in most(all?) interpreters
so we are changing the behavious to be more compliant.
Just like in c3d3fa5cff4b60e4839298643052bb3e77f1f15e , but now we clear
the cached exports when we copy the programs when making new VUs.
This is needed because otherwise:
1. We share exports between VUs so there are race conditions
2. The exports from the initial compilation without context are used
(when not running from archive) and this leads to not being able to call
functions that need context inside imported scripts.
Closes #659 and fixes #969
=> Run imports once per VU

cmd/options.go, js/runner_test.go, lib/netext/dialer.go, lib/options.go, lib/options_test.go
Net.IPNet does not support JSON unmarshalling, causing the blacklistIPs
configuration to fail when set through JS.
Fixed by wrapping net.IPNet for the purpose of JSON unmarshalling.
Fixes #973
=> Fix blacklistIPs JS configuration

js/lib/lib.go, release notes/upcoming.md
This PR caches the [`*goja.Program`](https://godoc.org/github.com/dop251/goja#Program) result from parsing the core-js library so we can reuse it across VUs. Thanks to [@matlockx for suggesting this](https://github.com/loadimpact/k6/issues/1036#issuecomment-497720581), despite my attempts to misunderstand it :blush: 
Brief performance comparisons on my laptop between this code and k6 v0.24.0 show an over **2x reduction of VU memory usage and initialization times** when running the 2000 VU/empty script test from the [StackOverflow question](https://stackoverflow.com/questions/56389653/k6-memory-consumption-per-vu/56395832) that started this whole investigation!
=> Reuse the parsed core-js library across VUs

js/bundle.go, js/runner_test.go
This was a regression introduced with 3506ee1. The core issue lies with
a difference in how we run archive files and not archived scripts.
If the script is not archived we run it once in order to gather all the
files that will be required and to calculate the options among other
things. This is not required for archives as it was done when the
archive was created, so this step was skipped and the fist time the
files were executed was when a VU was created. This should've lead to
executing and loading each file for each VU previously as well if not
for the fact that all the code is in map. That map is first generated in
the original `bundle` of source codes and than copied to a new bundle
when a VU is created. Or more accurately it is now copied, previously
just a reference to the map was …
=> Don't compile and transform all scripts for each VU if archive

js/modules/k6/http/request_test.go, lib/netext/httpext/request.go, lib/netext/httpext/tracer.go, lib/netext/httpext/transport.go, lib/testutils/httpmultibin.go
This should fix https://github.com/loadimpact/k6/issues/1041, fix https://github.com/loadimpact/k6/issues/1044, fix https://github.com/loadimpact/k6/issues/925, and also fix a potential minor data race in the `httpext.Tracer`! Hopefully, without introducing new bugs or performance regressions...
While investigating this, I realized that we should up the priority of fixing the HTTP digest authentication: https://github.com/loadimpact/k6/issues/800
=> Fix a bunch of HTTP measurement and handling issues

cmd/archive.go, cmd/cloud.go, cmd/collectors.go, cmd/config.go, cmd/config_consolidation_test.go, cmd/login_cloud.go, cmd/options.go, cmd/root.go, cmd/run.go, cmd/version.go, js/bundle.go, js/bundle_test.go, lib/archive.go, lib/consts/consts.go
This includes two minor improvements + refactoring and a bugfix:
- Include the k6 version in the tar archives' metadata.json 
- Do not include the derived execution options in tar archives
Also, since those options were included by k6 v0.24.0, only emit a warning instead of an error if the derived execution options match any `execution` options that are "specified" by the user, since at that level we can't distinguish if we're executing an archive or a script...
-  Allow simultaneous use of `duration` and `iterations` execution shortcuts
This would just produce a shared-iterations scheduler with the specified number of iterations and a `maxDuration` equal to the passed `duration`, similar to how it works in the current k6 execution. This should fix #1058.
=> Fix the execution derivation bug and work around the k6 0.24.0 wrong tar metadata

cmd/config.go, cmd/config_consolidation_test.go
Full description of the issue and rationale for the change can be found here: https://github.com/loadimpact/k6/pull/1007#issuecomment-509586983
=> Disable the execution mismatch check, but keep the other warnings

cmd/runtime_options.go, cmd/runtime_options_test.go
This should close https://github.com/loadimpact/k6/issues/1006
=> Fix handling of commas in environment variable values

lib/consts/consts.go, release notes/upcoming.md, release notes/v0.25.0.md
https://github.com/loadimpact/k6/pull/1059 has to be merged (preferably via squashing) before we merge this and tag the new version.
=> Release k6 v0.25.0

.circleci/config.yml, README.md, appveyor.yml, lib/consts/consts.go, release notes/v0.25.0.md
This commit contains a few different things:
- Add `--fail` to all curl calls, so CI runs will fail when we don't receive a 200 response from some remote system.
- Switch the homebrew installation instructions to use the [new formula from `homebrew-core`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/k6.rb) (still have to figure out how to update the formula in homebrew-code, but this closes https://github.com/loadimpact/k6/issues/380 - I forgot to do it earlier).
- Stop pointing to the `latest` .msi package on BinTray - it's stuck on v0.24.0 and we can't update it to v0.25.0 or delete it, since apparently BinTray doesn't allow us to modify or delete "versions" that are older than a year... :|
- Remove a wrong line from the `v0.25.0` release notes, referencing a pull …
=> Fix a bunch of minor release issues

js/modules/k6/http/request_test.go, lib/netext/httpext/request.go, lib/netext/httpext/request_test.go, release notes/upcoming.md
This is needed for correct handling of redirects of requests with bodies
and in http2 when the server sends GoAway without an error.
Unfortunately testing the GoAway case turned out to be problematic so it
is left for the future.
Fixes #1091
=> fix: use http.Request's GetBody

js/module_loading_test.go, lib/archive.go, lib/archive_test.go
This was always done when running a script, but for archives it was
deemed not needed as if it wasn't needed during the making of the
archive it shouldn't be needed during it's running. The problem arises
when a `require` is in a try block in order (to check if something is
support for example). In that case if it isn't loaded (for example a
nodejs module will not be loaded but will be resolved to an `https` url)
it will not be cached.
So if someone tries to run an archive from such a
script and there were no https imports k6 will panic at runtime.
=> fix: Always initialize filesystems for all schemes always

js/modules/k6/http/request_test.go, lib/netext/httpext/digest_transport.go, lib/netext/httpext/error_codes.go, lib/netext/httpext/httpdebug_transport.go, lib/netext/httpext/request.go, lib/netext/httpext/response.go, lib/netext/httpext/transport.go
Previously, there was an uncaught error (sometimes leading to panics) in the automatic response body decompression. This patch handles these decompression errors and even assigns a custom error code for them. As a bonus, k6 now also properly handles errors due to improper redirects, or too many redirects, and tags the resulting metric samples accordingly.
By necessity, I had to also move the digest authentication handling to its own `http.RoundTripper` layer. This by no means solves the issues of https://github.com/loadimpact/k6/issues/800, but it hopefully slightly improves the situation. A proper authentication cache and likely a different library still have to be used there eventually...
=> Fix response error handling and slightly improve the digest auth code

cmd/testdata/example.js, converter/har/converter.go, js/modules/k6/http/request_test.go, lib/netext/httpext/request.go
This would restore the behavior pre-#989, so that any content-length header values manually specified by users would be overwritten by k6. Only, this time it won't be done silently, a warning would be shown every time there was a mismatch.
The HAR converter is also modified to not include the content-length header in the generated sources. While that header isn't going to be a problem if its values matches the actual body content length, some HAR files are broken and include the header without any body data, and other times users may modify the body but forget the header. So, since k6 would automatically send it, we shouldn't include it in the script.
This will close https://github.com/loadimpact/k6/issues/1094
=> Always set the correct content-length for requests

cmd/config.go, cmd/config_consolidation_test.go, cmd/options.go
CLI options have the highest priority, so the cli options which have a
default value will always override options of other mechanisms.
To fix it, we only set default value after consolidated config process.
Close #1010
=> Fix handling cli options default value

api/server.go, api/server_test.go, cmd/cloud.go, cmd/config.go, cmd/config_consolidation_test.go, cmd/root.go, cmd/run.go, core/engine.go, core/engine_test.go, core/local/local.go, js/compiler/compiler.go, js/console.go, js/console_test.go, js/initcontext_test.go, js/modules/k6/html/gen/gen_elements.go, js/runner.go, lib/executor.go, lib/netext/httpext/httpdebug_transport.go, lib/netext/httpext/request.go, lib/state.go, lib/testutils/logrus_hook.go, loader/loader.go, stats/cloud/collector.go, stats/dummy/collector.go, stats/influxdb/collector.go, stats/json/collector.go, stats/kafka/collector.go, stats/statsd/common/collector.go
Also add some comments to keep linter silent.
Closes #1016
=> Use logrus import without alias

lib/archive.go, lib/old_archive_test.go
This PR adds a code workaround that discards the derived `execution` config value in the consolidated options that was wrongly saved by k6 in the archive `metadata.json` files until https://github.com/loadimpact/k6/commit/83193f8a96e06a190325b838b2cc451119d6b836. This basically means k6 v0.24.0 and surrounding `master` commits.
=> Discard execution metadata option from old archives

js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go
This is a very naive fix for #1116: it ensures the WS connection is established before running the setup function.
This avoids the panic and running the test script provided by @MStoykov now outputs:
```
ERRO[0011] GoError: lookup nonexistant on 172.16.1.1:53: no such host
at native
at file:///home/ivan/.local/go/src/github.com/loadimpact/k6/test-ws.js:5:61(14)
```
Closes #1116
=> fix(ws): return error before running setup fn if WS is not connectable

js/modules/k6/http/request_test.go, lib/netext/httpext/compression.go, lib/netext/httpext/request.go, lib/testutils/httpmultibin.go
k6 supports compression of request bodies with multiple layered algorithms but does not handle decompression body in the same manner. This PR adds support for decompression response body with multiple layered algorithms in the same manner.
Close #1108
=> lib/netext/httpext: add support decompression of stacked compressed response

cmd/collectors.go, cmd/config.go, stats/csv/collector.go, stats/csv/collector_test.go, stats/csv/config.go, stats/csv/config_test.go
Hi, I've noticed that json output takes up a lot of disk space for long running tests. I've found this issue #321, the csv output option was discussed there and I've decided to implement it. It works similar to json output, writing one sample per row. It uses twice as less space than json, so I've decided to open a pull request for it.
Maybe someone can suggest a way, how to transform the samples, so it would be one line per http request. Then I will make the changes and reopen the pull request.
I'm new to Go language, so I'm open to criticism.
=> Add output option for csv format

js/bundle.go, js/runner_test.go
This commit does the bare minimal to enable useage of console init
context. Unfortunetely this means that redirection to file is currently
not supported in init context.
This fixes #951
Message for the release notes:
> bugfix: `console` is now usable inside the init context. Unfortunately this doesn't respect `--console-output` (#1131) , and will be fixed in the future.
=> Enable console in the init context

stats/json/collector.go
The commit includes three main changes:
1. Don't write on Collect instead (as all other outputs) append to a
buffer and write the buffer in a separate goroutine every 100
milliseconds
2. Use json.Encoder for speed up
3. If the output file ends in `.gz` gzip the output which in my testing
decreases the file size by 30x. I couldn't measure any performance
degradation from the fact we need to compress if anything there is some
performance gain because of the smaller io writes
I was testing with simple script doing batch requests for a local zero
length file with 40VUS, that makes around 8k RPS using around 600-700mb
of memory. When running before those I was getting 5.8-6k RPS, after
this I am getting 6.5-6.9k RPS with around 3GB of memory usage.
At this point my cpu and memory profiling …
=> Speed up JSON output

js/modules/k6/marshalling_test.go, js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go, js/runner_test.go, lib/testutils/httpmultibin.go
=> don't use external service for testing websockets

lib/netext/httpext/error_codes_test.go
k6 tests fails to run on Mac, due to syscall.EBFONT is not available
there. Fixing it by using a syscall error which is available in windows,
linux and mac, like syscall.ENOTRECOVERABLE.
Close #1141
=> lib/netext/httpext: use syscall.ENOTRECOVERABLE for testing error

js/modules/k6/k6.go, js/modules/k6/k6_test.go
This fix ensures the check metric is failed if an error occurs inside the check function, while still allowing an unhandled error to be thrown and interrupt the test, keeping backwards compatibility.
Closes #1054
=> fix(js): fail check if an error is thrown

core/engine_test.go, js/http_bench_test.go, js/module_loading_test.go, js/modules/k6/http/request_test.go, js/modules/k6/marshalling_test.go, js/modules/k6/ws/ws_test.go, js/runner_test.go, lib/testutils/httpmultibin/httpmultibin.go, loader/loader_test.go, stats/cloud/collector_test.go
This is done because it gets in the way of using the `testutils` package
inside lib
=> move HTTPMultiBin to it's own package

core/engine_test.go, lib/testutils/httpmultibin/httpmultibin.go
This _should_ fix flaky test `TestSentReceivedMetrics`.
See https://circleci.com/gh/loadimpact/k6/6474, https://circleci.com/gh/loadimpact/k6/6484 .
This issue was introduced in a63bb586 (PR #1138), where the previous implementation of `getWebsocketEchoHandler()` closed the connection after writing, so this change brings that back.
It seems that closing the connection creates additional metrics which `TestSentReceivedMetrics` takes into account _sometimes_, hence the flakiness.
Please run `go test -count=1 ./core` on this branch a few times on your local machine to ensure it's fixed. :)
There are a few unrelated things to the fix here, but check out the individual commits, and let me know if you prefer another PR for them. I just added them here since they're kind of related.
=> Fix(?): flaky TestSentReceivedMetrics test

Dockerfile
Until https://github.com/golang/go/issues/34066 is fixed.
Update #1153
=> temporary use go1.12 for Dockerfile

stats/cloud/collector.go, stats/cloud/collector_test.go
Once the cloud test gets aborted by limit, we should not send metrics
anymore. The test and collector will still running, though.
Close #1074
=> stats/cloud: stop sending cloud metrics when limit reached

cmd/root.go
In #1162, we use new os.UserConfigDir to get user's config directory, and it will
panic when encounter an error. This is a backward in-compatible behavior and
can lead to bad UX.
This PR restore previous #1162 behavior. Instead of panic, we return a
default value for config dir if we can figure out user config directory.
Close #1176
=> Use default config directory value instead of panic

js/modules/k6/http/request_test.go, lib/netext/httpext/request.go, lib/netext/httpext/request_test.go, lib/netext/httpext/transport.go
This fixes the credential leak in HTTP metric tags.
Closes #1103
=> fix(httpext): remove user credentials from metric tags

js/bundle.go, js/bundle_test.go, lib/options.go, lib/types/types.go
This ensures any `guregu/null` values in `lib.Options` are correctly unpacked and saved as JS script options.
Closes #886
=> fix(js): properly marshal lib.Options values to JS options

core/engine_test.go
Usages of `testErrorWithString` was removed in 371b4af8d443dd1eb9717c35d9cdd19d633af40a, it is unused in current code base.
=> Remove unused testErrorWithString

.golangci.yml, lib/netext/httpext/request.go, lib/netext/httpext/request_test.go
Raise an error on a `101 Switching Protocols` response, since k6 doesn't support protocol upgrades in the current HTTP API. This avoids the hanging behavior described in #971.
See the commit description for details (I want to avoid GH's reference link spam).
=> fix(httpext): return error on unsupported 101 response

cmd/run.go, core/engine.go, stats/cloud/collector.go, stats/cloud/collector_test.go
In #1130, we stop sending metrics to cloud when limit reached. However,
after stop sending metrics, collector still collects data, causing the
memory usage quickly increase.
To fix it, do not collect data if stop sending metrics triggered.
While at it, also remove some useless condition checking that slice
length is greater than 0 before looping.
Fixes #1187
=> Fix memory leak after stop sending metrics to cloud

cmd/runtime_options.go, js/common/bridge.go
In #1188, I removed some useless `len` check before `for` loop. But there is one place in `cmd/` is not removed.
This PR removed it.
While at it, also run gofmt -s -w.
=> Remove another useless len check before for loop

.golangci.yml
[1.19 has issues on the GolangCI service](https://golangci.com/r/github.com/loadimpact/k6/pulls/1143), which is fixed by upgrading. Or it was a temporary hiccup, but regardless it works OK on 1.20 now and we should probably upgrade.
The `_gen.go` excludes were suggested by @na--.
=> chore: bump golangci-lint version, ignore _gen.go files

core/engine_test.go, js/runner.go
`minIterrationDuration` is affecting setup/teardown stages. That should not be the case, and must only affect normal iteration only.
So ignore `minterationDuration` when in setup/teardown stage.
Close #1003
=> Ignore minIterationDuration in setup/teardown stage

js/bundle_test.go, js/common/util_test.go, js/initcontext_test.go, lib/testutils/httpmultibin/httpmultibin.go, stats/cloud/client.go, stats/thresholds_test.go, ui/summary_test.go
This cleanup most warnings emitted by nilness check, including
potentinal accessing field of nil object in tests, or condition which is
always true.
Passes all current tests.
=> Cleanup some warnings emitted by nilness check

Dockerfile
PR #1157 used go1.12 temporary for Dockerfile, to mitigate https://github.com/golang/go/issues/34282. The backport issue was merged https://github.com/golang/go/issues/34285 and ~~go1.13.1~~ go1.13.3 is now released. so we can use go1.13 again.
Close #1153
=> Use go1.13 for CI again

js/modules/k6/http/request_test.go, lib/netext/httpext/request.go
A problem exists if a series of redirects occurs:
`user -> site A -> site B -> site A`
The current code saves cookies in ActiveJar relative to the redirect URL, and should in the source URL.
Explanation:
1. request to [site A], response cookies [C1]
2. [site A] redirect request to [site B]
3. k6 stores this cookies at activeJar[siteB]
4. [site B] response cookies [C2] redirect request to [site A]
5. k6 stores this cookies at activeJar[siteA]
6. final request to [site A] receives only [C2] cookies.
=> Fix cookie set, chain redirects

js/modules/k6/html/html.go, js/modules/k6/html/html_test.go
Selection.map currently calls the underlying goquery.Selection Map. It
causes problem when running inside goja runtime, all the nodes inside
the function body is treated as goquery.Selection instead of our wrapper
Selection, thus lead to wrong calling methods.
To fix it, we wrap goquery.Selection to Selection before passing to goja.
Fixes #1195
=> Fix js map causes wrong return type

cmd/cloud.go, cmd/collectors.go, cmd/config.go, cmd/config_test.go, cmd/options.go, cmd/run.go, js/modules/k6/http/request_test.go, lib/netext/httpext/request.go, lib/options.go, lib/options_test.go, lib/runtime_options.go, stats/cloud/config.go, stats/csv/config.go, stats/influxdb/config.go, stats/kafka/config.go
Works on #671 and fixing it in almost all cases.
This was done primarily by running:
```
rg -g "*.go"  'envconfig:"' --files-with-matches  |\
xargs -n 1 sed -s -i 's/envconfig:"/envconfig:"K6_/g'
```
And than manually fixing all remaing problems by hand.
In the mean time I found out we weren't properly combing the
configuration for statsd/datadog and fixed.
Also renamed HttpDebug to HTTPDebug in the Options struct.
Unfortunately due to the way the statsd and datadog share the same
struct for a config this doesn't fix the issue as a whole for them.
=> Prefix all envconfig struct tags with K6 directly

Gopkg.lock, Gopkg.toml, cmd/config_test.go, vendor/github.com/kelseyhightower/envconfig/env_os.go, vendor/github.com/kelseyhightower/envconfig/env_syscall.go, vendor/github.com/kelseyhightower/envconfig/envconfig.go, vendor/github.com/kelseyhightower/envconfig/usage.go
We were using a very old version (Jan 2017), and the new one includes fixes like https://github.com/kelseyhightower/envconfig/pull/119 , which would avoid workarounds in PRs like #1143.
=> Upgrade envconfig

.circleci/config.yml, Gopkg.toml
Usages of `configdir` library were removed in https://github.com/loadimpact/k6/pull/1162, but we forget to remove it from Gopkg.toml.
This PR removes its entry from Gopkg.toml, now `dep ensure` run without warnings.
=> Remove configdir from Gopkg.toml

stats/cloud/api_test.go, stats/cloud/client.go
When k6 requests to cloud API timeout, k6 will retry the request a
few times. This can be problematic, because the retrying request can
cause user's test start twice.
This PR tries to fix that problem by using a session token for each POST
request. With this token, cloud API can know that the request is the
retried one, and avoid creating new test, and return the old one.
Speaking in other way, k6 POST request to cloud API becomes idempotent.
Fixes #1205
=> Make cloud API requests idempotent

stats/cloud/client.go
Currently, we do header preparation in Client.do. It's a little verbose, and also done for every retried requests.
We can make it slightly better by factor out header preparation to its own function, and calling it once before retry loop.
=> Factor out header preparation from do

Dockerfile
Alpine 3.7 is 3 minor versions behind current version (as of Oct 26th 2019 it's 3.10.3).
AFAIK alpine 3.7 stopped receiving patches.
=> Upgraded Dockerfile to alpine:3.10

core/engine_test.go, js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go, lib/testutils/httpmultibin/httpmultibin.go
This avoids a hanging behavior when the server closes the WS connection, either via a [control close frame](https://tools.ietf.org/html/rfc6455#section-5.5.1) or by closing the connection prematurely without sending the control frame (deviating from the WS protocol).
If the control close frame is not received but the connection is closed, the error (`close 1006 abnormal closure): unexpected EOF`) will be returned to the user's WS error handler, as it indicates an issue with the server.
The user-specified close handler should be called in either case now.
Closes #581
=> Correctly handle server-initiated WebSocket close

stats/cloud/collector.go
This causes a native comparison loop to abort as soon as a match is found, potentially improving performance a lot when there are many different sub-buckets.
@MStoykov pointed out the missing `break` :blush:  Its lack wasn't causing any bugs, it was just making an already inefficient code even more so...  :man_facepalming:
=> Improve the cloud aggregation bucketing performance

stats/cloud/collector.go, stats/cloud/collector_test.go
For cloud output, we currently don't aggregate HTTP metrics with
different url tag, but with the same name tag.
This PR improves aggregation by setting url tag to be the same as name
tag. It's not ideal, but seems like the least bad option in term of UX.
Fixes #1166
=> Improve cloud aggregation for different URLs

cmd/config.go, cmd/config_consolidation_test.go, cmd/options.go, cmd/run.go, lib/options.go, ui/summary.go, ui/summary_test.go
This adds an optional `count` column for Trend metrics in the CLI summary output, while refactoring parts of `ui/summary.go` for code style (avoiding globals, explicit validation, etc.) and negligible performance improvements (using a map for column lookups).
To enable it run e.g. `k6 run --summary-trend-stats 'avg,p(99.99),count' test.js`.
This essentially makes the existing default Count metrics like "http_reqs" and "iterations" obsolete, so we might want to consider making `count` a default column after all and removing these two metrics from the output.
I added a test for `SummarizeMetrics`, so our coverage should improve a bit. :)
Closes #1087
=> Add optional 'count' column to CLI summary output

core/engine_test.go, core/local/local.go, core/local/local_test.go, js/runner.go, js/runner_test.go, lib/netext/dialer.go, stats/cloud/collector.go, stats/cloud/collector_test.go
This removes emission of `metrics.Iterations` as a standalone metric, and instead bundles it as part of `netext.NetTrail`, and only for `default` functions.
This is done to reduce the amount of individual metrics, and thus traffic, sent to backends, and has minor user-facing impact mentioned in #1189.
Closes: #1189
=> Emit iterations metric as part of netext.NetTrail

stats/cloud/bench_test.go
The benchmark is testing only for httpext.Trail and such that have
different urls and names which is probably the worst case performance
wise. The benchmark is somewhat flaky ... but with more runs it seems
consitant in 5% margins ;)
=> add benchmark for the cloud output

cmd/archive.go, cmd/cloud.go, cmd/common.go, cmd/root.go, cmd/run.go
If RootCmd.Execute returns any error, we always log that error. So
removing log from child command before returning to prevent duplicated
error message printed.
This PR also adds Hint field to ExitCode, to provide hint/details for
the underlying error. It helps the logger keep the semantic and provide
meaningful error message to user.
Updates #994
Fixes #702
=> Fix duplicated error messages

lib/netext/httpext/compression.go, lib/netext/httpext/request_test.go
Range over array make a copy of all elements in each iteration. Avoiding
this help improving the speed of `wrapDecompressionError` slightly.
```
name                       old time/op    new time/op    delta
WrapDecompressionError-12    14.5ns ± 2%     8.5ns ± 1%  -41.77%  (p=0.008 n=5+5)
name                       old alloc/op   new alloc/op   delta
WrapDecompressionError-12     0.00B          0.00B        ~     (all equal)
name                       old allocs/op  new allocs/op  delta
WrapDecompressionError-12      0.00           0.00        ~     (all equal)
```
=> Improve wrap decompress error

cmd/convert_test.go, js/initcontext_test.go
Discover this while I have been working on marking "k6 convert" as deprecated.
=> Remove un-necessary type conversion

cmd/convert.go
"k6 convert" should emit a warning and point user to https://github.com/loadimpact/har-to-k6
Fixes #1124
=> Mark "k6 convert" as deprecated

stats/csv/config.go, stats/csv/config_test.go
1. don't use external libraries, that we want to remove, to do it
2. error out on non existing keys in the argument
3. don't print to stdout if `file_name` is not provided in the argument
but there is an argument
=> Better parsing of the csv output's arguments

stats/cloud/client.go
In 09007b3, cloud request headers is centralized preparing, but it
breaks "k6 cloud" because some methods of Client still uses
http.NewRequest to create POST request with form data.
To fix it, we move back prepareHeaders inside Do.
=> Move prepareHeaders inside Do

stats/cloud/collector.go, stats/cloud/collector_test.go
fixes #1236
Text for release notes in bugfix section:
```
Cloud output: correctly set the "name" for scripts being ran through the shortcut urls (github.com,cdnjs.com), instead of returning an error. Thanks @Menda for reporting! (#1237)
```
=> Correctly set the "name" of scripts ran through the shortcut urls

js/initcontext.go, js/initcontext_test.go
closes #1234
proposed release notes in "Bugfixes"(we should have "small changes or miscellaneous"):
```
JS: add the path to the error message when `open()` is used with a directory (#1238)
```
=> Add the path to the error when trying to open() a directory

cmd/config.go, cmd/run.go, core/engine.go, ui/summary.go, ui/summary_test.go
Add --summary-export flag for "k6 run", the parameter is output file to
write report summary in JSON format.
Empty string means output is ignored.
Close #355
=> Add report summary CLI flag

cmd/root.go, cmd/version.go, lib/consts/consts.go
Not sure if this is the best way to format and present everything, and whether we can add some more information, but something like this should greatly help with debugging of various issues. And it's worth investigating the details of https://github.com/loadimpact/k6/issues/1070#issuecomment-552507335... Also, not sure if we should build our official images with something like `go build -ldflags "-X github.com/loadimpact/k6/lib/consts.VersionDetails=$(date --iso-8601=seconds)/$(git describe --always --long --dirty)"`...
=> Emit more detailed k6 version information

.circleci/config.yml
This reduces the amount of output `go test` generates about given pkg not being tested by the package currently under test, ultimately reducing a lot of log lines from circle's log.
Unfortunately the magical `all` includes everything (stdlib including) which just makes the tests take *way* too long ...
=> circleci: give --coverpkg only the pkg's dependancies 

.dockerignore, Dockerfile, build-release.sh
This refactors the `build-release.sh` script and adds detailed version information and (for Linux builds only) `CGO_ENABLED=0`. Reviewing commit by commit should be easier. 
Not sure if I should do anything with the .rpm, .deb, or .msi packages, considering that they are only ever built for properly tagged official releases, and the Linux packages already had `CGO_ENABLED=0`:  https://github.com/loadimpact/k6/blob/b41ed21c081900b3409955490ad9aea99819375e/.circleci/config.yml#L142
Forgot to specify, this closes https://github.com/loadimpact/k6/issues/930
=> Better release build script

.circleci/config.yml, Dockerfile, appveyor.yml, build-release.sh
Build release script assumes GNU toolchains to make it works, thus running the script under Mac OSX fails. There're two problems:
- `date` command invocation using GNU specific parameters.
- Incorrect handling of checksum command invocation.
To fix them:
- Use common parameters of both GNU `date` and BSD `date`, also use a specific time format form, instead of relying on `--iso-8601` GNU option. This will change the timezone offset format from `+00:00` to `+0000`.
- Use an array to handle checksum command invocation.
While at it, also add `-trimpath` to all `go build` and `go install` command.
=> Cleanup build script

js/runner_test.go
Currently, we check exactly matching of error message return by go
standard library. It's working nowaday but not guaranteed to work in
upcoming go version. At least in go1.14, all the certificate expried
message checking test will fail, due to the change of error message
format in net/http.
To fix this, we only check that error message contains the message we
want, e.g certificate expired error should contain word "expired".
While at it, also add some require.NoError to make sure no editor
complains above "can lead to nil pointer dereference".
=> Better error message checking

js/runner.go, js/runner_test.go
This should fix #867.
This is not ... a great fix in the sense that while doing it I found out
we are also asynchrnously touch VU.Runtime which should also not happen
and the currently added mutex should probably be locked in most other
functions, but this should fix the immediate problems and the other
should be fixed in a more ... complete redesign :)
=> Add a mutex to js.VU to prevent multiple asynchrnous calls to RunOnce

cmd/convert.go
This reverts commit 030d37d816042735c86746bb21774b5393197ac6.
=> Revert "cmd: mark convert command as deprecated"

lib/executor/common_test.go, lib/executor/constant_arrival_rate_test.go, lib/executor/per_vu_iterations_test.go, lib/executor/variable_arrival_rate_test.go, lib/runner.go
This adds a test for `PerVUIterations` while modeling `lib.MiniRunnerVU` closer to how `js.VU` works (setting `lib.State` in the context when `RunOnce`/`runFn` is called).
=> Add PerVUIterations test for #1007

js/modules/k6/http/request_test.go
The previously used https://stackoverflow.com seems to no longer do it, so I switched it to https://www.microsoft.com. This is just a short-term fix, so that the tests don't break...
=> Change the external website we use for the OCSP stapling test

.circleci/config.yml, README.md, release notes/v0.26.0.md
This is just a collection of short-term fixes:
- pin the latest .msi package in the README, instead of using a specific version
- use `go get -d` for the go-bin-deb and go-bin-rpm packages, to only download the source (without building them) before we use glide to get their precise dependencies
- inject the new full version information in the build process
As mentioned in https://github.com/loadimpact/k6/issues/1247#issuecomment-566029167, we should build and test the linux packages regularly, so we can fix them if something breaks...
=> Fix issues with the linux package builds and the README

release notes/v0.26.0.md
The `csv` keyword is required, otherwise k6 will error out with `ERRO[0003] unknown output type: file_name`.
IMO the way output parameters are specified is a bit confusing, as `=` is used both for delimiting the output type from its parameters, as well as delimiting parameter names from their values. It's even more confusing if `=` is used for the option itself, e.g. `--out=csv=file_name=somefile2.csv,save_interval=2s` (this is valid). There's surely a friendlier way to specify this. :)
=> Fix CSV output example in release notes

js/modules/k6/http/request_test.go, js/modules/k6/k6.go, js/modules/k6/metrics/metrics.go, js/modules/k6/ws/ws.go, lib/netext/httpext/request.go, lib/netext/httpext/request_test.go, lib/netext/httpext/transport.go, stats/stats.go, stats/thresholds.go
Go 1.13 and below has a bug that client timeout will not be propagated
to http request context. That bug was fixed already and will be present
in go1.14 (golang/go#31657).
With current go master, our TestSetupTeardownThresholds fails. The
reason is that we only push sample if the request context not done. When
the bug in Go stdlib was not fixed, our own http Client.Timeout is not
passed to request context, so when client makes request, it does not
aware about the request context, and always push the sample.
Now when Client.Timeout is passed to request context, as long as the
client finish the request, the request context is consider done, and we
do not push the sample anymore.
Further more, we are using the wrong context for PushIfNotCancelled.
It's intended to use with VU context instead …
=> Fix wrong context is used to decide pushing metrics or not.

js/http_bench_test.go, js/runner.go
```
$ benchstat old.txt new.txt
name            old time/op    new time/op    delta
HTTPRequests-4     261µs ±10%     256µs ±11%    ~     (p=0.097 n=18+18)
name            old alloc/op   new alloc/op   delta
HTTPRequests-4    27.7kB ± 0%    27.6kB ± 0%  -0.35%  (p=0.000 n=20+20)
name            old allocs/op  new allocs/op  delta
HTTPRequests-4       368 ± 0%       366 ± 0%  -0.54%  (p=0.000 n=20+20)
```
=> Don't create cookiejar before each iteration if it should be reused

api/server_test.go, api/v1/group_routes_test.go, api/v1/metric_routes_test.go, api/v1/status_routes_test.go, cmd/config_consolidation_test.go, core/engine_test.go, core/local/local_test.go, lib/executor/common_test.go, lib/executor/constant_arrival_rate_test.go, lib/executor/execution_test.go, lib/executor/per_vu_iterations_test.go, lib/executor/variable_arrival_rate_test.go, lib/runner.go, lib/testutils/mini_runner.go
Since I was a bit late posting my review of https://github.com/loadimpact/k6/pull/1255, I decided to transform my unpublished comments into actual code... Beside moving the `MiniRunner`, it was also slightly improved to not use random VU IDs, so it matches the JS runner more closely.
=> Move MiniRunner to testutils and simplify executor test setup

cmd/run.go, core/local/local.go, core/local/local_test.go, lib/executor/constant_arrival_rate.go, lib/executor/constant_looping_vus.go, lib/executor/externally_controlled.go, lib/executor/per_vu_iterations.go, lib/executor/shared_iterations.go, lib/executor/variable_arrival_rate.go, lib/executor/variable_looping_vus.go, lib/executors.go
For executor which has nothing to do in a given segment, we should not
include it in the list of executors.
To do it, add new method HasWork to ExecutorConfig. By filtering out no
work executor when creating new schedulter, we can prevents any un-necessary
works and provide better UX.
Fixes #1295
=> Exclude no work executor

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feat_req.md, README.md, SUPPORT.md
I don't have access to the repo Settings where these [can be created and previewed directly](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository), but it's standard Markdown so it should render fine.
Someone will still have to configure and select these files in the Settings. :)
Let me know if anything should be changed. I don't think we need a PR template as well, right?
Partially fixes #1063
=> Add GitHub issue templates

cmd/cloud.go, cmd/run.go, cmd/ui.go, lib/execution.go, lib/executor/base_executor.go, lib/executor/externally_controlled.go, lib/executor/helpers.go, ui/pb/helpers.go, ui/pb/progressbar.go, ui/pb/progressbar_test.go
This fixes a few alignment issues with the new progress bars:
- Dynamic padding-right of the left progress bar text; aligning all progress bars, making them easier to read.
- Trimming of long left progress bar text and replacing it with ellipsis. Currently fixed at 30 chars, this will be made configurable/dynamic in follow up PRs that deal with `cmd/ui`.
- Unit tests for all, so now `ui/pb` has 100% coverage! :tada:
- A few small refactors, see the commits.
Some comments:
- `ProgressBar` no longer implements `fmt.Stringer`. The interface was restricting what needed to be a more flexible `Render()` method. We can still wrap this in a `String()` method, calling it with some sane defaults, but I didn't think it was necessary, as nothing currently uses it.
- The additional locking needed in …
=> Improve progress bar rendering of #1007

.golangci.yml, lib/execution_segment.go, lib/execution_segment_test.go
The remaining work that was slated for this PR would be done in https://github.com/loadimpact/k6/pull/1323 instead
=> Execution segment sequences

cmd/cloud.go, cmd/ui.go, cmd/ui_test.go, core/local/local.go, lib/executor/constant_arrival_rate.go, lib/executor/constant_looping_vus.go, lib/executor/externally_controlled.go, lib/executor/helpers.go, lib/executor/per_vu_iterations.go, lib/executor/shared_iterations.go, lib/executor/variable_arrival_rate.go, lib/executor/variable_looping_vus.go, ui/pb/progressbar.go, ui/pb/progressbar_test.go
This implements a couple of features discussed in #1279:
- General cleanup of the right-side progress bar text: shorter, split into two columns, correct alignment. Initially I experimented with tabwriter to achieve this simply with tabs, but there would always be an edge case that would unexpectedly cause columns to shift further right, so tabs weren't reliable. The alignments done manually here with `fmt` padding unfortunately complicate the render code quite a bit, so let me know if it can be simplified. I still think it's worth it as columns make the progress much easier to follow, even though they don't strictly contain homogeneous elements.
- Adding a "status" column and field to `ProgressBar` to indicate when the executor is stopping, done, etc. This is shown after the executor …
=> More compact progress bar status text

js/bundle.go, js/bundle_test.go
as in #799(which was about the same issue with setup data), we
don't actually have problems with a VU seeing changes from
previous iterations. It will be too expensive to constantly copy, it
won't panic and there are no issues with distributed execution.
fixes #1328
=> Copy __ENV so that 2 VUs don't share the same one

lib/executor/common_test.go, lib/executor/constant_arrival_rate_test.go, lib/executor/constant_looping_vus_test.go, lib/executor/externally_controlled.go, lib/executor/externally_controlled_test.go, lib/executor/per_vu_iterations_test.go, lib/executor/shared_iterations_test.go, lib/executor/variable_arrival_rate_test.go, lib/executor/variable_looping_vus_test.go
This adds unit tests for ConstantLoopingVUs.Run, ExternallyControlled.Run, PerVUIterations.Run, SharedIterations.Run and VariableLoopingVUs.Run, while fixing a data race issue with the ExternallyControlled executor (see 36aedeff for details).
Weather warning: cloudy with a chance of flakiness for `TestExternallyControlledRun` and `TestVariableLoopingVUsRun`. I stress tested `lib/executor` using [this script](https://dave.cheney.net/2013/06/19/stress-test-your-go-packages) with `-race` enabled, and these two tests eventually fail after a few minutes. The failure rate is low in my tests (~5%), so they could still have value being merged as is.
I'm not sure how to further stabilize the tests (i.e. rely less on sleeps), so let me know if you have any suggestions.
=> Additional unit tests for #1007

lib/executor/variable_looping_vus.go, lib/executor/variable_looping_vus_test.go
This fixes the first bug mentioned in #1296, and adds a test that tries to ensure a smooth ramp-down.
I'm not proud of the test, and while it fairly consistently detected the bug and it might be useful for the second segment / execution plan issue, I'm concerned it might be flaky and would prefer a more deterministic approach of inspecting execution that doesn't rely on `time.Sleep`. Maybe inspecting metrics would be more reliable? Any ideas?
=> Fix variable-looping-vus VU wobble during graceful ramp-down

api/v1/status.go, core/local/local.go, lib/consts/consts.go, lib/execution.go
This started as just a few minor fixes, but then I realized that if I add an explicit execution status, the other things I'm currently doing would be much, much simpler, as well as any future debugging we might have to do.
=> Add ExecutionStatus and minor fixes

cmd/run.go
Closes #1301
This re-enables the usage report, and updates its payload to include executor types and number of them used.
Example of payload:
```json
{
"duration": "1m0.029405562s",
"executors": {
"constant-arrival-rate": 1,
"constant-looping-vus": 2,
"externally-controlled": 1,
"per-vu-iterations": 1,
"shared-iterations": 1,
"variable-arrival-rate": 1,
"variable-looping-vus": 2
},
"goarch": "amd64",
"goos": "linux",
"iterations": 2175,
"k6_version": "0.26.0",
"vus_max": 130
}
```
Note that currently this POST to https://reports.k6.io/ fails with a `502 Bad Gateway`, which I'm assuming is because of the change in schema and the backend will have to be updated to match. The differences are minor: this drops `duration_st` and adds `executors`.
=> Re-enable the usage report

api/v1/status.go, api/v1/status_routes.go, api/v1/status_routes_test.go, core/engine.go, core/engine_test.go
Including a new `stop` cmd to trigger it via the HTTP API.
Closes #1352.
=> Add a method to stop a running Engine

release notes/v0.26.2.md
This is a strange minor release that was done to fix the Windows build,
but otherwise doesn't have any functional changes, so this only updates
the release notes.
See https://github.com/loadimpact/k6/commit/459da79ef51b37e5eaba4575c9065d9e592e5c49
=> Add v0.26.2 release notes

lib/executor/variable_looping_vus_test.go
This refactors a couple of tests mentioned in #1357 to reduce their chances of failure. :) It doesn't get rid of the flakiness entirely, but merely shifts things around and uses safer timings. In my tests the behavior is much more stable now, though there could still be some failures on Windows during quick CPU usage bursts, which I'm hopeful we won't run into on GH Actions.
After these changes stress testing both for about an hour didn't produce failures on Linux nor Windows:
Whereas on `new-schedulers` both tests fail quickly:
It's likely these might be more susceptible to failure when run as part of the entire package instead of individually, and while I didn't see them fail when stress testing `lib/executor`, I did see others mentioned …
=> Make some executor tests more deterministic

lib/execution_segment_test.go
This is a test from #1339, which did a bunch of things that are not needed anymore, so this is a cut-down version of that.
See #1296
=> Add test for ExecutionSegment.Scale consistency

cmd/options.go, cmd/run.go, core/local/local.go, lib/execution.go, lib/execution_segment.go, lib/execution_segment_test.go, lib/executor/common_test.go, lib/executor/constant_arrival_rate.go, lib/executor/constant_arrival_rate_test.go, lib/executor/constant_looping_vus.go, lib/executor/constant_looping_vus_test.go, lib/executor/execution_test.go, lib/executor/executors_test.go, lib/executor/externally_controlled.go, lib/executor/externally_controlled_test.go, lib/executor/per_vu_iterations.go, lib/executor/per_vu_iterations_test.go, lib/executor/shared_iterations.go, lib/executor/shared_iterations_test.go, lib/executor/variable_arrival_rate.go, lib/executor/variable_arrival_rate_test.go, lib/executor/variable_looping_vus.go, lib/executor/variable_looping_vus_test.go, lib/executors.go, lib/options.go
The idea of this PR is to
1. Basic review of the algorithm - it is fairly short so it shouldn't take long and the basics of the implementations are hardly going to change.
2. Discuss whether it should be implemented as it is or should we basically calculate it for every segment so that it can be used in a future distributed mode? It really won't be much more code and will add some memory overhead but nothing big really. 
3. I think the returned values should be a list offsets(where the first one is the start) and the second the LCD, as you would otherwise need to calculate it again ... and there is really no point in having start and offsets as separate values.
=> Implement GetStripedOffsets

lib/execution_segment.go, lib/executor/constant_arrival_rate_test.go, lib/executor/variable_arrival_rate.go, lib/executor/variable_arrival_rate_test.go
The previous implementation worked basically as follows:
A list of changes to the arrival rate is generated where there is a
minimum time between this changes (currently 250ms). This means that for
any ramp-up/down there is a step every 250ms (more or less).
After this is generated a goroutine will read that list and send the
change on a channel at the appropriate time. During ramp-up/down this is
every 250ms (more or less).
Another goroutine will be receiving those changes and resetting a timer
to the new value. And here is where the problem lies:
If the arrival rate is more then 1 iteration each 250ms this means that
it will never trigger a start of a VU.
The extreme example is having ramp-up to 4 iteration per second - this
is exactly 1 iteration each 250ms, which means that for the …
=> Fix VariableArrivalRate not working well

api/v1/setup_teardown_routes_test.go, cmd/run.go, core/engine.go, core/engine_test.go, core/local/local.go, core/local/local_test.go, js/runner_test.go, lib/execution.go
This allows metric processing to still occur, even after the script run has completed. In practice, this allows you to run k6 with the `--linger --no-teardown` flags, and execute the `teardown()` function manually through the REST API, after the main test run has completed.
This also fixes https://github.com/loadimpact/k6/issues/1369 - now a second Ctrl+C will _always_ abort k6, albeit in a very abrupt way. On the other hand, the first Ctrl+C would be more graceful than it currently is, since it will now allow `teardown()` to be executed.
=> Refactor the Engine to process metrics independently from the test Run

lib/execution_segment_test.go, lib/executor/variable_looping_vus_test.go
I gave up on completely understanding all of the corner cases of https://github.com/loadimpact/k6/pull/1392, or on simplifying it... for now... :sweat_smile: But here's an extra test that hopefully validates that however we segment a `variable-looping-vus` executor, it will always execute what it would have executed if it was running on a single machine. 
Whether that execution is completely correct is another topic :smile: My manual tests didn't find any issues there, but I would still want some easier to follow implementation eventually, maybe when we adapt it to data partitioning.
=> Add a randomized test for the variable-looping-vus requirements

core/local/local_test.go, lib/executor/executors_test.go, lib/executor/shared_iterations.go
Unfortunately because of the way the ExecutorConfig interface is
designed I can't just cache some of the results which will result in
some probably unneeded amount of calculation.
This will need either a change to the interface or for ExecutionTuple to
cache the results of GetNewExecutionTupleBasedOnValue, but I find it
unlikely this to be noticeable outside of extreme examples
=> Use the striping algorithm for shared iterations

lib/execution_segment.go, lib/execution_segment_test.go, lib/executor/constant_arrival_rate.go, lib/executor/constant_arrival_rate_test.go, lib/executor/constant_looping_vus.go, lib/executor/externally_controlled.go, lib/executor/per_vu_iterations.go, lib/executor/shared_iterations.go, lib/executor/variable_arrival_rate.go, lib/executor/variable_arrival_rate_test.go, lib/executor/variable_looping_vus.go, lib/executors.go, lib/options.go
This cleans up the interfaces and makes it possible to re-use the heavy calculations for a segment sequence. 
closes https://github.com/loadimpact/k6/issues/1379
=> Refactor ExecutionSegment sequences, wrappers and tuples

js/common/bridge_test.go, js/common/util.go, js/common/util_test.go, js/console_test.go, js/module_loading_test.go, js/modules/k6/crypto/crypto_test.go, js/modules/k6/crypto/x509/x509_test.go, js/modules/k6/encoding/encoding_test.go, js/modules/k6/html/element_test.go, js/modules/k6/html/elements_gen_test.go, js/modules/k6/html/elements_test.go, js/modules/k6/html/html_test.go, js/modules/k6/html/serialize_test.go, js/modules/k6/http/http_test.go, js/modules/k6/http/request_test.go, js/modules/k6/http/response_test.go, js/modules/k6/http/tls_test.go, js/modules/k6/k6_test.go, js/modules/k6/metrics/metrics_test.go, js/modules/k6/ws/ws_test.go, js/runner_test.go
=> Js package optimizaitons

cmd/run.go, core/engine.go
This is a quick and dirty fix for https://github.com/loadimpact/k6/issues/1434, though as I mention in that issue, the proper solution would be rewriting that code from scratch...
=> Fix metrics processing after test run

js/bundle.go, js/bundle_test.go
Previously (since e693715b) running a TAR file would overwrite the options set in the metadata.json with the script's exported options. This is a hacky fix, but the alternatives weren't much cleaner.
=> Avoid overwriting options when grabbing exports from archive

cmd/convert_test.go
The main part is that we reset the `output` flag, but I have already fixed the usage of `os` (which was done before me just no one has deleted the making of files) so I decided to add this too.
To see what is broken run `go test -race -v ./cmd -count 2`
=> refactor TestIntegrationConvertCmd to be more stable

stats/json/collector.go
Address issues #1469
Increase time interval between log message to 200 milliseconds
Remove Writing JSON metrics message 
Add if statement output log based on no of count
=> make JSON output logging less noisy

loader/loader.go
This just is the only places where there is space and looks quite strange in the log:
=> remove space from logrus Field

js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go
Previous to this, running k6 compiled with the race detector and ws
code will most definitely leak enough goroutines in 10 seconds that it
will stop because of the 8k limit ...
After this it seems to not leak anymore :confetti: I tested with 2k VUs 
which use around 7.5k goroutines and it seemed to move withing 200/300 
goroutines over a period of 5minutes without ever actually looking like
some goroutines leaked
=> Don't leak goroutines everywhere in the ws code

core/local/local_test.go, js/runner.go, js/runner_test.go, lib/executor/helpers.go, lib/runner.go, stats/system_tag.go, stats/system_tag_set_gen.go
This tags all metrics emitted in the main "exec" function with a "scenario" tag set to the scenario name or "default" if no custom scenarios were defined. It can be disabled with the `--system-tags` option.
There's no issue for this specific feature, but see #796 and #1300.
=> Add "scenario" as default system tag

js/empty_iteartions_bench_test.go, js/http_bench_test.go, js/runner.go
This took way longer then I anticipated mostly because of ... how
strange some things work.
The basic idea came from that for each iteration we constantly remake the
iterations which looked (and probably is) the lowest hanging fruit in k6
about creating too many objects.
Unfortunately because of how .. tags work and that iteration is a tag I
need to still copy the tags for GetTrail .. (it gets copied either way
for other metrics).
When running with an empty body this changed the amount of cpu taken
by scanobject and decreased it from 7.98s to 5.81s (while most other not
GC related had difference within 0.3s).
This is very small step ... having tags being immutable so we don't have
to constantly copy them will likely be much more significant or if we
can reduce the calls to …
=> Reuse the context and state in js.VU as much as possible

lib/executor/externally_controlled.go
:vomiting_face: about this fix, but I don't want to spend the time deeply refactoring this executor now... :disappointed: This should close https://github.com/loadimpact/k6/issues/1521 
I can add a new issue to refactor it, so we also don't need the 100ms sleeps and to add some tests...
=> Fix startTime>0 messing up the externally-controlled executor

lib/executor/constant_arrival_rate.go, lib/executor/constant_arrival_rate_test.go, lib/executor/executors_test.go, lib/executor/ramping_arrival_rate.go, lib/executor/ramping_arrival_rate_test.go
=> Make MaxVUs equal to preallocatedVUs when missing for arrival rate executors

cmd/archive.go, cmd/cloud.go, cmd/inspect.go, cmd/run.go, js/initcontext.go, loader/cdnjs.go, loader/cdnjs_test.go, loader/github.go, loader/github_test.go, loader/loader.go, loader/loader_test.go, loader/readsource.go, loader/readsource_test.go
This doesn't change anything functionally just removes the (direct) usage of the global logrus logger from the loader module. 
I debated refactoring the module into a struct again that takes a `logger` but decided that will be MUCH bigger change with literally no benefits apart from removing 1 argument from a couple of function calls, only 2 of which actually get called outside the module.
=> Use a provided logger in the loader module

js/bundle.go, js/bundle_test.go, js/initcontext_test.go, js/runner.go
Closes #889
I started adding more tests for this, but a `js.Runner` test would basically be a duplicate of the `TestInitContextVU` one, and a higher level one to replicate the example in the issue would need to involve an executor, and those tests rely on `MiniRunner` which kind of defeats the purpose. Still, let me know if there should be other cases covered.
=> Make __VU available in init context

README.md
This is only so that we link it correctly, we are likely to drop bintray soon ...
=> Update README to link directly to 0.27.0 on bintray

cmd/login_cloud.go, cmd/login_influxdb.go, cmd/ui.go, ui/form_fields.go
Closes #1559
Confirmed working on the latest Git Bash (2.27.0) and mintty 3.1.6 on Windows 10 x64 1903.
The "error getting terminal size" warning will still be shown and the progressbars will be static, but at least it doesn't panic :sweat_smile:
=> Fix UI panic and login errors on mintty/Windows

lib/executor/constant_vus_test.go, lib/executor/per_vu_iterations.go, lib/executor/per_vu_iterations_test.go, lib/executor/ramping_arrival_rate_test.go
this also fixes a  (very unlikely to be noticed issue) in per-vu-iterations where some/all `droppedIterations` metrics might not be emitted in time:
for release notes, under bugs:
```
fix unlikely case where droppedIterations won't be emitted by per-vu-iterations on time
```
=> Flaky test fixes

lib/executor/constant_arrival_rate_test.go, lib/executor/ramping_arrival_rate_test.go, lib/executor/vu_handle_test.go
One more batch of changes for #1357
=> Flaky test fixes part2

lib/executor/ramping_vus.go
This should take care of the problem mentioned in https://github.com/loadimpact/k6/issues/1499#issuecomment-658698763, though that whole issue isn't solved, there are still things we can optimize in the `ramping-vus` executor.
I'm still testing this, and might even add a few more unit tests, but for now this ugly chunk of debug code is helpful in allowing me to visually spot any issues with funky configurations that will take me a ton of time to convert to proper unit tests:
```diff
diff --git a/lib/executor/ramping_vus.go b/lib/executor/ramping_vus.go
index 22d58a5f..09c409a3 100644
--- a/lib/executor/ramping_vus.go
+++ b/lib/executor/ramping_vus.go
@@ -23,6 +23,7 @@ package executor
import (
"context"
"fmt"
+	"strings"
"sync"
"sync/atomic"
"time"
@@ -550,6 +551,76 @@ type RampingVUs …
```
=> Optimize gracefulRampDown calculations

stats/csv/collector.go, stats/csv/collector_test.go
Fixes: #1550
Refactor:
- Add closeFn for CSV collector
- Made writeToFile protected
Tested this by using the following script
test.js
```
import { sleep } from 'k6';
http.get('http://test.k6.io');
sleep(1);
}
```
and running
```
./k6 run --out csv=test.csv.gz test.js
```
=> Add support for gzip in csv output format

cmd/ui.go
In some CI environments like Codefresh, k6 detects that it's running in a TTY, the err returned by `terminal.GetSize()` is `nil`, yet `termWidth` is 0. Strange scenario, and we should fix our TTY check if possible, but it shouldn't panic with `divide by zero` anymore.
Closes #1579
=> Fix panic after getting terminal width in some CI environments

js/bundle_test.go, js/common/bridge_test.go, js/initcontext_test.go, js/modules/k6/crypto/crypto_test.go, js/modules/k6/crypto/x509/x509_test.go, js/modules/k6/http/response_test.go, js/modules/k6/k6_test.go, js/runner_test.go
No functional changes, this is just changing the test so if/when we update to the goja's es6 branch we get fewer test failures
=> Rewrite js test to not fail with the goja es6 branch

lib/netext/httpext/request.go
Unfortunately the code slows down by a couple percent if I use
temp variables ... for some reason
name  old time/op    new time/op    delta
C-8     27.9ns ±11%    22.6ns ± 8%  -19.12%  (p=0.000 n=10+9)
name  old alloc/op   new alloc/op   delta
C-8      32.0B ± 0%     32.0B ± 0%     ~     (all equal)
name  old allocs/op  new allocs/op  delta
C-8       1.00 ± 0%      1.00 ± 0%     ~     (all equal)
=> Slightly optimized Url.Clean

.circleci/config.yml
After the Go modules switch, the golangci-lint job in CircleCI [started failing](https://app.circleci.com/pipelines/github/loadimpact/k6/597/workflows/af28bcf6-e3fd-4e28-ab1f-c979bc4f662d/jobs/12303) with `go: cannot use path@version syntax in GOPATH mode`.
Removing `GOPATH` from the job's env vars and forcing `GO111MODULE=on` fixes it. This also adds `git-merge-base` to determine the base commit to lint from, which should be more reliable than before, and upgrades golangci-lint to the latest version, which resolves some warnings.
=> Fix golangci-lint in CircleCI

api/v1/setup_teardown_routes_test.go, cmd/archive.go, cmd/cloud.go, cmd/inspect.go, cmd/run.go, cmd/runtime_options_test.go, converter/har/converter_test.go, core/engine_test.go, core/local/local_test.go, js/bundle.go, js/bundle_test.go, js/common/util.go, js/common/util_test.go, js/compiler/compiler.go, js/compiler/compiler_test.go, js/console.go, js/console_test.go, js/empty_iteartions_bench_test.go, js/http_bench_test.go, js/initcontext.go, js/initcontext_test.go, js/module_loading_test.go, js/modules/k6/http/http_test.go, js/modules/k6/http/request_test.go, js/modules/k6/marshalling_test.go, js/runner.go, js/runner_test.go, lib/state.go, lib/testutils/test_output.go
This isn't a functional change but it makes certain that all parts of
the js package that aren't for test use provided logger instead of the
global one.
Unfortunately changing to logrus.FieldLogger in lib.State turned out
to require rewriting way too many tests and as it really isn't required,
=> Thread a logrus.Logger through the js package

js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go
The issue is connected to https://github.com/dop251/goja/pull/190 in the
sense that instead of the float to int conversation to result in either
error or a clamped float value, it results in a 0 int value which panics
the stdlib time package.
Changing the parameter for the timeout/interval to float both makes it
possible to take values such as 0.5, meaning half a ms, and also checks
if the value is positive so we can be certain that it won't panic k6.
If not this results in an exception in the script.
=> Fix ws.Set(Timeout/Interval) panicking on float values

js/runner_test.go, lib/netext/dialer.go, lib/netext/dialer_test.go, lib/options.go, lib/options_test.go, lib/testutils/httpmultibin/httpmultibin.go
This is an extension for the host mapping feature. It allows people to map to a different port than the one in the original url.
This is very convenient when you run k6 against a fleet of docker
containers to test the same service but want to keep the port mapping.
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> feature: Add optional port to host mappings.

stats/system_tag.go, stats/system_tag_test.go
Also, sort the keys before marshaling them with SystemTagSet for
consistent output.
fixes #1602
=> Add (Un)Marshal functions to stats.TagSet

lib/options.go, lib/options_test.go
=> bug/1560 tlsCipherSuites and tlsVersion marshaling

.gitignore, js/modules/k6/http/request_test.go, lib/netext/httpext/request.go, lib/netext/httpext/transport.go
Closes #1474
The root cause was reusing the same 'name' tag for all requests processed by a transport. In the case of redirects and digest auth the transport would process more than one request and needs to update the 'name' tag in the same way as 'url' is. For the initial request we need the originally parsed one to be consistent with the credential masking feature (as this gets stripped in the request passed to `RoundTrip()`), and tags for subsequent requests will be dynamically generated.
I'm not sure if this confirms @MStoykov's gut feeling that it will break aggregation somehow, but I'd argue this is the correct approach so we'll have to deal with it. :smile:
I didn't add more tests for this as the current ones are quite thorough.
=> Fix wrong name tag for HTTP metrics from redirects

cmd/config_consolidation_test.go, lib/options.go
this also doesn't write down the default values in the metadata.json
unless they were set specifically.
=> Marshal/Unmarshal DNS settings in a more consistan way

js/modules/k6/http/request_test.go, lib/netext/httpext/request.go, lib/netext/httpext/request_test.go, lib/netext/httpext/transport.go
This fixes an issue introduced in #1570 where metrics for failed requests were being sent with missing `url`, `method` and `name` tags, causing requests to show up with "0" tags in the cloud.
=> Fix sending empty metric tags for failed requests

appveyor.yml, lib/consts/consts.go, release notes/v0.28.0.md
Hopefully I haven't missed anything. And, of course, this is contingent on https://github.com/loadimpact/k6/pull/1612 getting merged... :sweat_smile: 
For easier reading of the release notes: https://github.com/loadimpact/k6/blob/release-v0.28.0/release%20notes/v0.28.0.md
=> Release k6 v0.28.0

lib/netext/httpext/request.go, lib/netext/httpext/request_test.go, lib/netext/httpext/response.go
=> Add StatusText field

cmd/options.go, js/runner.go, lib/options.go, lib/options_test.go, lib/types/ipblock.go, lib/types/ipblock_test.go
=> Add multi source IP support

cmd/cloud.go
=> Don't exit on 'k6 cloud -q' just don't print progress

cmd/cloud.go
Trap signal and handle second sig-c to shutdown `k6 cloud` immediately
Closes #1530
=> Immediately  shutdown `k6 cloud`  on second sig-c signal

cmd/cloud.go
Also:
- move the signal handling as far up as possible
- stop the test in goroutine so if that takes a while a second ^C will
again stop the test
=> wait for cloud to actually stop the test on first '^C'

go.mod, go.sum, vendor/github.com/dop251/goja/ast/node.go, vendor/github.com/dop251/goja/compiler.go, vendor/github.com/dop251/goja/compiler_expr.go, vendor/github.com/dop251/goja/compiler_stmt.go, vendor/github.com/dop251/goja/parser/expression.go, vendor/modules.txt
=> Upgrade goja

js/bundle.go, js/common/context.go, js/common/context_test.go, js/common/initenv.go, js/initcontext.go, js/modules/k6/grpc/client.go, js/modules/k6/grpc/client_test.go, js/modules/k6/grpc/grpc.go, js/modules/k6/http/request_test.go, js/runner_test.go, samples/grpc.js
This should fix https://github.com/loadimpact/k6/issues/1696 (it's WIP since I want to write a few more tests).
I think I've managed to get away with very little refactoring for v0.29.0, so hopefully not introducing any bugs... :crossed_fingers: 
I'm also hopeful that the new `InitEnvironment` concept is a viable way to refactor the `InitContext` and `BaseInitContext` and get rid of some of the complexity and code smells (`ctxPtr` :vomiting_face:) there in future k6 releases. In principle, we should be able to extend the `InitEnvironment` struct so that there is nothing special about the built-in k6 functions like `open()` and even `require()`, i.e. refactor them so they use `GetInitEnv()` as well.
@rogchap, can you please also review this PR and test it, to see if it works for your …
=> Rename gRPC module to k6/net/grpc and track and bundle loaded protobuf files

js/init_and_modules_test.go, js/modules/k6/grpc/client.go, js/modules/k6/grpc/client_test.go, js/modules/k6/http/request_test.go, js/runner_test.go, samples/grpc.js
This adds a bunch of tests and changes one details in the gRPC JS API: instead of `grpc.newClient()`, we now have the more JS idiomatic `new grpc.Client()`.
cc @rogchap
=> gRPC and test fixes

.github/workflows/all.yml, README.md, lib/consts/consts.go, release notes/v0.29.0.md
For easier reading of the rendered release notes: https://github.com/loadimpact/k6/blob/release-v0.29.0/release%20notes/v0.29.0.md
=> Release k6 v0.29.0

lib/types/hostnametrie.go, lib/types/hostnametrie_test.go
This should close https://github.com/loadimpact/k6/issues/1721 (cc @curvedriver). There were 2 separate bugs... :disappointed: Wildcards didn't catch 0-length matches, and when you blocked both a `domain` and a `sub.domain`, the `HostnameTrie` stopped blocking the `domain` because the `len(t.children) == 0` check was no longer true (wrong assumption that you can't block both a top-level and a sub-domain). This script more succinctly demonstrates the issue, running it with k6 0.29.0 will fail all checks, whereas with this PR they all pass:
```js
import { check, group } from "k6";
blockHostnames: ['*httpbin.org', 'test.k6.io', 'k6.io']
}
export default function getFromBlockedHostname() {
[
'https://httpbin.org/get?my_param=my_value', …
```
=> Fix hostname blocking

core/local/local_test.go, js/runner_test.go, lib/netext/httpext/tracer_test.go
These were flaky on AppVeyor, but seem to pass on GHA. I ran the full suite a few times in https://github.com/imiric/k6/actions/runs/359816051 without any failures, so it seems safe to leave them on, unless they embarass me and fail now... :)
There are still two that failed consistently and weren't enabled: `TestRequestAndBatch` and `TestTracer`. I'll look into refactoring them before closing #902, though that can also wait for another PR.
=> Enable some tests on Windows

.github/workflows/all.yml
Closes #1034
I tested this in my fork and you can download the signed MSI from [here](https://github.com/imiric/k6/actions/runs/385130865). As explained in [this comment](https://github.com/loadimpact/k6/issues/1034#issuecomment-734268724), I chose to not use any 3rd-party extensions to avoid any security issues. As noted there, this won't remove the "Windows protected your PC" warning, but should eventually if we reach a certain "trust" level with Microsoft, which is gained by a lot of people choosing to run the app anyway.
Two secrets were added to the GitHub repo for this: `WIN_SIGN_CERT` and `WIN_SIGN_PASS`. Information about both can be found in the password manager.
Note that currently this only signs the binary in the MSI package and the MSI itself that are uploaded to Bintray. The …
=> Sign Windows release binary and installer

cmd/common.go, cmd/config_consolidation_test.go, js/modules/k6/grpc/client.go, js/modules/k6/grpc/client_test.go, js/modules/k6/http/request.go, js/modules/k6/http/request_test.go, js/modules/k6/ws/ws.go, js/runner.go, lib/types/types.go, lib/types/types_test.go
This should close https://github.com/loadimpact/k6/issues/1305
=> Unify duration configuration values

js/modules/k6/http/request.go, js/modules/k6/http/request_test.go
=> Dont skip host header

ui/form.go
Sorry, I deleted the branch instead of update the PR and now is duplicated. Anyway thanks for the pointers before.
Closes #1703
=> Fix break line after password input (loadimpact#1703)

js/modules/k6/html/html.go, js/runner_test.go
Hi, 
first time contributing on this project (which I find lovely), so let me know if there is anything I can make to improve this PR.
Solves https://github.com/loadimpact/k6/issues/1487
=> Prevent panic when slicing end is higher than nodes array size

js/modules/k6/http/request.go, js/modules/k6/http/request_test.go
This is part of #1020, just for supporting `ArrayBuffer` request bodies. It works fine for submitting binary data from `open()`, e.g.:
```
var img = open('image.png', 'b');
exports.default = function() {
var arr = new Uint8Array(img);
http.post('http://127.0.0.1:9000/postbin', arr.buffer,
{ headers: { 'Content-Type': 'image/png' }});
}
```
It should probably have much more tests, but let me know what other scenarios we should cover. All the other typed arrays?
I wasn't able to get it to work with submitting the typed array itself instead of the `ArrayBuffer`, i.e. submitting `arr` instead of `arr.buffer` above (as mentioned [here](https://github.com/loadimpact/k6/issues/1020#issuecomment-727911302)). Goja's `Export()` on it returns an empty `map[string]interface{}{}`, so I couldn't get …
=> Add support for ArrayBuffer request bodies

js/bundle.go, js/common/initenv.go, js/console_test.go, js/initcontext.go, js/modules.go, js/modules/k6/data/data.go, js/modules/k6/data/share.go, js/share.go, js/share_test.go
This is part of #532
The reason behind this not redefing ... how to open a file or load data
from one is that, as in the majority of the cases after that there is
some amount of ... transformation of the data, so that won't help much.
The original idea was to have a shareable JSON ... but the more concrete
array implementation is faster (in some cases by a lot) and also seems
like a better fix for the first iteration of this, as that will be the
majority of the data type. So it is very likely that the non array parts
will be dropped in favor of doing them later and this getting merged
faster.
There are still more things to be done and depending on whether or not
we want to support iterating (with for-of) it can probably be done
without some of the js code.
=> shareable array implementation

Dockerfile
Inspired by [this question](https://stackoverflow.com/q/65678315/96213) and similar we've had on the forum.
This might break some use cases, but it's safer to have this set in the final image than not, and it can be easily overriden.
=> Set Docker workdir to a writeable path

api/server_test.go, api/v1/group_routes_test.go, api/v1/metric_routes_test.go, api/v1/setup_teardown_routes_test.go, api/v1/status_routes_test.go, cmd/config.go, cmd/run.go, cmd/runtime_options.go, cmd/runtime_options_test.go, core/engine.go, core/engine_test.go, js/bundle.go, js/bundle_test.go, js/runner_test.go, lib/models.go, lib/runtime_options.go, samples/custom_metrics.js, samples/grpc.js, stats/cloud/cloud_easyjson.go, stats/stats.go, ui/summary.go, ui/summary_test.go
This contains the prerequisite changes (and a few minor unrelated ones) for https://github.com/loadimpact/k6/pull/1768. I've taken the [extraneous changes](https://www.youtube.com/watch?v=AbSehcT19u0) from that PR, split them apart in sensible commits, and added some more tests. Hopefully, the only thing that remains in https://github.com/loadimpact/k6/pull/1768 would be the actual `handleSummary()` changes, though I may have a few other minor commits to make here before I push the final version of the other PR (likely tomorrow).
=> Misc fixes for summary callback changes

cmd/run.go, cmd/run_test.go, js/summary.go, stats/stats.go
There were a few other things I wondered if I should fix in the current Go summary code, but at this point in time I'll probably just fix them in the upcoming JS replacement... For example, this code: https://github.com/loadimpact/k6/blob/c00a85bfea21d748f0f9d11fdbc326087f34c411/ui/summary.go#L91 
Should be
```go
if !inEscSeq && !inLongEscSeq {
n++
}
```
i.e. that `StrWidth()` function is completely broken... :man_facepalming: But this turns not to matter one bit, since almost all of the errors are by the same margin and mostly cancel out... :rofl: Not to mention that the Unicode normalization it tries to do might actually be worse than not doing anything at all: https://github.com/loadimpact/k6/blob/c00a85bfea21d748f0f9d11fdbc326087f34c411/ui/summary.go#L64-L65
See [this MDN …
=> Cleanup and handleSummaryResult() tests

.github/workflows/all.yml, build-release.sh
Closes #1750 
This restructures the GitHub Actions CI workflow to upload the signed MSI package to the GH release, and also fixes the checksum file generation (it no longer includes itself, d'oh!) and the `brew bump-formula-pr` command (🤞 ). Though this `brew` change is untested, I just confirmed that the command is correct.
You can see a test release [here](https://github.com/imiric/k6/releases/tag/v0.30.0-test2).
=> Restructure CI workflow + fixes

README.md, lib/consts/consts.go, release notes/v0.30.0.md
Reviewing the release notes probably is easiest by looking at them rendered: https://github.com/loadimpact/k6/blob/release-v0.30.0/release%20notes/v0.30.0.md
The current planned release date for v0.30.0 is tomorrow. Before that, I plan to make the jslib PR with the v0.0.1 JS summary functions, and hopefully also at least a WIP docs PR (help appreciated here)...
=> Release k6 v0.30.0

.github/workflows/all.yml
So that we don't forget for next release, although as we've seen from manual runs, it might break in other ways... 🤞
=> Maybe fix brew bump-formula-pr command

Dockerfile
practically LGTM
```
➜  k6 git:(bump-alpine-to-3-13) docker run -it --entrypoint=sh alpine-3-31
~ $ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.0
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
~ $ k6
/\      |‾‾| /‾‾/   /‾‾/
/\  /  \     |  |/  /   /  /
/  \/    \    |     (   /   ‾‾\
/          \   |  |\  \ |  (‾)  |
/ __________ \  |__| \__\ \_____/ .io
Usage:
k6 [command]
Available Commands:
archive     Create an archive
cloud       Run a test on the cloud
convert     Convert a HAR file to a k6 script
help        Help about any command
inspect     Inspect a script or archive
login       Authenticate with a service
pause       Pause a running test
resume      Resume a paused test
run         Start …
```
=> bump alpine to 3.13

js/common/util.go, js/common/util_test.go, js/initcontext.go, js/initcontext_test.go, js/modules/k6/crypto/crypto.go, js/modules/k6/crypto/crypto_test.go, js/modules/k6/encoding/encoding.go, js/modules/k6/encoding/encoding_test.go, js/modules/k6/http/file.go, js/modules/k6/http/file_test.go
This addresses the backwards compatible changes of #1020, and showcases a workaround for better handling of multipart requests (ref. #747, #843, #1571).
=> Expand ArrayBuffer support

js/common/bridge_test.go, js/common/util.go, js/console_test.go, js/modules/k6/crypto/crypto_test.go, js/modules/k6/crypto/x509/x509_test.go, js/modules/k6/data/share_test.go, js/modules/k6/encoding/encoding_test.go, js/modules/k6/grpc/client_test.go, js/modules/k6/html/element_test.go, js/modules/k6/html/elements_gen_test.go, js/modules/k6/html/elements_test.go, js/modules/k6/html/html_test.go, js/modules/k6/html/serialize_test.go, js/modules/k6/http/request_test.go, js/modules/k6/http/response_test.go, js/modules/k6/http/tls_test.go, js/modules/k6/k6_test.go, js/modules/k6/metrics/metrics_test.go, js/modules/k6/ws/ws_test.go
I used github.com/rsc/rf with
```
ex {
import "github.com/loadimpact/k6/js/common"
import "github.com/dop251/goja"
var rt *goja.Runtime
var s string
common.RunString(rt, s) -> rt.RunString(s)
}
```
to make it, which worked for all packages but `js` itself but that was
quick by hand.
This change has 0 practical changes apart from the fact that it doesn't
use a useless utility function. The utility function in the past was
doing stuff but that was changed in 923f8867 , but I didn't actually
drop the no longer needed utility function at the time, either because I
didn't realize it's not needed or under a time constraint.
The additional changes in k6_test.go and metrics_test.go are because of
golangci-lint and gofumpt.
=> Drop js.common.RunString as it is just goja.Runtime.RunString

js/bundle.go, js/bundle_test.go
this is only being added to the "extented" compatibility-mode as it was
being provided by core-js before it was dropped.
=> Add `global` as in nodejs for backwards compatibility

js/modules/k6/data/data.go, js/modules/k6/data/share.go, js/modules/k6/data/share_test.go
This should make it considerably faster, but probably more importantly, a
lot easier to reason about and also supporting all operations supported
by a normal Array in JavaScript.
From my quick testing it seems that now the difference even for 10
elements is within 5% CPU difference, which IMO is even within the
margin of error.
fixes #1820
=> Rewrite SharedArray to use goja.DynamicArray

stats/cloud/collector.go, stats/cloud/collector_test.go
This fixes https://github.com/loadimpact/k6/issues/923 and was originally part of https://github.com/loadimpact/k6/pull/1869, but it makes more sense as a separate PR, so I split it apart.
=> Require cloud scripts to always have a name

core/engine.go, core/local/local_test.go, js/internal/modules/modules.go, js/modules/k6/http/file_test.go, js/modules/k6/http/http.go, js/modules/k6/http/http_test.go, js/modules/k6/http/request.go, js/modules/k6/http/request_test.go, js/modules/k6/http/response.go, js/modules/k6/http/response_callback.go, js/modules/k6/http/response_callback_test.go, js/modules/k6/http/response_test.go, js/runner.go, lib/metrics/metrics.go, lib/netext/httpext/request.go, lib/netext/httpext/tracer.go, lib/netext/httpext/transport.go, lib/netext/httpext/transport_test.go, stats/cloud/bench_test.go, stats/cloud/cloud_easyjson.go, stats/cloud/data.go, stats/cloud/data_test.go, stats/system_tag.go, stats/system_tag_set_gen.go, stats/units.go
This is done through running a callback on every request before emitting
the metrics. Currently only a built-in metric looking at good statuses
is possible, but a possibility for future JS based callbacks is left
open.
The implementation specifically makes it hard to figure out anything
about the returned callback from JS and tries not to change any other
code so it makes it easier for future implementation, but instead tries
to do the bare minimum without imposing any limitations on the future
work.
Additionally because it turned out to be easy, setting the callback to
null will make the http library to neither tag requests as passed nor
emit the new `http_req_failed` metric, essentially giving users a way to
go back to the previous behaviour.
The cloud output is also not changed as the …
=> Add a way to mark http requests as failed or not(passed)

.github/workflows/xk6-tests/xk6-js-test/go.mod, .github/workflows/xk6-tests/xk6-js-test/jstest.go, .github/workflows/xk6-tests/xk6-output-test/go.mod, .github/workflows/xk6-tests/xk6-output-test/outputtest.go, .github/workflows/xk6-tests/xk6-test.js, .github/workflows/xk6.yml, output/cloud/output_test.go, output/json/json.go
This should close https://github.com/loadimpact/k6/issues/1873 and adds the missing test from https://github.com/loadimpact/k6/pull/1882. This can also be considered a somewhat tentative first step in https://github.com/loadimpact/k6/issues/342
=> More tests

core/engine.go
There was a race between these two branches of the `select`: https://github.com/loadimpact/k6/blob/f1413e601b021d19f06d4d72ee14714a46344162/core/engine.go#L330-L339
I didn't add a test, since apparently the xk6 one I added in https://github.com/loadimpact/k6/pull/1885 already covers it - yay for integration tests... :tada:  :sweat_smile: This should close https://github.com/loadimpact/k6/issues/1887
=> Fix metrics data race in the Engine test run finalization

.github/workflows/xk6.yml
As suggested [here](https://github.com/k6io/xk6/issues/9#issuecomment-791464324).
=> Run CI xk6 test also with Go 1.16

docker-compose.yml
Reported in https://github.com/loadimpact/k6/issues/1883, this fix should suffice until we get around to https://github.com/loadimpact/k6/issues/1730 and/or https://github.com/loadimpact/k6/issues/1614
=> Pin InfluxDB version to 1.8 until we add support for 2.0

output/json/json.go, output/json/json_test.go
Added the ability to set and flush the thresholds implementing the WithThresholds interface as required from the Engine.
The SetThresholds implementation is the same as the cloud version. If you like the idea, I could also refactor out it to centralize the logic.
Closes #1052
=> output/json: Set and flush thresholds

js/bundle_test.go, js/modules/k6/http/http.go, lib/netext/tls.go, lib/options_test.go, lib/tlsconfig.go
SSLv3 has been removed from the supported version list of the crypto protocols.
Closes #1083
=> Drop the SSLv3 support

output/cloud/bench_test.go, output/cloud/metrics_client.go, output/cloud/output.go, output/cloud/output_test.go
Continuation of https://github.com/loadimpact/k6/pull/1857 and https://github.com/loadimpact/k6/pull/1874
=> Split the cloud output so metric pushing is separate

.github/workflows/all.yml
This PR is linked to #1622 issue and implements Github package publishing in the new workflow.
As described in [Github Docs](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images) Github Packages will be replaced with Github Container Registry, so I have used it.
In order to launch pipelines correctly CR_PAT secret must be created and it contains a Personal Access Token with `write;packages` scope.
More details can be found on this [link](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry).
I have created tasks similar to Docker …
=> GitHub container registry

README.md
Some of these changes were part of #1935  but are only related to the move of the repo, not the actual go modules rename.
Also include some droppings of mentioning Load Impact which is overdue by a little bit :)
=> Update readme after rename

lib/executor/executors_test.go, lib/executor/ramping_vus.go, lib/executor/ramping_vus_test.go
Previously, this script would have run without an error, though also without actually doing anything :sweat_smile: 
```js
vus: 0,
stages: [
{ duration: '12s', target: 0 },
],
};
http.get('https://test.k6.io')
}
```
Now users will see a nice validation error like this:
```
ERRO[0000] There were problems with the specified script configuration:
- scenario default has configuration errors: either startVUs or one of the stages' target value should be greater than 0 
```
=> Improve the validation of ramping-vus executor's options

.github/workflows/all.yml, .golangci.yml
Might be a good idea to go through the complete list of current linter issues and try to prune certain classes of the most common errors we have. For example, disabling certain linters in tests, or in go-generated files, `gofumpt`-ing the whole codebase, etc.
=> Update golangci-lint to v1.39.0

core/engine_test.go, lib/execution.go, lib/executor/constant_arrival_rate.go, lib/executor/constant_vus.go, lib/executor/per_vu_iterations.go, lib/executor/ramping_arrival_rate.go, lib/executor/shared_iterations.go
Closes https://github.com/k6io/k6/issues/1954 and fixes https://github.com/k6io/k6/issues/1657
=> Fix a data race and double-counting of active VUs in arrival-rate executors

.github/workflows/packager.yml
Setting VERSION for the build step makes things difficult for pushing, so build `latest` locally and tag it for pushing only.
This should fix https://github.com/k6io/k6/runs/2322019274.
=> Build latest k6packager, fix image tagging

lib/netext/httpext/request_test.go, lib/netext/httpext/transport.go
There is still situation where it is possible k6 will get status code
and then while it is reading the rest of the response an error will
occur - timeout reading the body, bad compression, etc. All of those
cases emit status code `0` and return status code `0` to the js script.
But responseCallback was getting the status code directly from the
response which meant that you can have an emitted metric with tag
`status` and `expected_response` where the two don't make sense as the
`status` is `0` but the `expected_response` was calculated based on a
different value.
While it might be more logical to return the status and the error in
this case intact this has been the case for nearly 3 years and given the
way the current js HTTP API is used this will likely just lead to very
confused users …
=> Call responseCallback with the emitted status code

cloudapi/config.go, cloudapi/config_test.go, core/engine.go, output/cloud/output.go, output/cloud/output_test.go, output/types.go
This does add an interface that can be implemented by other outputs as well.
fixes #1880
TODOs:
Related to the last point,  I decided to have an error be "returned" not just to call some function is so that we can *always* print it in some good known format instead of it being a responsibility of the output.
=> Make possible for the cloud output to stop the engine

.github/workflows/all.yml
After the [recent breach](https://about.codecov.io/security-update/) this seems like the least we should do for now.
=> Pin Codecov bash uploader version and check its hash

.github/workflows/all.yml, .github/workflows/packager.yml, packaging/Dockerfile, packaging/bin/create-deb-repo.sh, packaging/bin/create-msi-repo.sh, packaging/bin/create-rpm-repo.sh, packaging/bin/entrypoint.sh, packaging/docker-compose.yml, packaging/k6-rpm-repo.spec, packaging/k6-rpm.repo
These are a few changes I did while copying packages from Bintray to https://dl.k6.io/. The biggest one is the switch back to `s3cmd` for S3 operations since [aws-cli doesn't preserve timestamps when syncing with S3](https://github.com/aws/aws-cli/issues/3069#issuecomment-818732309), and s3cmd does this nicely with object metadata. It also has better mimetype detection and checks file equality with MD5 hashes instead of relying on file size or `mtime`. So now we use aws-cli only for CloudFront invalidation and s3cmd for everything else.
I'll leave the original WIP branch (`ci/populate-dl-k6-io`) unmerged, since it has the script to download from Bintray and some additional tweaks, in case we need it again soon, and we can delete it in a few weeks.
=> Package repository tweaks

cmd/run.go, core/engine_test.go, js/bundle.go, js/bundle_test.go, js/initcontext_test.go, js/runner.go, js/runner_test.go, lib/executor/helpers.go, lib/types/types.go
also exit with error code 107 for both cases.
fixes #994
=> Print stacktrace on exception in init context or setup/teardown

packaging/k6-rpm-repo.spec, packaging/k6-rpm.repo
After some investigation, we decided to disable this explicitly to avoid it failing for users who have `repo_gpgcheck` enabled globally.
Our RPM packages are signed, but we're not planning to sign repo metadata since enabling this check is known to [cause](https://bugzilla.redhat.com/show_bug.cgi?id=1768206) [issues](https://bugzilla.redhat.com/show_bug.cgi?id=1636743) and it's not enabled even for main Fedora repositories.
=> Explicitly disable GPG check for RPM repo metadata

README.md
Maybe we shouldn't have used a link with a fragment, but this was recently changed in the docs, so just to update it here.
=> Fix Fedora link in installation instructions in README

js/modules/k6/data/data.go, js/modules/k6/data/share_test.go
previous to this the code (which I have no idea why I added the
function, it probably was moved into a separate function later) would
*not* unlock the lock if 2 writes raced on Write lock after as the
second writer would see that it was already written but not enter the
if to defer the unlock.
=> Do actually unlock SharedArray if write raced

core/engine.go
Previous to this it would've been aborted by system
=> Set cloud status to aborted by script on setup/teardown script errors

js/common/util.go, js/common/util_test.go, js/initcontext.go, js/initcontext_test.go, js/modules/k6/crypto/crypto.go, js/modules/k6/crypto/crypto_test.go, js/modules/k6/encoding/encoding.go, js/modules/k6/encoding/encoding_test.go, js/modules/k6/http/request.go, js/modules/k6/http/request_test.go, js/modules/k6/http/response.go, js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go, lib/netext/httpext/batch.go, lib/netext/httpext/compression.go, lib/netext/httpext/response.go
These are the leftover changes to close #1020. Most of them break backwards compatibility, as discussed in the issue.
It might be easier to review by commit.
=> More ArrayBuffer support

output/json/json.go, output/json/json_test.go, stats/thresholds.go, stats/thresholds_test.go
This fixes an encoding issue for thresholds that are marshalled to JSON, recently added to the JSON output in #1886.
[`json.Marshal()`](https://golang.org/pkg/encoding/json/#Marshal) escapes HTML-sensitive characters by default, so `<` is converted to `\u003c`, `>` to `\u003e`, etc.
We missed it in our tests since they also relied on this behavior which obscures the wrong encoding, but you can see it if you checkout af1e032e and run `go run main.go run -o json=- ./samples/thresholds.js`. The `http_req_duration` metric will be rendered as:
```
{"type":"Metric","data":{"name":"http_req_duration","type":"trend","contains":"time","tainted":null,"thresholds":["p(95)\u003c500"],"submetrics":null,"sub":{"name":"","parent":"","suffix":"","tags":null}},"metric":"http_req_duration"}
```
Whereas on …
=> Fix threshold encoding when marshalling to JSON

stats/thresholds.go
This avoids a potential `slice bounds out of range` panic.
=> Safer newline stripping when marshalling to JSON

.github/workflows/all.yml
Previously this would've been embedded in *all* binaries as go didn't
know that it shouldn't. This looks to have had no impact, but with the
addition of macos + arm64 binaries we found it as that platform doesn't
support embedding of the specific generate file.
=> Make the windows version info only for windows

cmd/root.go, output/statsd/output.go
This addresses https://github.com/k6io/k6/issues/2004 
Per the issue, I'm happy to discuss and implement longer term solutions for log flags but I figured this is a fast and non-controversial solution.
=> Fix log message in statsd output

core/local/local_test.go, js/modules/k6/http/request_test.go, lib/netext/httpext/error_codes.go
This is a follow up  to https://github.com/k6io/k6/pull/2008 - addresses comment on consistent capitalization
=> Make request timeout error message lowercase for consistency 

lib/netext/httpext/error_codes.go, lib/netext/httpext/error_codes_test.go, lib/netext/httpext/request.go, lib/netext/httpext/request_test.go, lib/netext/httpext/tracer_test.go, lib/netext/httpext/transport.go, lib/testutils/httpmultibin/httpmultibin.go
It seems http2, x509 and tls errors are not pointer errors, after all.
I mostly found this through the fact that even after the last patches it
still didn't match them, but now there are finally tests for all of
them, so hopefully this will be a permanent fix.
=> Fix error codes for http2, x509 and tls errors 

lib/executor/common_test.go, lib/executor/ramping_arrival_rate.go, lib/executor/ramping_arrival_rate_test.go
Switched the `ramping-arrival-rate` from goroutine per iteration to goroutine per VU.
Refactor the Run method is not part of this PR, it is scheduled for the original issue, so I tried to impact in a minimal way the code.
However, the main issue in terms of performance was already resolved from #1955 as the following tests should assert:
using this config:
```
exports.options = {
scenarios: {
test1: {
executor: 'ramping-arrival-rate',
preAllocatedVUs: 1000,
stages:[
{target:100000, duration:'0s'},
{target:100000, duration:'15s'},
],
},
},
};
exports.default =  function () {}
```
result with v0.31.1 still affected by the problem:
```
$ docker run -v $PWD:/home/k6 -i loadimpact/k6:0.31.1 run - <script.js
iterations...........: 200591 13368.444337/s
```
and the result with master
```
$ …
```
=> ramping-arrival-rate: Avoid to spawn a new goroutine for every iteration

js/modules/k6/http/request_test.go, js/modules/k6/http/response.go
This panic was still caught and didn't abort the whole k6 just the
current iteration.
=> Don't panic on binaryResponses where the body wasn't set

js/common/bridge_test.go, js/common/util.go, js/common/util_test.go, js/initcontext_test.go, js/modules/k6/crypto/crypto_test.go, js/modules/k6/crypto/x509/x509_test.go, js/modules/k6/http/file_test.go, js/modules/k6/http/response_test.go, js/modules/k6/k6_test.go, js/modules/k6/metrics/metrics_test.go
This avoids outputting "GoError" as mentioned in https://github.com/loadimpact/k6/issues/877#issuecomment-484396949 .
I split it off from #1769 to avoid the clutter in that PR.
=> Treat errors from Throw() as plain goja values

cmd/archive.go, cmd/cloud.go, cmd/common.go, cmd/config.go, cmd/config_test.go, cmd/root.go, cmd/run.go, core/engine.go, core/engine_test.go, core/local/local.go, errext/errext_test.go, errext/exception.go, errext/exit_code.go, errext/exitcodes/codes.go, errext/hint.go, js/runner.go, js/timeout_error.go, js/timeout_error_test.go, lib/executor/helpers.go, lib/types/types.go
This PR does a few things:
- refactors (and I think simplifies) a bunch of error handling and exit code determination
- fixes the bug of k6 returning an exit code of `103` for script errors in `VU>0` initialization, while preserving the helpful hints
- (breaking change) changes one `k6 cloud` exit code from 99 to 97, to make it distinct from the already existing `99` exit code for `k6 run` (the k6 cloud code doesn't always mean that the thresholds have failed)
=> Error refactoring and exit code fixes

js/modules/k6/http/request.go, js/modules/k6/http/request_test.go
This is a continuation of #1754, with an added check for the correct encoding and disabling of the `exhaustive` linter, since it doesn't seem like we can avoid the reflection.
Closes #1713
=> Fix array encoding in form data requests

loader/loader.go, loader/readsource.go, loader/readsource_test.go
=> Return better message on missing file with spaces

lib/executor/base_executor.go
Calling these methods defined on a value receiver copies the BaseExecutor instance and could cause a data race if another goroutine is writing to it. In practice this wasn't a problem and unlikely anyone would ever run into it on `master`, but it did appear on the `feat/1320-execution-api` branch (#1863) when running:
```
go run -race main.go run --quiet -u 5 -i 5 'github.com/k6io/k6/samples/http_get.js'
```
Clipped stack trace:
```
WARNING: DATA RACE
Write at 0x00c00050d7a8 by main goroutine:
go.k6.io/k6/lib/executor.(*SharedIterations).Init()
/home/ivan/Projects/k6io/k6/lib/executor/shared_iterations.go:179 +0x384
go.k6.io/k6/core/local.(*ExecutionScheduler).Init()
/home/ivan/Projects/k6io/k6/core/local/local.go:276 +0xc1c
go.k6.io/k6/core.(*Engine).Init() …
```
=> Fix unlikely data race when calling BaseExecutor methods

js/modules/k6/metrics/metrics.go, js/modules/k6/metrics/metrics_test.go, samples/custom_metrics.js
The original change was proposed in https://github.com/k6io/k6/issues/2053 and implemented in https://github.com/k6io/k6/pull/2058
=> Make `metric.getName()` into `metric.name`

.github/workflows/all.yml
We don't test with Go 1.15 at the moment because if using go:embed. The test-prev check is still here, but it is disabled and nothing depends on it. This will be the state until Go 1.17 is released and we can switch test-prev to 1.16. And even then, the build probably shouldn't depend on test-prev, its failure should be only informative, not aborting the whole CI.
=> Fix CI process to only depend on tests with latest stable Go

js/initcontext.go
=> Warn users on importing dependencies as absolute paths

lib/options.go, lib/options_test.go
Support JSON encoding for the `BlacklistIPs` option.
=> lib/options: BlacklistIPs json encoding/decoding

cloudapi/config.go, cloudapi/config_test.go, cmd/cloud.go, cmd/login_cloud.go, output/cloud/output.go
Previously after the usual consolidation of metrics where json config,
script options, cli, env order is followed the `ext.loadimpact` configs
(from within the script options) would take precedence over anything
else.
Now it has the same precedence as the script config.
This likely as always has additional sideeffects ... for example the
K6CLOUD_TOKEN to K6_CLOUD_TOKEN fix is being done after all of this
which should probably be dropped either way.
=> Fix cloud config merging

.github/workflows/all.yml, .github/workflows/packager.yml
This fixes the [recent `build-docker` failures on `master`](https://github.com/grafana/k6/runs/3174118226?check_suite_focus=true), as GitHub [has moved away from PATs](https://github.blog/changelog/2021-03-24-packages-container-registry-now-supports-github_token/) for authenticating with the Container Registry.
I confirmed this works by pushing from this branch and [the package was created](https://github.com/grafana/k6/pkgs/container/k6). Hopefully once it's pushed from `master` it will be the default tag. Otherwise we can delete it :)
I'll remove the `CR_PAT` secret when this is merged, since it's not used anywhere else.
=> Use GITHUB_TOKEN to login to GHCR

.github/workflows/xk6-tests/xk6-js-test/go.mod, .github/workflows/xk6-tests/xk6-output-test/go.mod, .github/workflows/xk6.yml
This is an attempt to fix the xk6 test failures we're seeing for external PRs:
- https://github.com/grafana/k6/pull/2103/checks?check_run_id=3228680151
- https://github.com/grafana/k6/pull/2104/checks?check_run_id=3228681771
```
go: downloading go.k6.io/k6 v0.33.0
go get: go.k6.io/k6@v0.33.0: verifying module: checksum mismatch
downloaded: h1:zBcinO3oMLQ+AWRBsVOBomLSueOK3tM8qwZIPjaMydk=
sum.golang.org: h1:NX/6hvAD6A780xg7STngX4ay8Le+V3rz7KOL2o5KzSk=
SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```
=> Fix xk6 test failures in CI

.github/workflows/packager.yml, packaging/docker-compose.yml
This fixes the [`permission_denied: The requested installation does not exist.` error](https://github.com/grafana/k6/runs/3271365155?check_suite_focus=true) we've seen when pushing the k6packager image to GHCR since the move to the grafana org.
=> Fix k6packager push to GHCR

stats/stats.go
i found unitMap is unused in stats/stats.go.
i guess this were forgotten to remove in [this commit](https://github.com/grafana/k6/commit/2810d834ed31108316567b9f96cf9089dfacd54d).
=> Remove unused code from stats/stats.go

cloudapi/api_test.go, cloudapi/logs.go, cloudapi/logs_test.go
It adds some capabilities to reconnect to our log tail service.
Some questions/notes:
* Re-generating `cloudapi` package the `_easyjson` file gets some changes
* Should we support the options from the json configuration? The already existing option doesn't so I replicated it.
* I added `gomock` as a dependency to support mocking some interfaces for unit testing. I find it generally very useful but we are not using it so I expect some cons with k6 that I'm not considering.
* The current abstraction is still tight with the current `gorilla/websocket`, if I'm in the right way with this PR, we could consider designing a better abstraction from the real streaming implementation.
* The current logic closes the connection before re-dial this generates to get some logs like this:
```
INFO[0064] …
```
=> cloudapi/logs: Keep connection reliable

core/local/k6execution_test.go, lib/executor/externally_controlled.go
Previously accessing some scenario state information using the externally-controlled executor would throw the error `getting scenario information in the init context is not supported`. This was because the context wasn't properly passed to the `externallyControlledRunState`.
The test added here checks access for all executors, which would've caught this initially.
=> Fix scenario information retrieval from externally-controlled executor

go.mod, go.sum, vendor/github.com/dop251/goja/compiler_expr.go, vendor/github.com/dop251/goja/date.go, vendor/github.com/dop251/goja/date_parser.go, vendor/github.com/dop251/goja/object_goslice.go, vendor/github.com/dop251/goja/object_goslice_reflect.go, vendor/modules.txt
=> Update goja to latest stable

cmd/config_consolidation_test.go, lib/options.go, lib/options_test.go
Very small fix :slightly_smiling_face:
=> Fix inconsistency in env variables names

.github/workflows/xk6.yml
+ `go get` is now only being used for adding dependencies to a Go module
+ this fix uses `go install` instead to install the xk6 binary (instead of `go get`)
=> Fix go get xk6 github action

.github/workflows/all.yml, .github/workflows/tc39.yml, Dockerfile, go.mod
=> Upgrade to Go 1.17

output/csv/config.go, output/csv/config_test.go, output/csv/output.go
This change adds support for camelCased versions of file_name and save_interval CSV output arguments,
writing a warning to the logs informing users the older snake cased argument will be deprecated in time.
=> Support camelCase CSV output argument for file_name and save_interval.

cloudapi/logs_test.go
I don't see a way for making the `RestoreConnFromLatestMessage` test more stable using `HTTPMultiBin`. Considering that we already skipped the option to mock the WebSocket connection during the original PR, I just raised the timeout hoping it would be enough for the CI.
=> cloudapi/logtail: Raise flush wait time for tests

.github/ISSUE_TEMPLATE/config.yml
It fixes https://github.com/grafana/k6/issues/2211
This PR adds a section in the `config.yaml` that would navigate to K6 Docs for any issue requests.
=> FEAT: Issue 2211 : Add Documentation Template as per new Github Issue

lib/fsext/changepathfs.go
Given that we won't be using this method I don't think we need to have
actual real implementation for it which will require us to update
aforo.Fs, so I just returned an error.
This is predominantly motivated by the fact that an extension having a
dependency on a newer afero.Fs ( through another dependency for example)
will not compile as the interface afero.Fs was extended in v1.5.0.
=> Make ChangePathFs compatible with new afero.Fs without updating

js/initcontext_test.go, js/modules/k6/execution/execution.go, js/modules/k6/execution/execution_test.go, js/modules/k6/grpc/client_test.go, js/modules/k6/http/request_test.go, js/modules/k6/http/response_test.go, js/modules/k6/k6.go, js/modules/k6/k6_test.go, js/modules/k6/metrics/metrics_test.go, js/modules/k6/ws/ws_test.go, js/runner.go, js/runner_test.go, lib/netext/httpext/request_test.go, lib/state.go, lib/state_test.go
Extended the `k6/execution` API to allow the get or set of a Tag in the VU's state.
This part of the [Stage tagging work](https://github.com/grafana/k6/issues/796), but it can be considered as an independent feature.
```js
import exec from 'k6/execution';
stages: [
{ duration: '1m', target: 10 },
{ duration: '1m', target: 20 },
{ duration: '1m', target: 0 },
],
};
exec.vu.tags['stage'] = 'stage#2'
console.log(exec.vu.tags['stage']) // returns stage#2
}
```
=> js/k6/exec: Set VU Tags

js/modules/k6/metrics/metrics.go
=> Limit the size of the warning from metrics' `Add()` methods

stats/system_tag.go
Removed the duplicated TagCheck from the default tag set.
=> Removed duplicated default TagCheck

js/modules/k6/k6_test.go
fix was done in 3a604bf4 (https://github.com/grafana/k6/pull/2235)
=> Add a test that the group reset the tag on exit

js/modules/k6/k6.go, js/modules/k6/k6_test.go
Migrated `k6` to the `modules.Module` (aka `modules.ModuleV2`) interface.
=> js/k6: ModuleV2 migration

js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go
`js/ws` module migration implementing the ModuleV2 API.
The `Connect` method requires some refactoring to remove the linter issues (too many statements and cyclomatic complexity). I tried to fix it directly here but from my exploration, it requires too many changes compared to this, so I would prefer to have a separated PR for refactoring instead unique one.
=> js/ws: modulev2 migration

js/modules/k6/data/data.go, js/modules/k6/data/share_test.go, js/share_test.go
Migrated `k6/data` to the `modules.Module` (aka `modules.ModuleV2`) interface.
=> js/data: ModuleV2 migration

js/modules/k6/encoding/encoding.go, js/modules/k6/encoding/encoding_test.go
Migrated `k6/encding` to the `modules.Module` (aka `modules.ModuleV2`) interface.
=> js/encoding: ModuleV2 migration

lib/executor/ramping_vus.go, lib/executor/ramping_vus_test.go
`RampingVUs.Run` method is complex and this PR aims to refactor it.
**Improvements:**
* Makes the `Run` method easier to read and understand.
* Makes it explicit which Goroutines are being fired in the `Run` method.
* Separates responsibilities to other parts like:
* `rampingVUsRunState` and its methods.
* Moves `trackProgress` Goroutine from the `makeProgressFn` to the `Run` method.
* Makes `populateVUHandles` to only handle initializing VU handles (_not firing up a GR_)
* Uses two strategy functions for code reusability and clarity (_`handleVUs` and `handleRemainingVUs` use them_).
* Makes the `handleVUs` algorithm easier to understand and manage.
* Adds a `handleRemainingVUs` test with explanations  to make newcomers' and new contributors' job easier
_Note: The other PR (#2124) is …
=> Refactor ramping VUs executor

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feat_req.yaml
The gh issues' templates are broken. The `title` field can't be empty so I'm removing it considering that we wouldn't have a fixed prefix for it. 
A preview is available at: https://github.com/grafana/k6/blob/2a1795644024adffb02c0a7c703c0ce1bc85a5a9/.github/ISSUE_TEMPLATE/bug.yaml
=> gh/templates: remove title field

js/console_test.go, js/initcontext_test.go, js/runner_test.go
The predominant reason was the use of context.Background() for a context, which leads to a goroutine waiting on it ending, to block indefinitely.
The other case were gRPC tests which did *not* close their connections.
=> Prevent goroutines getting blocked in js tests

go.mod, go.sum, vendor/github.com/Azure/go-ntlmssp/authenticate_message.go, vendor/github.com/Azure/go-ntlmssp/authheader.go, vendor/github.com/Azure/go-ntlmssp/negotiator.go, vendor/modules.txt
Hello,
A new version of go-ntlmssp has been released following a PR I did, to solve a bug.
The bug is : NTLM authentication doesn't work when two Authorization/WWW-Authenticate headers are returned by the back-end server.
With the new version of the go-ntlmssp package, the number of header doesn't matter, and the most accurate will be taken.
=> NTLM dependency package update to solve a duplicate headers bug upon NTLM authentication

lib/netext/httpext/request.go, lib/netext/httpext/response.go
A tiny PR making the `Request` attribute of `netext/httpext/Response` struct a pointer. This should avoid copies of said Request objects (as they can be rather big) to be made every time we instantiate a Response. This is in line with Go's standard library.
This is a tiny change, which, as far as I can tell, does not break tests. I've also verified that it does not break the JSON serialization of requests (pointers can be tricksters on that front). 
ref #1931
=> Make netext httpext Response's Request a pointer

.golangci.yml, js/modules/k6/html/element_test.go, js/modules/k6/html/elements_gen_test.go, js/modules/k6/html/elements_test.go, js/modules/k6/html/html.go, js/modules/k6/html/html_test.go, js/modules/k6/html/serialize_test.go, js/modules/k6/http/cookiejar.go, js/modules/k6/http/file.go, js/modules/k6/http/file_test.go, js/modules/k6/http/http.go, js/modules/k6/http/http_test.go, js/modules/k6/http/request.go, js/modules/k6/http/request_test.go, js/modules/k6/http/response.go, js/modules/k6/http/response_callback.go, js/modules/k6/http/response_callback_test.go, js/modules/k6/http/response_test.go, js/modules/k6/http/tls_test.go, js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go, js/modules/modules.go, lib/netext/httpext/batch.go, lib/netext/httpext/request.go, lib/netext/httpext/request_test.go, lib/netext/httpext/response.go, lib/state.go, samples/http_get.js
I thought I needed to refactor both `k6/html` and `k6/http` together, since the latter depends on the former, but turns out that wasn't quite the case and the panic was caused by something else... :sweat_smile: Still, it doesn't hurt and the `k6/html` changes are relatively minor...
I like how this looks like for now, and I'll probably make another PR after this to move some things out of the [`js.Runner.newVu()`](https://github.com/grafana/k6/blob/dae70006ca77767e456acafbdda284d064dbd882/js/runner.go#L149) and `lib.State` and into the `k6/http` module, for example:
- `TLSConfig`, `Transport` and `CookieJar` probably should go in the `Client` and be initialized in a constructor, which will use the global `lib.Options` as the default options for its initialization
- `BPool` can either be …
=> Refactor `k6/http` and `k6/html` to the new JS `Module` API

Dockerfile
=> Upgrade alpine base image to 3.15

go.mod, go.sum, vendor/github.com/dop251/goja/ast/node.go, vendor/github.com/dop251/goja/compiler.go, vendor/github.com/dop251/goja/compiler_expr.go, vendor/github.com/dop251/goja/compiler_stmt.go, vendor/github.com/dop251/goja/parser/expression.go, vendor/github.com/dop251/goja/parser/lexer.go, vendor/github.com/dop251/goja/parser/statement.go, vendor/github.com/dop251/goja/runtime.go, vendor/github.com/dop251/goja/token/token_const.go, vendor/github.com/dop251/goja/vm.go, vendor/modules.txt
It adds the support for:
* optional chaining
* error wrapping for interrupts
and fixes two issues with source maps
Commands executed:
```sh
$ go get github.com/dop251/goja@master
$ go mod tidy
$ go mod vendor
```
=> goja: bump version

cmd/archive.go, cmd/cloud.go, cmd/common.go, cmd/config.go, cmd/config_consolidation_test.go, cmd/inspect.go, cmd/root.go, cmd/run.go, js/runner.go
This PR adds additional output to `k6 inspect` with `--execution-requirements` CLI option. When switched on, it triggers calculation of execution requirements, substitutes config with the derived one and adds `maxVUs` and `totalDuration` fields to the output.
Signature of `getConsolidatedConfig` was modified: now it doesn't depend on `lib.Runner` but only on `lib.Options`.
Some minor refactoring in `cmd/` was added on the way, but not too much as that'd require additional work and likely a separate PR.
This is part of the work for implementing https://github.com/grafana/k6-operator/issues/9
=> Extend k6 inspect command with additional flag

js/bundle.go, js/initcontext.go, js/runner_test.go, lib/archive.go, lib/fsext/cacheonread.go, loader/readsource.go
Implementing a limitation for the open() that limits opening files
by the list of the files that were opened during the initialization
step (__VU == 0).
For example, a code like:
```js
if (__VU >0) {
JSON.parse(open("./arr.json"));
}
```
Should return an error.
Closes #1771
=> fix: Implementing a limitation for the open()

core/engine_test.go, stats/thresholds.go, stats/thresholds_parser.go, stats/thresholds_parser_test.go, stats/thresholds_test.go
This Pull Request addresses the minimum scope described in #1443 and replaces the current thresholds' expression evaluation implementation. It drops the reliance on the [Goja JS runtime](https://pkg.go.dev/github.com/dop251/goja#Runtime), in favor of a pure-go based implementation. With this PR, thresholds are parsed, and evaluated directly in Go, and all JS runtime-related threshold code has been dropped. It sticks to the existing format, and does not introduce any of the design and format changes proposed in #1443 and #1441.
Design notes regarding the PR's content:
- The introduction of a minimalistic parser combinators library, taken and adapted from [Jeffhail benthos' bloblang implementation](https://github.com/Jeffail/benthos/). The design choice of combinators was motivated by their …
=> Fix/1443 remove the JS runtime from threshold calculations

js/compiler/compiler.go
This prevents babel from using up a lot of memory (3.5x as much as
before source maps) on really big inputs.
=> Disable sourcemaps support in babel if input is big

loader/cdnjs_test.go, loader/github_test.go, loader/loader.go, loader/loader_test.go, loader/readsource_test.go
This removes 67 linter errors, does not (seem) to introduce any races in
the tests and it also seems to not improve their runtime as well :(
The changes were done with the idea of "as little change as possible" so
that there should be no bugs introduced.
=> Fix all linter errors in loader package

js/modules/k6/html/element.go, js/modules/k6/html/element_test.go, js/modules/k6/html/elements.go, js/modules/k6/html/elements_gen_test.go, js/modules/k6/html/elements_test.go, js/modules/k6/html/html_test.go, js/modules/k6/html/serialize_test.go
Fix some linter issues of the HTML package.
This PR is fixing ~340 linter issues.
```bash
golangci-lint run --print-issued-lines=false --out-format tab | sort | uniq | wc -l
1561
```
I'd like from time to time to fix existing linter issues.
=> HTML package linter fixes

go.mod, js/compiler/compiler.go, js/compiler/compiler_test.go
This should hopefully fix most of the cases where a source map that
is tried to be loaded but turns out to be gibberish doesn't stop the
whole execution of k6.
edit: this also fixes the error message about source map not being loaded, when goja also has other errors. Previous it would tell you stuff such as 
```
WARN[0000] Couldn't load source map for file:///home/mstoykov/work/k6io/k6/l.js  error="file:///home/mstoykov/work/k6io/k6/l.js: Line 1:1 Unexpected reserved word (and 1 more errors)"
```
when for example the source map wasn't loaded properly but also babel needs to be invoked in order to transpile import/export for example.
=> Try to load and parse the sourcemap before returning it

cmd/archive.go, cmd/cloud.go, cmd/common.go, cmd/config.go, cmd/config_consolidation_test.go, cmd/inspect.go, cmd/login_cloud.go, cmd/login_influxdb.go, cmd/outputs.go, cmd/pause.go, cmd/resume.go, cmd/root.go, cmd/run.go, cmd/run_test.go, cmd/scale.go, cmd/stats.go, cmd/status.go, cmd/ui.go, cmd/ui_test.go
edit: go commit by commit otherwise it's very hard to follow what happens IMO
edit2: I have optimized for *small* change so the code review can be done faster and also to not break anything. The final code is still pretty terrible for many ... many reasons, but fixing those is IMO outside the scope of this PR. 
edit3: this was split so that the smaller changes are now in #2357  and #2358. And this PR is based on #2358 as it kind of depends on it to run the tests in parallel
=> Cmd no globals

cmd/runtime_options_test.go
This is the first commit of #2353 which is part of me trying to make that PR smaller, easier to review and edit.
In this particular case we copy paste the global varible that is the table for the table driven test *in* the test + it's helper variables
=> Don't use global variables to initialize test cases

js/modules/k6/grpc/client.go, js/modules/k6/grpc/client_test.go
Closes #2244. I saw it during the module migration.
It includes:
* The refactoring of the parameters parsing part with a dedicated method.
* A warning for communicating about the `headers` deprecation
* The `metadata` support
=> js/grpc: Deprecated headers param

.github/workflows/all.yml, Makefile, README.md, docker-compose.yml
This PR updates CI to push to two DockerHub repositories at once: `loadimpact/k6` and `grafana/k6`, with accompanying small fixes.
Issue: https://github.com/grafana/k6-internal-docs/issues/155
=> DockerHub migration to Grafana org

js/modules/k6/crypto/crypto_test.go, js/modules/k6/crypto/x509/x509_test.go, js/modules/k6/data/share_test.go, js/modules/k6/encoding/encoding_test.go, js/modules/k6/execution/execution_test.go, js/modules/k6/k6_test.go, js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go
Something was missed from the module migration to the new `modules.Module` API, where the Runtime and the State are now directly accessible without getting them from the context.
This is required for #2344
=> js/modules: Remove common utils dependency

lib/executor/constant_arrival_rate_test.go
Temporary relax an assertion, while in the meantime we're preparing a proper solution
=> Relax assertion in TestConstantArrivalRateRunCorrectTiming

cmd/root.go, log/file.go, log/file_test.go, log/levels.go, log/levels_test.go, log/loki.go, log/tokenizer.go
Added file hook for logger.
Examples of usage:
```bash
k6 run --log-output file=./k6.log --logformat json ./examples/stages.js
```
With a defined log level:
```bash
k6 run --log-output file=./k6.log,level=info --logformat json ./examples/stages.js
```
Closes #2249
=> Added support for local files to `--log-output`

core/engine_test.go, core/local/local_test.go, js/bundle.go, js/initcontext_test.go, js/runner_test.go, lib/executor/common_test.go, lib/executor/constant_arrival_rate_test.go, lib/executor/constant_vus_test.go, lib/executor/externally_controlled_test.go, lib/executor/per_vu_iterations_test.go, lib/executor/ramping_arrival_rate_test.go, lib/executor/ramping_vus_test.go, lib/executor/shared_iterations_test.go, lib/executor/vu_handle_test.go, lib/testutils/minirunner/minirunner.go
Removed all not strictly required calls to the context-based utils functions. The `lib.GetState` required a refactor for the executors' tests and the relative used minirunner Fn.
This is expected to be the latest refactor PR before opening the PR for writing the deprecation comments.
=> Remove calls to context-based utils

api/common/context.go, js/common/bridge.go, js/common/context.go, js/initcontext.go, js/modules/modules.go, lib/context.go
Deprecating the context-based utils functions. They are anticipating the next step where we could remove all of them from the `k6` public API.
Closes https://github.com/grafana/k6/issues/2344
=> Deprecate context-based utils

.github/workflows/all.yml, .github/workflows/lint.yml
This was provoked as the new use of golangci-lint action fails on master
with all the lint errors there. But in reality it's probably not needed
to run those tasks on master - they are mostly about new code
=> CI: move deps and lint jobs only on pull requests

js/modules/k6/http/http.go, js/modules/k6/http/request_test.go, release notes/v0.36.0.md
This has been the case forever until v0.36.0.
=> Revert k6/http.head to not taking body as second argument

lib/options.go
With the current code, running this script:
```js
console.log(JSON.stringify(options, null, 4));
}
```
Will produce something like this:
```js
{
"scenarios,omitempty": {},
"summaryTrendStats": [ "avg", "min", "med", "max", "p(90)", "p(95)"],
"systemTags": ["check","error","error_code","expected_response","group","method","name","proto","scenario","service","status","subproto","tls_version","url"]
}
```
The actual issue is caused by the `lib.Options.ForEachSpecified()` hack: https://github.com/grafana/k6/blob/737dfa7ced6e4f94dbb3d6f2c2837085e783ac09/js/bundle.go#L290
where it doesn't actually properly parse the `json` struct tag and returns its whole value: https://github.com/grafana/k6/blob/737dfa7ced6e4f94dbb3d6f2c2837085e783ac09/lib/options.go#L615-L618 …
=> Fix wrong omitempty for options.scenarios

core/local/eventloop_test.go, js/bundle.go, js/doc.go, js/eventloop.go, js/eventloop_test.go, js/initcontext.go, js/modules/k6/experimental/experimental.go, js/modules/k6/k6.go, js/modules/modules.go, js/modulestest/modulestest.go, js/runner.go
A recent update to goja introduced support for ECMAScript Promise.
The catch here is that Promise's then will only be called when goja
exits executing js code and it has already been resolved.
Also resolving and rejecting Promises needs to happen while no other
js code is being executed as it will otherwise lead to a data race.
This more or less necessitates adding an event loop. Additionally
because a call to a k6 modules such as `k6/http` might make a promise to
signal when an http request is made, but if (no changes were made) the
iteration then finishes before the request completes, nothing would've
stopped the start of a *new* iteration. That new iteration would then
probably just again ask k6/http to make a new request with a Promise ...
This might be a desirable behaviour for some …
=> Add basic event loop with some API to be used by modules

cmd/archive.go, cmd/archive_test.go
Running `go test` with the current `master` leaves a dangling `cmd/archive.tar` file that "dirties" the repo. 
The proper fix would be to not use the OS filesystem at all, by threading an `afero.Fs` through everything, but that should probably wait for after v0.37.0 is released. I'll check it out and make another PR if it's quick.
=> Close archives after writing them and fix test to not add untracked files to the repo

cmd/root.go, log/file.go, log/file_test.go
This closes https://github.com/grafana/k6/issues/2413, a minor deficiency that slipped by in https://github.com/grafana/k6/pull/2285 
The integration test for this is unfortunately will have to wait until https://github.com/grafana/k6/pull/2412 is merged. That is in fact how I found the issue, tried to write an integration for sending logs to a file and it failed because the file didn't contain the expected text at the end of the test :sweat_smile: So we'll have to merge this in v0.37.0 without a test :disappointed:
=> Wait for file log to drain before k6 exits

cmd/inspect.go, js/bundle.go, js/runner.go
I tried to read https://github.com/grafana/k6/issues/1048 and honestly got lost in more than a few places... However, I am pretty sure this simplification is safe from reading through the code and thinking logically about it. There is no reason to create a runner and an execution scheduler to get the execution requirements a script. It should be enough to derive the `scenarios` and just use their `GetFullExecutionRequirements()` method, that's exactly what the execution scheduler does, after all... :sweat_smile:  https://github.com/grafana/k6/blob/1e28a3e1c8655d2118c823113e7a90ce44736cfe/core/local/local.go#L69
Anyway, tagged this as v0.38.0 since it doesn't really matter, but we should probably not introduce changes like this right before the release, even if they should not really …
=> Simplify execution requirements calculation in `k6 inspect`

api/v1/metric_jsonapi.go, api/v1/metric_routes_test.go
Fixes https://github.com/grafana/k6/issues/2420
I think this broke in https://github.com/grafana/k6/pull/2304, but nobody noticed since not a lot of people actually use this sub-command... :sweat_smile:
=> Fix missing metric name in k6 stats (MetricsJSONAPI)

cmd/inspect.go, js/bundle.go, js/runner.go
We didn't end up merging more PRs in the `next` branch, so this is exactly the same as https://github.com/grafana/k6/pull/2409, only a PR to `master` this time
=> Simplify requirements calculation in `k6 inspect`

lib/types/hostnametrie.go, lib/types/hostnametrie_test.go
This change is exposing the source of the `NullHostnameTrie`, otherwise, the only way of getting the access to the underlying array is to use Marshaling, like:
```go
func extractHostnames(list k6types.NullHostnameTrie) ([]string, error) {
if !list.Valid {
return []string{}, nil
}
tmp, err := list.MarshalJSON()
if err != nil {
return []string{}, err
}
var extracted []string
err = json.Unmarshal(tmp, &extracted)
if err != nil {
return []string{}, err
}
return extracted, nil
}
```
which isn't efficient
=> Expose the Source of the NullHostnameTrie

go.mod, go.sum, vendor/github.com/dop251/goja/compiler.go, vendor/github.com/dop251/goja/compiler_expr.go, vendor/github.com/dop251/goja/compiler_stmt.go, vendor/github.com/dop251/goja/vm.go, vendor/modules.txt
Use the latest goja's commit that includes:
* Added constant folding to variable assignments. Avoid using references where possible.
=> Update `dop251/goja` from `cfb079c` to `b09a6bf`

cmd/archive.go, cmd/archive_test.go, cmd/cloud.go, cmd/common.go, cmd/config.go, cmd/config_consolidation_test.go, cmd/convert.go, cmd/convert_test.go, cmd/inspect.go, cmd/login_cloud.go, cmd/login_influxdb.go, cmd/outputs.go, cmd/pause.go, cmd/resume.go, cmd/root.go, cmd/root_test.go, cmd/run.go, cmd/run_test.go, cmd/runtime_options.go, cmd/scale.go, cmd/stats.go, cmd/status.go, cmd/ui.go, cmd/ui_test.go, cmd/version.go, lib/testutils/logrus_hook.go, loader/filesystems.go, log/file.go, log/file_test.go
This wasn't quite part of the plan, but several hours of yak shaving produced some nice results :sweat_smile: Anyway, `cmd/` looks much nicer and it's now finally safe to test with basically full internal integration tests :tada: 
That said, there is a very high chance of bugs and errors, since we don't yet have full test coverage of `cmd/`... :disappointed: So a careful review and PRs that add more tests are going to be quite welcome :bow: Ideally, we should try to merge this at the beginning of the v0.38.0 cycle, so we also have the maximum time to safely hit any bugs during our manual tests and work...
And I think there were actually some (potential) bugs that were fixed by this refactor. For example, these loggers: https://github.com/grafana/k6/blob/1e28a3e1c8655d2118c823113e7a90ce4473 …
=> Remove most direct access to the `os` package, support `NO_COLOR` and `K6_NO_COLOR`

cmd/archive.go, cmd/archive_test.go, cmd/cloud.go, cmd/common.go, cmd/config.go, cmd/convert_test.go, cmd/inspect.go, cmd/integration_test.go, cmd/outputs.go, cmd/root.go, cmd/root_test.go, cmd/run.go, cmd/run_test.go, cmd/runtime_options.go, cmd/runtime_options_test.go, cmd/test_load.go, core/engine.go, js/bundle.go, js/runner.go, lib/runtime_options.go, log/file.go, log/file_test.go
More yak shaving, but after this, some parts of `cmd/` are almost normal looking :sweat_smile: :tada: I particularly like how clean `cmd/archive.go` became :tada: https://github.com/grafana/k6/blob/147e3d1beaf99aef837a3b30142c5728c0a6d17a/cmd/archive.go#L44-L72
Closes https://github.com/grafana/k6/issues/342
=> More `cmd/` refactoring to simplify test loading and support integration tests

cmd/archive.go, cmd/cloud.go, cmd/convert.go, cmd/inspect.go, cmd/login.go, cmd/login_cloud.go, cmd/login_influxdb.go, cmd/pause.go, cmd/resume.go, cmd/root.go, cmd/run.go, cmd/scale.go, cmd/stats.go, cmd/status.go, cmd/version.go
Closes https://github.com/grafana/k6/issues/2417... More yak shaving, I didn't intend on doing this now, but it's so much easier to work like this that I decided to spend the hour to do it... :sweat_smile: 
I suggest you review it with whitespace diffs disabled, it's mostly moving things around: https://github.com/grafana/k6/pull/2418/files?diff=unified&w=1
=> Flatten some long functions in `cmd/` and enable splitting them apart

lib/executor/constant_vus.go, lib/executor/externally_controlled.go, lib/executor/per_vu_iterations.go, lib/executor/ramping_arrival_rate.go, lib/executor/ramping_arrival_rate_test.go
The panic was happening in the `Init` but it was due to the fact that
HasWork wrongfully returned True when it should've returned false.
=> Fix panic due to error in HasWork

.github/workflows/xk6-tests/xk6-js-test/jstest.go, cmd/panic_integration_test.go, cmd/run_test.go, js/bundle.go, js/common/util.go, js/modules/k6/execution/execution_test.go, js/runner.go, js/runner_test.go
We change the behavior and the go `panic`'s will be treated as the run interruption
Otherwise it is hard to detect panics in the code
Closes #2354
=> Treat go panics as an interrupt error

lib/execution_segment.go, lib/executor/base_config.go, lib/executor/constant_arrival_rate.go, lib/executor/constant_vus.go, lib/executor/externally_controlled.go, lib/executor/externally_controlled_test.go, lib/executor/helpers.go, lib/executor/per_vu_iterations.go, lib/executor/ramping_arrival_rate.go, lib/executor/ramping_vus.go, lib/executor/ramping_vus_test.go, lib/executor/shared_iterations.go, lib/netext/httpext/response_type_gen.go
In a few cases, the CLI application stops running and returns an error, stating that some parameter "should" or "shouldn't" have a certain value.
The word "should," though, generally indicates _strong advice_. In these cases, the application stops running, so it makes more sense to indicate that that the error is stating _a requirement_. For requirements or impossibilities, the helping verbs "must" or "can't" would be more appropriate.
Believe it or not, there's already an RFC that covers almost exactly this topic.
https://datatracker.ietf.org/doc/html/rfc2119#section-4
=> Changes error messages. "should" --> "must", "can"

api/v1/metric_routes_test.go, api/v1/metric_test.go, core/local/local_test.go, js/summary_test.go, metrics/registry.go, output/csv/output_test.go, output/helpers_test.go, output/influxdb/bench_test.go, output/influxdb/output_test.go, output/json/json_test.go, output/statsd/test_helper.go, stats/stats.go, stats/stats_test.go
This PR removes the `stats.New` method from the `stats` package. This change is intended to facilitate the move of the `stats` package code in a top-level `metrics` code. It was triggered and requested, as preparation step to https://github.com/grafana/k6/pull/2433 and https://github.com/grafana/k6/pull/2426.
Note that this PR might be taking certain shortcut, assuming the API will be readjusted later by the mentioned PRs.
I took the initiative to use the `registry.NewMetric` in places where `stats.New` used to be. I could see two main alternatives: 
* using `registry.MustNewMetric`, but considering we use `require.NoError` everywhere else, I picked `registry.NewMetric` instead
* instantiating `Metric` instances “manually” everywhere it's possible. However, considering we want to explicit …
=> Remove `stats.New`

js/modules/k6/http/request_test.go
This no longer passes on gotip as it was fixed in
https://github.com/golang/go/commit/a41763539c7ad09a22720a517a28e6018ca4db0f
=> Remove test around redirects without Locations

.github/workflows/dev-release.yml
Added a workflow for testing the new windows certificate, it's a copy without the uploading phases of the current release process, it builds the request branch, creates the platform binaries and it signs the Windows version.
=> gh: dev release workflow

js/common/bridge.go, js/common/bridge_test.go, js/modules/modules.go
Removing the dead code reported by linters:
```sh
golangci-lint run --print-issued-lines=false --out-format tab | grep unused 
js/common/bridge.go:13:2                       deadcode          `ctxPtrT` is unused
js/common/bridge.go:14:2                       deadcode          `ctxT` is unused
js/common/bridge.go:15:2                       deadcode          `errorT` is unused
js/common/bridge.go:16:2                       deadcode          `jsValT` is unused
js/common/bridge.go:17:2                       deadcode          `fnCallT` is unused
js/common/bridge.go:19:2                       deadcode          `constructWrap` is unused
js/common/bridge_test.go:106:6                 unused            type `bridgeTestNativeFunctionContextType` is unused
js/common/bridge_test.go:218:33 …
```
=> chore: remove dead code reported by linters

.github/workflows/all.yml, .github/workflows/arm-tests.yml, .github/workflows/dev-release.yml, .github/workflows/xk6.yml
* Move `shell: powershell` to `shell: pwsh` (Powershell Core)  for Windows jobs.
* Set `go1.18` as the version for the current test job. 
* Updated legal entity for Windows build metadata
* Set Go version v1.17.x as stable for ARM and xk6 test 
~~It's blocked by #2465~~
=> Migrate powershell and Go version

js/console.go, js/console_test.go
Closes #1146
:warning: BREAKING CHANGE: After this PR will be merged, all `js/console` methods like `console.log` and `console.info`, in the case a JavaScript Object (or an Array) is passed as an argument then it is converted into a string encoded as a JSON object.
**Objects**
```js
var user = [{}]
console.log("the user", user) 
// before: the user [object Object]
// after: the user {"name":"Bob"}
}
```
**Arrays**
```js
var user = {name: "Bob"}
console.log([1, 2, "mytest", {user: "Bob"}]) 
// before: 1,2,mytest,[object Object]
// after: [1,2,"mytest",{"user":"Bob"}]
}
```
The previous way can be restored by directly parsing the object to a string using the `String` function.
```js
var user = {name: …
```
=> js/console: Marshal by default native JS objects

api/v1/setup_teardown_routes_test.go, cmd/integration_test.go, cmd/integration_tests/eventloop/eventloop_test.go, cmd/root_test.go, cmd/run.go, cmd/runtime_options.go, cmd/test_load.go, converter/har/converter_test.go, core/engine_test.go, core/local/k6execution_test.go, core/local/local_test.go, js/console_test.go, js/init_and_modules_test.go, js/module_loading_test.go, js/modules/k6/marshalling_test.go, js/runner.go, js/runner_test.go, js/share_test.go, lib/runtime_options.go, lib/runtime_state.go
Based on https://github.com/grafana/k6/pull/2485#issuecomment-1091650420 
fixes #1043
=> Add RuntimeState and keylogger to it

CONTRIBUTING.md, Makefile
#What?
This PR is updating the `CONTRIBUTING.md`
Also, WDYT if we add the Makefile's target with the tooling installation?
=> chore: update CONTRIBUTING.md

README.md
Bintray stopped working 1 year ago (May 2021), so these instructions are no longer necessary.
=> Remove instructions for bintray migration

cmd/integration_test.go, js/common/frozen_object.go, js/common/frozen_object_test.go, js/common/util.go, js/modules/k6/execution/execution.go, js/modules/k6/execution/execution_test.go, lib/options_test.go, lib/types/ipblock.go, lib/types/ipblock_test.go
This PR adds the capability for fetching the consolidated and derived options for tests using the `k6/execution` API. It adds a `test.options` object exporting all the potential set properties.
A simple example of the expected API:
```javascript
import exec from 'k6/execution';
vus: 10,
duration : '30s'
};
export default function() {
console.log(exec.test.options.scenarios.default.vus) // 10
}
```
1. ~We are defining the default values for some objects/arrays as `null`. An example is [Thresholds](https://k6.io/docs/using-k6/options/#thresholds).
Which value do we expect to get if we access properties like Thresholds? `undefined` or `null` or `{}` (empty object)?~ We will use the same value returned from the JSON marshal, at the moment, the k6 options' values are …
=> js/k6/exec: test.options object

lib/options.go, lib/options_test.go
**Related issue**: #2435 (Also presents the problem)
**Proposal**:
- Allow users to pass an password field which is used to decrypt the private key; If the key is not protected/encrypted, password will be ignored.
=> TLS Auth - Support for encrypted private key

js/modules/k6/execution/execution_test.go, lib/options.go, lib/options_test.go
Optional options should be nullable using a `guregu/null.`-like type for supporting consistently the `exec.test.options`.
Moved the `tlsAuth.password` option to null.String
=> Set tlsAuth.Password as a nullable string

cmd/config.go, cmd/options.go
=> Remove global max VUs deprecated option

js/console.go, js/console_test.go
Fixes the current implementation that doesn't support all the possible kinds for goja objects.
```javascript
let resp = http.get('https://httpbin.test.k6.io/anything');
// before: [object Object]
// after: {"url":"https://httpbin.test.k6.io/anything","status":200, ... }
console.log(resp);
}
```
=> Support logging as json all kind of goja's objects

lib/consts/consts.go, release notes/v0.38.0.md
We had overlooked a change that might affect extensions developers in our initial **v0.38.0** release notes. The `stats` package has been removed in favor of the `metrics` package. My bad 🙇🏻 
This PR adds a dedicated entry to the `Breaking Changes!` section.
=> Fix v0.38.0 release notes

lib/consts/consts.go, release notes/v0.38.1.md
Here are the release notes and k6 version bump for `v0.38.1`. Please let me know if I missed anything 🙏🏻
=> v0.38.1 release

core/engine.go, core/engine_test.go, metrics/engine/engine.go, metrics/sink.go, metrics/thresholds.go, metrics/thresholds_test.go
This Pull Request attempts to address #2520. It was discovered internally by the team that thresholds applied to checks (rate metrics) would immediately fail, and return a `NaN` result.
I've found out that the `NaN` was the result of a division by zero. I assumed it happens because the threshold was run before a single check sample was recorded (I might be wrong there though). I've thus introduced a check in `Thresholds.Run` to perform insert the sink's "rate" value computation only if the right-hand side of the division is not zero. 
Besides, the `Threshold.runNoTaint` function used to make a verification that a sink existed, before actually evaluating the threshold expression. This PR drops this verification, considering the thresholds are now verified at startup. Because of the …
=> Fix threshold over rate metric resulting in `NaN` result

lib/consts/consts.go, release notes/v0.38.2.md
These are the release version bump and release notes for `v0.38.2` which addresses further issues we've discovered (thanks @efdknittlfrank thresholds in `v0.38.0` and `v0.38.1`.
=> release v0.38.2

lib/executor/constant_arrival_rate.go, lib/executor/ramping_arrival_rate.go
This Pull Request addresses issue 1753.
If you set up a scenario where the executors run less than one iteration per second, the value is floored to zero while in progress.
By this PR, the behavior changes like at the below.
From:
To:
=> update iter/s precision from 0 to 2

metrics/sink.go
=> Ensure rate sinks with no samples are formatted as 0%

loader/loader.go
Previously we will always print the really long message that says we
tried everything. But in reality we only do this if we have something
that:
* is not local (start with ./)
* is not prefixed with `https://`
* is not a magical github or cdnjs URL (which entirely uses the Opaque
URL property)
But the if changed here basically checks that either we don't have
scheme *or* that it's Opaque. But in reality if it has scheme it never
has Opaque. And Opaque always has no scheme - so all cases enter the if.
The correct is to enter *only* when both are true as in that case it's
not magical and it doesn't have scheme so the schem
=> Fix printing wrong message on remote resolution

go.mod, go.sum, vendor/github.com/tidwall/gjson/gjson.go, vendor/modules.txt
The update is an optimizations by making a custom AppendJSONString
instead of using encoding/json. This is 2x faster for this particular
thing.
=> Update github.com/tidwall/gjson to 1.14.1 from 1.14.0

output/csv/config.go, output/csv/config_test.go, output/csv/consts.go, output/csv/doc.go, output/csv/output.go, output/csv/output_test.go
Simple PR to increase time unit granularity with CSV file output to be more in-line with JSON file output.
**file.csv**
Before:
`http_req_receiving,1638331259,...`
After:
`http_req_receiving,1638331421334748,...`
=> Add TimeFormat option for output/csv with 'unix' (default) and 'rfc3399' options

js/modules/k6/execution/execution.go, js/modules/k6/execution/execution_test.go
Setting a property of `vu.tags` as  `null` or `undefined`, like the following example, generates a panic. 
```javascript
import exec from 'k6/execution';
exec.vu.tags['any'] = null; // or undefined
}
```
- The new logic discards the set operation for `null` and `undefined` values and it prints a warning, instead, in case the `--throw` option is set, then it panics.
- In the case of the `--throw` option set, it's raised a panic passing a TypeError object.
=> exec.vu.tags: Handle null or undefined values

js/modules/k6/html/html.go, js/modules/k6/html/html_test.go
This PR attempts to address #2471.
The existing `Html.Selection.map` function would return a `[]string` under the hood. This behavior would result in effectively obfuscating any type that's not a string during the parsing of an HTML or XML document. This PR modifies the behavior and signature of the function to fit what we have [documented](https://k6.io/docs/javascript-api/k6-html/selection/selection-map).  The return value should be an `Array` of values on the JS script side, a `[]goja.Value` in the Go implementation of the library.
The reason why we returned `[]string` in the first place is because goquery, the library we depend on to perform HTML/XML parsing, own map method does so. To work around the limitation, I adopted an approach consisting in serializing the values with map over …
=> Make html.Selection.map return []goja.Value instead of []string

cmd/run_test.go, cmd/testdata/thresholds/empty_sink_no_nan.js, cmd/testdata/thresholds/name_contains_tokens.js, cmd/testdata/thresholds/thresholds_on_submetric_without_samples.js
This Pull Request addresses #2525 and adds tests covering the thresholds-related regressions observed in `v0.38.*` versions as a result of further replacement of the thresholds' evaluation logic.
Specifically, this PR adds tests covering #2518, #2512 and #2520.
I've tried different approaches for testing, but adding test scripts illustrating the issue, and writing tests for the `run` command, just like with did for thresholds validation at init ended up being the simplest, clearest and most convenient.
closes #2525
=> Add tests covering v0.38.* thresholds regressions

js/bundle_test.go, js/console_test.go, js/empty_iterations_bench_test.go, js/http_bench_test.go, js/initcontext_test.go, js/runner_test.go, js/share_test.go
The js tests had a bunch of places where they were using `assert` instead of `require`.
Mostly cases where the test should've not continued such as expecting error or no error. In some places `if assert....` was used which also is completely not needed.
I have kept most usage of `assert` where they will report multiple (and even singular failures sometimes), but I would argue in most cases just using `require` for everything is likely enough. 
There are also a few places where I've added `requires` that were previously missing.
Finally, there are few places that could've been left as `assert` but I decided to go for `require` in order for there to be no `assert.Error` for example. As I would argue this should always be with require.
Some of those lead to *fewer* reported failures as …
=> Use require a lot more than assert in js tests

lib/executor/ramping_vus.go, lib/executor/ramping_vus_test.go
Previous to this they were just ignored. Now ramping-vus will just not
do anything for that time.
closes #2531
=> Try to respect zero target stages at the end

js/modules/k6/execution/execution.go, js/modules/k6/execution/execution_test.go, js/runner_test.go
Always check if `scenarioState` is available for the `execution.scenario`, otherwise erroring.
It makes no sense to use this `execution.scenario` not inside the VU context.
Closes: #2545
=> fix: proper error exec.scenario.* in not init context

cmd/integration_test.go, metrics/engine/engine.go
This is connected to the future deprecations that are described at the end of the release notes (https://github.com/grafana/k6/pull/2581/files). The earlier we mention them, the better.
=> Add a deprecation warning for thresholds on tags we'll make non-indexable

js/modules/k6/http/request.go, js/modules/k6/http/request_test.go
Updated Batch method to contain array of goja.Value and if the size is greater than 1 then return and error. Else continue with the data.
=> #1289: Error will be displayed that only 1 array is allowed in batch

js/eventloop/eventloop.go, js/eventloop/eventloop_test.go
This should help with actually finding problems with code using it.
I have already seen multiple times code which seems okay but in fact
will call the returned callback twice. This effectively will lead either
to deadlock of the eventloop or earlier exit from a loop.
Given that it's never actually correct to that, panic seems okay.
We also make certain that if the user recovers from the panic we will
not have locked the eventloop either way,
In the future better APIs for most use cases should probably reduce the
need for people to use RegisterCallback and consequently worrying about
this.
=> Panic on RegisterCallback result being used more than once

output/json/json.go, output/json/json_easyjson.go, output/json/json_test.go, output/json/wrapper.go, samples/thresholds.js
:warning: [**Breaking Change**] The `tainted` field has been removed from the flushed fields for a metric type.
The previous implementation [makes a copy](https://github.com/grafana/k6/blob/bfa415c5fdfa6084f49b02877540cf6c05e23605/output/json/json_easyjson.go#L226) of the Metric struct where it generates a data race on the Observed field that [is written](https://github.com/grafana/k6/blob/bfa415c5fdfa6084f49b02877540cf6c05e23605/metrics/engine/engine.go#L133)
from the metrics.Engine.
The current implementation reduces the fields copied resolving the simplest race on Observed. The Observed field is not useful for the JSON output.
`metrics.Thresholds` shouldn't be racy because the output [mostly read "immutable"](https://github.com/grafana/k6/blob/bfa415c5fdfa6084f49b02877540cf6c05e23605/me …
=> output/json: Metric data race

core/engine_test.go, js/bundle.go, js/bundle_test.go, js/compiler/compiler.go, js/initcontext.go, js/initcontext_test.go, js/module_loading_test.go, js/runner.go, js/runner_test.go
This is the continuation of #2566 with a fix in which I wrap the main module the same way every other module.
This more or less gets us inline with what will be the behaviour once ESM lands from #2563. 
As you can see I had to also change other tests as they make no sense once the main module doesn't just work in the global scope.
This still needs work if we decide to merge it:
1. I will try to fix the lines for main modules(and not only) with no source maps and/or not going through babel. 
2. More polishing - I likely will want to refactor some of the code a bit more. Like `getExports` seems like of strangely out of place which I also noticed while working on ESM
=> Contain main module within it's own scope as well

.golangci.yml
Update the golangci-lint to v1.47.2 and use the list defined by the maintainers.
Keep the project codebase nice & clean using the latest possibility of automation.
=> chore: update golangci-lint to the v1.47.2

js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go
=> fix: fix ws not support throw option

metrics/system_tag.go, metrics/system_tag_test.go, metrics/tags.go, metrics/tags_test.go, output/statsd/config.go, output/statsd/output_test.go
It releases the name `TagSet` so we can reuse it for a set of tags instead of system tags that should fit better the name.
I moved it into a dedicated `tags.go` file so we can centralize a bit around tags and I will continue more in the time series.
=> Renamed TagSet to EnabledTags

cmd/config_consolidation_test.go, cmd/options.go, core/engine_test.go, core/local/local.go, js/modules/k6/execution/execution_test.go, js/runner.go, lib/executor/base_executor.go, lib/netext/httpext/request_test.go, lib/netext/httpext/transport_test.go, lib/options.go, lib/options_test.go
It removes the dependency from SampleTags. In this way, it facilitates the transition to a more efficient SampleTags.
Related to: https://github.com/grafana/k6/pull/2594
=> lib/options: Migrated RunTags to map[string]string type

js/modules/k6/http/request.go, js/modules/k6/metrics/metrics.go, lib/netext/httpext/request.go
The new TagSet will be not optimal in the case the same set is provided with a different order. Let's keep them sorted as provided by the JavaScript Object.
Related to: https://github.com/grafana/k6/pull/2594#discussion_r929894515
[:warning: BREAKING CHANGE] It was possible to pass multiple tag sets to [add metric](https://k6.io/docs/javascript-api/k6-metrics/counter/counter-add), it was an error and it has been fixed in this PR.
=> Keep the provided tags with a consistent order

core/engine_test.go, core/local/local_test.go, js/initcontext_test.go, js/modules/k6/execution/execution_test.go, js/modules/k6/grpc/client_test.go, js/modules/k6/http/request_test.go, js/modules/k6/k6_test.go, js/modules/k6/metrics/metrics_test.go, js/modules/k6/ws/ws_test.go, js/summary_test.go, lib/netext/httpext/request_test.go, lib/netext/httpext/tracer_test.go, lib/state_test.go, metrics/metric_test.go, metrics/sample_test.go, metrics/tags.go, metrics/tags_test.go, metrics/thresholds_test.go, output/cloud/bench_test.go, output/cloud/output_test.go, output/csv/output_test.go, output/helpers_test.go, output/influxdb/bench_test.go, output/influxdb/output_test.go, output/json/json_test.go, output/statsd/helper_test.go
Note: the source branch is `atlas`. It fixes https://github.com/grafana/k6/pull/2594#discussion_r936304976
=> Remove NewTagSet (old NewSampleTags) 

.github/workflows/build.yml
Because of a mistake I made in https://github.com/grafana/k6/pull/2591, we were pushing `master` builds as stable `latest` and `vX.Y-Z` docker images, which was not the intention :disappointed: 
So now we have a bunch `master` builds here https://hub.docker.com/r/grafana/k6/tags and https://hub.docker.com/r/loadimpact/k6/tags :disappointed:  And I guess this is also why the user from https://github.com/grafana/k6/issues/2623 encountered the issue :thinking:
=> Fix the pushing of docker images in the CI build process

cloudapi/config.go, lib/helpers.go
Minor fix to a misspelling in a comment.  
No user visible changes.  No code changes.
=> Fix spelling of "lose"

.github/workflows/test.yml, js/modules/k6/http/request_test.go, js/runner_test.go
=> Replace badssl.com in tests

js/eventloop/eventloop.go, js/modules/modules.go
~I will rename all of the uses of `EventLoop.RegisterCallback()` in the code as well, once we agree on the name.~
I have scaled this back to just improving the comments and adding a `TODO` with a rename suggestion for the future (e.g. during https://github.com/grafana/k6/issues/2544)
=> Improve the comments for `EventLoop.RegisterCallback()`

go.mod, go.sum, vendor/github.com/grafana/xk6-timers/timers/timers.go, vendor/github.com/grafana/xk6-websockets/websockets/websockets.go, vendor/modules.txt
This PR integrates the recent fixes included in [xk6-websockets](https://github.com/grafana/xk6-websockets) and [xk6-timers](https://github.com/grafana/xk6-timers). It effectively bumps k6's dependency on them to their respective `v0.1.3` and `v0.1.2` versions. Those fixes directly affect the `k6/experimental/websockets` and `k6/experimental/timers` modules.
=> Update xk6-websockets and xk6-timers versions

cmd/integration_test.go, metrics/engine/engine.go
This was mistakenly added in k6 v0.39.0 (https://github.com/grafana/k6/pull/2583), but it turns out we probably don't need it (see https://github.com/grafana/k6/issues/2584#issuecomment-1219618111)
=> Remove the warning for thresholds on url sub-metrics

cmd/archive.go, cmd/archive_test.go
This PR introduces a new flag to the `k6 archive` command. If this flag is provided we exclude environment variables provided with the `--env` from the script's archive (`metadata.json`).
There are some cases when environment variables are required for archiving, but it's safer to not store them.
Closes: #2587
=> Introduce a new flag to the k6 archive sub-command

.github/workflows/build.yml
This fixes https://github.com/grafana/k6/issues/2677. Because of a bug introduced in https://github.com/grafana/k6/pull/2591, the CI would push `vX.Y.Z` docker images when before they were with the format `X.Y.Z`, without the "v" prefix. The v0.40.0 image was manually fixed by https://github.com/grafana/k6/commit/c90346ae11b4c14380474d96ea5e8f43db919088
=> Fix Docker Hub image labels for official releases

log/tokenizer_test.go
Adds a couple more tests to the tokenizer in `log` package. Also formats the tests a bit to make it easy to add more if desired.
=> log: add more tokenizer tests

api/v1/status_routes.go, api/v1/status_routes_test.go
Currently, the api doesn't set `Content-Type` header which cause some http client that decode data base on `Content-Type` not working correctly. Fixes by set Content-Type header to /v1/status api (both GET and PATCH).
Fixes: #2688
=> Fix /v1/status doesn't set json content-type

Dockerfile, build-release.sh
Add a `--tags` flag to fetch all tags for the `git describe`.
Without that flag k6's version details gets a previous flag.
Closes: #2676
=> Fix VERSION_DETAILS does not contain the latest tag

js/eventloop/eventloop.go, js/runner_test.go
Previously when a promise is rejected but *not* handled, the event loop would end the current iteration and then let a new one start.
Unfortuantely it also didn't clear the failure so the next time it will again *fail* the iteration as it still thinks a promise has been rejected without a handler.
Heavily related to https://github.com/grafana/xk6-browser/issues/510
=> Dont lock the event loop once a promise rejection is left unhandled

cmd/runtime_options.go, cmd/runtime_options_test.go, cmd/test_load.go
Align the `--include-system-env-vars` with the `--env` in terms of the name validation.
In case of detecting an invalid name issue, the user will be warned.
```
env -i 'LOREM-ISPUM=hello' IPSUM=lorem ./k6 run --include-system-env-vars samples/http_2.js
```
As the result, archive metadata should contain only `IPSUM=lorem`.
Closes: #2650
=> Detecting and filtering invalid environment names

js/modules/k6/grpc/client_test.go, js/modules/k6/http/request_test.go, js/modules/k6/http/response_test.go, lib/netext/httpext/transport.go
This change was introduced in https://github.com/grafana/k6/pull/2654 but we decided to split it into a dedicated PR. The quote from the original PR and from the issue describe the reasons.
>One change from the original issue description has been the decision to have an indexable url tag, but to always have its value be equal to the name tag. See this for the details and the reason why: https://github.com/grafana/k6/issues/2584#issuecomment-1219618111
=> atlas: url tag value always equal to the name tag

js/modules/k6/experimental/README.md
It adds documentation about the steps for upgrading experimental modules.
=> Docs for bumping an experimental module's version

cmd/runtime_options.go, cmd/runtime_options_test.go, cmd/test_load.go
This reverts commit c6f57c6e22e6966e526643d2d0944e48df0ea36c.
And revert PR: #2652
To address the original issue, I'll open the task soon.
After an internal discussion, we decided to revoluate the pattern and probably relax the constraints.
=> Revert "Detecting and filtering invalid environment names"

output/csv/output.go, output/csv/output_test.go, output/json/json_easyjson.go, output/json/json_test.go, output/json/wrapper.go
It continues the work started in https://github.com/grafana/k6/pull/2654, we decided to split for having a scoped PR and discuss better the implementation details.
=> output/{json,csv}: Metadata migration

js/eventloop/eventloop.go, js/eventloop/eventloop_test.go
- fix a panic on `Promise.reject()` - rejection with `undefined` reason.
- include the actual rejection instead of only it's stack in case the stack exists.
=> Fixes for promise rejection reporting

js/common/util.go
According to the MDN docs, the JavaScript world prefers the term ArrayBuffer and considers "byte array" synonymous.
> [ArrayBuffer] is an array of bytes, often referred to in other languages as a "byte array".
>
> - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer
Having both terms in the same message suggests they are different concepts.
=> Remove byte array from redundant error message

lib/netext/httpext/tracer.go
This is not strictly necessary, but I've added it for consistency's sake. Users of `*httpext.Trail` can just get the metadata from its `Samples[0]`, for example, but that is a bit of a code smell.
=> Add `Metadata` to `httpext.Trail`

js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go
Allow users to process the error response, for example to implement and test backoff after receiving a 429 Slow Down.
I've also removed the log message for failed connections.  In my own load tests this is swamping out other log messages.
Issue link: https://github.com/grafana/k6/issues/2711
=> Return HTTP response to user for failed connections.

js/summary.go, metrics/sample.go, metrics/sink.go, metrics/sink_test.go, metrics/thresholds.go, metrics/thresholds_test.go
This PR addresses #2755. 
Turns out the Trend Sink median value was never calculated in time for thresholds to be able to evaluate them. The reason for that is that the median value can be quite expensive to compute, as it relies most notably on sorting the sink's array of values. As a result, its calculation happens in a dedicated `Calc` method. It appears we forgot to call that method in the `Thresholds.Run` method during our latest refactoring of the thresholds system.
This PR ensures the `Calc` method is called just in time, so that the costly computation only happens when Thresholds are effectively evaluated. It also adds a couple of tests to protect us from regressions in the future. Finally, it adds some documentation and comments to the code, so that next time we touch that part …
=> Fix 2755 and ensure evaulation of thresholds over trend metrics median 

js/modules/k6/ws/ws.go, js/modules/k6/ws/ws_test.go
Closes #2734
This only fixes the issue, but see #2768 for some related refactoring of `WS.Connect()`.
=> Fix emission of `ws_session_duration` when setup throws an error

.golangci.yml
Disabling the `containedctx`
It make no sense for this repo
=> Disable containedctx

js/initcontext.go, js/initcontext_test.go
This is inline with ESM and works for source code modules, but not for modules written in go as teh code was never made to work with it.
This also lets (as the test suggests) change what `k6/http`.get is across the VU just as it should be possible.
=> js: make certain only one copy of the exports is used per each module

js/path_resolution_test.go
=> Add tests around how require and open treat relative paths

lib/types/hostnametrie.go, lib/types/trie.go, lib/types/trie_test.go, lib/types/types.go
Hi @codebien 👋🏻 here is the aforementioned PR
What have changed:
- Moved `trieNode` to separate file
- New unit tests for trie implementation
- New benchmarks for the `trieNode.insert()` and `trieNode.contains()` methods
- Moved from recursive to iterative implementation
Here is a simple script that I used to create the benchmarks on my machine.
```bash
bench(){
echo "started: $2 benchmark"
git checkout "$1"  2> /dev/null
go test -run=^$ -bench=BenchmarkTrie -benchmem -count 30 > "$2"
}
cd lib/types
bench 2f14099  "original"
bench e11e0679 "remove_error"
bench 08933201 "iterative"
benchstat original remove_error > "bs_remove_error"
benchstat original iterative > "bs_iterative"
```
My machine was idle.
```
goos: darwin
goarch: amd64
pkg: go.k6.io/k6/lib/types
cpu: Intel(R) Core(TM) …
```
=> Move to Iterative Trie implementation (`trieNode`)

metrics/value_type.go
~Add the Sum stat into the resolvers map. It is helpful for reusing the same function from the Remote Write output. https://github.com/grafana/xk6-output-prometheus-remote/pull/64~
Just fix a comment
=> Fix code comment

cmd/integration_test.go, cmd/root.go, cmd/root_test.go, cmd/run.go, core/engine.go, core/local/local.go, output/cloud/output.go
Split among the first 3 commits are various improvements and additions to the existing integration tests: 
- proper exit code detection in integration tests
- mocking of the cloud API and checks for `run_status` and `result_status` values in `k6 run --out cloud` tests
- support for using and testing the k6 REST API in integration tests, without port collisions
- support for mocking signals (like Ctrl+C) mid-test run
The 4th commit actually fixes https://github.com/grafana/k6/issues/2788, a small bug I noticed while trying to remove the whole `core.Engine`  (https://github.com/grafana/k6/issues/1889). However, because the `Engine` removal will likely be merged at the start of the v0.43.0 cycle and because the bug was easy to fix even in the current implementation, I decided to fix it now. …
=> Integration test improvements and a few bugfixes

cmd/integration_test.go, core/local/local.go, js/runner.go
Previous to this PR, k6 would initialize a transient VU and try to execute `setup()` and `teardown()` even if we knew they were not defined and exported by the script. That VU was created and then immediately discarded afterwards. 
It was probably done like that because, when `setup()` and `teardown()` were implemented (https://github.com/grafana/k6/pull/457) in k6 v0.20.0, we didn't keep track of what JS functions were exported from the script. We only started doing that in k6 v0.27.0, when we added support for multiple scenarios, each with a potentially different `exec` function. We just didn't go back and improve the `setup()` and `teardown()` efficiency afterwards and they continued to use the "try to run it and see if it works" approach.
While it was inefficient, it didn't use to be …
=> Start to run `setup()` and `teardown()` only if they were defined

cmd/integration_test.go, cmd/root_test.go, core/engine_test.go
I've tried to make the commits in this PR very self-contained, so it might be easier to review them one by one. However, given that the only changes are in tests, it shouldn't matter too much either way.
The PR copies (with improvements) some of the more useful `core.Engine` tests, in preparation for https://github.com/grafana/k6/issues/1889. It also makes some minor fixes and improvements to the integration test framework and adds rudimentary support (and a few tests that) for verifying metrics sent to the JSON output, for extra assurance. It doesn't have any functional changes, so it should be safe to merge as soon as it's reviewed.
=> Increase and improve integration tests

cmd/integration_test.go, cmd/run.go, core/engine.go, core/local/local.go
Before these changes, `setup()` and `teardown()` exceptions or `test.abort()` calls would have made k6 exit prematurely, without waiting for the metrics processing to finish. **This bug was probably a cause for some of the "timed out" `k6 run --out cloud` tests we have seen, e.g. if they had some sort an error in `setup()` or `teardown()`.** It also caused a data race in the recent integration tests, this is how I caught it. So, as a nice bonus, this fix allowed me to remove one of the `FIXME`s for unnecessary locking in there earlier than expected :tada: 
This is another thing that should be fixed by the new `Engine`-less architecture (https://github.com/grafana/k6/issues/1889). However, once again, the fix was easy enough to do even now, and the bug severe enough that it's probably …
=> Wait for metrics handling to finish even when there is an error

cmd/integration_test.go, cmd/root_test.go
These integration tests might have been a little too real... :sweat_smile: 
The first commit masks a data race around stdout (only until https://github.com/grafana/k6/pull/2800 is merged) and a flaky check. The second commit ensures integration tests don't make usage report requests and adds a check to hopefully prevent a similar mistake in the future.
=> Prevent real requests to the cloud during integration tests

cmd/integration_test.go, cmd/outputs.go, cmd/ui.go, cmd/version.go, ext/doc.go, ext/ext.go, js/jsmodules.go, js/modules/modules.go, output/extensions.go
This is based on the work done in #2754 (thanks @HarrisChu!), and the suggested changes there.
It evolved into something slightly more elaborate, where the bulk of the changes are to unify the extension registry, so that registration and retrieval of extension information is done in a single place. See commit cf5fa6102 for details. We still need to keep the existing registration functions in `js/modules/` and `output/` to avoid breaking extensions, but internally they're both now handled in the new root `ext` package. This DRYs the handling of extensions, and simplifies adding new types of extensions. It also simplifies the retrieval of extension versions, which is why it was done on top of #2754.
Here's how it currently looks:
```bash
$ xk6 build 4df8d46169ecc3a0417fd902bdcb28800e8098f0 …
```
=> Show bundled extension versions in `k6 run` and `k6 version` outputs

js/modules/k6/grpc/client.go, lib/netext/grpcext/conn.go
This doesn't depend on anything else, it should be safe to merge as is.
This should close https://github.com/grafana/k6/issues/2535, I think :thinking: Between it and https://github.com/grafana/k6/pull/2536, `go.k6.io/lib` and its sub-packages shouldn't depend on `go.k6.io/js` or `github.com/dop251/goja`, right?
`go list -f '{{ join .Imports "\n" }}'  ./... | sort -u | grep -E 'goja|go.k6.io/k6/js'` returns no results in the `lib/` package, at least :crossed_fingers: 
Unfortunately, I couldn't make depbuard work correctly, and I have no time to debug that further, so I'll leave that to someone else if they want to. From what I understand by skimming https://golangci-lint.run/usage/linters/#depguard, adding something like this in the `linters-settings:` section of `.golangci.yml` should …
=> Remove dependency on the `js/` package (and goja) from `lib/*` packages

go.mod, go.sum, vendor/github.com/grafana/xk6-output-prometheus-remote/pkg/remotewrite/prometheus.go, vendor/modules.txt
Bump again the version of the Prometheus remote write output. It fixes a new bug.
=> Bump prom rw output @v0.1.0

api/server.go, cmd/root_test.go, cmd/run.go, go.mod, go.sum, vendor/go.uber.org/goleak/.gitignore, vendor/go.uber.org/goleak/CHANGELOG.md, vendor/go.uber.org/goleak/LICENSE, vendor/go.uber.org/goleak/README.md, vendor/go.uber.org/goleak/doc.go, vendor/go.uber.org/goleak/internal/stack/stacks.go, vendor/go.uber.org/goleak/leaks.go, vendor/go.uber.org/goleak/options.go, vendor/go.uber.org/goleak/testmain.go, vendor/go.uber.org/goleak/tracestack_new.go, vendor/modules.txt
This depends on https://github.com/grafana/k6/pull/2800
=> Ensure REST API server is shut down after test ends and check for goroutine leaks

api/v1/group_routes_test.go, api/v1/status_routes_test.go, cmd/integration_test.go, cmd/run.go, core/engine.go, core/engine_test.go, errext/exitcodes/codes.go
This is built on top of https://github.com/grafana/k6/pull/2803 and tackles a small part of https://github.com/grafana/k6/issues/2804, though definitely not the whole issue.
It was necessary to be able to split apart https://github.com/grafana/k6/issues/1889 into a few smaller PRs and it was also necessary for https://github.com/grafana/k6/issues/1342 in its own right.
=> Use non-zero exit codes for some aborted by Ctrl+C or REST API tests

release notes/template.md
The main goal is to reduce guessing from the writer's and the editor's work.  Besides that, a standardized structure also makes it easier for readers to scan across multiple release-note pages.
I based this on the [v0.40.0 Release notes](https://github.com/grafana/k6/blob/master/release%20notes/v0.40.0.md), which I thought were particularly successful.
=> Update template for release notes

output/csv/output.go, output/csv/output_test.go
Fix for https://github.com/grafana/k6/issues/2827 without refactoring the CSV output or adding integration tests (which are waiting on https://github.com/grafana/k6/pull/2821).
- Removes the empty `vu` and `iter` columns from the CSV output if they are included as system tags.
- Includes the `vu` and `iter` tags in the `metadata` column of the output if they are included as system tags.
I've not added any integration tests as the integration tests are being refactored in https://github.com/grafana/k6/pull/2821
Instead I get the follow results:
```
*** TEST 1 - vu and iter set in system tags ***
SCRIPT:
import { sleep } from "k6";
import http from "k6/http";
systemTags: ["vu", "iter"],
};
http.get("https://test.k6.io");
sleep(0.5);
} …
```
=> fix: csv output for non indexable metrics

cmd/integration_test.go
Unfortunately `require.Fail` first string argument isn't the format string, it is the second one. The first one is general error message string. Same goes for Failf, which just happens to require the actual format message as argument.
=> Fix asyncWaitForStdoutAndRun error message

cmd/tests/cmd_cloud_test.go, cmd/tests/cmd_run_test.go
This PR only has tests of the existing behavior, it doesn't have any actual code changes. Those will come in a separate PR.
=> Add and expand e2e tests for `k6 run --out cloud` and `k6 cloud`

cloudapi/api.go, cloudapi/config.go, cloudapi/util.go, cmd/cloud.go, cmd/config_test.go, cmd/tests/cmd_cloud_test.go, cmd/tests/cmd_run_test.go
This is built on top of https://github.com/grafana/k6/pull/2864
=> Add ability to display `testRunDetails` and logs from k6 cloud

api/v1/setup_teardown_routes_test.go, api/v1/status_routes_test.go, cloudapi/api.go, cloudapi/run_status.go, cmd/cloud.go, cmd/run.go, cmd/tests/cmd_cloud_test.go, cmd/tests/cmd_run_test.go, core/engine.go, core/engine_test.go, errext/abort_reason.go, errext/exception.go, errext/interrupt_error.go, js/runner.go, js/runner_test.go, js/timeout_error.go, lib/testutils/mockoutput/mockoutput.go, output/cloud/output.go, output/cloud/output_test.go, output/manager.go, output/types.go
This is built on top of https://github.com/grafana/k6/pull/2807 and is a part of https://github.com/grafana/k6/issues/1889 and part of https://github.com/grafana/k6/issues/2430
`RunStatus` is very specific to the k6 cloud and doesn't map perfectly to how k6 OSS sees the causes of prematurely stopped tests. So, this PR restricts the usage of `RunStatus` only to the `cloudapi/` package and to the `k6 cloud` command handling in `cmd/cloud.go`.
It does that by introducing a new type, `errext.AbortReason`, and a way to attach this type to test run errors. This allows us a cleaner error propagation to the outputs, and every output can map these generic values to its own internal ones however it wants. It is not necessary for that mapping to be exactly 1:1 and, indeed, as you can see, the …
=> Add new `errext.AbortReason` type, move and use old `RunStatus` type only for k6 cloud code

cmd/tests/tracing_module_test.go, js/modules/k6/experimental/tracing/module.go, js/modules/k6/experimental/tracing/module_test.go, samples/experimental/tracing/tracing-instrumentHTTP.js
To keep Pull Requests as small as possible and reduce the review burden, this PR is the third one in a chain of three implementing the decided API design for the experimental tracing module.
warning ✋🏻 This PR is part of a PR chain, and is based on https://github.com/grafana/k6/pull/2854
This second PR builds upon #2853 and #2854  and adds an `instrumentHTTP` function to k6/experimental/tracing.
Using this function in their k6 scripts, once, users can automatically have all their calls to the `http` module's methods (`http.{del,get,head,options,patch,post,put,request}`) automatically instrumented with tracing information, in the same fashion as described in #2854. Indeed, this function under the hood remaps the `http` module's method to use the `Client`'s methods instead.
The …
=> Experimental tracing module (3/3): define and expose a `instrumentHTTP` function

cmd/tests/tracing_module_test.go, js/modules/k6/experimental/tracing/client.go, js/modules/k6/experimental/tracing/client_test.go, js/modules/k6/experimental/tracing/goja.go, js/modules/k6/experimental/tracing/module.go, js/modules/k6/experimental/tracing/module_test.go, js/modules/k6/experimental/tracing/options.go, js/modules/k6/experimental/tracing/options_test.go, js/modules/k6/experimental/tracing/trace_id.go, samples/experimental/tracing-client.js, samples/experimental/tracing/tracing-instrumentHTTP.js
To keep Pull Requests as small as possible and reduce the review burden, this PR is the second in a chain of three implementing the decided API design for the experimental tracing module.
⚠️ ✋🏻 This PR is part of a PR chain, and is based on #2853  
This second PR builds upon #2853 and adds a `Client` type to `k6/experimental/tracing`. This type mimics the relevant part of the HTTP module to allow users to perform HTTP requests embedding a trace context while also attaching the produced trace id as output metadata on the HTTP-related samples. In the larger context of the module's goal, the `Client` should hold the underlying logic for the `instrumentHTTP` function that's to come in the third PR. Still, it also allows users to selectively trace requests and reconfigure their tracing …
=> Experimental tracing module (2/3): define and expose a `tracing.Client`

.github/workflows/build.yml, .github/workflows/pr-auto-assign.yml
These changes finalize the removalof the deprecated Node 12.X from our CI
Related to the:
* https://github.com/kentaro-m/auto-assign-action/issues/99
* https://github.com/kentaro-m/auto-assign-action/pull/98
Resolves #2763
=> Update the GitHub Actions to the latest versions

go.mod, go.sum, vendor/github.com/dop251/goja/func.go, vendor/github.com/dop251/goja/parser/expression.go, vendor/github.com/dop251/goja/parser/scope.go, vendor/github.com/dop251/goja/parser/statement.go, vendor/github.com/dop251/goja/runtime.go, vendor/github.com/dop251/goja/vm.go, vendor/modules.txt
Updating the goja dependencies which contain the fixes.
=> chore: upgraded github.com/dop251/goja 17fd568758fe => 78b980256d04

cmd/tests/cmd_run_test.go, core/engine.go, core/engine_test.go, execution/scheduler.go, execution/scheduler_ext_test.go
This is the first commit from https://github.com/grafana/k6/pull/2815, plus an extra test that checks the exit code when aborting a `k6 run --paused` test with Ctrl+C. 
Unfortunately, it turned out that https://github.com/grafana/k6/commit/19dd50593b90a79fa1883e248c63d385dbe7a8b9 from https://github.com/grafana/k6/pull/2813 introduced a regression. Interrupting the k6 process with a signal should result in a `105` exit code (`ExternalAbort`), but with that commit k6 exited with `103` if k6 was `--paused`. The good news is that the fix was already done in the first commit of https://github.com/grafana/k6/pull/2815, which was entirely self-sufficient and can be moved to this separate PR. As a bonus, this makes reviewing everything even easier... :sweat_smile: 
So, some details about the …
=> Remove the unnecessary `execution.Scheduler.Init()`
